### ISSUE TITLE
Hook for before team page load

### ISSUE THREAD

**Issue by mchauhan260** [apigee/apigee-edge-drupal#1012]
Hi Team,

I am using Apigee Edge with drupal 10 and I want to perform some action before team page load.
is there any hook for this?

**Comment by shishir-intelli** [comment]
@mchauhan260 
You can try Drupals's `hook_entity_load()`

**Comment by mchauhan260** [comment]
Thanks for the reply,
I am using this hook, but it's running on each instance of the team load. On view of team it's runs multiple time.
For example : on team view page, it's running minimum five time.(For edit, delete etc.) 
![team-menu](https://github.com/apigee/apigee-edge-drupal/assets/67674887/a31b997d-797a-4d24-a44b-a43bbd70933c)

**Comment by shishir-intelli** [comment]
We don't have separate hooks for team load page.
Do you mean, inside `if ($entity_type_id === 'team') {` you get team entity multiple times?

**Comment by mchauhan260** [comment]
Yes, When someone access view/detail page of team (e.g https://example.com/teams/test-team),
I get it multiple times

**Comment by shishir-intelli** [comment]
We have events listed here https://www.drupal.org/docs/contributed-modules/apigee-edge/manage-reaction-rules
However, there is no separate hooks for team load page, you can make use of Drupals `hook_entity_load` to achieve your requirement.

**Comment by mchauhan260** [comment]
Okay, Thanks!!

**Comment by shishir-intelli** [comment]
Closing this issue, feel free to reopen for any help.
