### ISSUE TITLE
Access Team members in custom module

### ISSUE THREAD

**Issue by mchauhan260** [apigee/apigee-edge-drupal#1016]
Hi Team,

I am using apigee-x with drupal 10, I wanna access team members of a team in my custom module.
I tried to call TeamMembershipManager class in my custom module, but I am unable to do so.
Can you please help me with this?

**Comment by shishir-intelli** [comment]
In Apigee X, you can get the Team `developer/members` information from the Drupal's database table `team_member_role` and `team_member_role__roles` itself. 

Alternatively, for Apigee Edge to X migration purpose the Team `developer/members` information is also store in `__apigee_reserved__developer_details` attribute. (`v1/organizations/{org_name}/appgroups`)
https://www.drupal.org/docs/contributed-modules/apigee-edge/migrate-teams-members-from-apigee-to-drupal-portal#s-migrationsynchronization-steps

For example :
> $team_membership_manager = \Drupal::service('apigee_edge_teams.team_membership_manager');
> $team_membership_manager->getMembers($team_name);

You can get the member invitation related information from `team_invitation` and `team_member_role__roles` tables.

**Comment by mchauhan260** [comment]
Thank you for guiding me in the right direction and providing a prompt response.
