### ISSUE TITLE
Get Team/Company information from Apigee X in custom module

### ISSUE THREAD

**Issue by mchauhan260** [apigee/apigee-edge-drupal#1027]
Hi Team,

I am using apigee-x with drupal 10, I wanna Get Team/Company information from Apigee X in a custom module.

I tried below code, but it's not working. In exception handling I am getting 404 error :
$sdk_connector = \Drupal::service('apigee_edge.sdk_connector');
$client = $sdk_connector->getClient();
$endpoint = $client->getUriFactory()
  ->createUri("/organizations/{$sdk_connector->getOrganization()}/companies/test-company");
    $response = $client->get($client->getEndpoint() . $endpoint);

Can you please help me with this?

**Comment by mchauhan260** [comment]
I think I have figured it out. As for me, I was using the wrong keyword. I need to use "app groups" instead of "companies."

**Comment by shishir-intelli** [comment]
Hi @mchauhan260 

In Apigee X, `AppGroups` are used to represents a relationship between one or more apps that are managed by the same set of people (_Teams_)

Companies are for `Apigee Edge` organization.

So please use AppGroup for Apigee X organization.
See [here](https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations.appgroups) to refer Apigee X AppGroups API documentation.

**Comment by mchauhan260** [comment]
Thanks!!
Are you aware if any issue with attributes of teams not getting saved for Apigee X in drupal10?

**Comment by shishir-intelli** [comment]
There was one issue here https://github.com/apigee/apigee-client-php/issues/343
If this is the same issue you are facing, then please update the Apigee edge module to the latest version.

**Comment by mchauhan260** [comment]
Thanks!!
You are a savior

**Comment by shishir-intelli** [comment]
Welcome! 😊

Closing this issue for now, feel free to reopen for any further help.
