### ISSUE TITLE
Get all appgroups to which a user is associated in Apigee X

### ISSUE THREAD

**Issue by mchauhan260** [apigee/apigee-edge-drupal#1032]
Hi Team,

I am trying to get the all appgroups of  a user but unable to do so.
Can you please tell me what's best why to get this information?
I tried getTeams function but it's not returning.

Thanks

**Comment by giteshk** [comment]
@mchauhan260, This is saved in the database table. @shishir-intelli can you provide more details please.

**Comment by shishir-intelli** [comment]
Hi @mchauhan260 

There is some improvement going on in the `getTeams()` method.

I would suggest you to try the code below for getting the Teams for a specific developer :

```
    $team_member_role_storage = \Drupal::entityTypeManager()->getStorage('team_member_role');
    foreach ($team_member_role_storage->loadByDeveloper($account) as $team_member_roles_in_team) {
      if ($team_member_roles_in_team->getTeam() !== NULL) {
          $developer_team_ids[] = $team_member_roles_in_team->getTeam()->id();
      }
    }
    return $developer_team_ids;
```

**Comment by mchauhan260** [comment]
Thanks for the information.

**Comment by mchauhan260** [comment]
Can I do something like this using SDK?

**Comment by shishir-intelli** [comment]
No, you cant get it from SDK as we are saving the member information in DB table.

Alternatively, we also store the member information in `__apigee_reserved__developer_details` attribute on the AppGroup/Team.

Example:
```
{
    "name": "foo",
    "channelUri": "",
    "channelId": "dev-portal",
    "status": "active",
    "attributes": [
        {
            "name": "__apigee_reserved__developer_details",
            "value": "[{\"developer\":\"user@example.com\",\"roles\":[\"member\",\"admin\"]}]"
        }
    ],
},
```

**Comment by mchauhan260** [comment]
okay, thanks
