### ISSUE TITLE
Filter the Apis Products  showing on create app form using ajax.

### ISSUE THREAD

**Issue by mchauhan260** [apigee/apigee-edge-drupal#1037]
Hi Team,

I am trying to update the Apis Products on create app form using ajax.

I have created a radio button field using hook_form_alter and on change of it I wanna filter the Apis Products  showing on create app form.

Below is my form_alter code
```
my_module_form_team_app_add_for_team_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
       $form['api_products']['#prefix'] = '<div id="custom-wraper-for-api-products">';
        $form['api_products']['#suffix'] = '</div>';

        $form['env_options'] = array(
          '#title' => t('Environment'),
          '#type' => 'radios',
          '#options' => array(
            'filter_option1' => t('Filter Option 1'),
            'filter_option2' => t('Filter Option 2'),
            'filter_option3' => t('Filter Option 3'),
          ),
          '#ajax' => array(
            'event' => 'change',
            'callback' => 'my_module_env_ajax_callback',
            'wrapper' => 'custom-wraper-for-api-products'
          ),
          '#weight' => -1,
        );
}
```

Below is my ajax_callback code

```
function my_module_env_ajax_callback(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
$options = [
          'option_1' => 'Option 1',
          'option_2' => 'Option 2',
          'option_3' => 'Option 3',
        ];
        $form['api_products']['#options'] = $options;
        return $form['api_products'];
}
```

But it's not updating the api products.

Can you please point me into the right direction?

Thanks

**Comment by kedarkhaire** [comment]
Hi @mchauhan260 

I checked your request on Teams Apps creation page.
So you are planning to update the Api products lists on change of the custom field environments using Ajax Callback.

But whenever you fire that Ajax callback, the existing Apis are also called which overrides your implementation.
If you can enable the Apigee Edge Debug module, this will help you to see what happens when the url is hit or when you use Ajax callback on that page.

Try overriding response for this API `/v1/organizations/***organization***/apiproducts` post the page is loaded.

Thanks!

**Comment by mchauhan260** [comment]
Hi @kedarkhaire ,

Thanks for responding, Yes you are right  existing Apis are overriding the options of checkbox.

I did some R&D, but didn't found any solution for this.
Do you have any idea how I can override the API response?

**Comment by kedarkhaire** [comment]
Hi @mchauhan260 ,
We have this function `alterFormWithApiProductElement` which allows to alter the form after API products form element have been added.

You can refer its implementation in our modules, This will help you.

Thanks!

**Comment by kedarkhaire** [comment]
Hi @mchauhan260 Closing this ticket, considering the above comment as helpful for your request.
