### ISSUE TITLE
Support for Drupal 10.2 in Github action

### ISSUE THREAD

**Issue by divya-intelli** [apigee/apigee-edge-drupal#1038]
## Is your feature request related to a problem? Please describe.
Add support for Drupal 10.2 in github actions.

**Comment by kedarkhaire** [comment]
Failing for PHP 8.1 | D10.2 | Edge & PHP 8.2 | D10.2 | Edge

1. Drupal\Tests\apigee_edge\Functional\DeveloperAppFieldTest::testFieldableDeveloperApp (121){Behat\Mink\Exception\ResponseTextException: The text "These settings apply to the F3VUSQBA field everywhere it is used." was not found anywhere in the text of the current page.}
2. Drupal\Tests\apigee_edge\Functional\DeveloperSyncTest::testDeveloperSync & Drupal\Tests\apigee_edge\Functional\DeveloperSyncTest::testDeveloperAsync &  Drupal\Tests\apigee_edge\Functional\DeveloperSyncTest::testCliDeveloperSync(147)
{Behat\Mink\Exception\ElementNotFoundException: Form field with id|name|label|value "field_storage[subform][settings][allowed_values]" not found.}
3. Drupal\Tests\apigee_edge\FunctionalJavascript\Form\AuthenticationFormJsTest::testUsingHybridForm (219)
{Behat\Mink\Exception\ElementNotFoundException: Element matching css ".messages--status" not found.}

Thanks!
