### ISSUE TITLE
Prevent Team or Organization having Zero members

### ISSUE THREAD

**Issue by techietk02** [apigee/apigee-edge-drupal#1044]
How To Prevent team or organizations having zero members ,how can i add validation for this remove team member form

**Comment by shishir-intelli** [comment]
Hi @techietk02

To prevent removing members you can try `Apigee Edge Actions module` which provides support for a number of Apigee Edge-specific Events
See https://www.drupal.org/docs/contributed-modules/apigee-edge/manage-reaction-rules#s-team

**Comment by techietk02** [comment]
Hi shishir ,Thanks for the reply , To enable action module we need to install rules module which i am getting error for drupal 10 versions (unable to install). Is there any other way ,Like programmatically so that i can achieve the solution to the problem.

**Comment by shishir-intelli** [comment]
Yes, action module requires `Rules` module and Rules module is available for Drupal 10.
Could you tell us what error you are getting while installing `Rules` module and please share the Drupal 10 and PHP versions as well.

**Comment by shishir-intelli** [comment]
Hope this issue is resolved.
Closing this issue, feel free to re-open for any further help.
