### ISSUE TITLE
Some users with many subscriptions are unable to view the create new app form

### ISSUE THREAD

**Issue by MahmoudSayed96** [apigee/apigee-edge-drupal#1067]
## Description
If the user has more than 100 subscriptions and API products count more than 250 product
and try to access the create app form portal not working fine and breaks down.

## Apigee Info
I am using  Apigee Edge.

## Steps to Reproduce
1. Go to the 'Apps page'
2. Click on 'Create app'

## Expected Behavior
Create app form page open and working fine.

# Screenshots
![create-app-form-issue](https://github.com/user-attachments/assets/82e26f4e-f8f5-486b-b72d-27f798e37ce6)

## Version Info
Apigee version: 3.0
Drupal version 10.2

**Comment by kedarkhaire** [comment]
Hi @MahmoudSayed96 
Thanks for sharing the bug, we will check the issue. Please confirm if the subscription is Rateplans, right.

**Comment by MahmoudSayed96** [comment]
Hi @kedarkhaire ,
Thanks for your response, yes

**Comment by kedarkhaire** [comment]
Hi @MahmoudSayed96 
I tried to replicate the issue with more than 800 products and all the subscriptions I have.
For me it is working fine, the app page is loaded and the app is also created.

Can you please enable Apigee Debug module and check the logs by following the same steps? Do provide us the details.
If same error occurs, the debug detail will be listed in Recent logs, Can you please check those and update the error here related to the issue.

Type of organization - if hybrid ?
how many rate plans the user has subscribed to.
PHP version.
apigee edge version used.
If any additional fields added via field ui or any custom fields added.

Thanks!

**Comment by kedarkhaire** [comment]
Hi @MahmoudSayed96 Closing this issue as there is no response on the ticket for long time. Feel free to reopen this if you have updated on the above queries asked.
Thanks!
