### ISSUE TITLE
Edit AppGroup is clearing the previously added developers in the appgroup

### ISSUE THREAD

**Issue by sindhuputti** [apigee/apigee-edge-drupal#1074]
## Description
Create an appgroup, add members to the appgroup. Edit AppGroup,  it is clearing the previously set developers in the appgroup.

## Steps to Reproduce
1. Add a new Appgroup on developer portal and add some members to it.
2. Edit the appgroup, it will reset all the existing members, only one developer who is editing the appgroup is being added as a developer.

## Actual Behavior
When editing the appgroup, all the previously added members after the appgroup creation are gone.

## Expected Behavior
An appgroup should persist the previously added developers.

## Version Info
This can be the version you can see on admin/modules in Drupal or 
the output of this command: `composer show`.  Add Drupal core and
other version information if needed.
apigee/apigee-client-php                        3.0.5           Client library for connecting to the Apigee Edge API.
apigee/apigee-mock-client-php             1.1.2           To be used for queueing mock API responses for the `apigee/apigee-client-php` library.
apigee/apigee_devportal_kickstart         2.1.6           A fast demo and starting point for Apigee Developer Portals.
drupal/core                                                10.1.8          Drupal is an open source content management platform powering millions of websites and applications.
drupal/core-composer-scaffold             10.1.8          A flexible Composer project scaffold builder.
drupal/core-project-message               10.1.8          Adds a message after Composer installation.
drupal/core-recommended                   10.1.8          Core and its dependencies with known-compatible minor versions. Require this project INSTEAD OF drupal/core.

**Comment by kedarkhaire** [comment]
Hi @sindhuputti I will check and look into it.
Thanks!

**Comment by kedarkhaire** [comment]
Hi @sindhuputti 
We checked the above implementation, 
Post editing the Appgroup, no members were deleted unless the Team member sync was ran.
We saw post running the Team member sync only when the Appgroup are edited/updated, we see the missing members on Appgroup.
We assume that there might be some code in your other custom module to sync the team members on AppGroup update, which leads to this issue.
Anyways this should not happen, so we have created a [PR](https://github.com/apigee/apigee-edge-drupal/pull/1072) & [patch](https://github.com/apigee/apigee-edge-drupal/pull/1072.patch) for it.

Please try to apply this [patch](https://github.com/apigee/apigee-edge-drupal/pull/1072.patch) and post your checks do let us know, if it works for you.

Thanks!
