### ISSUE TITLE
Website is going down and throwing error after updating apigee_edge module

### ISSUE THREAD

**Issue by sathyaprakash-mind** [apigee/apigee-edge-drupal#1084]
## Description
After updating the Apigee_edge module from 8.x-1.26 to the version
apigee_edge-2.1.4 . I am getting the below error and the site is going down.
I am not able to run the updb and clear cache using drush commands. It is throwing below error:

$ drush updb
   [warning] Undefined array key "apiProducts" App.php:358
PHP Fatal error:  Uncaught Error: Call to a member function
setDisplayConfigurable() on null in
C:\xampp\htdocs\devportal\web\modules\contrib\apigee_edge\src\Entity\App.php:358.

## Apigee Info
Please specify if you are using Apigee X, Apigee Edge, or OPDK. - Apigee Edge

## Steps to Reproduce
1. Update the apigee_edge drupal module from  8.x-1.26 to the version 2.1.4
2. Try to load the site or clear the cache
3. Issue is reproduced

## Actual Behavior
I am getting the below error and the site is going down.
I am not able to run the updb and clear cache drush commands. It is throwing below error:
$ drush updb
   [warning] Undefined array key "apiProducts" App.php:358
PHP Fatal error:  Uncaught Error: Call to a member function
setDisplayConfigurable() on null in
C:\xampp\htdocs\devportal\web\modules\contrib\apigee_edge\src\Entity\App.php:358.

## Expected Behavior
The site should not throw any errors after the upgrade of the apigee_edge module 

## Notes
I suppose the issue is with 'apiProducts' from App.php line. no. 348.

## Version Info
Drupal core version: 9.4.8
apigee_edge: 1.26.0.0 / 8.x.1.26

**Comment by kedarkhaire** [comment]
Hi @sathyaprakash-mind 
Please upgrade your Drupal site & Apigee modules to their latest version.

Also I see that you are migrating your modules directly from 8x1.26 to 2.1.4

I recommend you to do the following upgrades.

1. First do update database on the same version, to make sure, the current version updates are reflected on your current database.
2. Upgrade the module to specific version, where the security updates _(8.x 1.27)_ are mentioned. Please check [releases list](https://www.drupal.org/project/apigee_edge/releases). Once you are on those security update versions, do the database update, clear your cache and then check your site.
3. Continue point 2 till you have all the last security update, and do the database update, clear your cache and then check your site.
4. Post that upgrade your module to the latest version compatible to your drupal version site & do the database update, clear your cache and then check your site.

But also upgrade your site to Drupal's latest version as the version you are using has already reached its end of life.
Also accordingly do upgrade your modules.

Thanks!
