### ISSUE TITLE
Error during updating App

### ISSUE THREAD

**Issue by rajdeep2608** [apigee/apigee-edge-drupal#1090]
## Description
When we are trying to update an PP, its throwing an error : " 1 error has been found: APIs"

## Apigee Info
Apigee Edge

## Steps to Reproduce
1. Go to Edit form of any existing App
2. Click on Submit
3. The form is showing an error " 1 error has been found: APIs"
4. Hovering on the 'APIs' link gives "/user/401/apps/{user}/edit#edit-credential-{apiproduct-data}"

## Actual Behavior
The form is showing an error " 1 error has been found: APIs"

## Expected Behavior
the form must submit to update the App

## Screenshots
![image](https://github.com/user-attachments/assets/d911a05a-9a80-4d06-bda9-9600f110bce2)

## Version Info
Drupal 9.5.11
Apigee edge 2.0.11

**Comment by kedarkhaire** [comment]
Hi @rajdeep2608 

The Drupal & Apigee module version you are using is very old and are insecure to use.
Please upgrade your modules and your Drupal site to the latest version to avoid the issue.

Upgrade the and modules, update the database, clear cache and do check again.

I am editing your request details as you have mentioned the private details in it. Please try to avoid to add the PII data in public forums or issue lists.

Thanks!

**Comment by rajdeep2608** [comment]
@kedarkhaire 

Thanks for your input.

 Is it sufficient to update the Apigee Edge module to 3.0 version? 

Upgrading Drupal 9 to 10 will take much time for me.

**Comment by kedarkhaire** [comment]
Not with version 3
But you can check with [apigee_edge 2.1.4](https://www.drupal.org/project/apigee_edge/releases/2.1.4)
Thanks!

**Comment by kedarkhaire** [comment]
Hi @rajdeep2608 
Considering the query is solved by above inputs and closing this issue as there is no response on it. If the issue is not solved, feel free to reopen the issue with specific details and use cases.
Thanks!
