### ISSUE TITLE
[ERROR] Malformed inline YAML string:

### ISSUE THREAD

**Issue by rakeshjames** [apigee/apigee-edge-drupal#110]
[ERROR] Malformed inline YAML string: [ '@apigee_edge.sdk_connector',          
         '@apigee_edge.controller.organization',                                
         '@apigee_edge_teams.controller.cache.team',                            
         '@apigee_edge_teams.controller.cache.team_ids',                        
         '@apigee_edge.entity.controller.cache.general_app_cache_by_owner_factor
         y', '@apigee_edge.entity.controller.cache.app_name_by_owner_factory',  
         '@apigee_edge_teams.cache.company_membership_object',                  
         '@apigee_edge.controller.cache.developer_companies', at line 25 (near "
          '@apigee_edge.controller.cache.developer_companies',")

**Comment by rakeshjames** [comment]
Please review https://github.com/apigee/apigee-edge-drupal/pull/116

**Comment by mxr576** [comment]
#117 Fixes this, see details in #116. Thanks again @rakeshjames for reporting this!
