### ISSUE TITLE
Clearing the cache with drush without the private file system being configured produces a warning.

### ISSUE THREAD

**Issue by Jaesin** [apigee/apigee-edge-drupal#128]
| Q                           | A
| --------------------------- | -----------------------------------------------
| Bug?                        | yes

#### Actual Behavior

Clearing the cache without a private file system configured can cause a warning.

See; https://github.com/apigee/apigee-edge-drupal/pull/103#discussion_r252156341

#### Expected Behavior

Clearing the cache without a private file system configured should not cause a warning and should not create a token storage file in a `private:` directory in the web root.

#### Steps to Reproduce the behavior

Configure the Apigee edge connections settings using something other than `apigee_edge_private_file`. Clear the cache using drush. You should see:

```
...
 [warning] file_exists(): Unable to find the wrapper "private" - did you forget to enable it when you configured PHP? OauthTokenFileStorage.php:204
...
```

#### Proposed Solution

Check that the private file system is configure before saving token data.
Add a tests for this user case.

**Comment by mxr576** [comment]
Issue description is incorrect, it every cache clear attempt - including update hooks - can generate these errors when private FS is not configured.

**Comment by mxr576** [comment]
Fixed. https://github.com/apigee/apigee-edge-drupal/pull/103/commits/b6516582760a8f63904cbca6dd25f31cde518582
