### ISSUE TITLE
Getting file_private_path error during Edge configuration

### ISSUE THREAD

**Issue by jbennett13** [apigee/apigee-edge-drupal#143]
| Q                           | A
| --------------------------- | -----------------------------------------------
| Bug?                        |yes
| New Feature?                |no
| Module Version              |dev branch
| PHP Client version          |7.1.25
| Requires PHP client fix     |no

When setting up the Edge configuration for the connection the the Developer Portal, the connection fails even when the private file path is updated in the settings.php.  The error message states:  "Unable to initialize configuration.  The Apigee Edge connection settings are not configured... Make sure the file_private_path is configured and try again."

#### Steps to Reproduce the behavior

1.  Installed Apigee Kickstart and Drupal 8 using Lando
2.  Changed permissions to modify the settings.php in web/sites/default/settings.php
3.  Changed file_private_path to '/app/private'
4.  Saved, cleared caches in D8
4.  Checked Configuration >Media>File System to make sure that the  private file path was captured

On Edge configuration page:

<img width="1266" alt="screen shot 2019-02-28 at 10 01 49 am" src="https://user-images.githubusercontent.com/20446683/53597992-d5b7c300-3b60-11e9-80c4-96b97d3b99d5.png">

**Comment by cnovak** [comment]
This may mean the directory does not exist, or that Drupal does not have permission to write to that directory. Try going to **Reports > Status Report**, it should show you detailed errors if you have one of these issues.

Make the '/app/private' directory exists. Since you are using Lando the '/app/private' will be mounted to the root of your project directory. You should see a 'private' directory in the same directory you run `lando start` from.

**Comment by mxr576** [comment]
This is also related to #137. @peterserfozo is working on that in this sprint. He'll probably fix this problem and related ones in a new PR.

**Comment by mxr576** [comment]
#137 merged, @jbennett13 could you please install the latest dev version from Github and verify whether you still have the reported issue?

**Comment by mxr576** [comment]
@jbennett13 Can you confirm that the reported bug has gone away with RC1?
https://www.drupal.org/project/apigee_edge/releases/8.x-1.0-rc1

**Comment by mxr576** [comment]
This issue should be resolved since rc1. Closing this issue.
