### ISSUE TITLE
Multiword override of status yields invalid class

### ISSUE THREAD

**Issue by boobaa** [apigee/apigee-edge-drupal#153]
| Q                           | A
| --------------------------- | -----------------------------------------------
| Bug?                        | yes
| New Feature?                | no|yes
| Module Version              | 8.x-1.0-beta2
| PHP Client version          | 2.0.1
| Requires PHP client fix     | no

#### Actual Behavior

When the app status text is overridden from a custom module (like "in progress" instead of "pending"), the actual class becomes `status-value-in progress`.

#### Expected Behavior

In this case, the class should be `status-value-in-progress`.

#### Steps to Reproduce the behavior

- Override the `_controller` for the `entity.developer_app.collection_by_developer` route via a RouteSubscriber as usual.
- Override the `buildInfoRow()` method:
  ```php
  protected function buildInfoRow(AppInterface $app, array &$rows) {
    parent::buildInfoRow($app, $rows);
    $css_id = $this->getCssIdForInfoRow($app);
    $row = &$rows[$css_id];
    if ($row['data']['status']['data']['#value'] == 'pending') {
      $row['data']['status']['data']['#value'] = 'in progress';
    }
  }
  ```

#### Proposed Solution

Use `\Drupal\Component\Utility\Html::cleanCssIdentifier()` instead of `strtolower()` in `template_preprocess_status_property()`.

**Comment by mxr576** [comment]
Thanks for the bug report @boobaa, I'd suggest to call `\Drupal\Component\Utility\Html::getClass()` in `template_preprocess_status_property()` to make sure the generated CSS class from the field value is a valid.

**Comment by mxr576** [comment]
#154 merged, thanks again!
