### ISSUE TITLE
DRUP-667 Display expired credentials as such

### ISSUE THREAD

**Issue by boobaa** [apigee/apigee-edge-drupal#156]
| Q                           | A
| --------------------------- | -----------------------------------------------
| Bug?                        | yes
| New Feature?                | no
| Module Version              | 8.x-1.0-beta2
| PHP Client version          | 2.0.1
| Requires PHP client fix     | no

#### Actual Behavior

When a credential is expired, it is displayed on the app details page like:
```
Expires: 17 minutes 25 seconds ago
Key Status: approved
```
I understand that this is what the management server returns, but it's still confusing to the end users as they can't use this credential.

#### Expected Behavior

```
Key Status: expired
```

#### Steps to Reproduce the behavior

- On Edge's web UI, create a credential for an app with the expiration set to duration/2 minutes.
- Wait at least those 2 minutes.
- (Re)Load this app's details page in Drupal.

#### Proposed Solution

`template_preprocess_app_credential()` in `apigee_edge.module:998` could be changed to display `expired` as `#value` and `StatusPropertyElement::INDICATOR_STATUS_ERROR` as `#indicator_status` when the credential is expired.

**Comment by mxr576** [comment]
Thanks, @boobaa, I like the suggested solution. 
I would extend it with one additional change. I think if we start reporting expired keys (as we should) on the app details page, we should start reporting them on the app listing page as well:
![image](https://user-images.githubusercontent.com/1755573/54199732-f6213f00-44c9-11e9-9a5e-dd0e6b527041.png)

**Comment by mxr576** [comment]
Created a JIRA issue for this issue and any related PR.

**Comment by mxr576** [comment]
@cnovak @arunz6161 This is also something that we could pick for the next sprint. What do you think?

**Comment by arunz6161** [comment]
Arun to add screenshots to highlight expected behavior.

**Comment by arunz6161** [comment]
Below are a couple of screenshots that highlight the behavior in D7. We should have D8 exhibit the same behavior.
![expired_app](https://user-images.githubusercontent.com/4381612/67899791-47954180-fb20-11e9-9879-a8ebb19db849.png)
![Key_Expiry_status](https://user-images.githubusercontent.com/4381612/67899796-4a903200-fb20-11e9-899b-b7a202a789c6.png)
