### ISSUE TITLE
DRUP-683 Allows to configure maxBodyLength in FullHttpMessageFormatter

### ISSUE THREAD

**Issue by mxr576** [apigee/apigee-edge-drupal#168]
| Q                           | A
| --------------------------- | -----------------------------------------------
| Bug?                        | no
| New Feature?                | yes
| Module Version              | rc1
| PHP Client version          | n/a
| Requires PHP client fix     | no

Monetization API returns quite a huge API response bodies. The currently hardcoded 1000 characters that the debugger module stores in logs from response bodies may not be enough for debugging MINT API responses. It would be beneficial if this parameter could be configured with a service parameter or a config key.

**Comment by arunz6161** [comment]
To be reopened if we see community running in to the limitation. Closing this as per effort to narrow down the backlog.
