### ISSUE TITLE
DRUP-687 Prefix CSS selectors in Apigee Edge

### ISSUE THREAD

**Issue by shadcn** [apigee/apigee-edge-drupal#169]
| Q                           | A
| --------------------------- | -----------------------------------------------
| Bug?                        | yes
| New Feature?                | no
| Module Version              | 8.x-1.x
| PHP Client version          | 2.0.1
| Requires PHP client fix     | no

#### Actual Behavior

The Apigee Edge module adds CSS styles that are too general. Example:

https://github.com/apigee/apigee-edge-drupal/blob/ffeedfe54e7950260507c25e2ed50a36b0de2d98/css/apigee_edge.app_view.css#L18-L33

This breaks the layout of field on other pages (where the `apigee_edge.app_view` library is present) and makes it harder for themes to override.

#### Proposed Solution

Make this module/element-specific by using a selector prefix. Example: `.apigee-foo .field`.

**Comment by mxr576** [comment]
The `apigee_edge.app_view` library should be added to app view pages only, this is what its name suggests.
* Which pages do you see this problem?
* Can you make sure that you did not add accidentally this library (CSS) to the page(s) that you see this problem?

**Comment by mxr576** [comment]
Checked it and the Apigee Edge module only adds this library (CSS) to the app view pages.

https://github.com/apigee/apigee-edge-drupal/blob/8.x-1.0-rc1/apigee_edge.module#L247

Does your problem related to the app view page?

The CSS selectors are general enough in this file so you can override it with a more specific one any time.

**Comment by shadcn** [comment]
Yes. But we can't assume that there won't be any other `.field` element on the page. A simple block with fields in a region will break. See screenshot below.

Prefixing the selector solves this. It still works for Apigee Edge and does not break the styles for other fields. `.field` is a CSS class that is very common.

![apigee-edge-selector](https://user-images.githubusercontent.com/124599/55150523-b616b900-5165-11e9-8ad1-f1a02dd2693e.jpg)

**Comment by mxr576** [comment]
Good point. I did not write these CSS files so I did not notice that for the first sight. I'll create a PR with a fix that limits these selectors to the content region.

**Comment by mxr576** [comment]
https://www.drupal.org/project/drupal/issues/2808481 related issue on Drupal.org. Entities do not have default templates, therefore, they do not have an HTML wrapper within the content region ;S

**Comment by shadcn** [comment]
@mxr576 It seems that this is not going to be fixed anytime soon in core. Could we at least fix it in edge so that we are not breaking client sites? Maybe a `#prefix` or a container wrapper in the preprocess?

**Comment by mxr576** [comment]
Yes, I am going to work on this in the remaining days of this sprint.
