### ISSUE TITLE
DRUP-734 \Drupal\apigee_edge\Form\AuthenticationForm does not update key on submit

### ISSUE THREAD

**Issue by shadcn** [apigee/apigee-edge-drupal#176]
| Q                           | A
| --------------------------- | -----------------------------------------------
| Bug?                        | yes
| New Feature?                | no
| Module Version              | `8.x-1.x`
| PHP Client version          | `2.0.1`
| Requires PHP client fix     | no

#### Actual Behavior

On submit, the `\Drupal\apigee_edge\Form\AuthenticationForm` does not update the active key.

#### Expected Behavior

The active key should be updated when the `\Drupal\apigee_edge\Form\AuthenticationForm` form is submitted.

#### Steps to Reproduce the behavior

1. Enable Apigee Edge.
2. Visit _/admin/config/system/keys_ and edit the default key.
3. Select *Configuration* as the key provider.
4. Add credentials and save. Credentials are saved successfully.
5. Visit _/admin/config/apigee-edge/settings_
6. Enter credentials and save.
7. Credentials are *NOT* updated.

#### Proposed Solution

Replace

https://github.com/apigee/apigee-edge-drupal/blob/9e753e8f8f390489dea2e2ec38571a13563bdb5f/src/Form/AuthenticationForm.php#L361-L364

With

```
$this->activeKey->setKeyValue($processed_submitted);
$this->activeKey->save();
```

`$this->activeKey->save()` will call the `keyProvider->setKeyValue` automatically. See `\Drupal\key\Entity\Key::preSave`

**Comment by mxr576** [comment]
@arshad If you already have an idea for the fix, please create a PR. This issue surprises me because authentication form has not been touched since a couple of sprints.

**Comment by mxr576** [comment]
Also, if this true it means we are missing something in the authentication form tests so please provide a fix or an additional test case that covers this issue.

**Comment by mxr576** [comment]
PR merged.
