### ISSUE TITLE
Is there an upgrade path from D7?

### ISSUE THREAD

**Issue by nextagencyio** [apigee/apigee-edge-drupal#180]
There was a D7 module that provided similar functionality (ie connecting users, apps to apigee)? Is there any kind of migration path for D7?

**Comment by arunz6161** [comment]
As you are aware, there is a significant difference between D7 and D8 and hence one would have to rewrite any custom modules from D7 to get them working on D8. However since the data from edge remains the same, we are trying to explore what an migration would entail. We will keep you posted.

**Comment by nextagencyio** [comment]
Ya it seems like if you could Migrate the data, configuration from D7.

**Comment by mxr576** [comment]
It really depends on how much customization the Drupal 7 portal has that you would like to upgrade to Drupal 8. As Arun wrote, the vanilla Drupal 7 portal stores the majority of data in Apigee Edge. If you do not have too many customizations then you can use Apigee Edge as "shared storage". For example, you can use the Developer synchronization to pull down developers from Apigee Edge and create Drupal users from them in Drupal 8.
For migrating data from custom modules and data that is not stored in Apigee Edge you can use Drupal 8's quite advanced Migrate API: https://www.drupal.org/docs/8/upgrade

**Comment by nextagencyio** [comment]
Thanks for the info that makes sense. I was just thinking it might be nice to upgrade the Apigee connection configuration from 7 to 8 altho it probably isn't that much effort to just reconfigure in D8.

**Comment by mxr576** [comment]
@drupalninja You are right, it would not be that much effort to create a migration for that. Although it would definitely take more time to implement it than the 30-60 seconds that you spend with configuring the credentials manually on the UI and you only need to do this once.

**Comment by mxr576** [comment]
Closing this after 2 weeks inactivity.
