### ISSUE TITLE
Track release notes in CHANGELOG.md

### ISSUE THREAD

**Issue by mxr576** [apigee/apigee-edge-drupal#187]
Initially, it seemed to be a good idea to store and publish changes in a new release as release notes on Drupal.org. This is/was the Drupal way. Although this approach always caused extra work for us, we had to go through all new commits since the previous release and figure out what should we add to the release notes. This process is also prone to error.

If we would use the CHANGELOG.md for tracking changes, then we could add new entries to the release notes as part of a PR. We would not need to check back before a release what has changed since the previous version, because it would be in the CHANGELOG.md already, we would need to tag the list of changes with a release number. The related section in the CHANGELOG.md could be deeplinked in a release note on Drupal.org.

**Comment by mxr576** [comment]
I decided to open this issue finally when we made the 2nd (possible) BC breaking change in this sprint: #183 #181. We should not forget to highlight these in our release notes.

We could also try to auto-generate the changelog with a tool like https://packagist.org/packages/symplify/changelog-linker.

**Comment by jacine** [comment]
FYI: I found this the other day, and it may be worth a try.  There is an issue for it: DRUP-749.

App: https://github.com/apps/release-drafter
Source: https://github.com/toolmantim/release-drafter

**Comment by mxr576** [comment]
We should look for other alternatives. I'd rather prefer to use a tool that does not require complete write access to a repo.

**Comment by cnovak** [comment]
If we use `CHANGELOG.md` , we would need to make sure that stays in sync with the [release notes page on Drupal.org](https://www.drupal.org/project/apigee_edge/releases), and it takes a PR to change a `CHANGELOG.md` versus editing the release page on Drupal.org if we need to edit/update the release notes.

**Comment by mxr576** [comment]
It does not need to "stay in sync", because after changelog (release notes) gets tracked only in CHANGELOG.md, we'll only share a deep link to the related section in CHANGELOG.md in Drupal.org release notes.

Although the versioning is different but the PHP API client already has a CHANGELOG.md, so let's use that for an example. If 2.0.1 would be the next release of the Apigee Edge, on Drupal org, we would only add something like this to the release notes: "Please see the release notes on [Github](https://github.com/apigee/apigee-client-php/blob/2.x/CHANGELOG.md#201---2019-02-06)."

**Comment by mxr576** [comment]
Another MIT licensed, commonly used, option: https://github.com/github-changelog-generator/github-changelog-generator

**Comment by cnovak** [comment]
Our current process is to put up all changes on the project in Drupal.org and link to the GitHub milestone, for example: https://www.drupal.org/project/apigee_edge/releases/8.x-1.20
