### ISSUE TITLE
API product access tab missing from API Product Admin settings

### ISSUE THREAD

**Issue by cnovak** [apigee/apigee-edge-drupal#189]
| Q                           | A
| --------------------------- | -----------------------------------------------
| Bug?                        | yes
| New Feature?                | no
| Module Version              |  2473dfac8287566034fccc54d6d559a6da731d90 dev-8.x-1.x-smartdocs
| PHP Client version          |  2.0.1
| Requires PHP client fix     | no
#### Actual Behavior
The API product settings admin page is missing the "API product access" tab, it is being shown on the "Developers" tab
<img width="956" alt="Screen Shot 2019-05-03 at 5 01 14 PM" src="https://user-images.githubusercontent.com/613093/57171035-8cd0f480-6dc5-11e9-9f6f-18c445b75880.png">

#### Expected Behavior

Should display on "API product" settings page

#### Steps to Reproduce the behavior

Go to `admin/config/apigee-edge/product-settings/alias`, you will see "API product access" tab is missing.  

#### Proposed Solution

Change tab to display on "API product" settings page

**Comment by mxr576** [comment]
It is not "missing". It has been moved to a new place. See explanation in https://github.com/apigee/apigee-edge-drupal/pull/190#issuecomment-489514000.

**Comment by mxr576** [comment]
PR has been merged, documentation has to be updated. @llynch00
