### ISSUE TITLE
REQUIREMENT_ERROR during install

### ISSUE THREAD

**Issue by kscheirer** [apigee/apigee-edge-drupal#205]
| Q                           | A
| --------------------------- | -----------------------------------------------
| Bug?                        | yes
| New Feature?                | no
| Module Version              | 1.0.0-rc5
| PHP Client version          | 2.0.2
| Requires PHP client fix     | no

#### Actual Behavior

Installing via core/install.php fails on the "Verify requirements" tab. The install process cannot continue past this point.

#### Expected Behavior

Able to install successfully.

#### Steps to Reproduce the behavior

- `git clone https://github.com/laughingbiscuit/docker-apigee-drupal-kickstart.git`
- `cd docker-apigee-drupal-kickstart/`
- `./start.sh`
- open a browser tab for `localhost:8080`
- click "continue with english"

<img width="790" alt="Screen Shot 2019-05-28 at 2 43 13 PM" src="https://user-images.githubusercontent.com/283628/58514775-b4fb0b80-8157-11e9-8454-834ae028a096.png">

#### Proposed Solution

The hook_requirements() in https://github.com/apigee/apigee-edge-drupal/blob/8.x-1.x/modules/apigee_edge_apidocs/apigee_edge_apidocs.install is the source of this error.

Use REQUIREMENTS_WARNING for all phases? If you want it to be an error on the status report page, check for `$phase == 'runtime'`.

**Comment by mxr576** [comment]
@kscheirer This is a kickstarter issue (https://github.com/apigee/apigee-devportal-kickstart-drupal/issues/117) which has been addressed with the new rc1.

**Comment by kscheirer** [comment]
makes sense, thanks!
