### ISSUE TITLE
user name is not unique at edge but unique at devportal

### ISSUE THREAD

**Issue by aparnak123** [apigee/apigee-edge-drupal#21]
| Bug?                        | yes

#### Actual Behavior

What is the actual behavior?

Syncing developers causing failure due to duplicate usernames at edge

**Comment by mxr576** [comment]
Hi @aparnakondala123,

yes, this is an actual difference between Drupal and Apigee Edge. You should make sure that usernames on Apigee Edge are unique before you would start using the sync.

**Comment by aparnak123** [comment]
so its a manual process to make usernames unique?

**Comment by mxr576** [comment]
If you had non-unique names on Apigee Edge for some reasons then yes, fixing them is a manual process. You can use the https://github.com/apigee/apigee-client-php and write a simple PHP script that automatically fixes the non-unique usernames on the organization that you are using.
