### ISSUE TITLE
[DOC] Update install instructions

### ISSUE THREAD

**Issue by mxr576** [apigee/apigee-edge-drupal#211]
After a new version released from the PHP API Client with the change in #54, the install instructions of the Apigee Edge module needs to be updated all places.

For example:https://www.drupal.org/docs/8/modules/apigee-edge/configure-the-connection-to-apigee-edge#configuring-oauth2-authentication-for-apigee-edge

**Comment by mxr576** [comment]
Follow up on https://github.com/apigee/apigee-client-php/issues/56

This is currently *blocked* until the new PHP API client is not out.

**Comment by jbennett13** [comment]
Are we back on track with needing docs updated?  If so, could you point me to what has changed with the PHP API Client that should be updated?  Is it a patch that should be removed?  Thanks.

**Comment by cnovak** [comment]
I think this is outdated and no longer needed, but reopen if needed.
