### ISSUE TITLE
[DOC] Update the configure connection documentation

### ISSUE THREAD

**Issue by mxr576** [apigee/apigee-edge-drupal#212]
Since #179, the available key providers are also visible on the Authentication form so there is no need to navigate to the Key entity form to select a custom key provider as credentials storage.

https://www.drupal.org/docs/8/modules/apigee-edge/configure-the-connection-to-apigee-edge#user-defined-credential-storage

**Comment by arunz6161** [comment]
@arshad Can you cross check https://github.com/apigee/apigee-edge-drupal/pull/179 and provide  details on what in the doc should be udpated ?

**Comment by shadcn** [comment]
Sure. So previously you had to visit **Configuration** -> **System** -> **Keys** to change the key provider (see screenshot below).

![Edit_key_Apigee_Edge_connection___Apigee](https://user-images.githubusercontent.com/124599/79105691-35cbf180-7d82-11ea-9f5d-b021b3e82111.jpg)

You don't need to do this anymore. You can change the provider from the **Configuration** -> **Apigee Edge** -> **General** page itself (screenshot below).

![ps-provider](https://user-images.githubusercontent.com/124599/79105754-54ca8380-7d82-11ea-92b6-eba6f121bf9f.gif)

We need to update the following sections and remove wherever it says *Configuration > System > Keys*.

1. https://www.drupal.org/docs/8/modules/apigee-edge/configure-the-connection-to-apigee-edge#s-apigee-edge-credential-key-storage-details
2. https://www.drupal.org/docs/8/modules/apigee-edge/configure-the-connection-to-apigee-edge#s-update-the-key-provider

**Comment by jbennett13** [comment]
@arunz6161 :  I added **Configuration -> Apigee Edge -> General** to the sections addressing updates to the key provider.  I left **Configuration -> System -> Keys** for those sections that mention how to see key provider details (**type** and **provider**).  Can we close this?
