### ISSUE TITLE
Custom attributes (app/ developer) returning an array to edge

### ISSUE THREAD

**Issue by dharma-adusumilli** [apigee/apigee-edge-drupal#22]
| Q                           | A
| --------------------------- | -----------------------------------------------
| Bug?                        | Believe so

#### Actual Behavior
Custom attribute, may it be for a developer or developer app is returning an array in Edge UI.

#### Expected Behavior

Expect to just see the value in the custom attribute area of the entity (developer/ app) on the edge UI. This was functioning as expected with D7 devconnect module.

#### Steps to Reproduce the behavior

1. Create a custom attribute for a developer or developer app using UI on the  **Configuration -> Apigee Edge -> App Settings -> Manage fields** or  **Configuration -> People -> Account settings** pages

2. Create a developer or developer app from the DevPortal with some value entered for the custom attribute field created in the previous step

3. Open Edge UI and access the custom attribute under the entity (developer or app) - should see an array in the "Value" column

![image](https://user-images.githubusercontent.com/20174666/40991821-f895f200-68c2-11e8-945f-b620c2a0d9fd.png)

#### Proposed Solution

Populate just **value** from the array

**Comment by giteshk** [comment]
This will be addressed in Alpha3 release

We have decided to only allow the following fields to be serialized in simple format

- Text Box
- Text Area
- Drop-down Select
- Single Checkbox
- List of Checkboxes
- Radios


Any other complex drupal fields will be saved in the internal JSON format. We will address other fields when we see the need to add those.

**Comment by mxr576** [comment]
Alpha3 is out: https://www.drupal.org/project/apigee_edge/releases/8.x-1.0-alpha3

> Field values of the following field type are being saved in CSV format instead of JSON to attributes on Apigee Edge:
> 
>     Boolean
>     Numbers (integer, float, decimal)
>     List (integer, float, decimal)
>     Text (plain)
>     Text (plain, long)

**Comment by mxr576** [comment]
@dharma7 Have you tested the changes that we introduced in alpha3? Can we close this issue?

**Comment by mxr576** [comment]
I am closing this ticket. Feel free to re-open this or create a new one if you need.
