### ISSUE TITLE
Make the contents Team List/Members/Apps row contents theme-able.

### ISSUE THREAD

**Issue by jacine** [apigee/apigee-edge-drupal#220]
Since we do not have Views module to work with, and there has been no extra attempt to make these pages customizable, these pages are nearly impossible to customize in a theme.

The following contents are in these tables (across a few pages), and we should at least attempt to make them more easily customizable without having to write custom modules / controllers.

| Column | Theme-able? | Suggestion |
| :------ | :---------- | :--------- |
| Team/Member name | No | Use a template that allows for changing the link text and URL. |
| Roles | Almost | `item-list.html.twig` is used, but that is not enough, as no context is provided. Suggestions should be used, e.g. `'#theme' => 'item_list__member_roles'` |
| Status | Yes | Custom template implementation, `status-property.html.twig` exists. 👍  |
| Operations | No | `#type => 'operations'` is a wrapper around a more targeted `links` suggestion: `links__dropbutton__operations`.  Beyond that no context is available, so it's not possible to make any changes to this, without making them globally.  More targeted theme hook suggestions should exist, so the context can be determined, and this element on teams, team members, or both can be targeted and customized if desired. For example, on "Teams" the drop button contains "Team Apps", "Members", "Edit" and "Delete".  Viewing Team Apps/Members is not technically an operation, and it's reasonable to prefer to only print the actual operations, "edit" and "delete" and present them as simple links with icons, like: ![operations](https://user-images.githubusercontent.com/60979/59287347-79743d00-8c3f-11e9-906c-9bc90d7dca42.png) This same example/pattern should also be applicable to the team members list.

**Comment by mxr576** [comment]
I am not against making front-enders life easier, but this reasoning:

> Viewing Team Apps/Members is not technically an operation, and it's reasonable to prefer to only print the actual operations, "edit" and "delete" and present them as simple links with icons,

indicates to me that you are not satisfied with what the renderable content that the original page controller prepared and passed to the front-end and you are trying to manipulate it on the front-end side. In this case, we are not speaking about "what should be displayed where and how" type of change, you are actually trying to remove content that on _the page controller spent time_ to prepare it for the front-end.

If you would rather replace the original page controller of this page to a new controller and that controller would actually prepare and pass _only that data_ that the front-end needs you could achieve a better maintainable code and performance.

I am also open for suggestions where and how we could display "team apps" and "members" links in a better way in the original page controller. :)

**Comment by mxr576** [comment]
> item-list.html.twig is used, but that is not enough, as no context is provided. Suggestions should be used, e.g. '#theme' => 'item_list__member_roles'
> #type => 'operations' is a wrapper around a more targeted links suggestion: links__dropbutton__operations.

Processed all this information for a while and I have questions because I would like learn something new again :) 

These suggestions may fix theming issues of the team members list, but what about other places where we intentionally used built-in Drupal core render elements instead of custom ones? Should we also replace them? For example, the entity operations on the developer/team app lists.

Do you have a core or contrib module example that does something similar to make front-end developers' easier? Or every other contrib module developers also expects that if the default markup is not good enough for someone, it will override the component that produces the render array, for example, the page controller.

**Comment by kscheirer** [comment]
related to #239
