### ISSUE TITLE
"Apps" menu links does not respect the plural label of the developer apps entity anymore

### ISSUE THREAD

**Issue by mxr576** [apigee/apigee-edge-drupal#223]
Before #183 the "My Apps" menu link title always reflected the plural label (alias) of the developer app entity. For example, if the alias was "Foo" (singular) and "Foos" (plural) then the title of the "My Apps" menu item was "My Foos". Since #183 it is hard-coded to "Apps".
Even if the "My" prefix has been removed, it should respect and display the plural label of the developer app entity.

**Comment by mxr576** [comment]
Credit goes to @kittiradovics for the discovery.

**Comment by VladimirAus** [comment]
In addition, page title does not respect the same change as oppose to Team Apps settings.

<img width="1150" alt="Screen Shot 2020-09-07 at 11 05 56 pm" src="https://user-images.githubusercontent.com/1356166/92391809-a411b600-f160-11ea-801a-e57d61d71539.png">
===
<img width="1401" alt="Screen Shot 2020-09-07 at 11 04 36 pm" src="https://user-images.githubusercontent.com/1356166/92391816-a70ca680-f160-11ea-9ff8-c15f03a18ef7.png">
