### ISSUE TITLE
Add documentation for error page debug configuration

### ISSUE THREAD

**Issue by cnovak** [apigee/apigee-edge-drupal#231]
PR #227 adds a configuration to show better error messages when something goes wrong w/Apigee Edge API.  This task is to add information to our docs on how this should be turned off when going to production.

**Comment by mxr576** [comment]
Implementation in #227 needs to be fixed before it could roll-out. See #234.

**Comment by cnovak** [comment]
Closing this issue since it is duplicate of #334
