### ISSUE TITLE
Add translation to debug exception errors

### ISSUE THREAD

**Issue by cnovak** [apigee/apigee-edge-drupal#235]
PR #227 adds in the ability to show exception messages on screen, but are not translatable.  

Displaying translatable error messages from exceptions is not easy, but we already have something in the module: KeyProviderRequirementsException.

**Comment by phdhiren** [comment]
Won't fix this issue, as exceptions are not to be translated in Drupal. 
https://www.drupal.org/docs/develop/coding-standards/php-exceptions#conventions
https://github.com/apigee/apigee-edge-drupal/pull/545
