### ISSUE TITLE
Getting Failed to connect to Apigee Edge in drupal 8 module

### ISSUE THREAD

**Issue by chouhapr31** [apigee/apigee-edge-drupal#238]
Hi I already have drupal 7 based Dev portal and which is connecting to Edge without any issue, now when i tried to connect the Edge using drupal 8 apigee_edge module with the same configuration details like organization,username,password, I am getting below error: Failed to connect to Apigee Edge. Error message: cURL error 77: (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by mxr576** [comment]
Hi,

```
CURLE_SSL_CACERT_BADFILE (77)
Problem with reading the SSL CA cert (path? access rights?) 
```
Do you have HTTPS enabled on your MGMT API gateway? Hadn't you had that configured in Drupal 7? See #224

**Comment by mxr576** [comment]
@chouhapr31 If you still having connectivity issues please try verify your SSL key and configuration like it is described here:
https://github.com/apigee/apigee-edge-drupal/issues/224#issuecomment-505281853

**Comment by chouhapr31** [comment]
Hi, Thanks for your response, Now I am getting error  - Failed to connect to Apigee Edge. Error message: cURL error 58:
Actually, I am not much familiar with certificate. however I followed and used below url for cacert.pem file
https://stackoverflow.com/questions/30240840/laravel-5-socialite-curl-error-77-error-setting-certificate-verify-locations

**Comment by arunz6161** [comment]
@chouhapr31 , the initial error you reported "Error message: cURL error 77" indicates outdated SSL certificate(s) for cURL installed on server are missing or broken. If this is the case, you will have to work with you syadmin to get that sorted. A good test to confirm this would be to run on the server:

curl -v "https://{management}:{port}/v1/{edge_org}"  (substitute with your management server hostname and port)

curl -v  "https://api.enterprise.apigee.com/v1"

If you see the "cURL error 77" for both the calls, it would confirm the issue with outdated SSL certificate(s) for cURL.  In this case, please undo any changes you have done to resolve the issue and work with your sysadmin to sort the problem
