### ISSUE TITLE
Exception not handled for $entity->toUrl() in template_preprocess_apigee_entity

### ISSUE THREAD

**Issue by shadcn** [apigee/apigee-edge-drupal#241]
**Describe the bug**
In `template_preprocess_apigee_entity`, exceptions are not caught for `$entity->toUrl()`. This results in a fatal error if `toUrl()` fails.

**To Reproduce**
See https://github.com/apigee/apigee-m10n-drupal/issues/166

**Expected behavior**
Wrap into a try catch so that we do not see a fatal error.

**Comment by mxr576** [comment]
Answered to the original issue, because the root of the problem is not the missing try-catch. If you check usages of `toUrl()` in Drupal core you do not see that it would be try-catched either. https://github.com/apigee/apigee-m10n-drupal/issues/166#issuecomment-512287020

**Comment by shadcn** [comment]
Closed via https://github.com/apigee/apigee-m10n-drupal/pull/176
