### ISSUE TITLE
"Developer" default user role does show as an option while adding team members

### ISSUE THREAD

**Issue by arunz6161** [apigee/apigee-edge-drupal#243]
**Describe the bug**
By default, the teams feature has 2 default roles- Admin and Developer. However while adding new users to the team, only admin and any new role you add shows up as a option but not developer.

**To Reproduce**
1. Go to teams and select an existing team.
2. Click on Add members
3. Scroll down and you will notice "developer" missing under roles.

**Expected behavior**
"developer" role should show as an option.

**Screenshots**
![Screen Shot 2019-07-24 at 3 31 15 PM](https://user-images.githubusercontent.com/4381612/61833104-28ec2400-ae28-11e9-821a-3931c2beac18.png)
![Screen Shot 2019-07-24 at 3 31 33 PM](https://user-images.githubusercontent.com/4381612/61833111-2be71480-ae28-11e9-868d-ce07abfd7ef5.png)

**Additional context**
None

**Version Info**
Apigee teams version: 8.x-1.0
Apigee edge version: 8.x-1.0

**Comment by arlina-espinoza** [comment]
The _"Developer"_ or _"Member"_ role (machine name `member`) is the default role for anyone on a team, much like "authenticated user" is for anyone with an account. It does not need to show up because it is automatically assigned by becoming a part of a team.

Drupal core explains the authenticated role as a message on the roles configuration page:
![image](https://user-images.githubusercontent.com/4062676/62804726-fd616e80-baa2-11e9-88f2-dc0aadb2b17f.png)

I think we should add a similar message to the team roles configuration page as well. The text can say:

> A role defines a group of users that have certain privileges. These privileges are defined on the Team Permissions page. Here, you can define the names of the team roles on your site. Users who are part of a team have the  in have the Member team role, plus any other team roles granted to their account.

Let me know your thoughts @arunz6161 .

**Comment by cnovak** [comment]
This is unclear looking at the screens above until hearing @arlina-espinoza's explanation. Maybe the "member" checkbox should be shown as checked on the "add member" screen, but disabled to give context.  This would be along w/the message @arlina-espinoza is suggesting.

**Comment by mxr576** [comment]
@arlina-espinoza's explanation is correct and I am quite sure that back in the days I demonstrated this feature to you and explained the team member management works quite similar to Drupal's user management. I do not think that displaying the "member" role as a disabled would be necessary. Although, adding a similar explanation that Drupal core does for the authenticated role could be useful. Ofc, the documentation should be also extended regarding this, but I saw you already created an issue about it.

**Comment by cnovak** [comment]
I am thinking it should follow the Drupal standard of showing the role for clarification.  This is how user edit works in Drupal admin screens:

<img width="213" alt="drupal-user-edit" src="https://user-images.githubusercontent.com/613093/62885754-def3b100-bcf6-11e9-93f0-72c685269e11.png">

Also, we can add help text to the `team-settings/team_role` admin screen in a similar way as **Home > Admin > People** admin screen.
