### ISSUE TITLE
Documentation: Description of Team Apps seems unclear.

### ISSUE THREAD

**Issue by cnovak** [apigee/apigee-edge-drupal#252]
The [overview and explanation of the "Apigee Edge Teams" module](https://www.drupal.org/docs/8/modules/apigee-edge/understand-how-app-developers-interact-with-the-apigee-edge-module#teams) seems unclear.  The use case of this module is to allow developers to create teams so that they can add other members to collaborate on the same apps.  The way it is worded now makes it sound like the API provider can manage teams since the API provider will be reading and configuring up the module.  

Also we should add documentation to make it more clear that [a "member" role is a special role that all members of the team will get automatically](https://github.com/apigee/apigee-edge-drupal/issues/244#issuecomment-520037613), so default permissions can be configured using that role.

**Comment by jbennett13** [comment]
Updated docs here:
https://www.drupal.org/docs/8/modules/apigee-edge/configure-team-management
https://www.drupal.org/docs/8/modules/apigee-edge/understand-how-app-developers-interact-with-the-apigee-edge-module#teams
