### ISSUE TITLE
Document advanced settings on Edge connection settings page

### ISSUE THREAD

**Issue by cnovak** [apigee/apigee-edge-drupal#256]
The advanced connection settings in the Apigee Edge connection settings page is not documented:

<img width="462" alt="advanced-settings" src="https://user-images.githubusercontent.com/613093/62900150-a532a280-bd16-11e9-96bf-3ad1f572a94f.png">

**Comment by cnovak** [comment]
The Apigee Edge module uses the [Drupal Key module](https://www.drupal.org/project/key) to store the Apigee Edge connection settings.  The Key module allows admins to define how and where sensitive information will be stored, which is a good fit for the Apigee Edge credentials.

The Apigee Edge connection settings page is a simple display of the Key module configuration for the Apigee Edge credentials. You can see the full details of the Apigee Edge key by going to **Configuration >  System >  Keys** in the admin menu.  The "Key type" will always be "Apigee Edge Authentication" since the data being stored is custom to Apigee Edge credentials.  The "Key provider" is the configurable storage mechanism.  Key providers can be defined in the Key module or other modules to extend the ways the keys can be defined.  For example, if you install the [Drupal Lockr module](https://www.drupal.org/project/lockr), it will add a new key provider to store the key in [Lockr](https://www.lockr.io). 

Three key providers are part of the Key module. Read the [Key module docs on key providers](https://www.drupal.org/docs/8/modules/key/concepts-and-terminology#key-providers) for more information:
* Environment
* Configuration
* File

The Apigee Edge module adds the following key providers:
* **Apigee Edge: Private File:** The key will be stored in the Drupal private filesystem.  Make sure the private filesystem is set to be a directory outside the web root.
* **Apigee Edge: Environment Variables:** This key provider is the same as the Key module's "Environment" plugin and will be deprecated.

To make configuration easy for evaluation and local development, the Apigee Edge module by default stores the Apigee Edge connection settings in a simple way:
* If you install the Apigee Edge module on a base Drupal site, the credentials are stored in the private filesystem.  You may want to use a more secure key provider than the Drupal private filesystem on a production server.
* If you are using [Apigee Kickstart](https://www.drupal.org/project/apigee_devportal_kickstart), the key is stored in Drupal configuration. It is recommended to change the key provider if you are working on anything other than local development.  

The [key module's project page](https://www.drupal.org/project/key) describes the security recommendations on the key provider:

> By using key, administrators can choose to store their keys in the following locations:
> * Configuration (development only): The Configuration key provider stores the key in Drupal’s database
> * File (Better): The File key provider allows a key to be stored in a file, preferably outside of the webroot where it cannot be publicly accessed.
> * Environment (Better): The Environment key provider allows a key to be stored in an environmental variable.
> * External (Best): Use a key management solution external to Drupal. This allows your site to meet security best practices and compliance requirements. Lockr and Townsend Security’s Alliance Key Manager are currently two options with existing modules, however Key is extensible for any key storage provider.

**Comment by cnovak** [comment]
@jbennett13 it would be good to add info to Kickstart documentation explaining that the key provider settings should be changed for server installs and point them to this info so they know that is a needed post install step.

**Comment by jbennett13** [comment]
Thanks, Chris.  Will do.

**Comment by jbennett13** [comment]
Updates made here:  https://www.drupal.org/docs/8/modules/apigee-edge/configure-the-connection-to-apigee-edge.  Kickstart documentation points back to this step, post-installation.  I can also add a Note highlighting the importance of this step in the Kickstart docs.
