### ISSUE TITLE
Document details on how to configure portal to connect to management servers with self signed certificates

### ISSUE THREAD

**Issue by arunz6161** [apigee/apigee-edge-drupal#258]
**Is your feature request related to a problem? Please describe.**
Devportal throws a curl exception `(Error message: cURL error 51: (see http://curl.haxx.se/libcurl/c/libcurl-errors.html))` when connecting to a management server with a self-signed certificate.

**Describe the solution you'd like**
To allow the devportal to make an exception and trust the self-signed certificate, following configs should be added to settings.php

`$settings['http_client_config']['cert'] = 'path/to/self-seigned-cert';`

This should be used for self-signed certificates.

`$settings['http_client_config']['ssl_key'] = 'path/to/client.key';`

This settings to be used when management server is configured for 2 way SSL

`$settings['http_client_config']['verify'] = false;`

This settings to be used if there is a hostname mismatch with the certificate CN.

Refer https://github.com/apigee/apigee-edge-drupal/issues/224 for more details

**Comment by jbennett13** [comment]
Added this documentation to the Edge Drupal docs in the Troubleshooting section. https://www.drupal.org/docs/8/modules/apigee-edge/troubleshoot-issues#curl-error-51
