### ISSUE TITLE
Portal not compatible with External Auth on Edge

### ISSUE THREAD

**Issue by kbielawiec** [apigee/apigee-edge-drupal#261]
**Describe the bug**
When an Edge org (private cloud) is using External Auth, they are unable to connect their portal to Edge. The configuration page requires and email address, where External Auth requires a username (no @domain.com)

**To Reproduce**
Attempt to connect to an Edge organization using External Auth with a username (not email) and password. The portal will throw an error "Invalid email address" error. When attempting to connect with an email, you will receive a 401 error as Edge can only authenticate with a username.

**Expected behavior**
Dev portal should be able to connect to an Edge org with just a username - not only an email address.

**Version Info**
8.x-1.0

**Comment by arlina-espinoza** [comment]
Looking into the authentication form, it might be as simple as changing the field type from "email" to "textfield". Do you see any restriction to that @arunz6161 / @cnovak? Something like using an email field for public cloud, and a textfield for private cloud?

**Comment by cnovak** [comment]
We need both public and private to be able to handle a non-email username since either one could have usernames as far as I know, @arunz6161 correct me if I am wrong

**Comment by arunz6161** [comment]
With public cloud, it is not possible to use a non-email username- its a limitation. This option becomes only available to private cloud customers when they enable external auth.
