### ISSUE TITLE
Unable to retreive Analytics, Always showing page not found

### ISSUE THREAD

**Issue by rengan76** [apigee/apigee-edge-drupal#262]
<img width="473" alt="pagenot found" src="https://user-images.githubusercontent.com/4405193/65265288-9346db00-dade-11e9-8a6e-415e6ea47252.PNG">
After apigee edge connection setup
Below are working
1. Apps
2. Products
3. Catalogs

Not working is
1. Analytics. whenever i search for analytics its showing me page not found. Sometimes its showming me no errors other than page not found sometimes i got as error on [transaltion.[](url)](url)

**Comment by cnovak** [comment]
Same issue as apigee/apigee-devportal-kickstart-drupal#268

**Comment by mxr576** [comment]
https://www.drupal.org/project/drupal/issues/3082529 Just to make sure we are fixing this in the right component :)

**Comment by mxr576** [comment]
Btw, as a hotfix, disable the QuickEdit module.

**Comment by rengan76** [comment]
> Btw, as a hotfix, disable the QuickEdit module.

---- I am unable to disable quick edit. Please find attached. do you want me to uninstall the module.
<img width="339" alt="unabletoquickedit" src="https://user-images.githubusercontent.com/4405193/65327643-88458680-db82-11e9-9e76-eb4a2aa8dd09.PNG">

**Comment by rengan76** [comment]
Ok tried uninstalling quick edit. Still showing me page not found whenever i search for analytics submit with any options and custom range
<img width="666" alt="pagenotfound1" src="https://user-images.githubusercontent.com/4405193/65328784-1fabd900-db85-11e9-84bb-f65b9cf13158.PNG">

**Comment by jacine** [comment]
Hi @rengan76,

You need to click the "Uninstall" tab, or visit `/admin/modules/uninstall` directly. You'll be able to uninstall it from there.

HTH,
Jacine

**Comment by rengan76** [comment]
> Hi @rengan76,
> 
> You need to click the "Uninstall" tab, or visit `/admin/modules/uninstall` directly. You'll be able to uninstall it from there.
> 
> HTH,
> Jacine

--- Check my recent message i did that. but no luck. still showing me page not found

**Comment by arlina-espinoza** [comment]
Hi @rengan76,

I'm having trouble replicating this issue. Could you specify what version of Kickstart and apigee_edge modules do you have installed?

I also noticed in your screenshots that your site seems to be installed under _http://10.238.96.142/portal/web/_, but the URL that is shown for the app analytics is _http://10.238.96.142/portal/web/portal/web/user/58/apps/test-app-ranga/analytics_, which doesn't look correct. Could you try going to: _http://10.238.96.142/portal/web/user/58/apps/test-app-ranga/analytics_ and let us know if that page works? Thanks!

**Comment by rengan76** [comment]
Check this

**Comment by rengan76** [comment]
> Hi @rengan76,
> 
> I'm having trouble replicating this issue. Could you specify what version of Kickstart and apigee_edge modules do you have installed?
> 
> I also noticed in your screenshots that your site seems to be installed under _http://10.238.96.142/portal/web/_, but the URL that is shown for the app analytics is _http://10.238.96.142/portal/web/portal/web/user/58/apps/test-app-ranga/analytics_, which doesn't look correct. Could you try going to: _http://10.238.96.142/portal/web/user/58/apps/test-app-ranga/analytics_ and let us know if that page works? Thanks!
**_http://10.238.96.142/portal/web/user/58/apps/test-app-ranga/analytics this page works. As i said eariler when click on the submit with any changes with date range or metrics nothing showing up. Always showing me page not found**

**Comment by rengan76** [comment]
<img width="355" alt="analytics1" src="https://user-images.githubusercontent.com/4405193/65341224-dc119900-db9d-11e9-87ad-3ed979f66981.PNG">
<img width="828" alt="uptodate" src="https://user-images.githubusercontent.com/4405193/65341239-e2077a00-db9d-11e9-9e75-6cbab7fab637.PNG">

**Comment by arlina-espinoza** [comment]
I've posted a pull request that will fix the issue with the submit redirect: https://github.com/apigee/apigee-edge-drupal/pull/266
