### ISSUE TITLE
Creating company programmatically in Drupal 8

### ISSUE THREAD

**Issue by aditya1316** [apigee/apigee-edge-drupal#264]
Hi , 

I want to create company in Drupal 8 programatically , so is there is any kind of documentation available for that?

**Installed Modules**
Apigee_edge
Apigee_m10n

Thanks,
Aditya

**Comment by mxr576** [comment]
Hi @aditya1316, the equivalent of a company is a team in this module, which is a regular Drupal entity like node, so you can create a team entity the same way as you would create a node entity programmatically. You have to enable the `apigee_edge_teams` module for this.

**Comment by robin0888** [comment]
Hi @mxr576, I tried to create a team like a regular Drupal entity. I'm unable to create that. Please have a look at below code.

The first way I tried to create a team below:
$team = \Drupal::entityTypeManager()->getStorage('team')->create(array(
			  'type'        => 'team',
			  'title'       => 'z_cloud_test',
			));
			$team->save();
Error I'm getting is: Error: Call to a member function getStorage() on null in 

The second one I tried:
$team = Team::create(['type' => 'team']);
		$team->set('title', 'z_cloud_rr');
		$team->save();
Error: Call to a member function getValue()

Thanks,
Robin

**Comment by arlina-espinoza** [comment]
Hi @robin0888 ,

Getting this error `Error: Call to a member function getStorage() on null in` means `\Drupal::entityTypeManager()` returned null, which is really odd, as it is Drupal core's way of fetching the entity type manager service. I'd suggest verifying in what context you are running that code as that should not be null.
As for actually creating the team entity, it's best practice to use the entity storage rather than a direct call to the entity class, so an example would be:

```
$team_storage = \Drupal::entityTypeManager()->getStorage('team');
$team = $team_storage->create([
  'name' => 'abc',
  'displayName' => 'ABC team',
]);
$team->save();
```

**Comment by robin0888** [comment]
Thanks, @arlina-espinoza, @mxr576, 
Drupal 7 the company object was as given below, which I'm trying to achieve the same in Drupal 8. 
***************************
ApigeeCompanyEntity Object
(
	[name] => addy25092019
	[attributes] => Array
		(
			[ADMIN_EMAIL] => aditya.*****@******.net
			[MINT_COMPANY_ID] => 
			[MINT_REGISTRATION_ID] => 123456789
			[MINT_TAX_EXEMPT_AUTH_NO] => 
			[MINT_DEVELOPER_LEGAL_NAME] => addy25092019
			[MINT_BILLING_TYPE] => POSTPAID
			[MINT_DEVELOPER_PHONE] => 9898989898
			[MINT_APPROX_TAX_RATE] => 0.10
			[MINT_DEVELOPER_TYPE] => UNTRUSTED            
		)
	[displayName] => addy25092019
	[status] => active
	[developers] => Array
		(
			[Monetization Administrator] => Array
				(
					[0] => aditya.******@*******.net
				)

		)

	[createdAt] => 1569404031006
	[createdBy] => ************************
	[lastModifiedAt] => 1569404031006
	[lastModifiedBy] => *********************
	[apps] => Array
		(
		)

	[organization] => Lorem Ipsum
	[debugData] => ...
)
**********************************************
**In Drupal 8 I'm able to create company** using the only three attributes i.e name, display name and status(Please check below code for same) **but in case I'm trying to add more attribute i'm getting error(Pls check the code in _> Drupal 8 --- Other attribute_**

			$team_storage = \Drupal::entityTypeManager()->getStorage('team');

			$team = $team_storage->create(['name' => 'Loreum', 'displayName' => 'zzzzzyrobin','status' => 'active']);	
		
			$team->save();
***********************************************
**_Drupal 8 --- Other attribute_**

			$team_storage = \Drupal::entityTypeManager()->getStorage('team');

			$team = $team_storage->create(['name' => 'loreumIpsum', 'attributes' => array('ADMIN_EMAIL' => 'rob.******.net','MINT_APPROX_TAX_RATE' => 0.10, 'MINT_BILLING_TYPE' => 'POSTPAID', 'MINT_COMPANY_ID' =>'','MINT_DEVELOPER_ADDRESS' => '{"address1":"24 Street","address2":"","city":"Loreum Ipsum","country":"AU","isPrimary":"true","state":"loreum","zip":"213565"}','MINT_DEVELOPER_LEGAL_NAME' => 'ROB0502COM1','MINT_DEVELOPER_PHONE' => 1234567890,'MINT_REGISTRATION_ID' => 123456789, 'MINT_TAX_EXEMPT_AUTH_NO'=>'','MINT_DEVELOPER_TYPE' => 'UNTRUSTED'), 'displayName' => 'zzzzzyrobin','status' => 'active']);

			$team->save();

Error: Cannot unpack array with string keys in Apigee\Edge\Structure\BaseObject->__construct()

**Comment by mxr576** [comment]
```php
<?php
$team = $team_storage->create(['name' => 'Loreum', 'displayName' => 'zzzzzyrobin','status' => 'active']);
$team->setAttribute('foo', 'bar');
// or
$team->setAttributes(new \Apigee\Edge\Structure\AttributesProperty(['foo' => 'bar', 'bar' => 'baz"]);
$team->save();
```

![image](https://user-images.githubusercontent.com/1755573/65607391-c1c82880-dfac-11e9-891c-306d9f0b95bc.png)


Haven't tried it, but it should also work.  

```php
<?php
$team = $team_storage->create(['name' => 'Loreum', 'displayName' => 'zzzzzyrobin','status' => 'active', 'attributes' => new \Apigee\Edge\Structure\AttributesProperty(['foo' => 'bar', 'bar' => 'baz"])]);
$team->save();
```

**Comment by robin0888** [comment]
Thanks, @mxr576, it's working.
