### ISSUE TITLE
Rules Module Integration

### ISSUE THREAD

**Issue by giteshk** [apigee/apigee-edge-drupal#267]
Add integration to [Business Rules module](https://www.drupal.org/project/business_rules) so that users can create rules around events.

## Events to react on
* App
  * Created
  * Updated
  * Deleted
* Teams
  * Team Created 
  * Team Updated
  * Team Deleted
  * Team Member Added
  * Team Member Removed
* User (these may already exist)
  * Created 
  * Updated
  * Deleted

## Example use cases we want to cover
  * Send out email to **messaging** admins when the **messaging** API Product is added to an app
  * Send out email to admins when new app is created
  * Approve apps that are created by developers that have an @foo.com email address
  * Send out notification to a developer when their app is approved

**Comment by mxr576** [comment]
Rules is unstable and still under active development. It is not recommended to be used on production sites, I think it is too early to validate the compatibility because of these.
https://www.drupal.org/project/rules/releases/8.x-3.0-alpha5

(This should not be a bug ticket)

**Comment by giteshk** [comment]
If not Rules can we suggest any other approach which is repeatable? 
eg. Send email on app creation, app deletion, Team creation, Team invitation

Maybe add something to the documentation about possible approaches customers can try out.

**Comment by arunz6161** [comment]
To clarify the ask here is to evaluate if rules or business_rules will work better with D8P and document steps on how a user can setup email notification on common events like app creation, app deletion, team creation, team invitation.

**Comment by mxr576** [comment]
I have just wanted to suggest Business Rules as an alternative. At this moment, it seems more promising than the old-friend, Rules.

**Comment by minnur** [comment]
Business Rules integration is the module that works better than the Rules module.  For the full Business Rules module integration we would need to create more Event plugins and dispatch them where needed. Business Rules module RuleOn plugin is listening to those events and triggering actions. So far I see only about 4 events in the Apigee Edge module and almost all of them related to the credentials. Like new app credential created/deleted etc.

Actions to do:
1. Determine events that we need
2. Create Event plugins for each of the actions
3. Implement RuleOn Business Rules plugins. This would allow add actions such as send email, show message etc..

**Comment by mxr576** [comment]
> So far I see only about 4 events in the Apigee Edge module and almost all of them related to the credentials.

True, because another entity related CRUD operations automatically trigger certain hooks and we did not want to reinvent the wheel by introducing new events that Drupal core will provide in the future. There is Drupal core issue about replacing/extending entity hooks with events: https://www.drupal.org/project/drupal/issues/2551893 also there is a contrib module for now that we may rely on https://www.drupal.org/project/entity_events

The Business Rules integration probably should be provided by a new submodule, so it should be loosely coupled with the core functionality.

**Comment by mxr576** [comment]
https://github.com/apigee/apigee-edge-drupal/pull/289

**Comment by giteshk** [comment]
@minnur could we add Team invitation events as well

**Comment by giteshk** [comment]
CRUD events on entities [developer/app/companies] and key status change [pending to approval or approved to revoked or pending to revoked]

**Comment by cnovak** [comment]
@mxr576 we would like to use the events out of the box from Drupal but it sounds like it may be quite awhile before events are in core. @minnur looked into using a contrib module but none work properly since our entities are not config or content.

**Comment by arunz6161** [comment]
Minnur to update the latest on https://github.com/apigee/apigee-edge-drupal/pull/289

**Comment by cnovak** [comment]
@arshad  we have updated the description to explain the scope of this issue, let @arlina-espinoza or I know if you have any questions.

**Comment by cnovak** [comment]
This should be added as a submodule of the project.

**Comment by giteshk** [comment]
Do we have an update on this?

**Comment by cnovak** [comment]
This issue is in progress, planning to release next week.

**Comment by shadcn** [comment]
@giteshk yes this is in progress. We'll have a PR soon.
