### ISSUE TITLE
Change apigee settings page to accommodate hybrid org

### ISSUE THREAD

**Issue by arunz6161** [apigee/apigee-edge-drupal#268]
Change apigee settings page to accommodate hybrid org- by adding hybrid as an option which defaults to https://apigee.googleapis.com/v1/ as the endpoint and allow user to upload service account key (json key) for authentication.

**Comment by arlina-espinoza** [comment]
Depends on https://github.com/apigee/apigee-client-php/issues/64.

**Comment by arlina-espinoza** [comment]
Resolved by #275 .
