### ISSUE TITLE
Recent log messages shows incorrect user

### ISSUE THREAD

**Issue by cnovak** [apigee/apigee-edge-drupal#276]
## Description
Related to apigee/apigee-devportal-kickstart-drupal#270, the Recent log messages page shows wrong user for anonymous user logs, but detail page shows correct user. 

## Steps to Reproduce
1. Go to **Recent log messages**
2. Filter by type **cron**

** Actual Behavior **
The **User** column shows Firstname Lastname (not verified) as the username, which is the unfortunate name by default of the user uid 1.
<img width="1147" alt="Screen Shot 2019-10-02 at 10 52 45 AM" src="https://user-images.githubusercontent.com/613093/66068643-cfc4fe80-e502-11e9-8bde-4b256c9123c9.png">

**Expected behavior**
The username should be anonymous, as you can see when clicking into detail of the message:
<img width="646" alt="Screen Shot 2019-10-02 at 10 53 15 AM" src="https://user-images.githubusercontent.com/613093/66068680-e5d2bf00-e502-11e9-9b6a-5166e7196800.png">

## Version Info
apigee/apigee_devportal_kickstart        1.5.0

**Comment by mxr576** [comment]
I added my suggested solution to the problem to #277.

**Comment by shadcn** [comment]
@mxr576 Your suggestion is already being discussed. 

This PR is a possible solution to @kscheirer suggestion: 

> I think the answer is not to name the anonymous user account with "Firstname Lastname".

**Comment by mxr576** [comment]
Because these are default values coming from base fields and default values cannot vary per user AND

>  For some reason, Drupal 8 persist these default field values to the database,

I think we should not worry about them or do anything with them rather fix how the Apigee Edge module overrides the rendered username of a user. https://github.com/apigee/apigee-edge-drupal/pull/277#issuecomment-539979633

**Comment by shadcn** [comment]
I opened a new PR https://github.com/apigee/apigee-edge-drupal/pull/278
