### ISSUE TITLE
[DOC] - Update Drupal docs to include "planned features"

### ISSUE THREAD

**Issue by arunz6161** [apigee/apigee-edge-drupal#282]
**Is your feature request related to a problem? Please describe.**
Update the drupal docs section to include a "planned features" section ( similar to "API catalog" module) and add "To support [Apigee Hybrid](https://docs.apigee.com/hybrid/beta2/what-is-hybrid)"

**Describe the solution you'd like**
To update community about the planned work to support "Apigee Hybrid"

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by cnovak** [comment]
Closing this since we already cover Hybrid
