### ISSUE TITLE
Delete Company/Team in Drupal 8

### ISSUE THREAD

**Issue by robin0888** [apigee/apigee-edge-drupal#283]
Hi,

1) I want to delete a company/Team in Drupal 8 programmatically, so is there is any kind of documentation available for this? I'm using below code but unable to delete

$this->teamStorage->delete([$arr]);

2) I want to update a specific attribute or multiple attributes of the team at the edge.

Installed Modules
Apigee_edge
Apigee_m10n

Thanks,
Robin

**Comment by mxr576** [comment]
Hi,

> $this->teamStorage->delete([$arr]);

If $arr is an array of Team entities then it should be `$this->teamStorage->delete($arr);`. Team storage is like any other entity storage in Drupal 8.

> I want to update a specific attribute or multiple attributes of the team at the edge.

```
$team = $this->teamStorage->load($id);
$team->setAttribute('foo', 'bar');
$team->save();
```

![image](https://user-images.githubusercontent.com/1755573/67204353-a1ee1e00-f40d-11e9-8b0c-f72b28257185.png)

**Comment by robin0888** [comment]
Thanks @mxr576 ,
Please have a look at the below code, it's working for me and let me know if you need any optimization for the code.
**Delete Team:**
`$team_storage = \Drupal::entityTypeManager()->getStorage('team');`
`$load = $team_storage->load('zzyyrob_test');`
`$load->delete();`

**Set attribute:**
`team_storage = \Drupal::entityTypeManager()->getStorage('team');`
`$load = $team_storage->load('zzyyrob_test');`
`$load->setAttribute('MINT_DEVELOPER_ADDRESS', '{"address1":"24 Street","address2":"robinaddress","city":"Loreum Ipsum","country":"AU","isPrimary":"true","state":"loreum","zip":"213565"}');`
`$load->save();`

**The issues I'm facing:**
**1)** How to clear the cache at the edge after I update an attribute? Because I have to clear the cache manually every time if I update an attribute.

**2) Set Multiple attributes** -- Code mentioned below I'm using for the same but unable to update multiple attributes at the same time.
`$team_storage = \Drupal::entityTypeManager()->getStorage('team');`
`$load = $team_storage->load('zz_test_22_10');`
`$arr = ['MINT_DEVELOPER_PHONE' => '911111111121', 'MINT_REGISTRATION_ID' => '9898989898'];`
`$att_array = (object) array($arr);`
`$load->setAttributes($att_array);`
`$load->save();`

**Comment by mxr576** [comment]
`$att_array = (object) array($arr);
$load->setAttributes($att_array);`

The parameter type is incorrect. It should be `\Apigee\Edge\Structure\AttributesProperty`. 
![image](https://user-images.githubusercontent.com/1755573/67778274-3cc8a700-fa63-11e9-9610-08bcdede254c.png)

Btw I am not sure if the Apigee_m10n provides wrapper method for modifying MINT related attributes or not. 

> 1) How to clear the cache at the edge after I update an attribute? Because I have to clear the cache manually every time if I update an attribute.

Whenever you save/delete an entity the Apigee Edge module invalidates all entity related caches, including render caches. It depends on which page(s) you have cache invalidation issues after you run this code because it could happen that a cache context is missing from the page.

**Comment by robin0888** [comment]
Thanks @mxr576 ,

But I'm unable to upload entity rate_plan, purchased_plan, team_app, developer_app
while entities like team, developer, and api_products working fine.

1) I'm trying to **load specific app of team**(using code below) but getting a blank screen
	
 
```
                 $id = 'zzzzzyrobin'; //teams' app machine name

		$entity = \Drupal::entityTypeManager()->getStorage('team_app')->load($id);
```

            

2) I'm trying to **load specific app of developer**(using code below) but getting a blank screen
	   
```
             $developer = \Drupal::entityTypeManager()->getStorage('developer_app');

              $id = 'xtyapp4q6a'; //apps machine name

	      $developer->load($id);
```
         
    2.1) Create a developer app(code below) not working:
	```
            $dev_app = DeveloperApp::create([
            'name' => 'robin_app_test_08_11', //apps name
            'status' => App::STATUS_APPROVED,
            'developerId' => 523bbae7-eec6-4c93-84ef-7b04e7xxxxxx, // developer uuid
             ]);

            $dev_app = $dev_app->save();
     ```

While the same code works fine for loading the entities like team, developer, and api_products

**Comment by mxr576** [comment]
The ID is a UUID, not an app name. The UUID is unique per app, the app name is only unique when the developer id (email or UUID) is also available in the context.

**Comment by robin0888** [comment]
thanks, @mxr576, let me check this at my end.

**Comment by mxr576** [comment]
You can find some inspiration and answers to your questions if you check the implement of the "My apps" (nowadays called as "Apps") page and Team app listing pages. Those are filtering the returned entity list by a developer/team.

**Comment by robin0888** [comment]
yup, sure, thanks

**Comment by robin0888** [comment]
Hi @mxr576 , I'm creating a team and developer app, I'm able to create internal app only without any product. (Please have a look at below code)

```
$teamAppStorage = \Drupal::entityTypeManager()->getStorage('team_app');

    $teamApp = $teamAppStorage->create([
      'name' => 'robin_27_11_01',
      'companyName' => 'zzzzzyrobin',
 ]);
```
**Getting error while trying to add product for an app**

```
$teamAppStorage = \Drupal::entityTypeManager()->getStorage('team_app');

    $teamApp = $teamAppStorage->create([
      'name' => 'robin_27_11_01',
      'companyName' => 'zzzzzyrobin',
	 'credentials' => new \Apigee\Edge\Api\Management\Entity\AppCredential(['apiProducts' => 'tdev-content-api']),
 ]);
```
