### ISSUE TITLE
Analytics "chart" shows ranges but no series

### ISSUE THREAD

**Issue by kford** [apigee/apigee-edge-drupal#284]
**Describe the bug**
Developer App Analytics shows the appropriate range for the metric selected, but there are no "series" plotted onto it.  Export to CSV does appear to have the right values

**To Reproduce**
1. Create API Proxy with API Key Verification
2. Create API Product with API Proxy
3. Login to kickstart portal as user, create App, consume Product
4. Make calls to API Proxy, using API Key
5. View App Analytics
6. Chart has ranges but no "series"

**Expected behavior**
Expect to see Chart with series depicting metrics over time

**Screenshots**
attached

**Additional context**
---

**Version Info**
COMPOSER SHOW OUTPUT BELOW
-----------------------------------------------------------
drupal@9af78098554a:~/project$ cat composer_show.out 
apigee/apigee-client-php                 2.0.3        Client library for connecting to the Apigee Edge API.
apigee/apigee_devportal_kickstart        1.5.0        A fast demo and starting point for Apigee Developer Portals.
asm89/stack-cors                         1.2.0        Cross-origin resource sharing library and stack middleware
brumann/polyfill-unserialize             v1.0.4       Backports unserialize options introduced in PHP 7.0 to older PHP versions.
chi-teck/drupal-code-generator           1.30.4       Drupal code generator
clue/stream-filter                       v1.4.1       A simple and modern approach to stream filtering in PHP
commerceguys/addressing                  v1.0.6       Addressing library powered by CLDR and Google's address data.
commerceguys/intl                        v1.0.4       Internationalization library powered by CLDR data.
composer/installers                      v1.7.0       A multi-framework Composer library installer
composer/semver                          1.5.0        Semver library that offers utilities, version constraint parsing and validation.
consolidation/annotated-command          2.12.0       Initialize Symfony Console commands from annotated command class methods.
consolidation/config                     1.2.1        Provide configuration services for a commandline tool.
consolidation/filter-via-dot-access-data 1.0.0        This project uses dflydev/dot-access-data to provide simple output filtering for applications built with annotated-command / Robo.
consolidation/log                        1.1.1        Improved Psr-3 / Psr\Log logger based on Symfony Console components.
consolidation/output-formatters          3.5.0        Format text by applying transformations provided by plug-in formatters.
consolidation/robo                       1.4.10       Modern task runner
consolidation/self-update                1.1.5        Provides a self:update command for Symfony Console applications.
consolidation/site-alias                 3.0.0        Manage alias records for local and remote sites.
consolidation/site-process               2.1.0        A thin wrapper around the Symfony Process Component that allows applications to use the Site Alias library to specify the target for a remote call.
container-interop/container-interop      1.2.0        Promoting the interoperability of container objects (DIC, SL, etc.)
cweagans/composer-patches                1.6.7        Provides a way to patch Composer packages.
dflydev/dot-access-data                  v1.1.0       Given a deep data structure, access data by dot notation.
dnoegel/php-xdg-base-dir                 0.1          implementation of xdg base directory specification for php
doctrine/annotations                     v1.8.0       Docblock Annotations Parser
doctrine/cache                           v1.8.0       Caching library offering an object-oriented API for many cache backends
doctrine/collections                     v1.6.2       PHP Doctrine Collections library that adds additional functionality on top of PHP arrays.
doctrine/common                          v2.11.0      PHP Doctrine Common project is a library that provides additional functionality that other Doctrine projects depend on such as better reflection support, pers...
doctrine/event-manager                   v1.0.0       Doctrine Event Manager component
doctrine/inflector                       v1.3.0       Common String Manipulations with regard to casing and singular/plural rules.
doctrine/lexer                           1.1.0        PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Parsers.
doctrine/persistence                     1.1.1        The Doctrine Persistence project is a set of shared interfaces and functionality that the different Doctrine object mappers share.
doctrine/reflection                      v1.0.0       Doctrine Reflection component
drupal-composer/drupal-scaffold          2.6.1        Composer Plugin for updating the Drupal scaffold files when using drupal/core
drupal/address                           1.7.0        Provides functionality for storing, validating and displaying international postal addresses.
drupal/admin_toolbar                     1.27.0       Provides a drop-down menu interface to the core Drupal Toolbar.
drupal/adminimal_admin_toolbar           1.10.0       Adminimal styling brought to admin toolbar.
drupal/apigee_api_catalog                1.0.0        Apigee API Catalog for Drupal
drupal/apigee_edge                       1.1.0        Apigee Edge for Drupal.
drupal/apigee_m10n                       1.1.0        Apigee Edge Monetization for Drupal
drupal/better_exposed_filters            3.0.0-alpha6 Provides advanced options (such as links, checkboxes, or jQueryUI widgets) for exposed Views elements.
drupal/commerce                          2.14.0       Drupal Commerce is a flexible eCommerce solution.
drupal/components                        1.1.0        Registers “component libraries” defined in modules and themes with the Twig system
drupal/core                              8.7.8        Drupal is an open source content management platform powering millions of websites and applications.
drupal/ctools                            3.2.0        Provides a number of utility and helper APIs for Drupal developers and site builders.
drupal/default_content                   1.0.0-alpha8 Imports default content when a module is enabled
drupal/devel                             2.1.0        Various blocks, pages, and functions for developers.
drupal/email_registration                1.0.0-rc7    Allows users to register with an email address as their username.
drupal/entity                            1.0.0-rc3    Provides expanded entity APIs, which will be moved to Drupal core one day.
drupal/entity_reference_revisions        1.7.0        Adds a Entity Reference field type with revision support.
drupal/file_link                         1.7.0        Extends the core Link module by storing metadata about the target file.
drupal/fontawesome                       2.14.0       The web's most popular icon set and toolkit.
drupal/inline_entity_form                1.0.0-rc2    Provides a widget for inline management (creation, modification, removal) of referenced entities.
drupal/key                               1.10.0       Provides the ability to manage site-wide keys
drupal/paragraphs                        1.9.0        Enables the creation of Paragraphs entities.
drupal/pathauto                          1.5.0        Provides a mechanism for modules to automatically generate aliases for the content they manage.
drupal/profile                           1.0.0        Provides configurable user profiles.
drupal/radix                             4.6.0        Radix is a base theme for Drupal. It has Bootstrap, Sass, BrowserSync and Font Awesome built-in.
drupal/state_machine                     1.0.0-rc1    Provides code-driven workflow functionality.
drupal/token                             1.5.0        Provides a user interface for the Token API and some missing core tokens.
drush/drush                              9.7.1        Drush is a command line shell and scripting interface for Drupal, a veritable Swiss Army knife designed to make life easier for those of us who spend some of ...
easyrdf/easyrdf                          0.9.1        EasyRdf is a PHP library designed to make it easy to consume and produce RDF.
egulias/email-validator                  2.1.11       A library for validating emails against several RFCs
fightbulc/moment                         1.30.0       Parse, validate, manipulate, and display dates in PHP w/ i18n support. Inspired by moment.js
grasmash/expander                        1.0.0        Expands internal property references in PHP arrays file.
grasmash/yaml-expander                   1.4.0        Expands internal property references in a yaml file.
guzzlehttp/guzzle                        6.3.3        Guzzle is a PHP HTTP client library
guzzlehttp/promises                      v1.3.1       Guzzle promises library
guzzlehttp/psr7                          1.6.1        PSR-7 message implementation that also provides common utility methods
jakub-onderka/php-console-color          v0.2        
jakub-onderka/php-console-highlighter    v0.4         Highlight PHP code in terminal
league/container                         2.4.1        A fast and intuitive dependency injection container.
league/period                            3.4.0        A time range immutable value object
masterminds/html5                        2.7.0        An HTML5 parser and serializer.
nikic/php-parser                         v4.2.4       A PHP parser written in PHP
paragonie/random_compat                  v9.99.99     PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
pear/archive_tar                         1.4.8        Tar file management class with compression support (gzip, bzip2, lzma2)
pear/console_getopt                      v1.4.2       More info available on: http://pear.php.net/package/Console_Getopt
pear/pear-core-minimal                   v1.10.9      Minimal set of PEAR core files to be used as composer dependency
pear/pear_exception                      v1.0.0       The PEAR Exception base class.
php-http/client-common                   1.9.1        Common HTTP Client implementations and tools for HTTPlug
php-http/discovery                       1.7.0        Finds installed HTTPlug implementations and PSR-7 message factories
php-http/guzzle6-adapter                 v1.1.1       Guzzle 6 HTTP Adapter
php-http/httplug                         v1.1.0       HTTPlug, the HTTP client abstraction for PHP
php-http/message                         1.8.0        HTTP Message related tools
php-http/message-factory                 v1.0.2       Factory interfaces for PSR-7 HTTP Message
php-http/promise                         v1.0.0       Promise used for asynchronous HTTP requests
phpdocumentor/reflection-common          2.0.0        Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock        4.3.2        With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a DocBlock.
phpdocumentor/type-resolver              1.0.1        A PSR-5 based resolver of Class names, Types and Structural Element Names
psr/container                            1.0.0        Common Container Interface (PHP FIG PSR-11)
psr/http-message                         1.0.1        Common interface for HTTP messages
psr/log                                  1.1.0        Common interface for logging libraries
psy/psysh                                v0.9.9       An interactive shell for modern PHP.
ralouphie/getallheaders                  3.0.3        A polyfill for getallheaders.
stack/builder                            v1.0.5       Builder for stack middlewares based on HttpKernelInterface.
symfony-cmf/routing                      1.4.1        Extends the Symfony2 routing component for dynamic routes and chaining several routers
symfony/class-loader                     v3.4.32      Symfony ClassLoader Component
symfony/console                          v3.4.32      Symfony Console Component
symfony/debug                            v4.3.5       Symfony Debug Component
symfony/dependency-injection             v3.4.32      Symfony DependencyInjection Component
symfony/event-dispatcher                 v3.4.32      Symfony EventDispatcher Component
symfony/filesystem                       v4.3.5       Symfony Filesystem Component
symfony/finder                           v4.3.5       Symfony Finder Component
symfony/http-foundation                  v3.4.32      Symfony HttpFoundation Component
symfony/http-kernel                      v3.4.32      Symfony HttpKernel Component
symfony/inflector                        v4.3.5       Symfony Inflector Component
symfony/options-resolver                 v4.3.5       Symfony OptionsResolver Component
symfony/polyfill-ctype                   v1.12.0      Symfony polyfill for ctype functions
symfony/polyfill-iconv                   v1.12.0      Symfony polyfill for the Iconv extension
symfony/polyfill-mbstring                v1.12.0      Symfony polyfill for the Mbstring extension
symfony/polyfill-php70                   v1.12.0      Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-php72                   v1.12.0      Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/process                          v3.4.32      Symfony Process Component
symfony/property-access                  v4.3.5       Symfony PropertyAccess Component
symfony/property-info                    v4.3.5       Symfony Property Info Component
symfony/psr-http-message-bridge          v1.2.0       PSR HTTP message bridge
symfony/routing                          v3.4.32      Symfony Routing Component
symfony/serializer                       v3.4.32      Symfony Serializer Component
symfony/translation                      v3.4.32      Symfony Translation Component
symfony/validator                        v3.4.32      Symfony Validator Component
symfony/var-dumper                       v4.3.5       Symfony mechanism for exploring and dumping PHP variables
symfony/yaml                             v3.4.32      Symfony Yaml Component
twig/twig                                v1.42.3      Twig, the flexible, fast, and secure template language for PHP
typo3/phar-stream-wrapper                v2.1.3       Interceptors for PHP's native phar:// stream handling
webflo/drupal-finder                     1.2.0        Helper class to locate a Drupal installation from a given path.
webmozart/assert                         1.5.0        Assertions to validate method input/output with nice error messages.
webmozart/path-util                      2.3.0        A robust cross-platform utility for normalizing, comparing and modifying file paths.
zendframework/zend-diactoros             1.8.7        PSR HTTP Message implementations
zendframework/zend-escaper               2.6.1        Securely and safely escape HTML, HTML attributes, JavaScript, CSS, and URLs
zendframework/zend-feed                  2.12.0       provides functionality for consuming RSS and Atom feeds
zendframework/zend-stdlib                3.2.1        SPL extensions, array utilities, error handlers, and more
![Screenshot 2019-10-22 at 9 41 13 PM](https://user-images.githubusercontent.com/821268/67358261-b79a3b00-f514-11e9-9a0c-157f7958f34c.png)

**Comment by arunz6161** [comment]
Thanks @kford for logging the issue. I was able to simulate the behavior. Changes in the time range selection has no impact on the series which seems to plotting data for **every 1 millisecond**. We will take a look at this and keep the ticket updated with our findings.

**Comment by arunz6161** [comment]
Selecting the "To" time range to a value in future allows the series to render- but it ignores hours where there has been no value.

**Comment by arunz6161** [comment]
Adding a couple of screenshots that highlight the issue further

**From Devportal ( App - analytics, filter "Message Count")**
<img width="646" alt="Screen Shot 2019-10-24 at 2 18 03 PM" src="https://user-images.githubusercontent.com/4381612/67526824-71ef8680-f66a-11e9-858e-fc46c4170074.png">

**From Apigee Edge ( Customer report- Total Traffic filtered by App)**

![Screen Shot 2019-10-24 at 2 15 30 PM](https://user-images.githubusercontent.com/4381612/67526851-79af2b00-f66a-11e9-87d3-7b1089a5249f.png)

**CSV export from portal:**

Date,"Message count"
**"2019-10-24 21:00:00 +00:00",34
"2019-10-24 20:00:00 +00:00",1135
"2019-10-24 19:00:00 +00:00",0
"2019-10-24 18:00:00 +00:00",420**
"2019-10-24 17:00:00 +00:00",0
"2019-10-24 16:00:00 +00:00",0
"2019-10-24 15:00:00 +00:00",0
"2019-10-24 14:00:00 +00:00",0
"2019-10-24 13:00:00 +00:00",0
"2019-10-24 12:00:00 +00:00",0
"2019-10-24 11:00:00 +00:00",0
"2019-10-24 10:00:00 +00:00",0
"2019-10-24 09:00:00 +00:00",0
"2019-10-24 08:00:00 +00:00",0
"2019-10-24 07:00:00 +00:00",0
"2019-10-24 06:00:00 +00:00",0
"2019-10-24 05:00:00 +00:00",0
"2019-10-24 04:00:00 +00:00",0
"2019-10-24 03:00:00 +00:00",0
"2019-10-24 02:00:00 +00:00",0
"2019-10-24 01:00:00 +00:00",0
"2019-10-24 00:00:00 +00:00",0
"2019-10-23 23:00:00 +00:00",0
"2019-10-23 22:00:00 +00:00",0
"2019-10-23 21:00:00 +00:00",0

From the above, we can see that portal is ignoring all "zero" values resulting in incorrect trending.

**Comment by minnur** [comment]
@arunz6161 looks like LineChart does not work with 0 values properly See https://github.com/google/google-visualization-issues/issues/1118 

I managed to show 0 values in the chart by fixing `hAxis.viewWindow.min` and `hAxis.viewWindow.max` routine in the module.
