### ISSUE TITLE
Highlight "D8P" solution for hybrid being in alpha

### ISSUE THREAD

**Issue by arunz6161** [apigee/apigee-edge-drupal#291]
**Is your feature request related to a problem? Please describe.**
On the install screen and on the status page, indicate that implementation of D8P for hybrid is in alpha.

**Comment by cnovak** [comment]
You mean "beta" correct? @earth2marsh any good wording for us ? How about:

> Edge Hybrid support is currently a beta feature in the Apigee Edge module. Connecting to an Edge Hybrid organization should only be used for evaluation and testing purposes. Do not use the Edge Hybrid feature in a production environment.

**Comment by earth2marsh** [comment]
How about: 
> Support for Apigee Hybrid in the Apigee modules is in Beta. Connecting to a Hybrid organization is appropriate for evaluation and testing purposes during this pre-production stage.

**Comment by arlina-espinoza** [comment]
Fixed by #301
