### ISSUE TITLE
[Hybrid] Unable to create app on hybrid portal

### ISSUE THREAD

**Issue by arunz6161** [apigee/apigee-edge-drupal#296]
**Describe the bug**
Creating app fails with the error message `The machine-readable name is already in use. It must be unique.`

**To Reproduce**
1.  As an admin or as a developer, login to the portal
2. Click on Apps and "Add app"
3. Enter any value and select a product and click "ADD APP"
4. Error "The machine-readable name is already in use. It must be unique." is seen

**Expected behavior**
App creation should be succesful

**Screenshots**
<img width="760" alt="Screen Shot 2019-11-15 at 2 28 40 PM" src="https://user-images.githubusercontent.com/4381612/68980080-474da500-07b4-11ea-88e6-a9de3ba4da53.png">

**Additional context**
From debug logs

Unable to properly validate an app name's uniqueness. App name: apigeetest. Owner: test@gmail.com NOT_FOUND: App named apigeetest does not exist under test@gmail.com Apigee\Edge\HttpClient\Plugin\ResponseHandlerPlugin->decodeResponse() (line 104 of /srv/bindings/6420f4f7065c494287b7dd71bda39f5b/code/vendor/apigee/apigee-client-php/src/HttpClient/Plugin/ResponseHandlerPlugin.php).
#0 /srv/bindings/6420f4f7065c494287b7dd71bda39f5b/code/vendor/apigee/apigee-client-php/src/HttpClient/Plugin/ResponseHandlerPlugin.php(69): Apigee\Edge\HttpClient\Plugin\ResponseHandlerPlugin->decodeResponse(Object(GuzzleHttp\Psr7\Response), Object(GuzzleHttp\Psr7\Request))
#1 /srv/bindings/6420f4f7065c494287b7dd71bda39f5b/code/vendor/php-http/httplug/src/Promise/HttpRejectedPromise.php(33): Apigee\Edge\HttpClient\Plugin\ResponseHandlerPlugin->Apigee\Edge\HttpClient\Plugin\{closure}(Object(Http\Client\Exception\HttpException))
#2 /srv/bindings/6420f4f7065c494287b7dd71bda39f5b/code/vendor/apigee/apigee-client-php/src/HttpClient/Plugin/ResponseHandlerPlugin.php(75): Http\Client\Promise\HttpRejectedPromise->then(Object(Closure), Object(Closure))
#3 /srv/bindings/6420f4f7065c494287b7dd71bda39f5b/code/vendor/php-http/client-common/src/PluginClient.php(161): Apigee\Edge\HttpClient\Plugin\ResponseHandlerPlugin->handleRequest(Object(GuzzleHttp\Psr7\Request), Object(Closure), Object(Closure))
#4 /srv/bindings/6420f4f7065c494287b7dd71bda39f5b/code/vendor/apigee/apigee-client-php/src/HttpClient/Plugin/RetryOauthAuthenticationPlugin.php(57): Http\Client\Common\PluginClient->Http\Client\Common\{closure}(Object(GuzzleHttp\Psr7\Request))
#5 /srv/bindings/6420f4f7065c494287b7dd71bda39f5b/code/vendor/php-http/client-common/src/PluginClient.php(161): Apigee\Edge\HttpClient\Plugin\RetryOauthAuthenticationPlugin->handleRequest(Object(GuzzleHttp\Psr7\Request), Object(Closure), Object(Closure))
#6 /srv/bindings/6420f4f7065c494287b7dd71bda39f5b/code/vendor/php-http/client-common/src/Plugin/HistoryPlugin.php(39): Http\Client\Common\PluginClient->Http\Client\Common\{closure}(Object(GuzzleHttp\Psr7\Request))
#7 /srv/bindings/6420f4f7065c494287b7dd71bda39f5b/code/vendor/php-http/client-common/src/PluginClient.php(161): Http\Client\Common\Plugin\HistoryPlugin->handleRequest(Object(GuzzleHttp\Psr7\Request), Object(Closure), Object(Closure))
#8 /srv/bindings/6420f4f7065c494287b7dd71bda39f5b/code/vendor/php-http/client-common/src/Plugin/AuthenticationPlugin.php(36): Http\Client\Common\PluginClient->Http\Client\Common\{closure}(Object(GuzzleHttp\Psr7\Request))
#9 /srv/bindings/6420f4f7065c494287b7dd71bda39f5b/code/vendor/php-http/client-common/src/PluginClient.php(161): Http\Client\Common\Plugin\AuthenticationPlugin->handleRequest(Object(GuzzleHttp\Psr7\Request), Object(Closure), Object(Closure))
#10 /srv/bindings/6420f4f7065c494287b7dd71bda39f5b/code/vendor/php-http/client-common/src/Plugin/HeaderDefaultsPlugin.php(41): Http\Client\Common\PluginClient->Http\Client\Common\{closure}(Object(GuzzleHttp\Psr7\Request))
#11 /srv/bindings/6420f4f7065c494287b7dd71bda39f5b/code/vendor/php-http/client-common/src/PluginClient.php(161): Http\Client\Common\Plugin\HeaderDefaultsPlugin->handleRequest(Object(GuzzleHttp\Psr7\Request), Object(Closure), Object(Closure))
#12 /srv/bindings/6420f4f7065c494287b7dd71bda39f5b/code/vendor/apigee/apigee-client-php/src/HttpClient/Plugin/AddPathPlugin.php(78): Http\Client\Common\PluginClient->Http\Client\Common\{closure}(Object(GuzzleHttp\Psr7\Request))
#13 /srv/bindings/6420f4f7065c494287b7dd71bda39f5b/code/vendor/php-http/client-common/src/PluginClient.php(161): Apigee\Edge\HttpClient\Plugin\AddPathPlugin->handleRequest(Object(GuzzleHttp\Psr7\Request), Object(Closure), Object(Closure))
#14 /srv/bindings/6420f4f7065c494287b7dd71bda39f5b/code/vendor/php-http/client-common/src/Plugin/AddHostPlugin.php(64): Http\Client\Common\PluginClient->Http\Client\Common\{closure}(Object(GuzzleHttp\Psr7\Request))
#15 /srv/bindings/6420f4f7065c494287b7dd71bda39f5b/code/vendor/php-http/client-common/src/PluginClient.php(161): Http\Client\Common\Plugin\AddHostPlugin->handleRequest(Object(GuzzleHttp\Psr7\Request), Object(Closure), Object(Closure))
#16 /srv/bindings/6420f4f7065c494287b7dd71bda39f5b/code/vendor/php-http/client-common/src/PluginClient.php(175): Http\Client\Common\PluginClient->Http\Client\Common\{closure}(Object(GuzzleHttp\Psr7\Request))
#17 /srv/bindings/6420f4f7065c494287b7dd71bda39f5b/code/vendor/php-http/client-common/src/PluginClient.php(88): Http\Client\Common\PluginClient->Http\Client\Common\{closure}(Object(GuzzleHttp\Psr7\Request))
#18 /srv/bindings/6420f4f7065c494287b7dd71bda39f5b/code/vendor/apigee/apigee-client-php/src/Client.php(242): Http\Client\Common\PluginClient->sendRequest(Object(GuzzleHttp\Psr7\Request))
#19 /srv/bindings/6420f4f7065c494287b7dd71bda39f5b/code/vendor/apigee/apigee-client-php/src/Client.php(390): Apigee\Edge\Client->sendRequest(Object(GuzzleHttp\Psr7\Request))
#20 /srv/bindings/6420f4f7065c494287b7dd71bda39f5b/code/vendor/apigee/apigee-client-php/src/Client.php(194): Apigee\Edge\Client->send('GET', Object(GuzzleHttp\Psr7\Uri), Array, NULL)
#21 /srv/bindings/6420f4f7065c494287b7dd71bda39f5b/code/vendor/apigee/apigee-client-php/src/Controller/EntityLoadOperationControllerTrait.php(38): Apigee\Edge\Client->get(Object(GuzzleHttp\Psr7\Uri))
#22 /srv/bindings/6420f4f7065c494287b7dd71bda39f5b/code/web/modules/contrib/apigee_edge/src/Entity/Controller/AppByOwnerController.php(148): Apigee\Edge\Api\Management\Controller\AppByOwnerController->load('apigeetest')
#23 /srv/bindings/6420f4f7065c494287b7dd71bda39f5b/code/web/modules/contrib/apigee_edge/src/Entity/Form/DeveloperAppFormTrait.php(66): Drupal\apigee_edge\Entity\Controller\AppByOwnerController->load('apigeetest')
#24 [internal function]: Drupal\apigee_edge\Entity\Form\DeveloperAppCreateFormBase::appExists('apigeetest', Array, Object(Drupal\Core\Form\FormState))
#25 /srv/bindings/6420f4f7065c494287b7dd71bda39f5b/code/web/core/lib/Drupal/Core/Render/Element/MachineName.php(267): call_user_func(Array, 'apigeetest', Array, Object(Drupal\Core\Form\FormState))
#26 [internal function]: Drupal\Core\Render\Element\MachineName::validateMachineName(Array, Object(Drupal\Core\Form\FormState), Array)
#27 /srv/bindings/6420f4f7065c494287b7dd71bda39f5b/code/web/core/lib/Drupal/Core/Form/FormValidator.php(282): call_user_func_array(Array, Array)
#28 /srv/bindings/6420f4f7065c494287b7dd71bda39f5b/code/web/core/lib/Drupal/Core/Form/FormValidator.php(238): Drupal\Core\Form\FormValidator->doValidateForm(Array, Object(Drupal\Core\Form\FormState))
#29 /srv/bindings/6420f4f7065c494287b7dd71bda39f5b/code/web/core/lib/Drupal/Core/Form/FormValidator.php(118): Drupal\Core\Form\FormValidator->doValidateForm(Array, Object(Drupal\Core\Form\FormState), 'developer_app_a...')
#30 /srv/bindings/6420f4f7065c494287b7dd71bda39f5b/code/web/core/lib/Drupal/Core/Form/FormBuilder.php(576): Drupal\Core\Form\FormValidator->validateForm('developer_app_a...', Array, Object(Drupal\Core\Form\FormState))
#31 /srv/bindings/6420f4f7065c494287b7dd71bda39f5b/code/web/core/lib/Drupal/Core/Form/FormBuilder.php(319): Drupal\Core\Form\FormBuilder->processForm('developer_app_a...', Array, Object(Drupal\Core\Form\FormState))
#32 /srv/bindings/6420f4f7065c494287b7dd71bda39f5b/code/web/core/lib/Drupal/Core/Controller/FormController.php(93): Drupal\Core\Form\FormBuilder->buildForm(Object(Drupal\apigee_edge\Entity\Form\DeveloperAppCreateFormForDeveloper), Object(Drupal\Core\Form\FormState))
#33 [internal function]: Drupal\Core\Controller\FormController->getContentResult(Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\RouteMatch))
#34 /srv/bindings/6420f4f7065c494287b7dd71bda39f5b/code/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array)
#35 /srv/bindings/6420f4f7065c494287b7dd71bda39f5b/code/web/core/lib/Drupal/Core/Render/Renderer.php(582): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#36 /srv/bindings/6420f4f7065c494287b7dd71bda39f5b/code/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure))
#37 /srv/bindings/6420f4f7065c494287b7dd71bda39f5b/code/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array)
#38 /srv/bindings/6420f4f7065c494287b7dd71bda39f5b/code/vendor/symfony/http-kernel/HttpKernel.php(151): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#39 /srv/bindings/6420f4f7065c494287b7dd71bda39f5b/code/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#40 /srv/bindings/6420f4f7065c494287b7dd71bda39f5b/code/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#41 /srv/bindings/6420f4f7065c494287b7dd71bda39f5b/code/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#42 /srv/bindings/6420f4f7065c494287b7dd71bda39f5b/code/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#43 /srv/bindings/6420f4f7065c494287b7dd71bda39f5b/code/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#44 /srv/bindings/6420f4f7065c494287b7dd71bda39f5b/code/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#45 /srv/bindings/6420f4f7065c494287b7dd71bda39f5b/code/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#46 /srv/bindings/6420f4f7065c494287b7dd71bda39f5b/code/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#47 /srv/bindings/6420f4f7065c494287b7dd71bda39f5b/code/web/core/lib/Drupal/Core/DrupalKernel.php(693): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#48 /srv/bindings/6420f4f7065c494287b7dd71bda39f5b/code/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#49 {main}

**Version Info**
Apigee Edge Drupal integration ( hybrid)

**Comment by arlina-espinoza** [comment]
@arunz6161:  Fixed this from the PHP client library. It requires PR's:
- https://github.com/apigee/apigee-client-php/pull/92
- https://github.com/apigee/apigee-client-php/pull/91

I've updated our testing environment with all the required PR's/code.

**Comment by arshad** [comment]
I can confirm @arlina-espinoza's PRs fixes this.

**Comment by arlina-espinoza** [comment]
PRs merged, and issue should be fixed on the latest `2.x-hybrid` client library.

**Comment by arlina-espinoza** [comment]
Closed by PRs apigee/apigee-client-php#92 and apigee/apigee-client-php#91.
