### ISSUE TITLE
App Creation with product programmatically in Drupal8

### ISSUE THREAD

**Issue by robin0888** [apigee/apigee-edge-drupal#310]
Required help, Thanks
 
I'm creating a team and developer app, I'm able to create internal app only without any product. (Please have a look at below code)

```
$teamAppStorage = \Drupal::entityTypeManager()->getStorage('team_app');

    $teamApp = $teamAppStorage->create([
      'name' => 'robin_27_11_01',
      'companyName' => 'zzzzzyrobin',
 ]);
```
**Getting error while trying to add product for an app**

```
$teamAppStorage = \Drupal::entityTypeManager()->getStorage('team_app');

    $teamApp = $teamAppStorage->create([
      'name' => 'robin_27_11_01',
      'companyName' => 'zzzzzyrobin',
	 'credentials' => new \Apigee\Edge\Api\Management\Entity\AppCredential(['apiProducts' => 'tdev-content-api']),
 ]);
```

**Comment by arlina-espinoza** [comment]
Hi @robin0888 ,

When an app gets created, a credential is autogenerated as well, I don't think you can override it on app create. So you can either fetch the credential and update it after app creation, or generate a new key with your required information.

You can find some ideas on how this is done on the following files (they are using developer apps, but the process is analogous for team apps):

- This part deals with deleting the auto-generated credential and generating a new one: 
https://github.com/apigee/apigee-edge-drupal/blob/a5c28c454dc36cdb582a622046f8e49de0eba09c/tests/src/Functional/DeveloperAppCredentialEventTest.php#L131-L138

- Or just updating the API products and other properties (see https://github.com/apigee/apigee-client-php/blob/e5e352ed93fab670459396339f3257fe314207ad/examples/create_new_app_with_credential.php#L51-L53): 
```
$dacc->addProducts($credential->id(), $apiProducts); // $apiProducts is an array.
$dacc->updateAttributes($credential->id(), $credAttributes);
$dacc->overrideScopes($credential->id(), $scopes);
```

So maybe your code could look like _(untested)_:

```
$teamAppStorage = \Drupal::entityTypeManager()->getStorage('team_app');
$teamApp = $teamAppStorage->create([
  'name' => 'robin_27_11_01',
  'companyName' => 'zzzzzyrobin',
]);
$credentials = $teamApp->getCredentials();
$credential = reset($credentials);
$credentialsController = $this->container->get('apigee_edge_teams.controller.team_app_credential_controller_factory')->teamAppCredentialController($teamApp->getAppOwner(), $teamApp->getName());
$apiProducts = ['tdev-content-api'];
$credentialsController->addProducts($credential->id(), $apiProducts);
```

:)

**Comment by robin0888** [comment]
thanks, @arlina-espinoza. Let me check the same at my end.
