### ISSUE TITLE
During new site install, hybrid message is confusing on database connection page

### ISSUE THREAD

**Issue by cnovak** [apigee/apigee-edge-drupal#311]
**Describe the bug**
When installing a new Drupal site using Kickstart, a warning message is displayed on the database connections page.  This may be confusing to users on why this warning is being displayed when they may not even know what Hybrid is.

**To Reproduce**
1. Do a new kickstart install
2. On database connection page, the warning message "Support for Apigee hybrid in the Apigee modules is in Alpha. Connecting to a hybrid organization is appropriate for evaluation and testing purposes during this pre-production stage."  is displayed.

<img width="702" alt="connect-error" src="https://user-images.githubusercontent.com/613093/70650306-b677b700-1c03-11ea-9766-e66f25ee19a1.png">

**Expected behavior**
If I am doing a straightforward install of a site, I would not expect to see a warning on the database connection page, especially since I may not know what hybrid is.  I would expect this warning to only be displayed if I configured a connection to a Hybrid org.

**Version Info**
8.x-1.3

**Comment by kscheirer** [comment]
So the warning would happen post `Configure Apigee Edge` step?

**Comment by arlina-espinoza** [comment]
Agreed it looks out of place. What seems weird to me is that the message is getting shown before the module is even installed, so we should check how to avoid it.

**Comment by cnovak** [comment]
This error is no longer displayed
