### ISSUE TITLE
[Hybrid] App does not show on "Apps" after creation

### ISSUE THREAD

**Issue by Shanli-Yu** [apigee/apigee-edge-drupal#313]
**Describe the bug**
After the user creates an app, a message of the app successfully created will show up, but when on the "Apps" page, app will not appear. 

**To Reproduce**
1. Add an app from "Apps" page
2. See the message but no app getting displayed on page

**Expected behavior**
Along with the app successfully created message, the app should also be displayed on the page. 

**Screenshots**
![image](https://user-images.githubusercontent.com/45441018/70950836-8cb0fc80-2016-11ea-8107-612f9f8ca58f.png)
"-----------------------------------------------"
![image](https://user-images.githubusercontent.com/45441018/70950853-9b97af00-2016-11ea-8de7-3d72e1afa8f3.png)

**Additional context**
Below is the watchdog log of "Notice" severity: 
`Notice: Undefined property: stdClass::$value in Apigee\Edge\Denormalizer\AttributesPropertyDenormalizer->denormalize() (line 57 of /app/vendor/apigee/apigee-client-php/src/Denormalizer/AttributesPropertyDenormalizer.php) #0 /app/web/core/includes/bootstrap.inc(587): _drupal_error_handler_real(8, 'Undefined prope...', '/app/vendor/api...', 57, Array) #1 /app/vendor/apigee/apigee-client-php/src/Denormalizer/AttributesPropertyDenormalizer.php(57): _drupal_error_handler(8, 'Undefined prope...', '/app/vendor/api...', 57, Array) #2 /app/vendor/symfony/serializer/Serializer.php(182): Apigee\Edge\Denormalizer\AttributesPropertyDenormalizer->denormalize(Array, 'Apigee\\Edge\\Str...', 'json', Array) #3 /app/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php(276): Symfony\Component\Serializer\Serializer->denormalize(Array, 'Apigee\\Edge\\Str...', 'json', Array) #4 /app/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php(197): Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->validateAndDenormalize('Apigee\\Edge\\Api...', 'attributes', Array, 'json', Array) #5 /app/vendor/apigee/apigee-client-php/src/Denormalizer/ObjectDenormalizer.php(111): Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->denormalize(Object(stdClass), 'Apigee\\Edge\\Api...', 'json', Array) #6 /app/vendor/apigee/apigee-client-php/src/Api/Management/Denormalizer/AppDenormalizer.php(52): Apigee\Edge\Denormalizer\ObjectDenormalizer->denormalize(Object(stdClass), 'Apigee\\Edge\\Api...', 'json', Array) #7 /app/vendor/symfony/serializer/Serializer.php(182): Apigee\Edge\Api\Management\Denormalizer\AppDenormalizer->denormalize(Object(stdClass), 'Apigee\\Edge\\Api...', 'json', Array) #8 /app/vendor/symfony/serializer/Serializer.php(133): Symfony\Component\Serializer\Serializer->denormalize(Object(stdClass), 'Apigee\\Edge\\Api...', 'json', Array) #9 /app/vendor/apigee/apigee-client-php/src/Serializer/EntitySerializer.php(124): Symfony\Component\Serializer\Serializer->deserialize(Object(stdClass), 'Apigee\\Edge\\Api...', 'json', Array) #10 /app/vendor/apigee/apigee-client-php/src/Serializer/EntitySerializer.php(139): Apigee\Edge\Serializer\EntitySerializer->deserialize('{\n "appId": "0...', 'Apigee\\Edge\\Api...', 'json') #11 /app/vendor/apigee/apigee-client-php/src/Controller/EntityCreateOperationControllerTrait.php(42): Apigee\Edge\Serializer\EntitySerializer->setPropertiesFromResponse(Object(GuzzleHttp\Psr7\Response), Object(Apigee\Edge\Api\Management\Entity\DeveloperApp)) #12 /app/web/modules/contrib/apigee_edge/src/Entity/Controller/CachedEntityCrudOperationsControllerTrait.php(52): Apigee\Edge\Api\Management\Controller\AppByOwnerController->create(Object(Apigee\Edge\Api\Management\Entity\DeveloperApp)) #13 /app/web/modules/contrib/apigee_edge/src/Entity/Controller/DeveloperAppEdgeEntityControllerProxy.php(73): Drupal\apigee_edge\Entity\Controller\AppByOwnerController->create(Object(Apigee\Edge\Api\Management\Entity\DeveloperApp)) #14 /app/web/modules/contrib/apigee_edge/src/Entity/Storage/EdgeEntityStorageBase.php(165): Drupal\apigee_edge\Entity\Controller\DeveloperAppEdgeEntityControllerProxy->create(Object(Apigee\Edge\Api\Management\Entity\DeveloperApp)) #15 /app/web/modules/contrib/apigee_edge/src/Entity/Storage/EdgeEntityStorageBase.php(217): Drupal\apigee_edge\Entity\Storage\EdgeEntityStorageBase->Drupal\apigee_edge\Entity\Storage\{closure}(Object(Drupal\apigee_edge\Entity\Controller\DeveloperAppEdgeEntityControllerProxy)) #16 /app/web/modules/contrib/apigee_edge/src/Entity/Storage/EdgeEntityStorageBase.php(172): Drupal\apigee_edge\Entity\Storage\EdgeEntityStorageBase->withController(Object(Closure)) #17 /app/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php(457): Drupal\apigee_edge\Entity\Storage\EdgeEntityStorageBase->doSave(NULL, Object(Drupal\apigee_edge\Entity\DeveloperApp)) #18 /app/web/core/lib/Drupal/Core/Entity/EntityBase.php(394): Drupal\Core\Entity\EntityStorageBase->save(Object(Drupal\apigee_edge\Entity\DeveloperApp)) #19 /app/web/modules/contrib/apigee_edge/src/Entity/Form/AppForm.php(191): Drupal\Core\Entity\EntityBase->save() #20 /app/web/modules/contrib/apigee_edge/src/Entity/Form/AppForm.php(142): Drupal\apigee_edge\Entity\Form\AppForm->saveApp() #21 [internal function]: Drupal\apigee_edge\Entity\Form\AppForm->save(Array, Object(Drupal\Core\Form\FormState)) #22 /app/web/core/lib/Drupal/Core/Form/FormSubmitter.php(111): call_user_func_array(Array, Array) #23 /app/web/core/lib/Drupal/Core/Form/FormSubmitter.php(51): Drupal\Core\Form\FormSubmitter->executeSubmitHandlers(Array, Object(Drupal\Core\Form\FormState)) #24 /app/web/core/lib/Drupal/Core/Form/FormBuilder.php(590): Drupal\Core\Form\FormSubmitter->doSubmitForm(Array, Object(Drupal\Core\Form\FormState)) #25 /app/web/core/lib/Drupal/Core/Form/FormBuilder.php(319): Drupal\Core\Form\FormBuilder->processForm('developer_app_a...', Array, Object(Drupal\Core\Form\FormState)) #26 /app/web/core/lib/Drupal/Core/Controller/FormController.php(93): Drupal\Core\Form\FormBuilder->buildForm(Object(Drupal\apigee_edge\Entity\Form\DeveloperAppCreateFormForDeveloper), Object(Drupal\Core\Form\FormState)) #27 [internal function]: Drupal\Core\Controller\FormController->getContentResult(Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\RouteMatch)) #28 /app/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array) #29 /app/web/core/lib/Drupal/Core/Render/Renderer.php(582): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #30 /app/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure)) #31 /app/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) #32 /app/vendor/symfony/http-kernel/HttpKernel.php(151): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #33 /app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #34 /app/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #35 /app/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #36 /app/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #37 /app/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true) #38 /app/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #39 /app/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #40 /app/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #41 /app/web/core/lib/Drupal/Core/DrupalKernel.php(693): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #42 /app/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #43 {main}.`

**Comment by Shanli-Yu** [comment]
App will appear once site cache is cleared
![image](https://user-images.githubusercontent.com/45441018/70952307-b409c880-201a-11ea-9da0-3f2a97dbc7cf.png)

**Comment by cnovak** [comment]
We need to catch this error and log something more useful such as  a message indicating that there will be a delay in app showing up.

**Comment by shadcn** [comment]
@cnovak Regarding the error here, it looks like when a description is not provided, the response is `{ "attributes": { "name": "Notes"}}`.

`\Apigee\Edge\Denormalizer\AttributesPropertyDenormalizer::denormalize` expects data with a name and a value key. We should probably throw a `Symfony\Component\Serializer\Exception\UnexpectedValueException` here or set the attributes to empty string `""`.

```php
/**
     * Transforms input data to our internal representation.
     *
     * Acceptable inputs:
     *   - Edge response format: $data = [{'name' => 'foo', 'value' => 'bar'}, {'name' => 'bar', 'value' => 'baz'}]
     *     (from the EntityNormalizer for example)
     *   - Internal representation of attributes: ['foo' => 'bar', 'bar' => 'baz']
     *
     * @inheritdoc
     */
    public function denormalize($data, $class, $format = null, array $context = [])
    {
        $flatten = [];
        foreach ($data as $key => $item) {
            if (is_object($item)) {
                // $data came from the EntityNormalizer.
                $flatten[$item->name] = $item->value; <---- Fails
            } else {
...
```

This is on the PHP client.

**Comment by arunz6161** [comment]
WIth Hybrid GA release, this issue is no longer reproducible and hence we will move this to "postponed" state and revisit if there are reports of this resurfacing.

**Comment by cnovak** [comment]
Going to close this issue since it was most likely a pre GA issue.

**Comment by melayyoub** [comment]
This issue still in Core 8.9.10 Apigee Edge 8.x-1.20 , if you still have this issue just go to the includes/apigee.inc and change lines 99-117 from 

```
/**
 * Implement template_preprocess_app_credentials().
 */
function apigee_kickstart_preprocess_app_credential(&$variables) {
  // Render the consumerKey and the consumerSecret as secret fields.
  foreach (['consumerKey', 'consumerSecret'] as $field_name) {
    if (empty($variables['primary_wrapper'][$field_name]['value']['#value'])) {
      continue;
    }

    $variables['primary_wrapper'][$field_name]['value'] = [
      '#type' => 'apigee_secret',
      '#value' => $variables['primary_wrapper'][$field_name]['value']['#value'],
    ];
  }

 // Rename title to products.
  $variables['secondary_wrapper']['title']['#title'] = t('Products');
}
```

to 

```
/**
 * Implement template_preprocess_app_credentials().
 */
function svb_theme_preprocess_app_credential(&$variables) {
  // Render the consumerKey and the consumerSecret as secret fields.
  foreach (['consumerKey', 'consumerSecret'] as $field_name) {
    $variables['primary_wrapper'][$field_name]['#value'] = [
      '#type' => 'secret',
      '#value' => $variables['primary_wrapper'][$field_name]['value'],
    ];
  }

  // Rename title to products.
  $variables['secondary_wrapper']['title']['#title'] = t('Products');
}
```

**Comment by raakesh-blokhra** [comment]
Thanks @melayyoub ... we will review the suggestions and take the necessary action.

**Comment by phdhiren** [comment]
I'm not able to replicate with latest build. 
The warning is separate issue tracked at https://github.com/apigee/apigee-client-php/issues/108 for which I can see PR
