### ISSUE TITLE
Not able to login with Social Auth Google module, If Developer exists in Apigee Edge but not in developer portal

### ISSUE THREAD

**Issue by varuntit101** [apigee/apigee-edge-drupal#315]
Trying to login with google in developer portal :-
First scenario:-  Developer doesn't exist on Apigee Edge, In this case, as expected a new User is created in developer portal as well a Developer is created in Edge.

Second scenario:- Developer already exist on Edge, but not in Developer portal, In this case, when I am trying to login I am getting following error:-

TypeError: Argument 1 passed to Drupal\apigee_edge\Entity\Developer::setFirstName() must be of the type string, null given, called in /srv/bindings/55b4fa54bbfb4b3cb2ca4d91de385c2a/code/modules/contrib/apigee_edge/src/UserDeveloperConverter.php on line 107 in Drupal\apigee_edge\Entity\Developer->setFirstName() (line 368 of /srv/bindings/55b4fa54bbfb4b3cb2ca4d91de385c2a/code/modules/contrib/apigee_edge/src/Entity/Developer.php)

**Expected behavior**
User should be created in developer portal, If a developer already exists with the same email in Edge.

**Version Info**
Social Auth Google - 8.x-2.0
Apigee Edge - 8.x-1.3
Drupal core - 8.7.11

PFA:-
![screencapture-dev-ferguson-d8-pantheonsite-io-admin-reports-dblog-event-152-2020-01-03-23_22_04](https://user-images.githubusercontent.com/9864661/71739688-29312680-2e80-11ea-8e04-af8dea462a3e.png)

**Comment by arunz6161** [comment]
@varuntit101 could you please run "[developer sync](https://www.drupal.org/docs/8/modules/apigee-edge/synchronize-developers-with-apigee-edge)" to ensure that developers are copied over from edge to Drupal and then let us know if the issue persists.
