### ISSUE TITLE
Document integration between Drupal portals and Hybrid

### ISSUE THREAD

**Issue by arunz6161** [apigee/apigee-edge-drupal#317]
Similar to what we have for D7P: https://docs.apigee.com/api-platform/publish/drupal/communicating-between-developer-services-portal-and-edge

**Comment by cnovak** [comment]
Our documentation covers how you can configure Drupal portal to talk to Hybrid : https://www.drupal.org/docs/8/modules/apigee-edge/configure-the-connection-to-apigee-edge#configure-credentials-hybrid

Anything missing @arunz6161 ?

**Comment by cnovak** [comment]
@giteshk @arunz6161 , please reopen if any documentation additions are needed, thanks
