### ISSUE TITLE
Missing splat operator

### ISSUE THREAD

**Issue by teknikstudios** [apigee/apigee-edge-drupal#320]
**Describe the bug**
A missing splat operator is causing an exception to be thrown when calling the `setProxies()` method on a `\Drupal\apigee_edge\Entity\ApiProxy` object

**To Reproduce**
1. Create an instance of `\Drupal\apigee_edge\Entity\ApiProxy`
2. Call the `setProxies()` method with any string value as a parameter

**The Fix**
In the `setProxies()` method of `\Drupal\apigee_edge\Entity\ApiProxy`, add a splat operator to the call to `$this->decorated->setProxies()`
```php
public function setProxies(string ...$proxy): void {
  $this->decorated->setProxies(...$proxy);
}
```

**Comment by cnovak** [comment]
@teknikstudios  I believe you may be talking about `\Drupal\apigee_edge\Entity\ApiProduct`? 

# Steps to reproduce
Code:
```
    $entity_type_manager = \Drupal::service('entity_type.manager');
    $apiproduct1 = $entity_type_manager->getStorage('api_product')->load('ywQqS7kA');
    $apiproduct1->setProxies('testA');
```
Throws error:
```
TypeError : Argument 1 passed to Apigee\Edge\Api\Management\Entity\ApiProduct::setProxies() must be of the type string, array given, called in web/modules/contrib/apigee_edge/src/Entity/ApiProduct.php on line 112
vendor/apigee/apigee-client-php/src/Api/Management/Entity/ApiProduct.php:98
 web/modules/contrib/apigee_edge/src/Entity/ApiProduct.php:112
 web/modules/contrib/apigee_edge/tests/src/Unit/Entity/ApiProductTest.php:48
```

I am creating the fix for this now, but let me know if my steps to reproduce do not cover your issue.
