### ISSUE TITLE
team invitation for external members

### ISSUE THREAD

**Issue by mahesh-umarane** [apigee/apigee-edge-drupal#329]
Hi All,

I am using Apigee Developer Portal Kickstart distribution in Drupal 8.

With this members can be added to a team. But it is not similar to Company Invite of Drupal 7.

Could you please suggest, any module for Team invitation for external members in Drupal 8?

With this module,

1. External/Guests users can be invited to team using email address

2. With the invitation emails, User will register to portal and assigned to the team

3. Till user accepts invitation, the request will be in pending state

4. It can be cancelled before acceptance

**Comment by mikesson** [comment]
Hi, adding a +1 to this request as this would enhance the `teams` capabilities. Currently, only existing members can be added to a team. The invitation should send out an email and allow for user registration which then automatically adds the user to the team with the defined role (or with the member role by default)

**Comment by cnovak** [comment]
Thanks for the input @mikesson and @mahesh-umarane. The more feedback we get the better idea we have on how to plan out development for needed fixes or features. We don't have a timeline yet on this but we will keep the ticket updated.

**Comment by mikesson** [comment]
*One more consideration:*
When having developer invitations, the concept of a "company admin" roles should be considered, which allows creating teams and entering billing details, as well as sending invites to members who can then onboard as a "company user" to view team APIs.

Currently, there is only the "Create teams" and "View any Teams" permission to work with, but for the above to work, the modules also requires a "View my team apps" permission.

**Comment by mikesson** [comment]
Adding to the above, such roles can be built by editing permissions of team "Members" and "Admins" here: https://<your-site>/admin/config/apigee-edge/team-settings/permissions

**Comment by mikesson** [comment]
Suggestion from customer: as only users with existing accounts can be invited to a team, a workflow/setting could be: when inviting a specific email address, "if user does not exist, send email to user to register on portal.

**Comment by cnovak** [comment]
Added to upcoming release to assess requirements

**Comment by arlina-espinoza** [comment]
_Here is an overview of what this functionality would look like. Feedback is welcome :)_

Breaking it down to stories:

#### Story 1: Add a member to a team
- As a team admin, I should be able to invite users by email address (already happens) but if they are not yet a user on the Drupal site, it should email them to invite them to create an account. 
- Users (whether part of the site or not) should need to accept an invite to join the team.

Workflow:
1. Team admin fills out form for email to join
2. System looks up if user exists in Drupal
3. If user does not exist, an email is sent to user inviting them to create account
4. If user exists, email sent with link to accept/deny invite
5. User accepts or denies invite
6. If accepted, user is added to team (calling Apigee Company API)
7. If denied, change invitation status to declined

#### Story 2: Pending invitations block for Team
- As an admin, I can view a "pending invitations" list and see invite status (invitation sent or if they declined). Block should be in the "Members" tab of the team, under the "members" section.
- As a team admin, I can click a "resend" link to resend the email invite.
- As a team admin, I can cancel the invite.

#### Story 3: Pending invitations page for user
- As a user, I have access to a "Pending Invitations" tab under my account menu.
- From that page I can view any pending invitations to team, and accept/deny.

#### Story 4: Add events
- Throw events for membership status changes: created, declined, accepted, cancelled, etc.

#### Other tasks:
Need email templates for both emails.

**Comment by arunz6161** [comment]
Next steps: is to break these is smaller chunks and prioritize them in upcoming sprints.

**Comment by mxr576** [comment]
"as an admin" I hope it means that there is going to be a team level permission which is going to control which team role(s) can access to a certain operation/UI.
These new UI-s should also respect the "administer team" site-wide permission.

**Comment by mxr576** [comment]
Plus it would be great if the implementation would trigger events when the state of a membership request is changes: created, declined, accepted, cancelled, etc and the default email notifications would subscribe to these events and downstream developers could add further event subscribers to customize the onboarding workflow. (Also, can disabel the default email notifications if they are not sufficient for the customer.)

**Comment by cnovak** [comment]
@mxr576:  for permissions, we have "Administer Teams" and "Manage Team Members" in Drupal permissions. For the Team roles, we have "Manage Team Members".  Is there any permissions you can think of that are not covered by these?

**Comment by arlina-espinoza** [comment]
> Plus it would be great if the implementation would trigger events when the state of a membership request is changes: created, declined, accepted, cancelled, etc and the default email notifications would subscribe to these events and downstream developers could add further event subscribers to customize the onboarding workflow. (Also, can disabel the default email notifications if they are not sufficient for the customer.)

Good idea! We've added a 4th story with that requirement.

**Comment by arunz6161** [comment]
Being tracked via #438 , #439, #440, #441
