### ISSUE TITLE
Monetization Team creation fails

### ISSUE THREAD

**Issue by cnovak** [apigee/apigee-edge-drupal#330]
**Describe the bug**
The system will display the message "Cannot reach management server. An administrator should check the configuration of this site." when creating a team.

**To Reproduce**
1. Enable monetization teams module
2. Go to /add-team
3. Click on "Add Team" button
4. Error screen is displayed:  "Cannot reach management server. An administrator should check the configuration of this site." and error message in logs: `Attribute does not exist Drupal\apigee_edge\Entity\Storage\EdgeEntityStorageBase->withController() (line 220 of /apigee_edge/src/Entity/Storage/EdgeEntityStorageBase.php).`

**Additional context**
This same error comes back from Edge API if you try to create a company w/out the needed monetization fields:
```
curl --location --request POST 'https://api.enterprise.apigee.com/v1/organizations/{MY_ORG}/companies' \
--header 'Content-Type: application/json' \
--data-raw '{
   "name": "test33",
    "displayName": "Test33",
    "attributes": [ ]
}'
```

**Version Info**
This can be the version you can see on admin/modules in Drupal or 
the output of this command: `composer show`.  Add Drupal core and
other version information if needed.

```drupal/apigee_m10n                       1.1.0        Apigee Edge Monetization for Drupal```

**Comment by shadcn** [comment]
@sethhoward1988 is the `ADMIN_EMAIL` required for monetized org only? Seems to be the case.
