### ISSUE TITLE
Running Tests on docker:  run-test.sh: not found

### ISSUE THREAD

**Issue by cnovak** [apigee/apigee-edge-drupal#35]
| Q                           | A
| --------------------------- | -----------------------------------------------
| Bug?                        | yes
| New Feature?                | no
| Module Version              | 80472144b38ac88a66a455394d6cebac88730619
| PHP Client version          | 2.0.0-alpha2
| Requires PHP client fix     | no

#### Summary
The CONTRIBUTING.md explains how to run tests on docker, but I am seeing an error.

#### Steps to Reproduce the behavior

```
$ docker-compose run php /opt/drupal-module/run-test.sh
WARNING: The DRUPAL_CORE variable is not set. Defaulting to a blank string.
WARNING: The DEPENDENCIES variable is not set. Defaulting to a blank string.
/usr/local/bin/docker-php-entrypoint: exec: line 9: /opt/drupal-module/run-test.sh: not found
```

**Comment by mxr576** [comment]
Added a fix for this to your open PR @cnovak.

**Comment by mxr576** [comment]
Chris' PR stuck so I cherry-picked my commit and created a new PR to make this fix available in the next alpha version.

https://github.com/apigee/apigee-edge-drupal/pull/51
