### ISSUE TITLE
Document Apigee Edge integration with Rules module

### ISSUE THREAD

**Issue by cnovak** [apigee/apigee-edge-drupal#361]
Put together information to add to documentation on Apigee Edge module Rules integration.

**Comment by shadcn** [comment]
@cnovak I think the [README](https://github.com/apigee/apigee-edge-drupal/blob/955bcf2783163b6d2f17cad531c59f6ebb3d720f/modules/apigee_edge_actions/README.md) is a good starting point. This lists all the Apigee Edge entity types events implemented by `apigee_edge_actions`. 

We can take from this and add it to the documentation page on drupal.org.

We should also link to the following:

1. [The Rules documentation](https://www.drupal.org/docs/8/modules/d8-rules-essentials)
2. [How to implement custom actions](https://www.drupal.org/docs/8/modules/d8-rules-essentials/for-developers/actions)
3. [How to implement custom condition](https://www.drupal.org/docs/8/modules/d8-rules-essentials/for-developers/conditions)

I can't think of anything else right now. We have examples, docs and links for extending `apigee_edge_actions`. I think this covers most of it.

**Comment by jbennett13** [comment]
Draft for review:  https://docs.google.com/document/d/1EYQrmwpxDsyeVoqgn6NckJpIE_Rk_H4micv5BhEm3cQ/edit?usp=sharing
