### ISSUE TITLE
Mismatched entity and/or field definitions after First name, Last name field changes

### ISSUE THREAD

**Issue by balazswmann** [apigee/apigee-edge-drupal#385]
**Describe the bug**
After an `8.x-1.5` to `8.x-1.7` update it seems everything is working fine but I noticed the following message on the status page:

> Mismatched entity and/or field definitions
The following changes were detected in the entity type and field definitions.
User
The First name field needs to be updated.
The Last name field needs to be updated.

I have tried to view and edit user profiles and looks like everything is fine but this message appears.

**Screenshots**

![entity-field-definitions](https://user-images.githubusercontent.com/1757012/77311690-e0f80680-6d00-11ea-906d-8b7d5879259b.png).

**Additional context**

There is no custom code in the project which plays with the first name and last name fields or somehow modifies them.

**Comment by shadcn** [comment]
@balazswmann I created PR #386 to fix this. Thanks for the report.

**Comment by balazswmann** [comment]
Thank you!
