### ISSUE TITLE
Programmatically load developer apps based on the drupal user Id

### ISSUE THREAD

**Issue by arunz6161** [apigee/apigee-edge-drupal#391]
From Apigee community : https://community.apigee.com/questions/80298/how-to-load-developer-apps-by-drupal-developer-id.html

Programmatically load developer apps based on the drupal user Id, is it possible with current Edge module or with current php sdk?

Their is an option to load multiple

`$apps = DeveloperApp::loadMultiple()`
And an option to load based on raw id of apigee developer

`\Drupal::entityTypeManager()->getStorage('developer_app')->loadByProperties(['developerId' => <raw-id-of-developer-on-apigee>]);`Is their any way to load via drupal user id?

**Comment by shadcn** [comment]
@heykarthikwithu You can do so by retrieving the `email` address and passing it to `->loadByDeveloper`

Example:

```php
// Find the email for the user with Drupal uid 1
$email = Drupal\user\Entity\User::load(1)->getEmail();

// Load apps for this user.
\Drupal::entityTypeManager()->getStorage('developer_app')->loadByDeveloper($email);
```

Note: `loadByDeveloper` accepts the Apigee developerId as well.

```php
\Drupal::entityTypeManager()->getStorage('developer_app')->loadByDeveloper(<raw-id-of-developer-on-apigee>);
```

**Comment by Mainak9** [comment]
How to load Developer app interface sin developer id and app name?
I am trying this but failed
 ```
\Drupal::entityTypeManager()->getStorage('developer_app')->loadByProperties([
      'developerId' => 'raw_id' ,
      'name' => 'raw_app_name',
    ]);
```

**Comment by MahmoudSayed96** [comment]
How to load developer app by developer email and application name
```php
    // Load the developer's app.
    /** @var \Drupal\apigee_edge\Entity\DeveloperAppInterface $developer_app */
    return \Drupal::service('apigee_edge.controller.developer_app_controller_factory')
      ->developerAppController($developer_email)
      ->load($app_name);
```

**Comment by kedarkhaire** [comment]
Hi @MahmoudSayed96 
You can use this API for your request - https://apidocs.apigee.com/docs/developer-apps/1/routes/organizations/%7Borg_name%7D/developers/%7Bdeveloper_email%7D/apps/%7Bapp_name%7D/get

In [apigee/apigee-client-php](https://github.com/apigee/apigee-client-php/blob/fceb7f54c17d3bc49c963762a578ec879add2e41/src/Api/Management/Controller/DeveloperAppCredentialController.php#L64) we have already used this & also for reference on Apigee module, check - [DeveloperApps.php file](https://github.com/apigee/apigee-edge-drupal/blob/3.x/src/Entity/DeveloperApp.php).

Thanks!
