### ISSUE TITLE
Allow App entities to be loaded from storage using name

### ISSUE THREAD

**Issue by shadcn** [apigee/apigee-edge-drupal#395]
App entities (`DeveloperApp` and `TeamApp`) should use `name` as the unique identifier so that you could retrieve an app from storage using `Drupal::entityTypeManager()->getStorage('developer_app')->load('NAME')`

but this does not work right now. It works only with a UUID.

I think we should fix/implement this in apigee_edge.

Some notes from https://github.com/apigee/apigee-edge-drupal/pull/360#discussion_r400026606

1. The `entity_keys` is using `appId` (which is the UUID) for the `id`. 

https://github.com/apigee/apigee-edge-drupal/blob/6afe49a39993ec46e46c1969accbb537ffd17057/src/Entity/DeveloperApp.php#L78-L80

2. So the `ParamConverter` ends up converting `name` from the route to `uuid` to load entities.

https://github.com/apigee/apigee-edge-drupal/blob/6afe49a39993ec46e46c1969accbb537ffd17057/src/ParamConverter/DeveloperAppNameConverter.php#L81-L95

**Comment by mxr576** [comment]
App name is only unique in combination with its owner (developer or team), if the owner of an app is not known from the context then there is no way to load the app by name.

**Comment by raakesh-blokhra** [comment]
Since this is not affecting the current functionality in any negative way, and no issues have been reported that point towards this issue, we are closing this issue. We can re-open if needed.
