### ISSUE TITLE
Not able to fetch more than 1000 companies from APIGEE Edge Private Cloud

### ISSUE THREAD

**Issue by aditya1316** [apigee/apigee-edge-drupal#401]
Hi there , 

I am trying to fetch all the companies from APIGEE EDGE(Private Cloud) but it is returning only first 1000 companies even though i am passing `startKey` and `count` parameter in API.

**List Companies API** https://apidocs.apigee.com/management/apis/get/organizations/%7Borg_name%7D/companies

Any help will be appreciated.

Thanks , 
Aditya

**Comment by arunz6161** [comment]
@aditya1316 This appears to be problem on Apigee Management and not related to this Drupal module. Can you correct me if i am wrong ? You can reach out to Apigee support team to get help on Management related issues.

**Comment by arunz6161** [comment]
@aditya1316 we are closing this for now, do let us know if you see see more evidence of this being an issue with apigee-edge module
