### ISSUE TITLE
License Agreement on Product Subscription

### ISSUE THREAD

**Issue by acobat** [apigee/apigee-edge-drupal#406]
**Is your feature request related to a problem? Please describe.**
Hi team,

My customer asked for next functionality: 

~ While subscribing the app to product in Drupal-8 dev-portal, customer wants the developer to agree on specific Licence Agreement for each product (usage), i.e. - once you will choose product you want to subscribe to, you have to agree to license agreement for that specific product. Currently, as we see, this is not supported. Any ideas on how to create such functionality, or someone has done this \ similar functionality? 

**Describe the solution you'd like**
Once clicking on product subscription action (on click) - dialog will be presented with generic text, unique for each product

**Comment by cnovak** [comment]
The easiest way I can think of doing this is adding a checkbox to the app form that asks user to agree to terms. You can add a field by going to Configuration > Apigee Edge > Apps > Developer App and adding the field:

<img width="1239" alt="Screen Shot 2020-05-01 at 10 53 13 AM" src="https://user-images.githubusercontent.com/613093/80830180-6347d600-8b9d-11ea-8c56-02a7128faecf.png">

You can also add your own custom validation code and code to run after the form is submitted as explained here: http://www.codeexpertz.com/blog/drupal/drupal-8-custom-form-validate-and-submit-hookformalter-example

**Comment by cnovak** [comment]
I will close this issue, hopefully this info helped you find a solution.  Feel free to comment on the ticket if anything comes up.
