### ISSUE TITLE
API Consumers (Authenticated Users) are getting incorrect Teams(Companies)

### ISSUE THREAD

**Issue by Dhaneshmonds** [apigee/apigee-edge-drupal#408]
**Incorrect Teams(List of Teams which user does not belong to) are displaying for API Consumers(Authenticated Users) on Team(Company) List** 
   
 
  | API Consumers | API Providers | Administrators
-- | -- | -- | --
Issue   occurring for | Yes | No | No
  
**To Reproduce**

To reproduce the issue, we need two users.

Let's Consider **ConsumerOne** and **ConsumerTwo** as two API Consumers(Authenticated user) in the portal.

_API Consumers have permission to create teams on the portal._

When **ConsumerOne** created a new team; the team list for the user **ConsumerOne** can see valid teams (list of the teams which belong to **ConsumerOne**). But other API Consumers are getting the same list of **ConsumerOne**. For Other API Consumers(including **ConsumerTwo**), those are invalid teams(Companies). 

**Notes:** 

1. This issue is happening only when API Consumers(Authenticated users) creating a new team.
2. When we are clearing the Drupal Portal cache the issue is disappearing.
3. Apigee Edge Team Caching set as 0/-1, still, the issue persists. 

**Expected behavior**
API Consumers(Authenticated users) should get relevant teams which he/she created or he/she belongs to.

**Version Info**
Drupal           : 8.7.12
Apigee Edge : 8.x-1.8

**Comment by mxr576** [comment]
Isn't it caused by the the "API consumer" role has "View **any** Teams" permission?  Without granting this permission I could not reproduce this issue, which means, works as designed. There is no "View own Teams" permission because the owner/author/created information is not stored on Apigee for teams/companies.

**Comment by Dhaneshmonds** [comment]
> Isn't it caused by the the "API consumer" role has "View **any** Teams" permission? Without granting this permission I could not reproduce this issue, which means, works as designed. There is no "View own Teams" permission because the owner/author/created information is not stored on Apigee for teams/companies.

Hi Dezső BICZÓ **mxr576**,
Thanks for the reply. We didn't configure "View any Teams" in the permission for "API Consumers". 
But still getting the issue. We had a discussion with apigee support team and shared the permissions as well. We received feedback like it might be a bug in apigee-edge-drupal. 

> **We found a workaround for the same by disabling the dynamic caching.  After disabled dynamic caching "API Consumers" are getting proper teams.**

**Comment by varuntit101** [comment]
Hi I also faced the same issue and found a workaround by disabling dynamic cache

**Comment by arunz6161** [comment]
Thanks @varuntit101 for sharing the workaround. @Dhaneshmonds Can you try disabling dynamic cache and let us know if that works and if it a acceptable workaround ?

**Comment by Dhaneshmonds** [comment]
@arunz6161 I have mentioned the same in my previous comment. After disabling the dynamic cache, working as expected. I believe this is a temporary fix, after disabled dynamic cache; a couple of other functionalities got affected.

**Comment by arunz6161** [comment]
thanks @Dhaneshmonds - we will prioritize this soon

**Comment by arlina-espinoza** [comment]
I've posted a PR that could fix this: #419
