### ISSUE TITLE
Change/Remove the current status ("Experimental") of the Teams feature 

### ISSUE THREAD

**Issue by hbougdal** [apigee/apigee-edge-drupal#413]
**Is your feature request related to a problem? Please describe.**
Change the status of the Teams feature to "Stable" so that customers would feel comfortable to use that feature in their production portals.

**Describe the solution you'd like**
Change the status of the Teams feature from "Experimental" to "Stable".

**Describe alternatives you've considered**
N.A

**Additional context**
You have confirmed (by email) that this change can be done, hence this request :). A customer asked for tis change.

**Comment by cnovak** [comment]
We do have one issue #408 that needs to be resolved on Teams, once it is we can complete this.

**Comment by hbougdal** [comment]
What is a "rough" timeline?

Thanks,
Hicham

**Comment by cnovak** [comment]
We are currently working on #408 , should be ready at end of sprint, which is about 2 weeks.

**Comment by hbougdal** [comment]
Great, thank you so much.

**Comment by hbougdal** [comment]
Any update?

**Comment by cnovak** [comment]
You can follow the work on #408 to see the updates on the work. A PR has been created #408 but needs to be approved.
