### ISSUE TITLE
My Apps area should not retreive the key/secret at the same time

### ISSUE THREAD

**Issue by akac** [apigee/apigee-edge-drupal#416]
## Description
As a security concern, the My Apps area should not retreive the key/secret at the same time. When the user clicks the view icon, it should do a get of the key.

## Steps to Reproduce
1. Go to My Apps
2. View source

## Actual Behavior
You can see both the key/secret combo

## Expected Behavior
No security info seen. 

## Notes
We did a penetration test and these bugs were found as medium/high for their purposes.

## Version Info
Machine name: apigee_edge
Version: 8.x-1.6

**Comment by cnovak** [comment]
Thanks for reporting @akac , I will put this into our release queue for v1.12

**Comment by mxr576** [comment]
I do not see how this could be solved, since there is no API on Apigee Edge that could return only the required data for the app listing. You can get the ids of the apps or complete app objects which includes app display names and yes, app credentials too, but credentials are not cached or displayed, so why it is a security issue?

**Comment by akac** [comment]
The issue is that plugins, web-scrapers, etc… can steal the info from HTML source code in this case. You could resolve the issue by using the same API to return the data twice - once for what you display on the web - but ignore (i.e. don’t render the keys), and then another that gets the same data, but extracts just the key.

**Comment by mxr576** [comment]
Are those secrets are available _in the HTML source of the listing page_? :thinking: I do not think so or I do not remember that... but I do remember that credentials (secrets) has to be retrieved to be able to calculate the "status" of the app.
Web scrapers can only access to this page if they can login to the site, which is already a security risk if they can do. Plugins, I guess you referred to browser plugins, what is the difference between if they cannot access to creds from the listing page's HTML but they can from the view page's HTML?

**Comment by minnur** [comment]
See https://github.com/apigee/apigee-edge-drupal/issues/415
