### ISSUE TITLE
Calling Apigee API /apiproducts resource

### ISSUE THREAD

**Issue by cnovak** [apigee/apigee-edge-drupal#423]
I want to consume the below query from the apigee Management API.

http://{$hostname}/v1/organizations/{$org_name}/apiproducts/{$api_product_name}?query=count&entity=apps

Do we have any inbuilt method in apigee-php-client?

If anyone can guide me on this, It would be appreciated.

Regards,
Dhanesh

_Originally posted by @Dhaneshmonds in https://github.com/apigee/apigee-edge-drupal/issues/87#issuecomment-639348431_

**Comment by mxr576** [comment]
This API is marked as deprecated for a long-long time ago so it is probably not a good idea using it: https://apidocs.apigee.com/management/apis/get/organizations/%7Borg_name%7D/developers/%7Bdeveloper_email_or_id%7D/apps/%7Bapp_name%7D
Probably because of the above mentioned reason, it does not seem that the PHP API client have support it. Support to this API on a project can be easily added by a developer by extending the DeveloperAppController and/or TeamAppController.

**Comment by arlina-espinoza** [comment]
As @mxr576 mentioned, the endpoint has been marked for deprecation, so it's usage is not recommended. That said, in general, here is how custom code can leverage the Drupal Apigee Edge client and connection settings to connect to the management API.
Note: this is only for those cases where endpoints have not been already provided in Drupal by either the controllers  or entity storage, nor the [apigee-client-php](https://github.com/apigee/apigee-client-php) library!

```
/** @var \Drupal\apigee_edge\SDKConnectorInterface $sdk_connector */
$sdk_connector = \Drupal::service('apigee_edge.sdk_connector');
try {
  $sdk_connector->testConnection();
  $client = $sdk_connector->getClient();
}
catch (\Exception $exception) {
  // Handle error in the connection to Apigee Edge.
}

$api_product = 'binproduct';
$query_params = [
  'query' =>'list',
  'entity' => 'apps',
];
$endpoint = $client->getUriFactory()
  ->createUri("/organizations/{$sdk_connector->getOrganization()}/apiproducts/{$api_product}")
  ->withQuery(http_build_query($query_params));
try {
  $response = $client->get($client->getEndpoint() . $endpoint);
}
catch (\Exception $exception) {
  // Handle exception.
}

$results = json_decode((string) $response->getBody());
```

**Comment by arlina-espinoza** [comment]
Closing this issue, but free to reopen if follow up is needed.
