### ISSUE TITLE
How to Enhance Add App Customization,  App Analytics form with  loading Developer Apps by Drupal Developer Id in the form , Any documentation or reference would be of great help

### ISSUE THREAD

**Issue by samhaldia** [apigee/apigee-edge-drupal#427]
**Is your feature request related to a problem? Please describe.**
Extending or Overloading Apigee_Edge Contrib Module to Include own functionality without disturbing the Upgrade process in future Ex: Adding Filter : list all apps in App Analytics

**Describe the solution you'd like**
A documentation to brief usage or extending the existing functionalities like: Extend Add App form to include Custom fields programatically and make those fields value available while editing app.
 
Extending App Analytics form to Include Custom Fieelds like: App List Filter

Migrate Smartdocs form Old Site to be included as Apigee Docs Entity Type.

Extending Apigee Docs to change its content layout and content compared to old (samrtdocs.hbr template file)

**Describe alternatives you've considered**
I have tried to list  apps Filter field  by loading apps by loadByDeveloper in App Analytics form. But unable to put the selected app object reference to fetch analytics data.

A brief docs or snippets to extend these would be of great help.

**Comment by cnovak** [comment]
@samhaldia can you fill out more details in the body of this issue on exactly what you are trying to do? Hard to figure out with just one sentence in the title.  Thanks

**Comment by arlina-espinoza** [comment]
Thanks for the context @samhaldia . There are several items in this issue:

> A documentation to brief usage or extending the existing functionalities like: Extend Add App form to include Custom fields programatically and make those fields value available while editing app.

You can find documentation on how to add custom fields to the app form here: https://www.drupal.org/docs/8/modules/apigee-edge/configure-app-registration#configuring-the-app-registration-form

> Extending App Analytics form to Include Custom Fieelds like: App List Filter

This would likely involve extending the `Drupal\apigee_edge\Form\DeveloperAppAnalyticsForm`. Could you provide more details?

> Migrate Smartdocs form Old Site to be included as Apigee Docs Entity Type.

It is not in the current roadmap to migrate old smartodcs. There is a new Drupal 8/9 module that can be used for the same purposes: [Apigee API Catalog](https://www.drupal.org/project/apigee_api_catalog).

> Extending Apigee Docs to change its content layout and content compared to old (samrtdocs.hbr template file)

samrtdocs.hbr isn't supported in the new apigee_api_catalog module. Please refer to this page to customize some aspects of the API Docs: https://www.drupal.org/docs/8/modules/apigee-api-catalog/customize-your-api-catalog
We also have an open issue about having Smartdocs follow the color schema of the Kickstart theme (https://github.com/apigee/apigee-api-catalog-drupal/issues/64).

**Comment by samhaldia** [comment]
Thank you @arlina-espinoza  for response and reference provided, i had gone through earlier also for making cutomizations from Frontend.  Could you please provide few docs or reference in extending such features mentioned below in italic.

> A documentation to brief usage or extending the existing functionalities like: Extend Add App form to include Custom fields programatically and make those fields value available while editing app.

You can find documentation on how to add custom fields to the app form here: https://www.drupal.org/docs/8/modules/apigee-edge/configure-app-registration#configuring-the-app-registration-form

*Extending app registration form to include fields using custom modules, reference docs  or example modules*

> Extending App Analytics form to Include Custom Fieelds like: App List Filter

This would likely involve extending the Drupal\apigee_edge\Form\DeveloperAppAnalyticsForm. Could you provide more details?

*App Analytics form to include another filter (Currently its Analytics metrics only corresponding to the app selected) to list all apps created and approved by a developer instead going back to select another app to see analytics data*

> Migrate Smartdocs form Old Site to be included as Apigee Docs Entity Type.

It is not in the current roadmap to migrate old smartodcs. There is a new Drupal 8/9 module that can be used for the same purposes: Apigee API Catalog.

*On migrating Old Smartdocs in Drupal 7  to Drupal 8 keeps it as a page node only. How is it possible to import as API Catalog Docs or convert to API docs either pre migration or post migration.*

> Extending Apigee Docs to change its content layout and content compared to old (samrtdocs.hbr template file)

samrtdocs.hbr isn't supported in the new apigee_api_catalog module. Please refer to this page to customize some aspects of the API Docs: https://www.drupal.org/docs/8/modules/apigee-api-catalog/customize-your-api-catalog
We also have an open issue about having Smartdocs follow the color schema of the Kickstart theme (apigee/apigee-api-catalog-drupal#64).

*How is it possible to customize the Content Rendering and Display of Components like "Overview" or "API Reference" Section in Left Portlet of API entity. Is it possible to customize or control content rendering API docs (How we can change like it used to be smartdocs.hbr template file in Drupal 7).*

*The ref link says API docs gets rendered using Angular App, how can we customize it any reference or Example modules to do so*

*Is there ways to extend these using custom modules to bring in own feature*

**Comment by mxr576** [comment]
Related #87

**Comment by cnovak** [comment]
For the SmartDocs questions:
> How is it possible to customize the Content Rendering and Display of Components like "Overview" or "API Reference" Section in Left Portlet of API entity. Is it possible to customize or control content rendering API docs (How we can change like it used to be smartdocs.hbr template file in Drupal 7).
>
> The ref link says API docs gets rendered using Angular App, how can we customize it any reference or Example modules to do so

Unfortunately at this point the only way you could do any changes to any part of SmartDocs is by targeting it with JS or CSS. There isn't a template mechanism for either the left side panel or the docs itself. You can always use a Drupal basic page to display your API Docs and have full control over the template, but you would then need to start from scratch and would not have any of the "Try it now" functionality.

**Comment by arlina-espinoza** [comment]
> App Analytics form to include another filter (Currently its Analytics metrics only corresponding to the app selected) to list all apps created and approved by a developer instead going back to select another app to see analytics data.

A way to do it is to programmatically create a new route and have it handled by a class that extends `Drupal\apigee_edge\Form\DeveloperAppAnalyticsFormForDeveloper`. That class assumes the app name is in the URL path, so you'd need to override the methods `submitForm()` and `buildForm()` to fit your use case. For `buildForm()`, the original method body can be copied and modified for easier development, as you'd need to add a dropdown field to list the developer apps, which can be retrieved by using the `developer_app` storage, something like this:

```
/** @var \Drupal\user\Entity\User $account The user. */
/** @var \Drupal\apigee_edge\Entity\Storage\DeveloperAppStorageInterface $developer_app_storage */
$developer_app_storage = \Drupal::entityTypeManager()->getStorage('developer_app');
$apps = $developer_app_storage->loadByDeveloper($account->getEmail());

$active_apps = [];
/** @var \Drupal\apigee_edge\Entity\DeveloperApp $app */
foreach ($apps as $app) {
  if ($app->getStatus() == AppInterface::STATUS_APPROVED) {
    $active_apps[$app->getName()] = $app->getDisplayName();
  }
}
```

Hopefully this gives you an idea of how it can be done.

---

> On migrating Old Smartdocs in Drupal 7 to Drupal 8 keeps it as a page node only. How is it possible to import as API Catalog Docs or convert to API docs either pre migration or post migration.

There isn't a preconfigured migration path. If you have few API Docs, I'd suggest manually recreating the API Doc nodes from the information you had on D7. If there are a large amount of docs you can look into using Drupal's Migrate API. Using it you can migrate Drupal 7 entities into Drupal 8 entities (for apigee_api_catalog 2.x API Docs are nodes, so there is a lot of documentation on how to migrate into nodes). Core docs are [here](https://www.drupal.org/docs/8/api/migrate-api/migrate-api-overview), but there are many blog posts as well that summarize the process.

**Comment by arlina-espinoza** [comment]
Closing this issue, feel free to reopen @samhaldia if you have further questions.

**Comment by samhaldia** [comment]
Thank You @arlina-espinoza The example code snippet is really very helpful, It would be really very helpful to know, as what routes being currently used for App Analytics Form for re routing the Analytics form to be overridden as i am unable to find any services or routing entry for App Analytics form

**Comment by arlina-espinoza** [comment]
@samhaldia The route itself is registered by the route provider class [`DeveloperAppRouteProvider`](https://github.com/apigee/apigee-edge-drupal/blob/8.x-1.x/src/Entity/DeveloperAppRouteProvider.php), and it uses the link templates defined in the [`DeveloperApp`](https://github.com/apigee/apigee-edge-drupal/blob/8.x-1.x/src/Entity/DeveloperApp.php#L65-L79) entity.
