### ISSUE TITLE
API Key Creation/Rotation within one App 

### ISSUE THREAD

**Issue by mikesson** [apigee/apigee-edge-drupal#432]
Similarly to what has been implemented for Drupal 7 here: https://github.com/apigeecs/apigee_apikey_regeneration, it would be valuable to have the ability to manage multiple API keys within one app. I have seen in many cases that the "App" is being renamed to "Keys" straight away due to the missing capability, so it does not confuse API consumers.

It is important for enterprises as keys need to be rotated (esp. for security reasons), and would be less of a disruption when this can be done within an existing app (with existing configuration tying it to a specific API Product) as opposed to creating a new app from scratch.

**Comment by arunz6161** [comment]
Next Steps:

Replicate the behavior noticed in integrated portals where there is an option to add new keys and delete old ones.
Explore if it is a possibility to provide expiration date during key creation.


![Screen Shot 2020-07-07 at 9 37 38 AM](https://user-images.githubusercontent.com/4381612/86813979-aad35e00-c035-11ea-95b1-bb86a7886035.png)

**Comment by mxr576** [comment]
https://github.com/apigee/apigee-edge-drupal/pull/446#issuecomment-662287598
