### ISSUE TITLE
#3 Pending invitations page for user ( Team invitation for external members)

### ISSUE THREAD

**Issue by arunz6161** [apigee/apigee-edge-drupal#440]
Breaking down #329 in to smaller stories

- As a user, I have access to a "Pending Invitations" tab under my account menu.
- From that page I can view any pending invitations to team, and accept/deny.
-

**Comment by jannakha** [comment]
Users can click on "Accept" on expired invitations - creating a bug for it.
https://github.com/apigee/apigee-edge-drupal/issues/498
