### ISSUE TITLE
Filtering of Apps on the Apps Page based on Custom Attribute

### ISSUE THREAD

**Issue by pandatrooper** [apigee/apigee-edge-drupal#442]
Our team was looking forward towards a more micro level control on the filtering of apps on the App Page.

We require to restrict the Apps being displayed on the Apps page of Developer Portal based on the Custom Attributes defined either in the Edge Management UI or based on the ones created during app creation from Developer Portal. To give a background we have two Developer Portal Environments - One for Internal Users and other for External. However the catch here is both of the Developer Portals are pointing to the same organization on Edge. Though rare, but if certain individuals have roles and access for both the portals, the below use case comes into picture.Say if an  portal 1 user A, accesses portal 2, A has the apps that A had subscribed to, available on portal 2 as well [ due to common organization and email-id on Edge ] .

Hence, we were looking for granular level access to each app, so that we can regulate the display of apps for those certain individuals on the respective portals.

Currently, as a last resort, we are planning to make some custom code configurations in the AppListBuilder PHP file within Edge Module by restricting the display of apps with certain custom attribute based on internal or external environment using the old school if else statements. But that would have its own repercussions and risks, as that would involve tweaking core bare-metal modules that should be best left untouched. Also, we thought custom JavaScript, however JavaScript is not going to prevent the Restricted app details coming to the client side and hence we abandoned it.

**Comment by arunz6161** [comment]
Todo: Answer and capture in developer guide : https://www.drupal.org/docs/8/modules/apigee-edge/apigee-edge-developer-guide

**Comment by arlina-espinoza** [comment]
Hi @pandatrooper ,

The Apigee Management API does not provide an endpoint to filter out apps based on attributes (see https://apidocs.apigee.com/management/apis/get/organizations/%7Borg_name%7D/developers/%7Bdeveloper_email_or_id%7D/apps), so the filtering has to be done _after_ the apps listing has been retrieved. I provide here a summary and example of how this can be done.

You will need a custom module (assume the module machine name is `mymodule`), with the following structure:
```
mymodule
 ⊢ mymodule.info (contains the usual module declarations)
 ⊢ mymodule.module
 ⊢ src
     ⊢ Entity
         ⊢ Storage
             ⊢ DeveloperAppStorage.php
```

In `mymodule.module`, we are going to override the storage handler for the `developer_app` entity type:
```
<?php

use Drupal\mymodule\Entity\Storage\DeveloperAppStorage;

/**
 * Implements hook_entity_type_alter().
 */
function mymodule_entity_type_alter(array &$entity_types) {

  /** @var \Drupal\Core\Entity\EntityTypeInterface[] $entity_types */
  if (isset($entity_types['developer_app'])) {
    // Override the storage class.
    $entity_types['developer_app']->setStorageClass(DeveloperAppStorage::class);
  }
}

```

In `DeveloperAppStorage.php`, we will override the `loadMultiple()` method (used internally to load single or multiple apps) to apply the attribute filtering (in this example, apps belonging Portal 1 have an attribute `portal_1 == 1`, code example can be modified to match your custom attribute): 
```
<?php

namespace Drupal\mymodule\Entity\Storage;

use Drupal\apigee_edge\Entity\DeveloperAppInterface;
use Drupal\apigee_edge\Entity\Storage\DeveloperAppStorage as EdgeDeveloperAppStorage;

/**
 * Overriden entity storage class for Developer app entities.
 */
class DeveloperAppStorage extends EdgeDeveloperAppStorage {

  /**
   * {@inheritdoc}
   */
  public function loadMultiple(array $ids = NULL) {
    $entities = parent::loadMultiple($ids);

    return array_filter($entities, function (DeveloperAppInterface $app) {
      return ($app->hasAttribute('portal_1') && ($app->getAttributeValue('portal_1') == 1));
    });
  }

}

```

You might also want to extend the `save()` method to ensure apps created in the portal have the attribute set to `portal_1 == 1`.

**Comment by pandatrooper** [comment]
Hi @arlina-espinoza 

Thanks a lot for the response. My hunt for this functionality finally comes to an end. It works like a charm ! We already assign the `portal_1` with a default Attribute Value in the Add Trusted app form hence `save() ` was not necessary for us.

Really appreciate your time and efforts. Please feel free to close it, if your team is not planning to pursue this enhancement further.

**Comment by kscheirer** [comment]
@jbennett13 This is great example code, probably worth adding to docs as a recipe or howto somewhere.

**Comment by arlina-espinoza** [comment]
Thanks, we have added it to the Apigee Edge Developer Guide here:
https://www.drupal.org/docs/contributed-modules/apigee-edge/apigee-edge-developer-guide#s-filter-apps-using-custom-attributes
