### ISSUE TITLE
Delete requests to Edge can leave an inconsistent state

### ISSUE THREAD

**Issue by tfroseman** [apigee/apigee-edge-drupal#454]
## Description
If a delete fails at Edge this can leave Drupal + Edge in an inconsistent state with no direct path to recovery. 

## Steps to Reproduce
1. Use the edge module to delete an object
2. Request fails at edge due to unstated error
3. Resource is deleted in Drupal but still exists in Edge
4. Attempt to create resource in Drupal with same key or unique identifier, fails due to existing object. 

## Actual Behavior
Drupal reports that object is removed but is still present in Edge

## Expected Behavior
If a destructive request fails at Edge, the same action in Drupal should not be executed.

**Comment by arlina-espinoza** [comment]
@tfroseman Almost all of the Apigee data is fetched remotely and only saved temporarily on cache (they are not saved to Drupal's database), so clearing Drupal cache should solve any issues. You can also adjust the cache-expiration time on each entity on the module configuration settings.

The only place where I can see this being an issue would be when deleting users, as a Drupal user is tied to an Apigee developer, and deleting a Drupal user but the developer delete request failing would in fact create an inconsistent state. This can be solved by using the developer sync at `/admin/config/apigee-edge/developer-settings/sync`. 

Let us know if you find any other scenario where this could happen.

**Comment by cnovak** [comment]
I will close this issue, but let us know if you have any scenarios that you can come up with and what we can do to mitigate this. I do agree that there could be inconsistencies for users due to a failed transaction, but I am not sure what we can do to handle this since we don't have a way to do ACID transactions against the API.
