### ISSUE TITLE
Apigee Edge module 8.x-1.12 disabled auto complete feature on the "add team member"

### ISSUE THREAD

**Issue by kthotti** [apigee/apigee-edge-drupal#458]
**Is your feature request related to a problem? Please describe.**
The new version, Apigee Edge module 8.x-1.12, replaced the email autocomplete field on the "add team member" form with a text field that accepts comma separated emails, to avoid displaying email addresses of users of the system. The autocomplete feature was very useful for the team owner as it is difficult to have the email addresses handy

**Describe the solution you'd like**
Allow for autocomplete for users who have the same email domain as a team owner. Autocomplete for your own domain, the admin or team owner should be able to type or paste the emails of other domains as well without autocomplete

**Comment by cnovak** [comment]
We are concerned that this could still leak information, for example if you are using the `gmail.com` domain.  Maybe a better feature for a separate module?

**Comment by cnovak** [comment]
I am going to close this issue since we are still concerned about data privacy.
