### ISSUE TITLE
Regenerating a customer secret on an existing credential

### ISSUE THREAD

**Issue by cnovak** [apigee/apigee-edge-drupal#459]
What about regenerating a customer secret on an existing credential?

_Originally posted by @mxr576 in https://github.com/apigee/apigee-edge-drupal/pull/446#issuecomment-662287598_

**Comment by arlina-espinoza** [comment]
I'm not aware that the API allows regenerating secrets on a set of credentials: https://apidocs.apigee.com/api/developer-app-keys
@cnovak Could you confirm or point me in the right direction?

**Comment by arunz6161** [comment]
Regenerating just the secret it not an option provided by Apigee MGMT. Alternative revoke credentials and add new ones.
