### ISSUE TITLE
Problem integrating Stripe Commerce

### ISSUE THREAD

**Issue by mnalpas** [apigee/apigee-edge-drupal#461]
## Description
I try to implement Stripe Commerce on Apigee on Drupal 8. Whenever I try to add some credit to my account I get the error "We have accountered an unexpected error while analyzing your payment method. Please try later"

## Steps to Reproduce
1. Go to Pricing & Plans
2. Click on a Product, then purchase it.
3. Funds are insufficient so click on Add credit
4. Then add the needed funds
5. Continue
6. Purchase

## Actual Behavior
I get the error : "We have accountered an unexpected error while analyzing your payment method. Please try later" and no fund is added.
I get the following error on the portal reports : You cannot create a charge with a PaymentMethod. Use the Payment Intents API instead.

And the following errors on the error.log of the nginx : 
[error] 12427#0: *1371 FastCGI sent in stderr: "PHP message: Error: Call to undefined method Drupal\apigee_m10n\Entity\RatePlan::hasTranslation() in /opt/portal/web/core/modules/quickedit/src/QuickEditController.php on line 150 #0 [internal function]: Drupal\quickedit\QuickEditController->metadata(Object(Symfony\Component\HttpFoundation\Request))
apigee/apigee-m10n-drupal#1 /opt/portal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array)
apigee/apigee-m10n-drupal#2 /opt/portal/web/core/lib/Drupal/Core/Render/Renderer.php(573): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
apigee/apigee-m10n-drupal#3 /opt/portal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure))
apigee/apigee-m10n-drupal#4 /opt/portal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscr" while reading response header from upstream, client: 10.23.77.31, server: 10.23.75.222, request: "POST /quickedit/metadata HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm/php-fpm.sock:", host: "10.23.75.222", referrer: "http://10.23.75.222/user/1/plans"

## Expected Behavior
Money should be added to my account

## Version Info
Drupal core : 8.9.0
Apigee Edge 8.x-1.10
Drupal Commerce 8.x-2.19
Commerce Stripe : I have tried 3 versions  : 8.x-1.0-rc2, 8.x-1.0-rc3 and 8.x-1.0-rc4

**Comment by arlina-espinoza** [comment]
Moving to `apigee_edge` issue queue, as the underlying issue is an incompatibility between Edge entities and the quick edit module.

**Comment by arlina-espinoza** [comment]
@mnalpas We have a fix for this on the `apigee_edge` module, should be available on the next release 8.x-1.13.
