### ISSUE TITLE
Secret is broken, requires js cleanup and implementation...

### ISSUE THREAD

**Issue by VladimirAus** [apigee/apigee-edge-drupal#467]
## Description

Secret is broken, clicking hide and show would actually break the functionality. 

## Steps to Reproduce

Steps to reproduce the behaviour:
1. Enable module by itself without https://github.com/apigee/apigee-devportal-kickstart-drupal
2. Go to app
3. Secret functionality is broken and occasionally doesn't work when trying to show/hide again.

## Actual Behaviour

Functionally was partially fixed in https://github.com/apigee/apigee-devportal-kickstart-drupal

## Expected Behaviour

Secret should be hidden on hide and displayed on display.

## Post fix

Address this issue in kickstart https://github.com/apigee/apigee-devportal-kickstart-drupal/issues/411

**Comment by purushotamrai** [comment]
Quick Updates: I was looking into this issue and realized that we are doing wrong in **apigee_edge_entity_view** as:
`        
$build['credentials'][] = [
          '#type' => 'app_credential',
          '#credential' => $credential,
          '#app_name' => $entity->getName(),
          '#team_app_name' => isset($team_app_name) ? $team_app_name : '',
          '#attributes' => [
            'class' => 'items--inline',
          ],
        ] + $defaults;
`

the variables like app_name, team_app_name never reaches **template_preprocess_app_credential** and hence we can see **undefined index '#app_name'** in the dblogs. So, we will have to find a way to pass the app name correctly to template_preprocess_app_credential.

_As a solution, in my project I'm using apigee_entity twig to pass/print data-app attribute and use the parent div in JS to call secretcode callable._

This information might help others, hence I'm posting this here.

**Comment by arlina-espinoza** [comment]
There is a PR pretty close to getting merged with the resolution to this issue: https://github.com/apigee/apigee-edge-drupal/pull/496

**Comment by arlina-espinoza** [comment]
Latest apigee_edge release includes the fix of PR #496: 
https://www.drupal.org/project/apigee_edge/releases/8.x-1.17
