### ISSUE TITLE
Move app actions from kickstart to edge modules

### ISSUE THREAD

**Issue by VladimirAus** [apigee/apigee-edge-drupal#469]
## Description

App actions were introduced in kickstart, so there is no way to access edit app functionality within the module. 

## Steps to Reproduce

Steps to reproduce the behaviour:
1. Enable module by itself without https://github.com/apigee/apigee-devportal-kickstart-drupal
2. Go to apps on user profile
3. Try to edit the app

## Actual Behaviour

Functionally was partially fixed in https://github.com/apigee/apigee-devportal-kickstart-drupal

## Expected Behaviour

There should be app actions.

## Post fix

Address this issue in kickstart https://github.com/apigee/apigee-devportal-kickstart-drupal/issues/412

**Comment by arlina-espinoza** [comment]
Hi @VladimirAus , I'm unclear of what you mean that there is no way to access the edit app functionality without Kickstart. If you use this module without Kickstart, the apps listing page for a given user looks like (the links to app entity operations appear according to the user permissions):
![image](https://user-images.githubusercontent.com/4062676/92566393-0508bf00-f231-11ea-8923-06247b3c4b02.png)

And in the app page itself, there are the tabs to edit or perform other operations on the app:
![image](https://user-images.githubusercontent.com/4062676/92566538-3ed9c580-f231-11ea-8e55-0d514dccc8b1.png)

Could you help me identify where you say these links are missing?

**Comment by shadcn** [comment]
@VladimirAus did you figure this out? The app actions are provided by the EntityListBuilder and `AppListBuilder`.

https://github.com/apigee/apigee-edge-drupal/blob/bf99f73629850b932a681dcd202c43e7cb515e5c/src/Entity/ListBuilder/AppListBuilder.php#L119-L130

**Comment by VladimirAus** [comment]
@arshad - yep. I figured it out, however I need to add it to module first before removing it form profile so waiting on @arlina-espinoza to finish review of https://github.com/apigee/apigee-edge-drupal/pull/470/files for the following task: 
* https://github.com/apigee/apigee-edge-drupal/issues/469

**Comment by arlina-espinoza** [comment]
Hi @VladimirAus ,

I'm still not seeing the issue you are describing, as there is a way to edit and get to the app actions just using this module (without using Kickstart), see https://github.com/apigee/apigee-edge-drupal/issues/469#issuecomment-689358044. Could you elaborate what you are seeing?

**Comment by arunz6161** [comment]
@VladimirAus We are closing this out since we haven't heard back . Please reopen when you are able to provide additional information.
