### ISSUE TITLE
Not able to view all Apps created by all developers which are available in apigee edge as administrator

### ISSUE THREAD

**Issue by Ramadevi-cts** [apigee/apigee-edge-drupal#471]

**Comment by arunz6161** [comment]
Hi @Ramadevi-cts - Portals does not list all apps belonging to an Org. Could you please explain the need to display this information in portals when it is already available in edge ?

Please provide all the information suggested by the template. This will help us understand your requirement better.

**Comment by Ramadevi-cts** [comment]
Hi @arunz6161 - As administrator access to developer portal (Drupal 8), I have given access to **View any app/ Update any app/ Delete any app**. But when I am login into portal I can access apps which are created by me as developer.
As per my understand, with provided access permissions Admins can view all apps in one org. 

Please clarify me on this permissions *View any app/ Update any app/ Delete any app**. 
If I remember correctly, we were able to access all apps in previous versions of dev portals (eg: drupal 7)

**Comment by mxr576** [comment]
There is a secret `/developer-apps` and `/team-apps` path. Those have been added as a generic listing page for _all_ developer apps and team apps. (Just like `/admin/content` for nodes.) It has not been finished, pagination is missing from it for example, this is the reason why it is not available in the menu system.

**Comment by mxr576** [comment]
@arunz6161 One simple use case is when ppl are using the devportal as a management UI to solve things that the Apigee Edge MGMT UI API/UI cannot solve at this moment, like:
* email notifications
* calling 3rd party APIs before/after an app change
* app dashboard - managing apps and keys in one centralized place and combining one- or more features from the previous points
* Providing access to internal ppl/groups (ex.: support team) to limit app related operations without giving access to Apigee Edge MGMT UI for security reasons
* etc.

**Comment by arlina-espinoza** [comment]
> Hi @arunz6161 - As administrator access to developer portal (Drupal 8), I have given access to **View any app/ Update any app/ Delete any app**. But when I am login into portal I can access apps which are created by me as developer.
> As per my understand, with provided access permissions Admins can view all apps in one org.
> 
> Please clarify me on this permissions _View any app/ Update any app/ Delete any app_*.
> If I remember correctly, we were able to access all apps in previous versions of dev portals (eg: drupal 7)

The permission does allow visiting another user apps page (eg: user/15/apps) and administering them.

**Comment by arlina-espinoza** [comment]
> There is a secret `/developer-apps` and `/team-apps` path. Those have been added as a generic listing page for _all_ developer apps and team apps. (Just like `/admin/content` for nodes.) It has not been finished, pagination is missing from it for example, this is the reason why it is not available in the menu system.

@cnovak / @arunz6161 Should these pages be documented and added to a menu? As @mxr576 mentioned, they still need some work.

**Comment by cnovak** [comment]
There is a module created by Stratus Meridian that may have the functionality you need: https://www.drupal.org/project/sm_appdashboard_apigee

This functionality was never in our Drupal 7 offering, but was created as a separate module by @giteshk .  Stratus Meridian decided to port this over to Drupal 8. I will close this, but reopen if you see any remaining gaps in functionality.
