### ISSUE TITLE
Support environment selection on App analytics page

### ISSUE THREAD

**Issue by balazswmann** [apigee/apigee-edge-drupal#472]
**Is your feature request related to a problem? Please describe.**

Currently, the user specific App analytics page (**/user/[UID]/apps/[APP ID]/analytics**) fetches the analytics data from one environment which can be changed only by admins through the **/admin/config/apigee-edge/app-settings/general/analytics** page.

It would be nice if end users would be also able to switch among environments on the App analytics page. Otherwise, they only see analytics data for one pre-defined environment.

**Describe the solution you'd like**

A new filter option could be added to the App analytics page which would list the available environments.

**Describe alternatives you've considered**

Perhaps the analytics related admin page (**/admin/config/apigee-edge/app-settings/general/analytics**) could be also modified or extended with additional settings to restrict or control which environments can be selected on the App analytics page.

**Comment by arunz6161** [comment]
Todo: Add a proposal to explain the new behavior.

**Comment by arlina-espinoza** [comment]
Here's how we see this feature (discussed with @arunz6161 and @cnovak).

- App analytics configuration page at **/admin/config/apigee-edge/app-settings/general/analytics** would allow choosing which environments would be made available to end users on the app analytics form, and which environment should be default. Example:
![image](https://user-images.githubusercontent.com/4062676/96034898-17b97980-0e17-11eb-96d1-cb662dc559ec.png)

- App analytics form at **/user/{{uid}}/apps/{{app}}/analytics** would show the environment selector as a dropdown, showing only the environments that the admin configured in the above admin form. The environment selector _would only be displayed_ if there are 2 or more environments to choose from.

- Sites updating the module would get their previously selected analytics environment as the only exposed environment and set as default, so the update would not change how their site works. They will have the option to reconfigure the settings as needed.

This is open for feedback @balazswmann.

**Comment by balazswmann** [comment]
@arlina-espinoza @arunz6161 @cnovak Thank you for the feedback. The proposal looks good to me, it would be a nice improvement.
