### ISSUE TITLE
Team: Current admin is automatically added to the team

### ISSUE THREAD

**Issue by VladimirAus** [apigee/apigee-edge-drupal#484]
## Steps

* Create new team
* Result: creator added as team admin

## Proposal

* create flag to add current user as admin
* flag should be unchecked by default

**Comment by arunz6161** [comment]
@VladimirAus Could you explain your use case in more detail ? You can always remove yourself from a team. Adding an option to let users create an orphaned team can lead to issues.

**Comment by cnovak** [comment]
@VladimirAus I will close this for now, but feel free to add more details on your use case if you are still interested in this enhancement. The reason we are asking is that if the default is to not add the admin to the team, we may get teams that have no administators.
