### ISSUE TITLE
A11Y: API Edge: invalid aria attribute

### ISSUE THREAD

**Issue by jannakha** [apigee/apigee-edge-drupal#487]
## Description
WCAG 4.1.1, WCAG 4.1.2

Path: --wrapper
Fix the following:
-ARIA attribute is not allowed: aria-required="true"

When creating a new App, API products checkboxes' aria attribute is invalid

**Comment by arlina-espinoza** [comment]
@jannakha There is a fix provided in https://github.com/apigee/apigee-edge-drupal/pull/504 that should go out in the next release.
