### ISSUE TITLE
App listing and team apps listing load time is high

### ISSUE THREAD

**Issue by gangwalanil** [apigee/apigee-edge-drupal#489]
## Description
I am using Apigee edge module and using apps and team apps features.

- When i create multiple user apps and go to the listing page, its take very high time to load.
- Similarly i create multiple team apps   go to the listing page, its take very high time to load.

## Actual Behavior
As the data on both of the pages are coming from Apigee, its take very high time to load.

## Expected Behavior
Both of the pages should load faster.

**Comment by arunz6161** [comment]
@gangwalanil as you have already mentioned that the response for apps and team apps is coming from Apigee edge, we can enable apigee_edge_debug module and log the corresponding time for each of these Apigee MGMT Api requests. Here is the documentation link : https://www.drupal.org/docs/8/modules/apigee-edge/monitor-apigee-edge-debug-logs#enable

Could you also let us know the version of Apigee edge module in use and at what number of apps & teams apps did you start noticing slowness ? This will help us reproduce the issue if we can rule out the Apigee MGMT Api requests response times.

**Comment by arunz6161** [comment]
Reopen if this is still an issue.
