### ISSUE TITLE
Application API warnings are not present in apigee edge module

### ISSUE THREAD

**Issue by VladimirAus** [apigee/apigee-edge-drupal#492]
## Description

Warnings only present when profile is present making module is not fully functional.

<img width="1036" alt="Screen Shot 2020-09-29 at 6 30 15 pm" src="https://user-images.githubusercontent.com/1356166/94533077-0d797600-0282-11eb-912f-56684dbe15c7.png">

## Steps to Reproduce

1. Invalidate one of the APIs used by the application.
2. Warning only visible when installation profile is enable

## Proposal

Move the code from kickstart into the apigee edge module:

* https://github.com/apigee/apigee-devportal-kickstart-drupal/blob/f1672a9822c6294f02cd87a4974aaa322e582fec/modules/custom/apigee_kickstart_enhancement/apigee_kickstart_enhancement.module#L110-L139
* https://github.com/apigee/apigee-devportal-kickstart-drupal/blob/f1672a9822c6294f02cd87a4974aaa322e582fec/modules/custom/apigee_kickstart_enhancement/apigee_kickstart_enhancement.module#L258-L313

**Comment by shadcn** [comment]
@VladimirAus Can you attach a screenshot of the Apps page in a non-kickstart setup please? I'm trying to reproduce this and I *can* see the warnings for expired credentials.

![Apps___Apigee](https://user-images.githubusercontent.com/124599/94592535-170ed800-029a-11eb-8f27-443ed921bdfa.jpg)

Thank you

**Comment by shadcn** [comment]
See also the related comment here: https://github.com/apigee/apigee-devportal-kickstart-drupal/issues/431#issuecomment-700844379

**Comment by arunz6161** [comment]
Todo: Logic to be changed to show a warning if there are no valid keys ( invalid keys are expired or revoked)

**Comment by jannakha** [comment]
here's a screenshot of kickstart:
![image](https://user-images.githubusercontent.com/1356783/94635323-bcb35d00-0315-11eb-84aa-9f3121db9dfd.png)

here's a screenshot of non-kickstart installation:
![image](https://user-images.githubusercontent.com/1356783/94635493-1b78d680-0316-11eb-9a50-21638e8f950a.png)

non-kickstart version does show api is pending/expired but it doesn't show a warning with a reason for it.
This functionality is should be in the core apigee_edge module, not just in a profile.

Cheers,
J

**Comment by shadcn** [comment]
Thanks for the screenshot @jannakha 

Looks like we need to consolidate the app warnings. Here's the current list of warnings (see screenshot):

1. A warning is displayed if an app has **at least one expired key**.
2. A warning is displayed if an app has **an approved key with at least one expired product**.

3. We are going to add a third case where an app has **no approved keys. i.e all keys are revoked**.
4. Note that right now, **it is possible for an app to have revoked keys (no warnings are shown)**.

![Apps___Apigee](https://user-images.githubusercontent.com/124599/94655993-83c4b980-0310-11eb-8570-384e5df86346.jpg)

@VladimirAus @jannakha is this what you were going for? Any other cases to consider?

**Comment by jannakha** [comment]
yes, if all keys are **revoked** or **expired** a warning can be displayed as well.
NOTE: it's possible to revoke all keys, but not via Drupal interface (only via apigee edge interface)
