### ISSUE TITLE
Add ability to limit an app to one API Product in UI

### ISSUE THREAD

**Issue by cnovak** [apigee/apigee-edge-drupal#494]
There is an ability to limit an app to one API Product through configuration, but it is not displayed in the UI: https://www.drupal.org/docs/8/modules/apigee-edge/configure-app-registration#allowing-app-developers-to-select-a-single-API-product-only

This task is to add this to the UI so that users understand it is available.

**Comment by earth2marsh** [comment]
From discussion, it sounds like this exists in D8 modules because it existed in D7 modules. Until we have a clearly defined use case, ideally with some user demand, I'm in favor of removing it in favor of custom development.

**Comment by cnovak** [comment]
Unfortunately, we don't have any info on who is using this. Surfacing the feature with a checkbox will be very easy to do, and will have less impact on anyone using this feature.
