### ISSUE TITLE
Document team invitation feature

### ISSUE THREAD

**Issue by arlina-espinoza** [apigee/apigee-edge-drupal#497]
Add/update docs to reflect new team invitation functionality added in https://github.com/apigee/apigee-edge-drupal/pull/474.

- https://www.drupal.org/docs/8/modules/apigee-edge/configure-team-management

**Comment by shadcn** [comment]
Checklist:

- [x] Setup cron for handling expired invitations
- [x] Permissions

**Comment by jbennett13** [comment]
@arlina-espinoza :  Let me know if I can help with this.

**Comment by shadcn** [comment]
# Team invitation

Apigee Edge 8.x-1.16 ships with team invitation feature which lets you invite new team members using their email address.

## Installation

If you are updating from a previous version of Apigee Edge, make sure you run the database updates (`drush updb`).

## Configuration

To configure team invitation:

1. Select **Configuration > Apigee Edge > Teams**.
2. Click the **Team invitation** tab.
3. Configure the **expiry days** and **email templates**.
4. Click **Save configuration**.

![team-invitation-01](https://user-images.githubusercontent.com/124599/96963848-7323ef80-151a-11eb-938b-56292f10d0e5.jpg)

Notes:

- There are two email templates available: one for existing users and another one for new users.
- To handle team invitation expiration, you need a configured cron. See https://www.drupal.org/docs/user_guide/en/security-cron.html

## Permissions

There are two types of permissions you need to set for team invitations: **global** and **team** permissions.

### Global permission

To configure global permissions, select **People > Permissions**.

Here’s a list of the minimum permissions required:

**Authenticated users**:

1. Accept own team invitation
2. Decline own team invitation

**Administrator**:

1. Administer team invitation settings.

Note: the **Manage team members** permission is a global permission that can be turned on for roles that are allowed to globally add/remove/invite new team members for all teams.

### Team permission

To configure team permissions, select **Configuration > Apigee Edge > Teams > Permissions**.

**Administrator**:

1. Manage team members and invitations

## Inviting users to a team

Any user with the **Manage team members global permission** or the **Manage team members and invitations team permission** can invite users to a team.

1. Select **Teams** in the top nav bar of your application.
2. Click the name of the team to view details.
3. Click the **Members** tab to view members.
4. Click the **Invite members** button.
5. Fill in the user **email addresses separated by a comma**.
6. Select the **Roles**.
7. Click **Invite members**.

![team-invitation-02](https://user-images.githubusercontent.com/124599/96963873-7dde8480-151a-11eb-8c13-16a1b9f70824.jpg)

## Managing team invitations

On the **Members** tab, you can find a list of all pending team invitations.

![team-invitation-03](https://user-images.githubusercontent.com/124599/96963893-859e2900-151a-11eb-8f7c-61cafa10ffc1.jpg)

### Resend invitation email

To resend the invitation email, find the team invitation under **Pending Invitations** and click **Resend**. You will get a confirmation prompt.

### Revoke team invitation

To revoke a team invitation, select **Revoke** under the operations for a team invitation.

## Viewing team invitations

As a user, to view a list of pending invitations, select **My account > Invitations**.

**Comment by arlina-espinoza** [comment]
Thanks @arshad.
@jbennett13 Should we add this directly under https://www.drupal.org/docs/8/modules/apigee-edge/configure-team-management, or create a new subpage? LMK.

**Comment by jbennett13** [comment]
Updated documentation throughout the Team Management page, but primarily here:  https://www.drupal.org/docs/contributed-modules/apigee-edge/configure-team-management#s-create-and-manage-team-invitations

**Comment by jbennett13** [comment]
Closing as complete.  Please feel free to reopen if additional detail is required.
