### ISSUE TITLE
Pending invitations block should be visible to a user with Drupal "Manage team members" permission (not only team permission)

### ISSUE THREAD

**Issue by jannakha** [apigee/apigee-edge-drupal#499]
## Description
Pending invitations block is displayed to users with team permission "Manage team members", but if a user is not a team admin but has "Manage team members" Drupal permissions - this block is not displayed.

Users with Drupal "Manage team members" are able to send invitation to users even if they are not a member of the team.

## Steps to Reproduce
1. Create a user who can manage Teams but not a Team admin (eg Dev portal manager)
2. Invite a user to a team

## Actual Behavior
Pending invitations block is not displayed.
Dev portal manager user can try to send invitation to same user again, but they'll get "this user already has invitation" error

## Expected Behavior
pending invitations should be displayed to users with **team permissions** "Team Admin" OR **Drupal** permissions "Manage team members" permissions 

**Users with Drupal "Manage team members" should be able to revoke/resend invitations as well**

## Note
I changed permissions to on that view to Drupal permission "Manage team members"
then Dev portal manger is able to view pending invitations, but this user cannot resend/revoke them.
If this user is able to create invitations, they should be able to revoke invitations.

## Screenshots
View's permissions:
![image](https://user-images.githubusercontent.com/1356783/94763987-112a0b80-03ee-11eb-8888-8b3fb5f600e4.png)

## Version Info
apigee_edge 8.x-1.16

**Comment by jannakha** [comment]
Dev portal manager has Manage team members Drupal permission as well

**Comment by shadcn** [comment]
Looks like this needs documentation too (or maybe better wording?).

The `Administer team invitations` is actually for administering team invitation config at `/admin/config/apigee-edge/team-settings/invitation`.

The team permission "Manage team members" handles team invitation.

I agree this can be confusing though. Maybe rename to:

"Administer team invitations" to "Administer team invitation settings"
"Manage team members" to "Mange team members and invitations"

/cc @arlina-espinoza

**Comment by jannakha** [comment]
ah, ok
then user with Drupal "Manage team members" should be able to view pending invitations even if they are not "Team Admin"
and they should be able to revoke/resend invitations (as they already can send out invitations).

@arshad I have updated the original task as it's not about documentation. It's about team vs Drupal permissions "Mange team members" as user doesn't have to be a member of a team to manage members/invitations.

**Comment by shadcn** [comment]
> then user with Drupal "Manage team members" should be able to view pending invitations even if they are not "Team Admin"

@jannakha Only if you give the "Manage team members" permission to the "Member" role.

![Permissions___Apigee](https://user-images.githubusercontent.com/124599/94807707-16448600-0401-11eb-863b-9ba7c68d6618.jpg)

Note: the "Manage team members" permission is a **team permission".

**Comment by shadcn** [comment]
@jannakha I created the following PR: https://github.com/apigee/apigee-edge-drupal/pull/501

**Comment by jannakha** [comment]
@arshad no this is not what I reported.
I don't think this issue can be closed.

- Users who can manage team members don't have to be a **part** of the team
Example: DEV PORTAL MANAGER, aka ADMIN (but not USER 1): this user is not a member of any team, but can create teams and send invitations to the teams, remove/change permissions to users within the team.

- Drupal permission **Manage team members** allows user who is NOT a part of a team to manage team members and send invitations
- Team permission **Manage team members**  allows ONLY user WHO IS A MEMBER of a team to manage invitations

BUG: User who has Drupal permission **Manage team members** SHOULD be able to manage invitations even if they are not a member of the team.

Please re-open this bug!

According to Drupal.org - you should not be closing issues unless they are reviewed and tested by the community.

**Comment by shadcn** [comment]
Ah I see what you mean now. I'm going to look into this.

PS: We did not mean to close this. It was closed as part of the PR merge. If this happens again, feel free to re-open. We're happy to help. Thank you.

**Comment by jannakha** [comment]
fixed! yeah! thanks guys! works well!
