### ISSUE TITLE
Team invitations are cached even after status/expiry date update

### ISSUE THREAD

**Issue by shadcn** [apigee/apigee-edge-drupal#500]
See https://github.com/apigee/apigee-edge-drupal/issues/498#issuecomment-701883915

Originally reported by @jannakha

> When admin re-sends expired invitation, invitee gets error "invitation expired" when they're trying to accept - even though it has a new expiration date.
> After clearing cache user was able to accept this invitation.

**Comment by shadcn** [comment]
@jannakha somehow I cannot reproduce this anymore. Can you help me / list the steps to reproduce this bug? Thank you.

**Comment by arunz6161** [comment]
Closing this out- please reopen if you continue to see the issue with detailed steps to reproduce the issue.
