### ISSUE TITLE
able to modify app inside inactive company

### ISSUE THREAD

**Issue by acobat** [apigee/apigee-edge-drupal#508]
Hi, 

We are using Apigee OPDK + Drupal 8.x + Monetization (Companies\Teams).

We hit a situation, which is super strange to us, while the company is inactive status, the company owner able to do anything inside the company apps (add apps, modify, delete etc.) - our understanding is that if company is inactive, all the other things are kind of open from UI\UX POV. 

We are aware that they cannot use the apps, and this is fine, but from UI\UX customer would like to also make the inside of company read-only. 

Is this a bug or feature, little explanation?

Thanks,

Denis

**Comment by arlina-espinoza** [comment]
Hi @acobat ,

The API will just not allow calls to the apps to go through when the team is disabled, but any management API calls (edit apps, members, etc) will still go through. However, we do see that it presents a confusing UX, so we think we can make it so when a team is disabled, prevent any member or team apps creation/deletion/editing, and prevent editing the company itself from the Drupal side.

Is this aligned with what you were expecting? Let us know.

**Comment by acobat** [comment]
yes, this is exactly what we need, can this be implemented? It is super confusing, and flow-speaking not correct. 

once company is in 'inactive' state - all manipulations on the apps\members or company meta data should be disabled, because we disabling company for reason and don't want company admin to be able for example, to modify the company app and subscribe to product. 

Thanks,
