### ISSUE TITLE
Updating apigee_edge module fails with Cannot redeclare Drupal\apigee_edge_teams\Entity\ListBuilder\TeamListBuilder

### ISSUE THREAD

**Issue by yenoomluap** [apigee/apigee-edge-drupal#510]
I am using composer to update apigee_edge module from 1.10 to 1.17. When I attempt to update the module (composer require drupal/apigee_edge:1.12/17), I receive this error:

PHP Fatal error: Cannot redeclare Drupal\apigee_edge_teams\Entity\ListBuilder\TeamListBuilder::render() in /var/www/html/web/modules/contrib/apigee_edge/modules/apigee_edge_teams/src/Entity/ListBuilder/TeamListBuilder.php on line 148
[warning] Drush command terminated abnormally. Check for an exit() in your Drupal site.

I receive this error for upgrades to 1.12 and 1.17.

I'm attaching my composer.json file if that helps. 
[composer.txt](https://github.com/apigee/apigee-edge-drupal/files/5410215/composer.txt)

edit: apigee support team directed me here

**Comment by shadcn** [comment]
@tool-rules What does `modules/apigee_edge_teams/src/Entity/ListBuilder/TeamListBuilder.php` look like after the update?

**Comment by yenoomluap** [comment]
@arshad here is TeamListBuilder.php after the update (1.10 -> 1.12)

[teamlistbuilder-v112.txt](https://github.com/apigee/apigee-edge-drupal/files/5440479/teamlistbuilder-v112.txt)

**Comment by arlina-espinoza** [comment]
Hi @tool-rules,
You have a patch on your composer.json file that is re-adding the `render()` method to the `TeamListBuilder` class:

```
"drupal/apigee_edge": {
    "Kill Cache temporarily": "patches/apigee_edge_teams/killing-cache-tempoarily.patch"
},
```

You will need to update the patch (if still needed) so that is compatible with the newer version of `apigee_edge`.
I'll close this issue, but feel free to reopen if you have further questions.
