### ISSUE TITLE
Make app notification messages (warning) more configurable

### ISSUE THREAD

**Issue by mxr576** [apigee/apigee-edge-drupal#511]
Since PR #507 app warnings have been decoupled to a new service.

This allows downstream to customize app warning messages. [In an early state of that PR](https://github.com/apigee/apigee-edge-drupal/pull/507#discussion_r503830960) I have raised an idea that besides customized warning messages, the downstream probably also would like to customize the severity of the displayed messages. This would also allow them displaying status- and error messages on the built-in app listing page just by decorating a service.

**Comment by shadcn** [comment]
Thanks for the suggestion @mxr576. We are going to look into this.

**Comment by arunz6161** [comment]
To be discussed in deep dive 11/02
