### ISSUE TITLE
can't see the keys

### ISSUE THREAD

**Issue by yenoomluap** [apigee/apigee-edge-drupal#515]
after upgrading to apigee_edge 1.17 - we receive the following message when we use admin/config/system/keys:

`The website encountered an unexpected error. Please try again later.`

`Drupal\Component\Plugin\Exception\PluginNotFoundException: The "apigee_edge_basic_auth" plugin does not exist. Valid plugin IDs for Drupal\key\Plugin\KeyPluginManager are: apigee_auth, authentication, authentication_multivalue, encryption, user_password in Drupal\Core\Plugin\DefaultPluginManager->doGetDefinition() (line 53 of core/lib/Drupal/Component/Plugin/Discovery/DiscoveryTrait.php).`

Prior to update we would see the edge keys.  Would you be able to assist with correcting this behavior?

Thank You

**Comment by yenoomluap** [comment]
composer.json

[composer.txt](https://github.com/apigee/apigee-edge-drupal/files/5478232/composer.txt)

**Comment by arlina-espinoza** [comment]
Hi @tool-rules, the `apigee_edge_basic_auth` was removed since the release of apigee_edge `8.x-1.0-beta1`. You can try deleting the old key from `/admin/config/system/keys`, and re-configuring your connection details at `/admin/config/apigee-edge/settings`. That should create a new key.

**Comment by arlina-espinoza** [comment]
Closing, please reopen if you have further questions.
