### ISSUE TITLE
Unable to invite members to another team, if teams get deleted with pending member invitation

### ISSUE THREAD

**Issue by varuntit101** [apigee/apigee-edge-drupal#517]
## Description
Unable to invite members to another team, if teams get deleted with pending member invitation

## Steps to Reproduce
1. Create a team
2. Add a member to the team. (Do not accept/reject the invitation yet)
3. Delete the team.
3. Create a second team
4. Add the same member to the second team

## Actual Behavior
This throws an error saying "The following developer has already been invited to the team: 'developer_email@abc.com'."

## Expected Behavior
All invitation of the team(pending), should be deleted once a team is deleted, and a member should be allowed to add in second team.

## Version Info
1.18

**Comment by msgowtham** [comment]
facing the same issue

**Comment by shadcn** [comment]
I created a PR to fix the "inviting to more than one team" issue.

> All invitation of the team(pending), should be deleted once a team is deleted.

I'm wondering how we can properly handle this. 

We could implement a hook to cascade delete referenced team invitations when a team is deleted. This would work but there might be situations where a team/company is deleted on the Apigee server.

In https://github.com/apigee/apigee-edge-drupal/pull/522 I implement a query access subscriber to filter out team invitations with deleted team.

So team invitations with deleted team will not show up in the UI.

Suggestion: We could implement a cron that deletes orphaned team invitation.

@arlina-espinoza What do you think?
