### ISSUE TITLE
Facing error when altering Drupal 8 user registration form.

### ISSUE THREAD

**Issue by msgowtham** [apigee/apigee-edge-drupal#520]
## Description
Whenever we are trying to modify the user registration form to a multi-step or adding/modifying a field using Ajax callback, I am seeing a cache error. 
**Please refer below for the error message:**
TypeError: Return value of Drupal\apigee_edge\Entity\Controller\Cache\DeveloperIdCache::getEntityId() must be of the type string, null returned in Drupal\apigee_edge\Entity\Controller\Cache\DeveloperIdCache->getEntityId() (line 40 of C:\Users\Admin\Sites\devdesktop\********\******-developer-portal\web\modules\contrib\apigee_edge\src\Entity\Controller\Cache\DeveloperIdCache.php)

## Screenshots
![image](https://user-images.githubusercontent.com/71095961/99298316-8d2dc500-286f-11eb-8772-0854d47f5531.png)

**Comment by shadcn** [comment]
@msgowtham I can take a look at this. Can you share the code (or a snippet) of what you've tried so far?

**Comment by msgowtham** [comment]
@arshad 
I am trying to do a multistep user registration form. 
**Sample snippet code:**
function partner_registration_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
  if ($form_id == 'user_register_form') {
// adding a custom button "Next"
 $form['my_module_actions']['next'] = [
      '#type' => 'submit',
      '#value' => t('Next'),
      '#name' => 'Next',
      '#submit' => [
       'my_module_register_next_previous_form_submit'
      ],
      '#limit_validation_errors' => $validation,
      '#access' => FALSE,
      '#weight' => 1,
    ];
}
/**
 * Custom form submit for the user registration form.
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 */
function my_module_register_next_previous_form_submit(array &$form, FormStateInterface $form_state ) {
 // Get the current page that was submitted.
  $current_page = $form_state->get('page_num');
 
  // Get the fields for the pages.
  // These are the same as the $pages variable in the form_alter.
  // I've excluded them here for brevity.
  $fields = [...];
 
  // Setup our page values variable.
  if (!$form_state->get('page_values')){
    $page_values = [];
  }
 
  if ($form_state->getValue('next')) {
    // Add the values to the page_value array.
    foreach ($fields[$current_page] as $key) {
      $page_values[$current_page][$key] = $form_state->getValue($key);
    }
    // Increment the page number.
    $current_page++;
  }
  else if ($form_state->getValue('previous')) {
    // Discard the values the page_value array.
    foreach ($fields[$current_page] as $key) {
      $form_state->setValue($key, $page_values[$current_page][$key]);
      unset($page_values[$current_page][$key]);
    }
    // Decrement the page number.
    $current_page--;
  }
 
  $form_state
    ->set('page_num', $current_page)
    ->set('page_values', $page_values)
    ->setRebuild(TRUE);
}

Here whenever we try to click on the "Next" button, I am seeing this error.
**TypeError**: Return value of Drupal\apigee_edge\Entity\Controller\Cache\DeveloperIdCache::getEntityId() must be of the type string, null returned in Drupal\apigee_edge\Entity\Controller\Cache\DeveloperIdCache->getEntityId() (line 40 of C:\Users\Admin\Sites\devdesktop**************-developer-portal\web\modules\contrib\apigee_edge\src\Entity\Controller\Cache\DeveloperIdCache.php)

**Reference link:** https://philfrilling.com/blog/2018-09/drupal-8-change-user-registration-form-multi-step-form

**Comment by shadcn** [comment]
@msgowtham It looks like we found a bug here. There's a computed field `apigee_edge_developer_id` on the `User` entity which is trying to load a `Developer` with an empty email address.

I created a PR here which should fix this: https://github.com/apigee/apigee-edge-drupal/pull/523 (CI is running. Let's see if this breaks anything).

As for the multi steps form, see if a combination of the [Field Group](http://drupal.org/project/field_group) and [Simple Multistep](https://www.drupal.org/project/simple_multistep) works. I tried it on my local copy and it seems to be working fine (with the patch from the PR).

## Group fields

![multi-step-1](https://user-images.githubusercontent.com/124599/100098865-0f257b80-2e78-11eb-9def-b1b7ec9dc23c.jpg)

## Registration form

![mutli-step-2](https://user-images.githubusercontent.com/124599/100098881-15b3f300-2e78-11eb-9593-f23e2f751dd5.jpg)

**Comment by arlina-espinoza** [comment]
@msgowtham We have merged the PR that should fix the error that was coming from this module regarding the registration form. Feel free to reopen if there is further feedback or questions.

**Comment by msgowtham** [comment]
> @msgowtham We have merged the PR that should fix the error that was coming from this module regarding the registration form. Feel free to reopen if there is further feedback or questions.

@arlina-espinoza I applied the patch in my local and it's working fine now. Thank you
