### ISSUE TITLE
Multiple Issues with Apps pages in Hybrid

### ISSUE THREAD

**Issue by giteshk** [apigee/apigee-edge-drupal#521]
I connected the developer portal to Apigee Hybrid organization.

I was able to create an App but the following errors happen:

1. But I am unable to view the API Key
![Screen Shot 2020-11-19 at 5 23 58 PM](https://user-images.githubusercontent.com/6208023/99731699-4963d700-2a8c-11eb-862f-54181a80a280.png)

2. Unable to edit the app
![Screen Shot 2020-11-19 at 5 23 29 PM](https://user-images.githubusercontent.com/6208023/99731764-5ed90100-2a8c-11eb-87ff-347c5e1674f0.png)

3. Randomly get the following error and am unable to view existing credentials.
![Screen Shot 2020-11-19 at 5 22 56 PM](https://user-images.githubusercontent.com/6208023/99731821-70220d80-2a8c-11eb-9cd1-3c38dd2a8288.png)
Verified the credential exists in Edge:
![Screen Shot 2020-11-19 at 5 23 05 PM](https://user-images.githubusercontent.com/6208023/99731839-79ab7580-2a8c-11eb-8e63-d8f6042287db.png)

**Comment by arunz6161** [comment]
Update from Eng-

While we continue investigating this further, it would be good to verify the following:

1. The service account is missing the right level of permissions resulting in some calls failing. Could you verify the role assigned to the service account ?
2. Org could be running into a cache issue. Could you try disabling all caches in the apigee module config and checking if that helps ?

**Comment by arunz6161** [comment]
Could we enable Apigee debug and verify what the backend is returning when errors are seen ?

Refer documentation : https://www.drupal.org/docs/8/modules/apigee-edge/monitor-apigee-edge-debug-logs

**Comment by arlina-espinoza** [comment]
I've been able to replicate the issue when using a service account with the role "Apigee Developer Admin":
- When viewing an app, sometimes the credentials will load or not.
- 404 when trying to edit an app.

Enabling `apigee_edge_debug` shows that all calls to `/organizations/***organization***/apps/***appId**` are failing:

```
GET /v1/organizations/***organization***/apps/470bb26d-7c54-4868-a17d-89bdc465d6f6 HTTP/1.1
Host: apigee.googleapis.com
X-Apigee-Edge-Api-Client-Profiler: X-Apigee-Edge-Api-Client-Profiler
User-Agent: Apigee Edge DevPortal 8.x-1.x-dev (Apigee Edge PHP Client 2.0.5)
Accept: application/json; charset=utf-8
Authorization: Bearer ***

HTTP/1.1 403 Forbidden
Vary: X-Origin, Referer, Origin,Accept-Encoding
Content-Type: application/json; charset=UTF-8
Date: Mon, 30 Nov 2020 18:48:25 GMT
Server: ESF
Cache-Control: private
X-XSS-Protection: 0
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
Alt-Svc: h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Accept-Ranges: none
Transfer-Encoding: chunked

{
  "error": {
    "code": 403,
    "message": "The caller does not have permission",
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.RequestInfo",
        "requestId": "1114225228044541219"
      }
    ]
  }
```

So:
- The error of the random appearance of credentials could be if the app was cached when loaded through another endpoint (`/organizations/***organization***/developers/***developerId***/apps/***appName***` does work correctly), but if it wasn't yet in cache, the call to fetch credentials uses the /apps endpoint which fails.
- The app edit page uses the /apps endpoint which fails.

**Comment by cnovak** [comment]
This issue has been reported to the Apigee internal team. It looks like the GCP IAM "Apigee Developer Admin" role does not have the proper permissions. We will update status here, but in the meantime you can use the "Apigee Organization Admin" role for now.

**Comment by raakesh-blokhra** [comment]
The internal team wasn't able to reproduce the issues with newer versions of Hybrid / NGSaaS. We will close this issue but feel free to re-open it in case the issues are not resolved.
