### ISSUE TITLE
caching on team level

### ISSUE THREAD

**Issue by acobat** [apigee/apigee-edge-drupal#524]
Hi, we have found a bug (as we think): 

To reproduce: 

1. Create company in Apigee
![image](https://user-images.githubusercontent.com/5484385/100214982-2f594700-2f19-11eb-9a24-9439d9e1345a.png)

2. Observe the status of the company in the list in the portal: 

![image](https://user-images.githubusercontent.com/5484385/100215023-3aac7280-2f19-11eb-8a48-22cbcee70fdb.png)

![image](https://user-images.githubusercontent.com/5484385/100215048-40a25380-2f19-11eb-86d8-d6977f1cd8d4.png)

Now, change the status in Apigee to Inactive:
![image](https://user-images.githubusercontent.com/5484385/100215130-53b52380-2f19-11eb-9e03-fad6c6979cf5.png)

Observe the portal: 

![image](https://user-images.githubusercontent.com/5484385/100215169-5ca5f500-2f19-11eb-9a34-bfa446aa937b.png)

![image](https://user-images.githubusercontent.com/5484385/100215194-63346c80-2f19-11eb-9b39-0b00be54f877.png)

As we can see all works as expected, however, this works only for Global Portal admin, 

For team member\team admin we can see that change only reflected in the list of companies: 

![image](https://user-images.githubusercontent.com/5484385/100215291-7e06e100-2f19-11eb-9dbf-8ab56f5dd197.png)

While in the company we can see status remains 

![image](https://user-images.githubusercontent.com/5484385/100215415-a2fb5400-2f19-11eb-9d83-b7ef43c39c8d.png)

(flushing routing and links cache) solves this

But we want the behavior be same between admin and enduser

Thanks,

Denis

**Comment by acobat** [comment]
@arlina-espinoza hi, any assistance please? 👍

**Comment by shadcn** [comment]
@acobat It looks like the `cache_expiration` config was not properly set for `Team` entity view. I created a PR to fix this.

Note: There's not much we can on the Drupal site when something changes remotely (unless caching is turned off). With the above PR, if you want remote changes done to be loaded in Drupal, you can set the `cache_expiration` to 0.

**Comment by acobat** [comment]
cache_expiration 0 works only for admin, not for regular user, this is the actual bug :)

**Comment by shadcn** [comment]
The PR should fix this :)

**Comment by m-khan23** [comment]
This is actually a much bigger issue. We have seen some users are able to see other team's apps. This reveals confidential information that we definitely do not want to share. Any update on when this will be complete? @arshad

**Comment by shadcn** [comment]
@m-khan23 did you try the PR? Does it fix the issue?

**Comment by m-khan23** [comment]
@arshad It looks like the PR is not yet merged. Will try as soon as we have a complete release.

'Flush all caches' temporarily fixes the issue so this probably will resolve this issue

**Comment by arlina-espinoza** [comment]
@arshad 's PR has been merged to the main dev branch. Let us know if this fixes the issue @m-khan23 .

**Comment by cnovak** [comment]
Closing since PR is now merged.
