### ISSUE TITLE
Apigee "Configure credentials: Connect to Apigee Edge or Edge for Private Cloud" documentation outdated

### ISSUE THREAD

**Issue by cnovak** [apigee/apigee-edge-drupal#533]
## Description
The documentation page [Configure credentials: Connect to Apigee Edge or Edge for Private Cloud](https://www.drupal.org/docs/contributed-modules/apigee-edge/configure-the-connection-to-apigee-edge#configure-credentials-edge) is outdated.

The page should be updated with information about apigee.google.com instances.  This is related to issue #526

**Comment by phdhiren** [comment]
@cnovak ,

Can you please review to close this issue?
https://www.drupal.org/docs/contributed-modules/apigee-edge/configure-the-connection-to-apigee

Thank you @jbennett13  for updating the documentation which looks good to me. I've updated one of figure which reflect latest change of #526

**Comment by raakesh-blokhra** [comment]
@phdhiren and @jbennett13 I don't see a PR associated with it, assuming because it the document needed an update on drupal.org. I will close this issue for now, if there are any pending issues, please let me know and re-open this.
