### ISSUE TITLE
Ability to transfer App ownership from User to Team

### ISSUE THREAD

**Issue by m-khan23** [apigee/apigee-edge-drupal#537]
## Is your feature request related to a problem? Please describe.

We often see users create an app on the portal. Later on, they want to share credentials with a team (or they leave the company). Transferring ownership from a user to a team is not an easy user friendly process today. 

## Describe the solution you would like

A simple admin UI that let's Admins transfer ownership of apps from a user to a team

## Describe alternatives you have considered

Putting together a process to force users to use teams instead of individual apps. Unfortunately, this does not work well since RBAC is not very easy to implement for teams.

**Comment by earth2marsh** [comment]
Thanks for the request. This isn't a problem specific to the Drupal modules, as app ownership is an immutable relationship at the time of app creation. Note also that you should be able to modify the code to prevent individual app ownership UI in Drupal today as a custom modification, which would allow you to sidestep app ownership transfer issues by always creating team-owned apps. We are also working with other teams to improve the app ownership data model, but that's a new API that will take some time and is outside the scope of the Drupal modules.

**Comment by m-khan23** [comment]
Hey, thanks for the info. Yes, we would go that route but then we (admin team) would be on the hook for creating team apps. There is no easy way to control which API Products different teams could see - similar to RBAC for apps.

Looking forward to the improved app ownership data model. Right now, we don't think it's great but we are making it work! Thanks.

**Comment by mxr576** [comment]
> There is no easy way to control which API Products different teams could see - similar to RBAC for apps.

Building a solution for "Team-based API product access" is not impossible on the devportal side, as far as I remember, we have built something like that at Pronovix before. In general, I am not sure if that should be covered by this module or it should be always a custom development/separate contrib module.

> We are also working with other teams to improve the app ownership data model, 

I am looking forward to learning more about this when it is ready :)
