### ISSUE TITLE
Cannot use Apigee Rules

### ISSUE THREAD

**Issue by m-khan23** [apigee/apigee-edge-drupal#549]
## Description
We are trying to use Reaction Rules with Apigee to manage API Access Control. However, Rules throws an error with any Apigee Edge Related Rule (Apps, Teams, Products, etc)

## Steps to Reproduce
1. Home  -> Administration ->  Configuration  -> Workflow  Rules
2. Add Reaction Rule
3. 'After Adding an API Product'
4. Add any Label
5. Save

Error is thrown

## Notes

Here is the error that is thrown:

`[error] 2397#2397: *280 FastCGI sent in stderr: "PHP message: TypeError: Argument 2 passed to Drupal\rules\Engine\RulesComponent::addContextDefinition() must implement interface Drupal\rules\Context\ContextDefinitionInterface, array given, called in /var/www/devportal/web/modules/contrib/rules/src/Engine/RulesComponent.php on line 175 in /var/www/devportal/web/modules/contrib/rules/src/Engine/RulesComponent.php on line 145 #0 /var/www/devportal/web/modules/contrib/rules/src/Engine/RulesComponent.php(175): Drupal\rules\Engine\RulesComponent->addContextDefinition('developer_app', Array)
#1 /var/www/devportal/web/modules/contrib/rules/src/Entity/ReactionRuleConfig.php(159): Drupal\rules\Engine\RulesComponent->addContextDefinitionsForEvents(Array)
#2 /var/www/devportal/web/modules/contrib/rules/src/Entity/ReactionRuleConfig.php(266): Drupal\rules\Entity\ReactionRuleConfig->getComponent()
#3 /var/www/devportal/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityBase.php(318): Drupal\rules\Entity\ReactionRuleConfig->calculateDependencies()
#4 /var/www/" while reading response header from upstream, client: 10.250.123.172, server: localhost, request: "POST /admin/config/workflow/rules/reactions/add HTTP/1.1"`

## Version Info
Drupal Core: 8.9.12
apigee/apigee-client-php                                  2.0.6  
apigee/apigee_devportal_kickstart                         1.13.0      
drupal/apigee_api_catalog                                 2.0.0     
drupal/apigee_edge                                        1.20
drupal/apigee_m10n                                        1.8.0

**Comment by m-khan23** [comment]
Able to fix this by:

Removing drupal/typed_data (1.0.0-alpha5)
Installing drupal/typed_data:1.x-dev
Installing drupal/rules:3.0.0-alpha6

May want to update documentation here:
https://www.drupal.org/docs/contributed-modules/apigee-edge/manage-reaction-rules

**Comment by cnovak** [comment]
Thanks for update @m-khan23 . I am going to reopen so that we can verify and document this like you pointed out.

**Comment by raakesh-blokhra** [comment]
@jbennett13 Can you please check this and document the above as needed? Please close the issue after it is addressed. Thanks.
