### ISSUE TITLE
Handle situations when $form_state->getValue brings back wrong type in AddTeamMembersForm

### ISSUE THREAD

**Issue by cnovak** [apigee/apigee-edge-drupal#554]
Aan error is being thrown in the `validateForm()` method:

```
Warning: explode() expects parameter 2 to be string, array given in Drupal\apigee_edge_teams\Form\AddTeamMembersForm->validateForm() (line 181 of .../apigee_edge/modules/apigee_edge_teams/src/Form/AddTeamMembersForm.php)
```

On line 181 in `AddTeamMembersForm` the call `$form_state->getValue('developers', '')` is returning an array instead of a string which causes `explode()` to fail, which causes the `$emails` array to be null: https://github.com/apigee/apigee-edge-drupal/blob/0d88019a0f6e2994005cecbfce8d1f50471429d1/modules/apigee_edge_teams/src/Form/AddTeamMembersForm.php#L181

We should check for the case where `$form_state->getValue('developers', '')` comes back as an array and handle it by appending the array together with a space so that explode() can handle the input as a string, and throw an error in the logs showing the `$form_state->getValue('developers', '')` array values so that we can understand what input is coming in. I have no idea how an array is getting returned however.

_Originally posted by @cnovak in https://github.com/apigee/apigee-edge-drupal/issues/548#issuecomment-769472262_

**Comment by cnovak** [comment]
I wanted to add this as a follow up on #548 in case other developers may have custom changes that would be affected by upgrades, or any other reason. We should decide if this is worth doing.

**Comment by raakesh-blokhra** [comment]
@cnovak got it, good idea. Will look into this.
