### ISSUE TITLE
Add Drupal core version to the user agent string

### ISSUE THREAD

**Issue by cnovak** [apigee/apigee-edge-drupal#556]
## Description
When calls are made to Apigee APIs, the user agent string sends info about the Apigee Edge version and PHP Client version:

`Apigee Edge DevPortal 8.x-1.10 (Apigee Edge PHP Client 2.0.3)`

This task is to add the Drupal core version along with this information:

`Drupal Core 8.19, Apigee Edge DevPortal 8.x-1.10 (Apigee Edge PHP Client 2.0.3)`

**Comment by cnovak** [comment]
@earth2marsh FYI

**Comment by earth2marsh** [comment]
Thanks, this info is critical to understanding what versions are in active use!

**Comment by mxr576** [comment]
How about `Apigee Edge DevPortal 8.x-1.10 (Apigee Edge PHP Client 2.0.3 | Drupal Core 8.19)`? 
This is also a piece of secondary information, just like the PHP API client.

**Comment by cnovak** [comment]
@mxr576 format makes sense to me, WDYT @earth2marsh ?

**Comment by earth2marsh** [comment]
Yes, placing it in parens as secondary info makes sense to me. Nice idea.

**Comment by shishir-intelli** [comment]
@cnovak
Do you think we should also change "`Apigee Edge DevPortal 8.x-1.10`" to "`Apigee Edge Drupal module 8.x-1.10`" instead?

`Apigee Edge Drupal module 8.x-1.10 (Apigee Edge PHP Client 2.0.3 | Drupal Core 8.19)`

**Comment by cnovak** [comment]
> @cnovak
> Do you think we should also change "`Apigee Edge DevPortal 8.x-1.10`" to "`Apigee Edge Drupal module 8.x-1.10`" instead?
> 
> `Apigee Edge Drupal module 8.x-1.10 (Apigee Edge PHP Client 2.0.3 | Drupal Core 8.19)`

Yes, this makes sense FYI @giteshk

**Comment by giteshk** [comment]
How would this look with Monetization module?

**Comment by raakesh-blokhra** [comment]
> How would this look with Monetization module?

@giteshk Are you asking whether we can add Monetization module version as well?

**Comment by shishir-intelli** [comment]
@giteshk  This is how it will look with monetization module

- With Monetization module enabled

![m10_enabled](https://user-images.githubusercontent.com/75600200/122174819-aef03880-cea0-11eb-93e9-2c6e7d4d4e94.png)

- Without Monetization module

![without_m10](https://user-images.githubusercontent.com/75600200/122174836-b4e61980-cea0-11eb-91cd-04b65ca4fafb.png)

Let me know if this looks good or do we need to make it more shorter.

**Comment by giteshk** [comment]
@arunz6161 Do you think this format is good to query.

**Comment by mxr576** [comment]
Since we are planning to change/extend the original format, It just came into my mind if we should switch to a formatting like web browsers are using nowadays. What do you think?

Example: 
`Apigee Edge/1.22 (Apigee Edge PHP Client/2.0.3; Drupal/8.9.16; PHP/7.3.11)`
and
`Apigee Monetization/1.10 (Apigee Edge/8.x-1.22; Apigee Edge PHP Client/2.0.3; Drupal/8.9.16; PHP/7.3.11)`

(Monitoring PHP runtime version could be useful to know when we can drop < PHP 7.4 support and start using new language level features.)

Note: The `8.x-` prefix was dropped since semver is also [available on Drupal.org](https://www.drupal.org/node/3108648), makes version parsing much easier.

Source:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent

**Comment by cnovak** [comment]
I like @mxr576's solution, let's go that direction unless anyone else sees an issue doing this.

**Comment by giteshk** [comment]
Looks good to me.

**Comment by shishir-intelli** [comment]
> Note: The 8.x- prefix was dropped since semver is also available on Drupal.org, makes version parsing much easier. 

For this, there is already a ticket created in Github https://github.com/apigee/apigee-edge-drupal/issues/605 so wont make any changes in this PR. 
Once https://github.com/apigee/apigee-edge-drupal/issues/605 is fixed automatically it will get resolved.

**Comment by phdhiren** [comment]
@raakesh-blokhra @giteshk 
Had given few reason to have at  https://github.com/apigee/apigee-client-php/pull/171#pullrequestreview-720165285
I would suggest to have simpler format so Apigee Edge and Client PHP Library do not have dependency just for UA string

Example:
`Apigee Edge/1.22; Drupal/8.9.16 (PHP Client/2.0.3; PHP/7.3.11)`
and
`Apigee Monetization/1.10; Apigee Edge/8.x-1.22;  Drupal/8.9.16; (PHP Client/2.0.3; PHP/7.3.11)`

This way other consumers of `apigee-client-php` don't have to upgrade by adding unnecessary '-' or any other separator and will not have dependency just for the format on each other.

**Comment by raakesh-blokhra** [comment]
> @raakesh-blokhra @giteshk
> Had given few reason to have at [apigee/apigee-client-php#171 (review)](https://github.com/apigee/apigee-client-php/pull/171#pullrequestreview-720165285)
> I would suggest to have simpler format so Apigee Edge and Client PHP Library do not have dependency just for UA string
> 
> Example:
> `Apigee Edge/1.22; Drupal/8.9.16 (PHP Client/2.0.3; PHP/7.3.11)`
> and
> `Apigee Monetization/1.10; Apigee Edge/8.x-1.22; Drupal/8.9.16; (PHP Client/2.0.3; PHP/7.3.11)`
> 
> This way other consumers of `apigee-client-php` don't have to upgrade by adding unnecessary '-' or any other separator and will not have dependency just for the format on each other.

I think this is good and makes sense, also efficient in terms of coding. @giteshk do you see any issues? If not, let's move in this direction. @mxr576 what do you think?
