### ISSUE TITLE
In Teams module - apps, the consumer key and consumer secret are not visible \ does not exists

### ISSUE THREAD

**Issue by ayalador** [apigee/apigee-edge-drupal#557]
The consumer key and consumer secret are masks with *** , but there is no data behind it.
ver 8.X-1.20

![image](https://user-images.githubusercontent.com/63708996/107952234-29b45000-6fa2-11eb-89a5-70db0decb39c.png)

**Comment by acobat** [comment]
I will add - this bug exists only in latest version, 1.20 (before that all works) @cnovak

**Comment by phdhiren** [comment]
@ayalador @acobat I checked with 1.20 but could not replicate the issue and I could copy consumer key and secret for Team's App. Is there any other module do exists which may possibly conflict with?

**Comment by aparnakcvs** [comment]
/**if you are using custom theme wrapper got changed .. Please 
New file should in your theme**/

/**profiles/contrib/apigee_devportal_kickstart/themes/custom/apigee_kickstart/templates/apigee/apigee-secret.html.twig
****/
/*
 * Implement template_preprocess_app_credentials().
 */
function cvs_preprocess_app_credential(&$variables) {
  // Render the consumerKey and the consumerSecret as secret fields.
  foreach (['consumerKey', 'consumerSecret'] as $field_name) {
    if (empty($variables['primary_wrapper'][$field_name]['value']['#value'])) {
      continue;
    }

    $variables['primary_wrapper'][$field_name]['value'] = [
      '#type' => 'apigee_secret',
      '#value' => $variables['primary_wrapper'][$field_name]['value']['#value'],
    ];
  }

  // Rename title to products.
  $variables['secondary_wrapper']['title']['#title'] = t('Products');
}

**Comment by aparnak123** [comment]
template got changed.. If you are using custom theme.. please copy proper new twig and includes (apigee.inc) changes

1) custometheme_preprocess_app_credential(&$variables)

2) docroot/profiles/contrib/apigee_devportal_kickstart/themes/custom/apigee_kickstart/templates/apigee/apigee-secret.html.twig

**Comment by ayalador** [comment]
There was a JS conflict due to changes in the module.
We solved it - the issue can be close.
