### ISSUE TITLE
Changing team status in the APIGEE is not reflected in the portal

### ISSUE THREAD

**Issue by ayalador** [apigee/apigee-edge-drupal#558]
In case of updating the team's status- the status is not reflected in the developers portal.
After creating a company and updating the status to Inactive and from Inactive to active.
The cache is set to 0 (zero).

Ver 8.X- 1.20

**Comment by phdhiren** [comment]
@ayalador , I've tried to recreate on test environment, however updating the status of company in APIGEE is reflecting immediately to developer portal if cache is set to 0 at admin/config/apigee-edge/team-settings/caching. Do you have any additional caching enabled at Drupal or at server level?

**Comment by ayalador** [comment]
@phdhiren We checked the issue without any additional development (vanilla) and it seems that in the companies list page the status is reflected correctly. when entering to the company view page the status is not displayed correctly. Note that the status is displayed correctly when logged in as a Drupal admin.

**Comment by ayalador** [comment]
@phdhiren Hi, it is a BUG, I am not able to change the label.
please advise.

**Comment by phdhiren** [comment]
I'm able to replicate when user is not admin and cached data is coming. With admin user status is displayed correctly.

**Comment by ayalador** [comment]
@phdhiren Any plan in resolving the issue?

**Comment by phdhiren** [comment]
Let me add the ticket to next milestone

**Comment by ayalador** [comment]
@phdhiren  what is the timeline for next milestone?
Thanks
