### ISSUE TITLE
Denormalize  logs in the portal - warnings that block the servers

### ISSUE THREAD

**Issue by ayalador** [apigee/apigee-edge-drupal#559]
Denormalize logs are created a lot of times although does not affect the functionality of the portal - it caretes a memory issues in the server.

Log example:
![image](https://user-images.githubusercontent.com/63708996/107964281-c7fbe200-6fb1-11eb-9190-6b69c2494bd8.png)

Ver 8.X - 1.20

**Comment by phdhiren** [comment]
@ayalador, I've checked with 8.x-1.20, however could not see any errors in recent logs. Do you've any other custom module enabled along with?

**Comment by ayalador** [comment]
@phdhiren The teams module is also enabled.
It seems that the issue is due to data that we get from the APIGEE that includes optional fields, in case that the data does not exists the log is created. The fields are not mandatory so the log should not be created.

**Comment by phdhiren** [comment]
@ayalador , If you can share more info around this? Can you enable debug module and share the [debug log](https://www.drupal.org/docs/8/modules/apigee-edge/monitor-apigee-edge-debug-logs) after sanitization

**Comment by mxr576** [comment]
@ayalador I think this is related to this bug: https://github.com/apigee/apigee-client-php/pull/122

**Comment by phdhiren** [comment]
@ayalador Can you confirm, the issue got solved with apigee/apigee-client-php#122 ?
