### ISSUE TITLE
Apigee Edge Module gives error while upgrading from Drupal 8.7 to 8.9

### ISSUE THREAD

**Issue by pandatrooper** [apigee/apigee-edge-drupal#563]
While performing updates for upgrading Apigee Drupal Kickstart from 8.7 to 8.9, I face integrity constraint violation error.

1. Place the portal on maintenance mode and update to the latest version using `composer update --with-dependencies --optimize-autoloader`
2.  Run `drush updb`

## Actual Behavior
While all the updates were carried out successfully, only one update threw an Integrity constraint violation error i.e the **apigee_edge_update_8101**

```
[notice] Update started: apigee_edge_update_8101
[error]  Drupal\Core\Database\IntegrityConstraintViolationException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'name' cannot be null: INSERT INTO {tmp_6f455cusers_field_data} (uid, langcode, preferred_langcode, preferred_admin_langcode, name, pass, mail, timezone, status, created, changed, access, login, init, default_langcode, first_name, last_name) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6, :db_insert_placeholder_7, :db_insert_placeholder_8, :db_insert_placeholder_9, :db_insert_placeholder_10, :db_insert_placeholder_11, :db_insert_placeholder_12, :db_insert_placeholder_13, :db_insert_placeholder_14, :db_insert_placeholder_15, :db_insert_placeholder_16); Array
(
[:db_insert_placeholder_0] => 0
[:db_insert_placeholder_1] => en
[:db_insert_placeholder_2] => 
[:db_insert_placeholder_3] => 
[:db_insert_placeholder_4] => 
[:db_insert_placeholder_5] => 
[:db_insert_placeholder_6] => 
[:db_insert_placeholder_7] => 
[:db_insert_placeholder_8] => 
[:db_insert_placeholder_9] => 
[:db_insert_placeholder_10] => 
[:db_insert_placeholder_11] => 
[:db_insert_placeholder_12] => 
[:db_insert_placeholder_13] => 
[:db_insert_placeholder_14] => 
[:db_insert_placeholder_15] => 
[:db_insert_placeholder_16] => 
 )
in Drupal\Core\Database\Connection->handleQueryException() (line 698 of /var/www/html/devportal/web/core/lib/Drupal/Core/Database/Connection.php). 
[error]  The entity update process failed while processing the entity type user, ID: 0. 
[error]  Update failed: apigee_edge_update_8101 
[error]  Update aborted by: apigee_edge_update_8101
```

I went into the database to check the `users_field_data` however I could not find the user with `uid:0`. However, on further research I saw the `uid:0` in the `users` table rather than the `users_field_data`. On performing a count of both the `users` and `users_field_data`, I discovered that there were some additional uid (including the uid above that threw error ) in the `users` than the `users_field_data`.  **On removing the uids in `users` table that are not available in `users_field_data` table, the error was resolved.**

However, since it was our test servers therefore I could play around with our Drupal MySQL database. We might not have the same liberty in our production server. 

Any suggestions on how to eliminate this issue without manually deleting rows from database ? Additionally, what's the connection between the `users` & `users_field_data` ?  As per the above error, the update is trying to add the additional uids in `users` table to the `users_field_data` table and that's where everything goes haywire.

**Comment by phdhiren** [comment]
@pandatrooper ,

Before doing on production, if you can have following checks
1. `users` and `users_field_data` to have one to one relationship. Both should have same count. 
2. uid:0 is considered to be anonymous user of Drupal, if not there you can check this [drupal documentation](https://www.drupal.org/node/1029506)

If the [Developer synchronization](https://www.drupal.org/docs/8/modules/apigee-edge/synchronize-developers-with-apigee-edge) process was finished properly earlier? And only uid:0 was only difference between `users` and `user_field_data` or there were few more?

**Comment by pandatrooper** [comment]
@phdhiren 

Thanks for the information. There were a few more. There were around 7 additional `uid` in `users` that were not available in `users_field_data`.

When I checked for these additional 7 users via UI, I was unable to find them in People section. However, if I navigated to their profiles manually via `https://mydeveloperportal.com/user/additionaluid` [ Ex `https://mydeveloperportal.com/user/96` ], the portal guides me to an `anonymous` profile with the following details :

![image](https://user-images.githubusercontent.com/30631676/110083928-51365580-7db5-11eb-8f06-d715bdecbc07.png)

These user have all the fields `null` apart from the role. We have a scheduled Developer Synchronization process every week. Even `drush` fails to recognize these anonymous users. I tried to purge users (if any ) using [Auto Purge](https://www.drupal.org/project/purge_users) module, but even that did not yield any results. 

I did some investigation and found out that some of these anonymous users have authored node, or a comment etc. in the past and maybe those `uids` are associated with the author metadata. Not sure if that's breaking the update or not. Any leads would be appreciated

**Comment by phdhiren** [comment]
I assume these are spam data as creation date before 51 years seems not logical, creation timestamp seems to be 0. Unknown user should not have administrator role

**Comment by pandatrooper** [comment]
So manually deleting rows with additional `uids` from the `users` table is the only way around ?

**Comment by phdhiren** [comment]
Current yes that seems to be better option. As I've also tried from 8.7 to 8.9 but its not due to migration but due to earlier data in database.

**Comment by phdhiren** [comment]
@pandatrooper,

Closing the issue as it is specific to user data, feel free to reopen if issue persist.
