### ISSUE TITLE
Option to edit team information for an "inactive" team

### ISSUE THREAD

**Issue by ayalador** [apigee/apigee-edge-drupal#564]
## Description
We need the option for the user to update information in the EDIT tab.
It was enabled in previous versions. currently we get an error message.

## Steps to Reproduce
Create a new TEAM and update in the APIGEE the status to "inactive"
Go to EDIT tab in the team details.
An error message is displyed.

## Expected Behavior
The user should be able to update information

## Screenshots
![image](https://user-images.githubusercontent.com/63708996/110424103-edf53d80-80aa-11eb-8dee-091c4837b817.png)

## Version Info
Ver 8.X- 1.20

**Comment by phdhiren** [comment]
The change has been made intentional by design - You can more info why it has been disabled from https://github.com/apigee/apigee-edge-drupal/issues/508
