### ISSUE TITLE
Cron job to synchronize Developers from Apigee edge to drupal dev portal

### ISSUE THREAD

**Issue by vchikane** [apigee/apigee-edge-drupal#566]
## Is your feature request related to a problem? Please describe.
Currently, we are adding developers from Apigee edge only (Kind of on-boarding). We are then performing certain custom operations related to monetization from the developer portal. The developer portal is only accessible to admins and some other custom roles that can perform operations for any developer. So basically, the developer can not access the portal right now.
Now, since onboarding is done on Apigee edge, we want to synchronize new developers from edge to drupal portal using the automated job. 

## Describe the solution you would like
I need a cron job that can run at a certain frequency to fetch the new developers from edge to portal

## Describe alternatives you have considered
I was checking cron related modules of drupal but all require accessive coding as far as I understood. If you could suggest a module for this task, well not good. Otherwise, I request you to help me with providing a better solution for this task.

**Comment by phdhiren** [comment]
Hi @vchikane ,

Consider the [documentation](https://www.drupal.org/docs/8/modules/apigee-edge/synchronize-developers-with-apigee-edge)  which explain how you can synchronize the developers.

There is drush and drupal command also available

`$ vendor/bin/drush apigee-edge:sync`

**Comment by vchikane** [comment]
@phdhiren Thanks for the document. Though I have already explored this option of synchronization on the developer portal. But this has to be done manually. What I need is, this should be done automatically at a certain frequency. The reason behind this is, the client will create developers on Apigee edge UI. But a different developer portal user will perform certain activities for that developer. So this developer should be available on the drupal developer portal as well.

Not sure if this feature is already available somehow and I am missing it. Could you please guide me?

**Comment by phdhiren** [comment]
@vchikane ,
It is recommended from documentation to use the Drupal portal to manage app developers instead of using the Apigee Edge UI with reasons.
The developers sync via command line is already there using drush or drupal - this would be automatic option, when set in crontab,

**Comment by vchikane** [comment]
Got it @phdhiren Let me explore this and try. Thanks for the suggestion :)

**Comment by vchikane** [comment]
Got it @phdhiren Let me explore this and try. Thanks for the suggestion :)

**Comment by phdhiren** [comment]
@vchikane , Hope the solution worked for you. Closing the issue, feel free to open if required.

**Comment by vchikane** [comment]
Hi, @phdhiren I actually couldn't find where to add that command. I found that it has to be added in the Cron.php file, but as I am new to the developer portal and PHP. So couldn't figure out how to add it. If you could help, would be great.

**Comment by phdhiren** [comment]
@vchikane, 
Here is the some reference to set the crontab in Linux and can be schedule per your choice.

https://phoenixnap.com/kb/set-up-cron-job-linux

**Comment by vchikane** [comment]
Sorry @phdhiren I didn't understand. Are you saying that I need to setup this cron on a server? Can't it be done on the developer portal itself?

**Comment by phdhiren** [comment]
@vchikane, "Background developer sync" option mentioned in [documentation](https://www.drupal.org/docs/contributed-modules/apigee-edge/synchronize-developers-with-apigee-edge) will allow you sync along with Drupal cron. As you mention, you need the automated job, which will be fulfilled by the drush command.
