### ISSUE TITLE
TypeError: Argument 1 passed to Drupal\apigee_edge\Entity\Developer::setEmail() 

### ISSUE THREAD

**Issue by sivakrishna-yarlagadda** [apigee/apigee-edge-drupal#567]
Please help us on following error.

The website encountered an unexpected error. Please try again later.
TypeError: Argument 1 passed to Drupal\apigee_edge\Entity\Developer::setEmail() must be of the type string, null given, called in /var/www/devportal/web/modules/contrib/apigee_edge/src/UserDeveloperConverter.php on line 107 in Drupal\apigee_edge\Entity\Developer->setEmail() (line 358 of modules/contrib/apigee_edge/src/Entity/Developer.php).

Environment :--

Apigee Drupal 9.2
Ldap Module :-- beta2

**Comment by sivakrishna-yarlagadda** [comment]
Please find below steps to replicate issue

 1)Install Apigee kickstart Drupal 9
 2)Install Ldap module and configure it 
 3)User successfully able to register   in ldap server, we are getting following error message when we try to login from developer portal.

 The website encountered an unexpected error. Please try again later.
 TypeError: Argument 1 passed to Drupal\apigee_edge\Entity\Developer::setEmail() must be of the type string, null given, called in /var/www/devportal/web/modules/contrib/apigee_edge/src/UserDeveloperConverter.php on line 107 in Drupal\apigee_edge\Entity\Developer->setEmail() (line 358 of modules/contrib/apigee_edge/src/Entity/Developer.php)

**Comment by shishir-intelli** [comment]
Hi @sivakrishna-yarlagadda ,

Here it seems that the value of `Email` field is null which is why this error kicked in.

Could you please check are the mapping for fields are configured correctly especially Email  ("`mail`") and then let us know if the issue persists.

**Comment by shishir-intelli** [comment]
Hope this issue has been resolved, 
Closing this ticket for now, feel free to re-open if in case you are still facing any issue.
