### ISSUE TITLE
Callback URL forces http/https

### ISSUE THREAD

**Issue by yenoomluap** [apigee/apigee-edge-drupal#576]
(basically recreating https://github.com/apigee/apigee-devportal-kickstart-drupal/issues/447)

Description
When editing app, it enforces callback url to begin with http or https, if trying to change the regexp pattern to allow .* for example it still forces http/https. Basically a native client will have its own reserved URL scheme and would require to register "myapp://" as their callback.

In addition, if you configure and app in Apigee edge with custom url scheme callback then the module crashes for the user who owns that app once visiting their list of apps in the portal

"Callback URL External site to which an app consumer is redirected to log in when using three-legged OAuth. Valid values must be prefixed with one of the following protocols: http:// or https://"

Steps to Reproduce

Apps> App > Edit > Set callback to myapp:// > Save (does not work)
or
Go to Apigee Edge, create an app with callback url myapp://
Go to Developer portal > Apps > Crash happens
Actual Behavior
Crash/Bug see above

Expected Behavior
Apigee edge module should allow the entry of custom callback URLs.  The ability to onboard native apps using a custom url is an important feature to our customers and is a component of three-legged OAuth with PKCE flow.

Screenshots:
![104913869-8cf49780-598e-11eb-95d9-57912bdd5a2e](https://user-images.githubusercontent.com/8030275/115787374-b8b95c00-a387-11eb-89f0-b3c960c5fbc0.png)

extra:
drupal core only allows a list of accepted protocols for routing found in protocol_filter list in web/stes/default/services.yml (/var/www/html/web/core/lib/Drupal/Core/Utility/UnroutedUrlAssembler.php)?
```
InvalidArgumentException: The URI 'sap://mynativeapp' is invalid. You must use a valid URI scheme. Use base: for a path, e.g., to a Drupal file that needs the base path. Do not use this for internal paths controlled by Drupal. in Drupal\Core\Utility\UnroutedUrlAssembler->assemble() (line 65 of /var/www/html/web/core/lib/Drupal/Core/Utility/UnroutedUrlAssembler.php).
```

**Comment by yenoomluap** [comment]
Temporary workaround.

First step:
add the protocol (ex. sap) to the protocol_filter list at web/sites/default/services.yml

filter_protocols:
  - http
  - https
  - ftp  
  - news  
  - nntp  
  - tel  
  - telnet  
  - mailto  
  - irc  
  - ssh  
  - sftp  
  - webcal  
  - rtsp  
  - sap  

second step:
rebuild the drupal cache (drush cr)

third step:
manually add the redirect uri to the app in edge ui

![add the redirect uri in edge](https://user-images.githubusercontent.com/8030275/115787536-f9b17080-a387-11eb-838f-46ef287a6684.png)

fourth step:
view app in developer portal, app should show updated redirect uri
![updated redirect in portal](https://user-images.githubusercontent.com/8030275/115787686-3715fe00-a388-11eb-98e4-f065938cf674.png)

**Comment by yenoomluap** [comment]
@cnovak what are your thoughts on this?

**Comment by divya-intelli** [comment]
@yenoomluap I tested the temporary workaround as suggested by you, it didn't work for me. Regarding http/https restriction I will let @cnovak respond to it.

**Comment by cnovak** [comment]
Thanks for detailed information @yenoomluap. @divya-intelli are we adding any restrictions on this field ourselves, or is this only Drupal core doing the validation?  We can open our validation requirements, but if this is a Drupal core validation we will not be able to do anything except document the way to fix it using @yenoomluap steps.

We try to keep as close as possible to Drupal best practices as possible. For example, if Drupal has a way to do URL validations, we should use that field/validator and not try to make our own.

**Comment by divya-intelli** [comment]
@cnovak , Drupal core accepts by default 'http and  https' and in devportal we have a configuration page where it validates for http and https to avoid the 'InvalidArgumentException'.
![image](https://user-images.githubusercontent.com/75604843/117924339-34695180-b313-11eb-84b1-8b5ea277abf0.png)

**Comment by cnovak** [comment]
@divya-intelli I am not sure how your comment helps. What are the next steps for this issue?

**Comment by divya-intelli** [comment]
@cnovak  currently for 'callbackurl ' field we are using 'uri_link' field from drupal core .
A solution for this will be to change the field type to 'text' field and have custom validation to allow values from service.yml .

**Comment by giteshk** [comment]
@divya-intelli 

1. Agree with converting the **callbackurl** field to text
2. We should limit the validation of this field to the Pattern field in the callback configuration.
3. Customers should be allowed to change this regex to whatever they want.
4. We should have a validation on the Pattern field to just validate it is a valid regex and not worry about what protocols. Today the regex tests if it starts with `http`. We should remove that validation.

**Comment by yenoomluap** [comment]
Bump - this is still a major issue.  Considering its importance, hopefully this can move to in progress.

**Comment by giteshk** [comment]
@yenoomluap we will add this to our board to track.

**Comment by yenoomluap** [comment]
bump
________________________________
