### ISSUE TITLE
Apigee Edge is not rendering in Drupal 9.1.7 with Golden AMI

### ISSUE THREAD

**Issue by jyotierudkar** [apigee/apigee-edge-drupal#582]

**Comment by phdhiren** [comment]
@jyotierudkar 
Can you share error log around that?

You can checkout the [installation instruction from the documentation](https://www.drupal.org/docs/contributed-modules/apigee-edge) and install module using composer

**Comment by phdhiren** [comment]
@jyotierudkar  I will close this issue for now, but if you need further assistance regarding this, please feel free to reopen it.
