### ISSUE TITLE
Disable user/developer deletion in Apigee from drupal

### ISSUE THREAD

**Issue by lalit774** [apigee/apigee-edge-drupal#584]
## Is your feature request related to a problem? Please describe.
- As per our business requirement, we usually do not delete a user from apigee. we are suing employee id as a username in drupal. sometime, employee id is changed due to moving the departments. so our user are getting the problem for login. We delete the users in drupal and resync with apigee. so we will get new user id. But when we delete users from drupal. It will delete the user and data from apigee too. so we loose the data.
- We have dev/qa servers too, so don't want to delete data from Apigee. 

## Describe the solution you would like
- There should be a configuration for "disable delete from apigee" in developer settings in APIgee Edge module. Based on that, deletion should trigger.

## Describe alternatives you have considered
- There should be a 4th option "when cancelling a user account"
   Delete the account and content from drupal only.

## Additional context 
Temporary I just remove the apigee_edge_user_delete. Please suggest me, if there is any way to overwrite this hook.

**Comment by divya-intelli** [comment]
Hi @lalit774, As per the scenario that you have mentioned , doing developer sync will update the user in Drupal portal with the changes done in Apigee edge. [Synchronize developers with Apigee Edge](https://www.drupal.org/docs/contributed-modules/apigee-edge/synchronize-developers-with-apigee-edge) has detailed explanation on how the sync works.
