### ISSUE TITLE
Forbidden error when I click on "My Apps" section in Drupal 8 portal

### ISSUE THREAD

**Issue by navodit07** [apigee/apigee-edge-drupal#585]
## Description

I was able to successfully make the connection with Apigee edge and the Drupal 8 portal.  When I click the "My App" under the user account. Then I am getting a Forbidden error while I am viewing the Apps. However, I am able to access the edit screen and also getting all relevant data with is associated with the App. 

## Steps to Reproduce
1. Login with the user account. 
2. Click on "My app" under the user account 
3. Under "My app" page there will be a list of apps and when click on view app then its giving Forbidden error.

## Actual Behavior

 Login user is not able to view the App as its giving Forbidden error. However, Edit screen pull up correct data from Apigee portal to Drupal   

## Expected Behavior

When the user will be login they should be able to view apps content under the "view" screen.

## Screenshots
 
![image](https://user-images.githubusercontent.com/84181674/118272120-c58d2380-b4df-11eb-8681-ceea06b3f8b9.png)
![image](https://user-images.githubusercontent.com/84181674/118272033-a8585500-b4df-11eb-914a-408d3dd8ac7d.png)
![image](https://user-images.githubusercontent.com/84181674/118272384-27e62400-b4e0-11eb-8765-d8c9e1fadf81.png)

**Comment by divya-intelli** [comment]
@navodit07 can you enable 'Apigee Edge Debug' module and pull out the API call/responses that happen after replicating issue, we can see why this issue is happening. If there is any sensitive info, you can modify/sanitize it before posting it.

**Comment by navodit07** [comment]
@divya-intelli  Thanks for your response. Please refer attached screenshot for 'Apigee Edge Debug'. 
![apigee-debug](https://user-images.githubusercontent.com/84181674/118285484-1e17ed00-b4ef-11eb-8778-1bf0cbc53692.png)

**Comment by divya-intelli** [comment]
@navodit07,  can you provide/check the below points.

1.Is there any custom module enabled at the time of this error?
2. Can you give us the version number for 'apigee-edge-drupal', 'apigee-client-php', 'apigee_devportal_kickstart'.
3. Can you share all debug logs with us? Here is the documentation on how to get the [debug log and remove credentials](https://www.drupal.org/docs/8/modules/apigee-edge/monitor-apigee-edge-debug-logs#configure). Mark @cnovak in the email as well.
4.Also let us know which 'Apigee instance type' your using.This can be found in '/admin/config/apigee-edge/settings'

**Comment by navodit07** [comment]
@divya-intelli  @cnovak 

Please find my comment on mentioned points.

1. Yes, But I have uninstalled all custom modules after checking that it's still giving the same error.  
2. 'apigee-edge-drupal' is running with 8.x-1.22 version. 'apigee-client-php', 'apigee_devportal_kickstart' modules are not installed in the system as Apigee Edge successfully connected with the Drupal portal and we are getting this forbidden error only for few users. Apart from that, it's working as expected. 
3. Attached debug logs as pdfs.
4. 'Apigee instance type' -  Apigee Edge (Endpoint: https://api.enterprise.apigee.com/v1).



[bug-apigee-2.pdf](https://github.com/apigee/apigee-edge-drupal/files/6493479/bug-apigee-2.pdf)
[bug-apigee-1.pdf](https://github.com/apigee/apigee-edge-drupal/files/6493480/bug-apigee-1.pdf)
[bug-apigee.pdf](https://github.com/apigee/apigee-edge-drupal/files/6493481/bug-apigee.pdf)

**Comment by phdhiren** [comment]
@navodit07 ,
Can you confirm apigee_edge_teams module is enabled and really required or not? if not require, uninstall and check.
Further to that can you check with Apigee support that why the api `/companies?expand=true` is throwing 403 Forbidden error?

**Comment by navodit07** [comment]
@phdhiren @divya-intelli , Thanks for your help. 

The apigee_edge_teams module enabled and I have uninstalled the module then the forbidden error got fixed. But I wanted to know that how we can make work both modules together. We might need to install the apigee_edge_teams in the future. Please refer to the attached screenshot In which you can see what permission I have given in the Apigee portal. is there any need to change the permission to work the apigee_edge_teams module along with API edge?

![apigee-portal-permission](https://user-images.githubusercontent.com/84181674/118701578-7de4ff80-b831-11eb-860d-34eb8655560c.jpg)

**Comment by phdhiren** [comment]
Hi @navodit07 ,

Please checkout documentation of [creating custom apigee role](https://www.drupal.org/docs/contributed-modules/apigee-edge/configure-the-connection-to-apigee#create-custom-apigee-role), this should allow the user to access `/companies` api.

**Comment by phdhiren** [comment]
@navodit07 
I hope your issue has been resolved with above documentation.

**Comment by navodit07** [comment]
@phdhiren 

Thanks for you help to resolve this issue.

I am following above mentioned document to get resolve the issue for teams module which need to work together with Apigee edge.

**Comment by phdhiren** [comment]
Thanks for confirming, closing the issue.
