### ISSUE TITLE
Developer Portal Fails to recognize Apigee Registered Developers

### ISSUE THREAD

**Issue by pandatrooper** [apigee/apigee-edge-drupal#586]
We have two Developer Portals [ I'll be addressing them `DP1` and `DP2` hereafter ] which are connected to the same Edge Environment.

**Scenario**

- The developer `X` does not exist on Apigee Edge. This user has never accessed either `DP1` or `DP2`. 
- This new user `X` logs into `DP1` for the first time, therefore, a new user profile `X` is created in `DP1` as well the user `X` is registered as a Developer in Edge.  
-  Now, user `X` heads to `DP2` and tries to login for the first time in `DP2`. Since `DP2` treats `X` as a new user, `DP2` tries to register a new developer profile in Edge. `X` already exists in Edge, however Drupal does not know that the developer is in Edge.
- Instead of syncing with 'X' developer profile, `DP2` is throwing the following error:

`§ TypeError: Argument 1 passed to Drupal\apigee_edge\Entity\Developer::setFirstName() must be of the type string, null given, called in /var/www/html/devportal/web/modules/contrib/apigee_edge/src/UserDeveloperConverter.php on line 107 in Drupal\apigee_edge\Entity\Developer->setFirstName() `
						
**Issues with Existing Solutions**

The `developer sync` cron job in `DP2` would regularly create Drupal accounts for all those Edge Developers unavailable in `DP2`. However, only a small amount of those synced users access the portal. A large number of users would never access the portal in their lifetime. 

**Possible Solutions**

If a developer exists in Edge, the developer profile should be automatically detected and synced by Developer Portal when the user tries to login to the developer portal for the first time.

**Comment by shishir-intelli** [comment]
Hi @pandatrooper 

In the above scenario, you need to do `developer sync` in `DP2` so that all the users in same org gets imported in your `DP2` instance. (This will also include the `DP1` users).  Refer developer sync document - [here](https://www.drupal.org/docs/contributed-modules/apigee-edge/synchronize-developers-with-apigee-edge) 
Once this is done the X user who registered on `DP1` will able to directly login with same credentials. Drupal dev-portal will not automatically sync while user tries to registered who already exists in `Edge` and `DP1`

Also I was not able to reproduce this error - Can you please share me the steps to reproduce this error.
`§ TypeError: Argument 1 passed to Drupal\apigee_edge\Entity\Developer::setFirstName() must be of the type string, null given, called in /var/www/html/devportal/web/modules/contrib/apigee_edge/src/UserDeveloperConverter.php on line 107 in Drupal\apigee_edge\Entity\Developer->setFirstName()`

**Comment by pandatrooper** [comment]
Hi @shishir-intelli

Thanks for the info.

I am aware that the `developer sync` cron job can be enabled to regularly synchronize users between Edge and Drupal. 

However the issue with that is, if there are 1000 developers who are registered on Edge through `DP1`, only a 100 of them would actually access `DP2` ( and vice versa ). 

Therefore, if I run a `developer sync` on `DP2`, Drupal would create 1000 user profiles based on Edge.  So, if 100 odd people access `DP2`, other 900 other user profiles would remain a dummy account forever. 

As far as replication of the error is concerned, we use Single Sign On for authorization of users. But the same issue exists for Google Social Auth module as well ( refer #315 ).  So whenever a user logs in using SSO, their First Name, Last Name, Email Id and employee ID is passed to Drupal. If the user's account exists, well and good. However, If it does not exist in Drupal, it tries to create a new user in Edge as a new developer. However, if the developer already exists during this process, this error kicks in.

**Comment by shishir-intelli** [comment]
@pandatrooper,

Thanks for the detail information,
For registering a developer who already exists in Apigee Edge and not in Drupal, you have this 2 options as of now.
1. **As an Admin** - If you create an account for a developer on `DP2` using the same email address as registered on Edge, you will get an option with a checkbox (see screenshot) that allows you to still go ahead and create the user account. 
![image](https://user-images.githubusercontent.com/75600200/120809447-ae35d900-c567-11eb-9408-1edd9500ecbb.png)

2. **As a Developer** - If a developer goes to `DP2` and registers for an account, they will get an email to verify that they want to continue creating an account despite having an account on edge(see screenshot) . Once they click on the verification link received on there email ID they need to again enter the user details and can create an account.
![image](https://user-images.githubusercontent.com/75600200/120808849-1d5efd80-c567-11eb-9132-bc2446b237ea.png)

_`Example of verification link `"https://YOUR-SITE/user/register?developer-verification-token=[###]&timestamp=1622782569"``_


For the Single Sign On for authorization of users issue which you have mentioned, we are working on it and will soon update you.

**Comment by pandatrooper** [comment]
Hi @shishir-intelli 

Thanks a lot for the information.

I'm afraid, we don't manually create or modify any information for users through UI unless and until we face the error that I mentioned above. We rely on parameters provided by Single Sign On entirely. For some strange reason, in case of the above error, when Edge refuses to create the developer, Drupal creates a dummy user with just one data field i.e the unique ID alone while rest of the fields remains empty. So in order to convert that dummy account to a legitimate account, we are forced to manually fill all other parameters through UI [ which defeats the purpose of SSO ].

With that being said, really appreciate your help. Please let me know if you have any success on Single Sign On.

**Comment by shishir-intelli** [comment]
Hi @pandatrooper ,

I have created a PR for this issue #592. 

I hope this will resolve your issue.
