### ISSUE TITLE
some API products aren't displayed while app creation

### ISSUE THREAD

**Issue by RimonTawadrous** [apigee/apigee-edge-drupal#589]
## Description
hello, my issue that not all the API products are shown in the app creation form even for admin. some API products are displayed and others are not. I investigated the API products that are not shown and found no difference between them and the shown ones. also removed the RBAC module and issue still the same, made all users can access all API products and still facing the same problem. Also the API product storage have all the APIs i printed them. so i think it is permission problem. 

## Steps to Reproduce
unfortunately i don't know we have 31 API products 23 API product displayed.

## Expected Behavior
Expect to show all the API products that the user can view according to its role.
![1](https://user-images.githubusercontent.com/35565654/121018369-a3b15480-c79e-11eb-80e5-54eef8df6d26.jpg)

## Screenshots
![some API products from apigee edge. some of them aren't displayed](https://user-images.githubusercontent.com/35565654/121018698-030f6480-c79f-11eb-8d88-b62c9888e52a.jpg)
![all the displayed API products in apigee edge](https://user-images.githubusercontent.com/35565654/121018701-060a5500-c79f-11eb-9356-c20a81e13907.jpg)

## Notes
Add any other ; about the problem here.

## Version Info
8.x-1.16

**Comment by phdhiren** [comment]
@RimonAdel 
Can you enable 'Apigee Edge Debug' module and share all debug logs with us? Here is the documentation on how to get the [debug log and remove credentials](https://www.drupal.org/docs/8/modules/apigee-edge/monitor-apigee-edge-debug-logs#configure).

**Comment by RimonTawadrous** [comment]
Hello @phdhiren 
thank you for your replay. here are the logs
[logs.txt](https://github.com/apigee/apigee-edge-drupal/files/6621994/logs.txt)

**Comment by RimonTawadrous** [comment]
** comment removed **
