### ISSUE TITLE
Exception while generating an URL to confirm identity of a user with existing developer mail

### ISSUE THREAD

**Issue by heykarthikwithu** [apigee/apigee-edge-drupal#590]
While generating an URL to confirm identity of a user with existing developer mail. An exception like the below is seen.
`Symfony\Component\Routing\Exception\InvalidParameterException: Parameter "user" for route "entity.user.edit_form" must match "\d+" ("" given) to generate a corresponding URL. in Drupal\Core\Routing\UrlGenerator->doGenerate() (line 204 of core/lib/Drupal/Core/Routing/UrlGenerator.php).`

This happens when the developer exists on Apigee but doesn't exist on Portal.

here are the screenshots of the failure
![Screenshot from 2021-06-08 14-25-31](https://user-images.githubusercontent.com/7745441/121167445-91531b80-c86f-11eb-83b1-3b4cd64045f5.png)
![screenshot-developer-globe local_8082-2021 06 08-15_37_59](https://user-images.githubusercontent.com/7745441/121167479-97e19300-c86f-11eb-96b8-779d4a9bf24c.png)

**Comment by raakesh-blokhra** [comment]
Hi @heykarthikwithu , Can you run the developer sync once to synchronize the users on edge and portal?
Please do the above and if you are still running into the error, send us steps to reproduce it and we'll be able to look into it further. Thanks

**Comment by heykarthikwithu** [comment]
`when the developer exists on Apigee but doesn't exist on Portal`
This case is not reproducible in the case of developer sync, But reproducible during the registration. 

Ideally, this exception should not happen while triggering notification on registration.

**Comment by phdhiren** [comment]
@heykarthikwithu 

Ideally when setup the Developer portal first time that the developer sync should be triggered
Consider [documentation](https://www.drupal.org/docs/contributed-modules/apigee-edge/synchronize-developers-with-apigee-edge)

> After the initial configuration, we recommend that you use the user administration features of the Drupal developer portal site to manage app developers instead of using the Apigee UI

Above is the ideal workflow, please advise to use Developer portal instead of Apigee UI for developer.

**Comment by heykarthikwithu** [comment]
@phdhiren Yes, agree with this and this is the ideal way to use the developer portal & apigee (and also this raised issue will not be seen)

But the case in which I raised this issue.. should have a handled expectation instead of an unhandled exception. right?
