### ISSUE TITLE
Cannot view teams/<guid>/members

### ISSUE THREAD

**Issue by yenoomluap** [apigee/apigee-edge-drupal#591]
## Description
After updating to 1.23, we can no longer view teams/_guid_/members

## Steps to Reproduce
go to site/teams/_guid_/members

## Actual Behavior
Receive message:
The website encountered an unexpected error. Please try again later.

Log Message:
```
TypeError: Return value of Drupal\apigee_edge_teams\CompanyMembersController::getMembers() must be an instance of Apigee\Edge\Api\Management\Structure\CompanyMembership, null returned in Drupal\apigee_edge_teams\CompanyMembersController->getMembers() (line 97 of /var/www/html/web/modules/contrib/apigee_edge/modules/apigee_edge_teams/src/CompanyMembersController.php)
#0 /var/www/html/web/modules/contrib/apigee_edge/modules/apigee_edge_teams/src/TeamMembershipManager.php(113): Drupal\apigee_edge_teams\CompanyMembersController->getMembers()
#1 /var/www/html/web/modules/contrib/apigee_edge/modules/apigee_edge_teams/src/Controller/TeamMembersList.php(112): Drupal\apigee_edge_teams\TeamMembershipManager->getMembers('cec7e5c8_d8cb_4...')
#2 [internal function]: Drupal\apigee_edge_teams\Controller\TeamMembersList->overview(Object(Drupal\apigee_edge_teams\Entity\Team))
#3 /var/www/html/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array)
#4 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(573): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#5 /var/www/html/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure))
#6 /var/www/html/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array)
#7 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(151): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#8 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#9 /var/www/html/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#10 /var/www/html/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#11 /var/www/html/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#12 /var/www/html/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#13 /var/www/html/vendor/asm89/stack-cors/src/Asm89/Stack/Cors.php(49): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#14 /var/www/html/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Asm89\Stack\Cors->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#15 /var/www/html/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#16 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#17 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(708): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#18 /var/www/html/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#19 {main}
```

## Expected Behavior
I expect to see team members view

## Screenshots
![members-view](https://user-images.githubusercontent.com/8030275/121571829-1a419280-c9e9-11eb-9225-83e5355125d3.png)

## Notes
If we remove this piece of code, we can view the membership page:

![remove-code](https://user-images.githubusercontent.com/8030275/121572088-668cd280-c9e9-11eb-8f8e-919868b97822.png)

## Version Info
1.23

## Request
Please assist so we may view team memberships.

**Comment by phdhiren** [comment]
@yenoomluap 
Can you help me with caching timeout which has been set in the path `/admin/config/apigee-edge/team-settings/caching`?  Can you invalidate earlier cache, if any.

**Comment by yenoomluap** [comment]
@phdhiren 
Invalidate earlier cache had no effect.
We changed the value of caching from 0 to 1, and I'm able to view the members.  
Can you explain a little more about this caching and also the -1 configuration for it?

**Comment by phdhiren** [comment]
@yenoomluap 

Yes that is allowed. The value 0 is also allowed you can change that back, as per your need.

You can consider [Configure caching](https://www.drupal.org/docs/8/modules/apigee-edge/configure-caching) section from the documentation.

**Comment by yenoomluap** [comment]
@phdhiren If we set the value back to 0, we return to previous issue of not able to view members.  Are you able to recreate?  The value 0 is not allowed for us.

**Comment by phdhiren** [comment]
@yenoomluap 
I'm not able to recreate above issue with the value 0.
Reopening the issue for you, Can you help with apigee edge debug log, you can share it over email.

**Comment by phdhiren** [comment]
@yenoomluap

I've checked the shared debug log, but those are different for positive and negative case. Do you have any specific observation other then cache settings?

**Comment by yenoomluap** [comment]
@phdhiren Thank you for checking debug log.  The team cache setting is the only item we found which creates the error (when value is 0).  We have also found that it does not affect viewing team membership altogether.  Some team memberships can viewed, while others cannot.

**Comment by phdhiren** [comment]
@yenoomluap We have not been able to replicate the issue on our end despite making the cache setting changes as you specified. I will close this issue for now, but if you need further assistance regarding this, please feel free to reopen it.

**Comment by inbalj** [comment]
Hi there,
I have encountered the same problem with D9 installation. I didn't understand how was it fixed.
I would appreciate an explanation.
