### ISSUE TITLE
App credentials not visible in application details

### ISSUE THREAD

**Issue by vjmatl** [apigee/apigee-edge-drupal#596]
## Description
See below screenshot the App credentials is not visible and it doesnt get copied when clicking on copy button. 

Checking if anyone had seen this issue.

## Screenshots
![app_creds](https://user-images.githubusercontent.com/86080241/122467804-f81bb780-cf88-11eb-9529-3fdd31c22bb7.png)

## Version Info:
     Drupal version: 8.9.2
    "apigee/apigee_devportal_kickstart": "^1.17",
    "drupal/apigee_api_catalog": "2.5",
    "drupal/apigee_edge": "1.21.0",
    "drupal/apigee_m10n": "1.6",

**Comment by phdhiren** [comment]
@vjmatl 

Can you confirm if there are no custom theme/module alter is there? As with above version I'm not able to replicate issue. Specifically around apigee-secret.html.twig or theme_preprocess_app_credential

Also you can share all debug logs with us via Apigee support ticket? Here is the documentation on how to get the [debug log and remove credentials](https://www.drupal.org/docs/8/modules/apigee-edge/monitor-apigee-edge-debug-logs#configure).

**Comment by phdhiren** [comment]
@vjmatl
I hope above have helped. Closing this issue for now, but if you need further assistance regarding this, please feel free to reopen it.
