### ISSUE TITLE
Error: Call to undefined method Drupal\apigee_edge\KeyEntityFormEnhancer::config() when failed to connect to Apigee.

### ISSUE THREAD

**Issue by VladimirAus** [apigee/apigee-edge-drupal#601]
## Description
When connection fails, some configuration options are access in incorrect way cause PHP error below

```
Error: Call to undefined method Drupal\apigee_edge\KeyEntityFormEnhancer::config() in Drupal\apigee_edge\KeyEntityFormEnhancer->createSuggestion() (line 580 of /app/web/modules/contrib/apigee_edge/src/KeyEntityFormEnhancer.php)

#0 /app/web/modules/contrib/apigee_edge/src/KeyEntityFormEnhancer.php(355): Drupal\apigee_edge\KeyEntityFormEnhancer->createSuggestion(Object(Apigee\Edge\Exception\ApiRequestException), Object(Drupal\key\Entity\Key)) 

#1 [internal function]: Drupal\apigee_edge\KeyEntityFormEnhancer->validateForm(Array, Object(Drupal\Core\Form\FormState)) 

#2 /app/web/core/lib/Drupal/Core/Form/FormValidator.php(82): call_user_func_array(Array, Array) 

#3 /app/web/core/lib/Drupal/Core/Form/FormValidator.php(273): Drupal\Core\Form\FormValidator->executeValidateHandlers(Array, Object(Drupal\Core\Form\FormState)) 

#4 /app/web/core/lib/Drupal/Core/Form/FormValidator.php(118): Drupal\Core\Form\FormValidator->doValidateForm(Array, Object(Drupal\Core\Form\FormState), 'apigee_edge_aut...') 

#5 /app/web/core/lib/Drupal/Core/Form/FormBuilder.php(589): Drupal\Core\Form\FormValidator->validateForm('apigee_edge_aut...', Array, Object(Drupal\Core\Form\FormState)) 

#6 /app/web/core/lib/Drupal/Core/Form/FormBuilder.php(321): Drupal\Core\Form\FormBuilder->processForm('apigee_edge_aut...', Array, Object(Drupal\Core\Form\FormState)) 

#7 /app/web/core/lib/Drupal/Core/Controller/FormController.php(73): Drupal\Core\Form\FormBuilder->buildForm(Object(Drupal\apigee_edge\Form\AuthenticationForm), Object(Drupal\Core\Form\FormState))

...
```

## Steps to Reproduce
1. Install module, setup Apigee connection as environmental variables (insert incorrect credentials).
2. Go to Authentication page [`/admin/config/apigee-edge/settings`]
3. Select `Advanced settings`, select `Apigee Edge: Environment Variables` as `Key Porvider`
4. Click `Send Request`, go to `Reports` > `Recent log messages`

## Actual Behavior
Above error.

## Expected Behavior
Error should be handled gracefully and get correct config.

## Screenshots
![apigee-connect](https://user-images.githubusercontent.com/1356166/124589239-1b0cfd80-de9d-11eb-9c6b-5b8e34092a74.png)

## Version Info
* Drupal 9.2.0
* Apigee Edge 1.23

**Comment by shishir-intelli** [comment]
Hi @VladimirAus 

I followed the same steps mentioned here, 
I was not able to replicate this issue, when I clicked `Send Request` with incorrect credentials in Environment-variable I was able to see this
![Screenshot 2021-07-07 8 11 25 PM](https://user-images.githubusercontent.com/75600200/124779673-98994200-df5f-11eb-84a3-11838d9385df.png)

**Comment by shishir-intelli** [comment]
@VladimirAus,
Closing this issue for now,
Please feel free to reopen, if in case you are still facing any issue.
