### ISSUE TITLE
basic auth support

### ISSUE THREAD

**Issue by acobat** [apigee/apigee-edge-drupal#608]
Hi,

We are aware that Basic Auth for Apigee Management API's (Onprem) is deprecated, yet, still available on latest apigee plugin and Drupal 9.x. 

What is the dead line where you will remove the option to work with Basic in UI UX level? 

Thanks,

**Comment by raakesh-blokhra** [comment]
Hi @acobat I have assigned this to Gitesh, he will be able to get us a date.

**Comment by acobat** [comment]
@raakesh-blokhra hi, any update on this?

**Comment by giteshk** [comment]
@acobat I checked with the team we don't have any plans to remove Basic Auth support from the Apigee Drupal module.

I was told we introduced support for OAuth authentication for management APIs from 7.51  but there was no mention of removing Basic Auth support at the moment for OPDK.

I will post back updates when this happens. For now you should feel comfortable using Basic Auth for calling MGMT APIs for OPDK.

**Comment by acobat** [comment]
Thanks, 
but still, this message is confusing
![image](https://user-images.githubusercontent.com/5484385/127894079-4de17227-478b-4bee-b6e0-79d5ba6d9437.png)

So please either remove it or state that this is supported :)
