### ISSUE TITLE
Critical error when receiving analytics

### ISSUE THREAD

**Issue by maxim8898** [apigee/apigee-edge-drupal#612]
## Description
The site crashes with the message "The website encountered an unexpected error. Please try again later." when trying to get app analytics.

## Steps to Reproduce
1. Go to analytics page (/user/682/apps/App_Test_Analytics/analytics)
2. Select a long period (From: 2 month ago)
3. Click on "Apply"

## Actual Behavior
ERROR: The website encountered an unexpected error. Please try again later.

## Expected Behavior
Analytics is displayed

## Screenshots
<img width="1336" alt="image" src="https://user-images.githubusercontent.com/20277024/128507604-73dafaef-db7d-41f9-868b-43c80df95436.png">

## Notes
In the process of debug, I found a weak point: 
vendor/apigee/apigee-client-php/src/Api/Management/Controller/StatsController.php:285
`$metricsData[$key]['values'] = array_combine($originalTimeUnits, $metric['values']);`
It's trying to combine arrays with different size (see screenshot)
<img width="852" alt="image" src="https://user-images.githubusercontent.com/20277024/128508034-ce5a80fd-8fd0-4230-8bb5-b8ae8a246633.png">

I tried this code to fix the problem:
<img width="980" alt="image" src="https://user-images.githubusercontent.com/20277024/128508773-fba077d1-eb76-4e07-85ca-ed19658da8e7.png">
I'm using array_walk instead of array_merge

I see update in apigee_edge module regarding "apigee/apigee-client-php" (commit: https://git.drupalcode.org/project/apigee_edge/-/commit/1e16a4c6598d0a679a3e8cd1e0250351e48ca92d)
Maybe that's a reason.
## Version Info
Drupal core 9.2.1
Apigee Edge 8.x-1.23

**Comment by maxim8898** [comment]
Note: this is not a regular error, it is reproduced on some combinations of filters, for example, for the Message Count filter it works well

**Comment by phdhiren** [comment]
Can you share PHP and apigee-client-php version along with other Apigee related module's version?

**Comment by maxim8898** [comment]
@phdhiren Please see all information about installed modules:


alchemy/zippy                            0.4.9        Zippy, the archive manager companion
apigee/apigee-client-php                 2.0.6        Client library for connecting to the Apigee Edge API.
apigee/apigee_devportal_kickstart        1.23         A fast demo and starting point for Apigee Developer Portals.
asm89/stack-cors                         1.3.0        Cross-origin resource sharing library and stack middleware
behat/mink                               v1.8.1       Browser controller/emulator abstraction for PHP
behat/mink-goutte-driver                 v1.2.1       Goutte driver for Mink framework
behat/mink-selenium2-driver              v1.4.0       Selenium2 (WebDriver) driver for Mink framework
chi-teck/drupal-code-generator           1.33.1       Drupal code generator
clue/stream-filter                       v1.5.0       A simple and modern approach to stream filtering in PHP
commerceguys/addressing                  v1.2.1       Addressing library powered by CLDR and Google's address data.
commerceguys/intl                        v1.1.0       Internationalization library powered by CLDR data.
composer/ca-bundle                       1.2.10       Lets you find a path to the system CA bundle, and includes a fallback to the Mozilla CA bundle.
composer/composer                        2.1.3        Composer helps you declare, manage and install dependencies of PHP projects. It ensures you have the right stack ...
composer/installers                      v1.11.0      A multi-framework Composer library installer
composer/metadata-minifier               1.0.0        Small utility library that handles metadata minification and expansion.
composer/semver                          3.2.5        Semver library that offers utilities, version constraint parsing and validation.
composer/spdx-licenses                   1.5.5        SPDX licenses list and validation library.
composer/xdebug-handler                  2.0.1        Restarts a process without Xdebug.
consolidation/annotated-command          4.2.4        Initialize Symfony Console commands from annotated command class methods.
consolidation/config                     1.2.1        Provide configuration services for a commandline tool.
consolidation/filter-via-dot-access-data 1.0.0        This project uses dflydev/dot-access-data to provide simple output filtering for applications built with annotate...
consolidation/log                        2.0.2        Improved Psr-3 / Psr\Log logger based on Symfony Console components.
consolidation/output-formatters          4.1.2        Format text by applying transformations provided by plug-in formatters.
consolidation/robo                       2.2.2        Modern task runner
consolidation/self-update                1.2.0        Provides a self:update command for Symfony Console applications.
consolidation/site-alias                 3.1.0        Manage alias records for local and remote sites.
consolidation/site-process               4.1.0        A thin wrapper around the Symfony Process Component that allows applications to use the Site Alias library to spe...
container-interop/container-interop      1.2.0        Promoting the interoperability of container objects (DIC, SL, etc.)
cweagans/composer-patches                1.7.1        Provides a way to patch Composer packages.
defuse/php-encryption                    v2.3.1       Secure PHP Encryption Library
dflydev/dot-access-configuration         v1.0.3       Given a deep data structure representing a configuration, access configuration by dot notation.
dflydev/dot-access-data                  v1.1.0       Given a deep data structure, access data by dot notation.
dflydev/placeholder-resolver             v1.0.2       Given a data source representing key => value pairs, resolve placeholders like ${foo.bar} to the value associated...
doctrine/annotations                     1.13.1       Docblock Annotations Parser
doctrine/collections                     1.6.7        PHP Doctrine Collections library that adds additional functionality on top of PHP arrays.
doctrine/instantiator                    1.4.0        A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                           1.2.1        PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Parsers.
doctrine/reflection                      1.2.2        The Doctrine Reflection project is a simple library used by the various Doctrine projects which adds some additio...
drupal/address                           1.9.0        Provides functionality for storing, validating and displaying international postal addresses.
drupal/admin_toolbar                     2.4.0        Provides a drop-down menu interface to the core Drupal Toolbar.
drupal/adminimal_admin_toolbar           1.11.0       Adminimal styling brought to admin toolbar.
drupal/adminimal_theme                   1.6.0        Drupal administration theme with modern minimalist design.
drupal/apigee_api_catalog                2.5.0        Apigee API Catalog for Drupal
drupal/apigee_edge                       1.23.0       Apigee Edge for Drupal.
drupal/apigee_m10n                       1.8.0        Apigee Edge Monetization for Drupal
drupal/better_exposed_filters            5.0.0-beta3  Replaces the Views default single- or multi-select boxes with more advanced options.
drupal/coder                             8.3.13       Coder is a library to review Drupal code.
drupal/commerce                          2.25.0       Drupal Commerce is a flexible eCommerce solution.
drupal/components                        2.4.0        Registers folders of components defined by your theme or module as Twig namespaces
drupal/console                           1.9.7        The Drupal CLI. A tool to generate boilerplate code, interact with and debug Drupal.
drupal/console-core                      1.9.7        Drupal Console Core
drupal/console-en                        v1.9.7       Drupal Console English Language
drupal/console-extend-plugin             0.9.5        Drupal Console Extend Plugin
drupal/consumers                         1.11.0       Declare all the consumers of your API
drupal/core                              9.2.1        Drupal is an open source content management platform powering millions of websites and applications.
drupal/core-dev                          9.2.1        require-dev dependencies from drupal/drupal; use in addition to drupal/core-recommended to run tests from drupal/...
drupal/core-recommended                  9.2.1        Locked core dependencies; require this project INSTEAD OF drupal/core.
drupal/ctools                            3.7.0        Provides a number of utility and helper APIs for Drupal developers and site builders.
drupal/default_content                   1.0.0-alpha9 Imports default content when a module is enabled
drupal/email_registration                1.1.0        Allows users to register with an email address as their username.
drupal/entity                            1.2.0        Provides expanded entity APIs, which will be moved to Drupal core one day.
drupal/entity_reference_revisions        1.9.0        Entity Reference Revisions
drupal/file_link                         2.0.6        Extends the core Link module by storing metadata about the target file.
drupal/fontawesome                       2.19.0       The web's most popular icon set and toolkit.
drupal/inline_entity_form                1.0.0-rc9    Provides a widget for inline management (creation, modification, removal) of referenced entities.
drupal/jquery_ui                         1.4.0        Provides jQuery UI library.
drupal/jquery_ui_datepicker              1.1.0        Provides jQuery UI Datepicker library.
drupal/jquery_ui_slider                  1.1.0        Provides jQuery UI Slider library.
drupal/jquery_ui_touch_punch             1.0.0        Provides jQuery UI Touch Punch library.
drupal/key                               1.14.0       Provides the ability to manage site-wide keys
drupal/metatag                           1.16.0       Manage meta tags for all entities.
drupal/paragraphs                        1.12.0       Enables the creation of Paragraphs entities.
drupal/pathauto                          1.8.0        Provides a mechanism for modules to automatically generate aliases for the content they manage.
drupal/profile                           1.2.0        Provides configurable user profiles.
drupal/radix                             4.10.0       Radix is a base theme for Drupal. It has Bootstrap, Sass, BrowserSync and Font Awesome built-in.
drupal/redirect                          1.6.0        Allows users to redirect from old URLs to new URLs.
drupal/redis                             1.5.0        Integration of Drupal with the Redis key-value store.
drupal/requirement                       1.1.0        A Drupal module to that gives modules a way to declare configuration requirement and suggestions.
drupal/restui                            1.20.0       Provides a user interface to manage REST resources.
drupal/simple_oauth                      4.5.0        The Simple OAuth module for Drupal
drupal/simple_sitemap                    3.10.0       Creates a standard conform hreflang XML sitemap of the site content and provides a framework for developing other...
drupal/sitemap                           2.0.0-beta1  Display a sitemap.
drupal/state_machine                     1.4.0        Provides code-driven workflow functionality.
drupal/token                             1.9.0        Provides a user interface for the Token API, some missing core tokens.
drush/drush                              10.5.0       Drush is a command line shell and scripting interface for Drupal, a veritable Swiss Army knife designed to make l...
easyrdf/easyrdf                          1.1.1        EasyRdf is a PHP library designed to make it easy to consume and produce RDF.
egulias/email-validator                  2.1.25       A library for validating emails against several RFCs
enlightn/security-checker                v1.9.0       A PHP dependency vulnerabilities scanner based on the Security Advisories Database.
fabpot/goutte                            v3.3.1       A simple PHP Web Scraper
fightbulc/moment                         1.33.0       Parse, validate, manipulate, and display dates in PHP w/ i18n support. Inspired by moment.js
firebase/php-jwt                         v5.4.0       A simple library to encode and decode JSON Web Tokens (JWT) in PHP. Should conform to the current spec.
friends-of-behat/mink-browserkit-driver  v1.5.0       Symfony2 BrowserKit driver for Mink framework
grasmash/expander                        1.0.0        Expands internal property references in PHP arrays file.
grasmash/yaml-expander                   1.4.0        Expands internal property references in a yaml file.
guzzlehttp/guzzle                        6.5.5        Guzzle is a PHP HTTP client library
guzzlehttp/promises                      1.4.1        Guzzle promises library
guzzlehttp/psr7                          1.8.2        PSR-7 message implementation that also provides common utility methods
instaclick/php-webdriver                 1.4.9        PHP WebDriver for Selenium 2
justinrainbow/json-schema                5.2.10       A library to validate a json schema.
laminas/laminas-diactoros                2.6.0        PSR HTTP Message implementations
laminas/laminas-escaper                  2.7.0        Securely and safely escape HTML, HTML attributes, JavaScript, CSS, and URLs
laminas/laminas-feed                     2.14.1       provides functionality for consuming RSS and Atom feeds
laminas/laminas-stdlib                   3.3.1        SPL extensions, array utilities, error handlers, and more
laminas/laminas-zendframework-bridge     1.2.0        Alias legacy ZF class names to Laminas Project equivalents.
lcobucci/jwt                             3.4.5        A simple library to work with JSON Web Token and JSON Web Signature
league/container                         2.5.0        A fast and intuitive dependency injection container.
league/event                             2.2.0        Event package
league/oauth2-server                     7.4.0        A lightweight and powerful OAuth 2.0 authorization and resource server library with support for all the core spec...
league/period                            3.4.0        A time range immutable value object
masterminds/html5                        2.7.4        An HTML5 parser and serializer.
mikey179/vfsstream                       v1.6.8       Virtual file system to mock the real file system in unit tests.
myclabs/deep-copy                        1.10.2       Create deep copies (clones) of your objects
nikic/php-parser                         v4.11.0      A PHP parser written in PHP
paragonie/random_compat                  v9.99.100    PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
pear/archive_tar                         1.4.13       Tar file management class with compression support (gzip, bzip2, lzma2)
pear/console_getopt                      v1.4.3       More info available on: http://pear.php.net/package/Console_Getopt
pear/pear-core-minimal                   v1.10.10     Minimal set of PEAR core files to be used as composer dependency
pear/pear_exception                      v1.0.2       The PEAR Exception base class.
phar-io/manifest                         2.0.1        Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                          3.1.0        Library for handling version information and constraints
php-http/client-common                   2.4.0        Common HTTP Client implementations and tools for HTTPlug
php-http/discovery                       1.14.0       Finds installed HTTPlug implementations and PSR-7 message factories
php-http/guzzle6-adapter                 v2.0.2       Guzzle 6 HTTP Adapter
php-http/httplug                         2.2.0        HTTPlug, the HTTP client abstraction for PHP
php-http/message                         1.11.1       HTTP Message related tools
php-http/message-factory                 v1.0.2       Factory interfaces for PSR-7 HTTP Message
php-http/promise                         1.1.0        Promise used for asynchronous HTTP requests
phpdocumentor/reflection-common          2.2.0        Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock        5.2.2        With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve informatio...
phpdocumentor/type-resolver              1.4.0        A PSR-5 based resolver of Class names, Types and Structural Element Names
phpoption/phpoption                      1.7.5        Option Type for PHP
phpspec/prophecy                         1.13.0       Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage                9.2.6        Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator                3.0.5        FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-invoker                      3.1.1        Invoke callables with a timeout
phpunit/php-text-template                2.0.4        Simple template engine.
phpunit/php-timer                        5.0.3        Utility class for timing
phpunit/phpunit                          9.5.6        The PHP Unit Testing framework.
psr/cache                                1.0.1        Common interface for caching libraries
psr/container                            1.1.1        Common Container Interface (PHP FIG PSR-11)
psr/http-client                          1.0.1        Common interface for HTTP clients
psr/http-factory                         1.0.1        Common interfaces for PSR-7 HTTP message factories
psr/http-message                         1.0.1        Common interface for HTTP messages
psr/log                                  1.1.4        Common interface for logging libraries
psy/psysh                                v0.10.8      An interactive shell for modern PHP.
ralouphie/getallheaders                  3.0.3        A polyfill for getallheaders.
react/promise                            v2.8.0       A lightweight implementation of CommonJS Promises/A for PHP
sebastian/cli-parser                     1.0.1        Library for parsing CLI options
sebastian/code-unit                      1.0.8        Collection of value objects that represent the PHP code units
sebastian/code-unit-reverse-lookup       2.0.3        Looks up which function or method a line of code belongs to
sebastian/comparator                     4.0.6        Provides the functionality to compare PHP values for equality
sebastian/complexity                     2.0.2        Library for calculating the complexity of PHP code units
sebastian/diff                           4.0.4        Diff implementation
sebastian/environment                    5.1.3        Provides functionality to handle HHVM/PHP environments
sebastian/exporter                       4.0.3        Provides the functionality to export PHP variables for visualization
sebastian/global-state                   5.0.3        Snapshotting of global state
sebastian/lines-of-code                  1.0.3        Library for counting the lines of code in PHP source code
sebastian/object-enumerator              4.0.4        Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector               2.0.4        Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context              4.0.4        Provides functionality to recursively process PHP variables
sebastian/resource-operations            3.0.3        Provides a list of PHP built-in functions that operate on resources
sebastian/type                           2.3.4        Collection of value objects that represent the types of the PHP type system
sebastian/version                        3.0.2        Library that helps with managing the version number of Git-hosted PHP projects
seld/jsonlint                            1.8.3        JSON Linter
seld/phar-utils                          1.1.1        PHAR file format utilities, for when PHP phars you up
sirbrillig/phpcs-variable-analysis       v2.11.2      A PHPCS sniff to detect problems with variables.
squizlabs/php_codesniffer                3.6.0        PHP_CodeSniffer tokenizes PHP, JavaScript and CSS files and detects violations of a defined set of coding standards.
stack/builder                            v1.0.6       Builder for stack middleware based on HttpKernelInterface.
stecman/symfony-console-completion       0.11.0       Automatic BASH completion for Symfony Console Component based applications.
symfony-cmf/routing                      2.3.3        Extends the Symfony routing component for dynamic routes and chaining several routers
symfony/browser-kit                      v4.4.25      Simulates the behavior of a web browser, allowing you to make requests, click on links and submit forms programma...
symfony/config                           v4.4.27      Helps you find, load, combine, autofill and validate configuration values of any kind
symfony/console                          v4.4.25      Eases the creation of beautiful and testable command line interfaces
symfony/css-selector                     v4.4.25      Converts CSS selectors to XPath expressions
symfony/debug                            v4.4.25      Provides tools to ease debugging PHP code
symfony/dependency-injection             v4.4.25      Allows you to standardize and centralize the way objects are constructed in your application
symfony/deprecation-contracts            v2.4.0       A generic function and convention to trigger deprecation notices
symfony/dom-crawler                      v4.4.25      Eases DOM navigation for HTML and XML documents
symfony/error-handler                    v4.4.25      Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher                 v4.4.25      Provides tools that allow your application components to communicate with each other by dispatching events and li...
symfony/event-dispatcher-contracts       v1.1.9       Generic abstractions related to dispatching event
symfony/filesystem                       v4.4.26      Provides basic utilities for the filesystem
symfony/finder                           v4.4.25      Finds files and directories via an intuitive fluent interface
symfony/http-client-contracts            v2.4.0       Generic abstractions related to HTTP clients
symfony/http-foundation                  v4.4.25      Defines an object-oriented layer for the HTTP specification
symfony/http-kernel                      v4.4.25      Provides a structured process for converting a Request into a Response
symfony/inflector                        v5.3.0       Converts words between their singular and plural forms (English only)
symfony/lock                             v4.4.26      Creates and manages locks, a mechanism to provide exclusive access to a shared resource
symfony/mime                             v5.3.0       Allows manipulating MIME messages
symfony/options-resolver                 v4.4.25      Provides an improved replacement for the array_replace PHP function
symfony/phpunit-bridge                   v5.3.3       Provides utilities for PHPUnit, especially user deprecation notices management
symfony/polyfill-ctype                   v1.23.0      Symfony polyfill for ctype functions
symfony/polyfill-iconv                   v1.23.0      Symfony polyfill for the Iconv extension
symfony/polyfill-intl-grapheme           v1.23.0      Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-idn                v1.23.0      Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer         v1.23.0      Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring                v1.23.0      Symfony polyfill for the Mbstring extension
symfony/polyfill-php72                   v1.23.0      Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73                   v1.23.0      Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80                   v1.23.0      Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/polyfill-php81                   v1.23.0      Symfony polyfill backporting some PHP 8.1+ features to lower PHP versions
symfony/process                          v4.4.25      Executes commands in sub-processes
symfony/property-access                  v4.4.25      Provides functions to read and write from/to an object or array using a simple string notation
symfony/property-info                    v4.4.25      Extracts information about PHP class' properties using metadata of popular sources
symfony/psr-http-message-bridge          v2.1.0       PSR HTTP message bridge
symfony/routing                          v4.4.25      Maps an HTTP request to a set of configuration variables
symfony/serializer                       v4.4.25      Handles serializing and deserializing data structures, including object graphs, into array structures or other fo...
symfony/service-contracts                v2.4.0       Generic abstractions related to writing services
symfony/string                           v5.3.3       Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters in a uni...
symfony/translation                      v4.4.25      Provides tools to internationalize your application
symfony/translation-contracts            v2.4.0       Generic abstractions related to translation
symfony/validator                        v4.4.25      Provides tools to validate values
symfony/var-dumper                       v5.3.0       Provides mechanisms for walking through any arbitrary PHP variable
symfony/yaml                             v4.4.25      Loads and dumps YAML files
theseer/tokenizer                        1.2.0        A small library for converting tokenized PHP source code into XML and potentially other formats
twig/twig                                v2.14.6      Twig, the flexible, fast, and secure template language for PHP
typo3/phar-stream-wrapper                v3.1.6       Interceptors for PHP's native phar:// stream handling
vlucas/phpdotenv                         v4.2.0       Loads environment variables from `.env` to `getenv()`, `$_ENV` and `$_SERVER` automagically.
webflo/drupal-finder                     1.2.2        Helper class to locate a Drupal installation from a given path.
webmozart/assert                         1.10.0       Assertions to validate method input/output with nice error messages.
webmozart/path-util                      2.3.0        A robust cross-platform utility for normalizing, comparing and modifying file paths.
zaporylie/composer-drupal-optimizations  1.2.0        Composer plugin to improve composer performance for Drupal projects

**Comment by mxr576** [comment]
Isn't this all about https://github.com/apigee/apigee-client-php/pull/159?

@maxim8898 Can you enable the Apigee Edge debug module and check the response payload when this issue occurs for global averages? (Or by using Xdebug like you did) The only time when I bumped into this different array size issue in this method when Apigee returned a global average in the response (which was not requested). That is always an array with one item.

**Comment by phdhiren** [comment]
@maxim8898 
Can you please upgrade all apigee related modules/ libraries to latest version and confirm if you still get the error? 
Also, if you can confirm which metric parameters, time span you're getting above error?

**Comment by maxim8898** [comment]
Hi @mxr576 I see these logs after enabling the Apigee Edge debug module

GET /environments/uat/stats/apps?_optimized=js&filter=%28developer_email+eq+%27SESA533007%40se.com%27+and+developer_app+eq+%27Test_Analytics_Maksim%27%29&timeUnit=hour&tsAscending=false&select=avg%28total_response_time%29&timeRange=01%2F01%2F2021+11%3A46%7E08%2F11%2F2021+11%3A46 HTTP/1.1
>>>>>>>>
GET /v1/organizations/***organization***/environments/uat/stats/apps?_optimized=js&filter=%28developer_email+eq+%27SESA533007%40se.com%27+and+developer_app+eq+%27Test_Analytics_Maksim%27%29&timeUnit=hour&tsAscending=false&select=avg%28total_response_time%29&timeRange=01%2F01%2F2021+11%3A46%7E08%2F11%2F2021+11%3A46 HTTP/1.1
Host: api.enterprise.apigee.com
X-Apigee-Edge-Api-Client-Profiler: X-Apigee-Edge-Api-Client-Profiler
User-Agent: Apigee Edge DevPortal 8.x-1.23 (Apigee Edge PHP Client 2.0.6)
Accept: application/json; charset=utf-8

<<<<<<<<
HTTP/1.1 200 OK
Access-Control-Allow-Headers: origin, x-requested-with, accept, authorization
Access-Control-Allow-Methods: GET, PUT, POST, DELETE
Access-Control-Allow-Origin: *
Access-Control-Max-Age: 3628800
Content-Type: application/json;charset=utf-8
Date: Wed, 11 Aug 2021 11:46:57 GMT
Server: Apigee LB
Content-Length: 928
Connection: keep-alive

```
{
    "Response": {
        "TimeUnit": [
            1613998800000,
            1613570400000
        ],
        "metaData": {
            "errors": [],
            "notices": [
                "Source:Postgres",
                "query served by:66a19e83-eab8-44c9-af86-6e8041677517",
                "Metric with Avg of total_response_time was requested. For this a global avg was also computed with name global-avg-total_response_time",
                "Table used: edge.api.raxgroup110.agg_app",
                "PG Host:uap-eu-west1-2:europe-west1:rgeu1uappg02s"
            ]
        },
        "resultTruncated": false,
        "stats": {
            "data": [
                {
                    "identifier": {
                        "names": [
                            "developer_app"
                        ],
                        "values": [
                            "Test_Analytics_Maksim"
                        ]
                    },
                    "metric": [
                        {
                            "env": "uat",
                            "name": "avg(total_response_time)",
                            "values": [
                                26,
                                170.5
                            ]
                        },
                        {
                            "env": "uat",
                            "name": "global-avg-total_response_time",
                            "values": [
                                141.6
                            ]
                        }
                    ]
                }
            ]
        }
    }
}
```
Transfer statistics:

total_time: 5.059s
namelookup_time: 0.068s
connect_time: 0.142s
pretransfer_time: 0.307s
starttransfer_time: 5.059s
redirect_time: 0s
appconnect_time: 0.306s

**Comment by mxr576** [comment]
`global-avg-total_response_time` so this is the same issue that https://github.com/apigee/apigee-client-php/pull/159 tries to address.

**Comment by maxim8898** [comment]
Got it, any estimation about bug fix?

**Comment by mxr576** [comment]
You can install and validate my PR with Composer patches already on your project, confirming that the fix is working in https://github.com/apigee/apigee-client-php/pull/159 could make a push on that issue, I guess :)

**Comment by maxim8898** [comment]
I just updated all modules/libraries and applied patch. Now it works fine!

**Comment by mxr576** [comment]
Thanks, please also report this positive result on the https://github.com/apigee/apigee-client-php/pull/159 as confirmation that the fix is working.

**Comment by maxim8898** [comment]
Sure, I already commented https://github.com/apigee/apigee-client-php/pull/159#issuecomment-896879491

**Comment by phdhiren** [comment]
@mxr576 , @maxim8898 Appreciate the effort for closing the issue. The code is merged with 2.x branch and it should be available with next release of https://github.com/apigee/apigee-client-php

**Comment by maxim8898** [comment]
@mxr576 , @phdhiren Thank you guys for a quick response and a clean solution!
