### ISSUE TITLE
Unable to uninstall apigee_egde_teams module with Apigee X connection

### ISSUE THREAD

**Issue by dkim625** [apigee/apigee-edge-drupal#617]
## Description
WIth a valid connection to an Apigee X instance, I get the following error message when attempting to uninstall the `apigee_edge_teams` module.

> <!DOCTYPE html> <html lang=en> <meta charset=utf-8> <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width"> <title>Error 404 (Not Found)!!1</title> <style> *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px} </style> <a href=//www.google.com/><span id=logo aria-label=Google></span></a> <p><b>404.</b> <ins>That’s an error.</ins> <p>The requested URL <code>/v1/organizations/ORG_NAME/companies?expand=true</code> was not found on this server. <ins>That’s all we know.</ins>  Drupal\apigee_edge\Entity\Storage\EdgeEntityStorageBase->withController() (line 220 of /app/web/modules/contrib/apigee_edge/src/Entity/Storage/EdgeEntityStorageBase.php).

## Version Info
Version: 8.x - 1.22

**Comment by phdhiren** [comment]
@dkim625 

Apigee edge teams is not for Apigee X and should not be installed, there is an installation restriction.
https://cloud.google.com/apigee/docs/api-platform/get-started/compare-apigee-products#unsupported-apis

Please help to understand how you were able to install it.

**Comment by dkim625** [comment]
Hi @phdhiren 

So originally, I had a connection to Apigee Edge (with Apigee Edge Teams installed) via the Apigee Edge module and I made a switch to Apigee X. Since Apigee Edge Teams is not supported by Apigee X, I tried to uninstall the Apigee Edge Teams module but kept running into the 404 issue.

I may be wrong here but I think the underlying issue is that Apigee Edge Teams is installable with or without a connection to Apigee Edge. However, it is not uninstallable unless you have a valid Apigee Edge connection.

**Comment by phdhiren** [comment]
@dkim625 

Apigee Edge Teams module is not allowing to install when Apigee X / Hybrid connection is there and so difficulty while uninstalling. It is for Apigee Edge.

IMO here is what can be done to improve:
1. When someone switch the connection (like your case) - It should ask to uninstall Apigee Edge Teams module
2. Should not validate anything while uninstalling Teams module

@raakesh-blokhra @giteshk  What do you think?
