### ISSUE TITLE
Unable to select checkbox on any field

### ISSUE THREAD

**Issue by dattasharma540** [apigee/apigee-edge-drupal#618]
Hi,

I am unable to select any checkbox on any page. 
_Permissions_ page 100's of checkboxes where as _URL Restriction by Role_ page has only one checkbox. I can't select or un-select anything on either page. See screenshots. AM I missing any module or configuration?

I am running Drupal v8.9

Thanks,
Datta

![image](https://user-images.githubusercontent.com/81440848/131442417-7e415c66-50d1-4486-9c1c-592a13ee9655.png)

![image](https://user-images.githubusercontent.com/81440848/131442570-f2312b89-5836-4f69-99fe-fcc1a6896213.png)

**Comment by phdhiren** [comment]
@dattasharma540 

Third party module https://www.drupal.org/project/url_restriction_by_role issue should be open in its own issue queue.
Try to change admin theme, it may help.

Closing this issue as it is not relevant with apigee_edge module issue queue, feel free to reopen if you need any other help.

**Comment by dattasharma540** [comment]
Thanks for the tip. I was using default Aapigee_kickstart theme. I switched to Bartik and it worked.
