### ISSUE TITLE
Rollback or fix #609 or find an alternative solution

### ISSUE THREAD

**Issue by mxr576** [apigee/apigee-edge-drupal#624]
## Description
PR #609 was merged but there are several problems with it.

Approach 1) If we would like to keep the _current_ solution then it should be fixed, see review comments on https://github.com/apigee/apigee-edge-drupal/commit/1f15f9148f15066c6ba7584f8e9c56ac5ce654e7

Approach 2) Since even Drupal core is tending to get away Drupalism called "alter hooks" and use events, the SDKConnector should rather trigger an event instead of exposing an alter hook.

Approach 3) (This would be my preference) instead of extending the public API of the module "unnecessarily", I would verify what changes are needed to be made (if any) to allow a simple SDK connector _service decorator_ to change (extend or override) the user agent string. 

## Version Info
Latest master.

**Comment by mxr576** [comment]
@shishir-intelli @cnovak What do you think? I have not had time to review the final version of #609 but I have concerns with the merged state.

**Comment by raakesh-blokhra** [comment]
@mxr576 acknowledged, I will look into it with @shishir-intelli and see what needs to be done. Thanks for your contributions as always.

**Comment by shishir-intelli** [comment]
We are going with approach #1. 

We appreciate the effort and time you have spent to share your suggestion and comments. Thanks @mxr576 !
