### ISSUE TITLE
Getting PHP Exception While Installing Apigee Edge Module 

### ISSUE THREAD

**Issue by codetochangeMinds** [apigee/apigee-edge-drupal#625]
## Description
I am getting an error while installing the Apigee Edge module using the Drupal admin UI. 

## Steps to Reproduce
1. Go to Drupal Admin UI. 
2. Navigate to Extend>Apigee Edge
3. Check the listed Apigee Edge module. 
4. Click on the _install_. Click on _continue_. 

## Actual Behavior
It gave the php exception 
`PHP message: Uncaught PHP Exception LogicException: "Only content and config entity types are supported." at /web/cor
e/modules/jsonapi/src/ResourceType/ResourceTypeRepository.php line 324`

## Expected Behavior
It should not throw any error and module should be installed 

## Version Info

> apigee/apigee-client-php             2.0.10   Client library for connecting to the Apigee Edge API.
asm89/stack-cors                     1.3.0    Cross-origin resource sharing library and stack middleware
clue/stream-filter                   v1.5.0   A simple and modern approach to stream filtering in PHP
composer/installers                  v1.11.0  A multi-framework Composer library installer
composer/semver                      3.2.5    Semver library that offers utilities, version constraint parsing and validation.
doctrine/annotations                 1.13.1   Docblock Annotations Parser
doctrine/lexer                       1.2.1    PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent P...
doctrine/reflection                  1.2.2    The Doctrine Reflection project is a simple library used by the various Doctrine pr...
drupal/apigee_edge                   1.24.0   Apigee Edge for Drupal.
drupal/core                          9.2.0    Drupal is an open source content management platform powering millions of websites ...
drupal/core-composer-scaffold        9.2.0    A flexible Composer project scaffold builder.
drupal/core-project-message          9.2.0    Adds a message after Composer installation.
drupal/core-recommended              9.2.0    Locked core dependencies; require this project INSTEAD OF drupal/core.
drupal/entity                        1.2.0    Provides expanded entity APIs, which will be moved to Drupal core one day.
drupal/key                           1.14.0   Provides the ability to manage site-wide keys
drupal/restui                        1.20.0   Provides a user interface to manage REST resources.
egulias/email-validator              2.1.25   A library for validating emails against several RFCs
fightbulc/moment                     1.33.0   Parse, validate, manipulate, and display dates in PHP w/ i18n support. Inspired by ...
firebase/php-jwt                     v5.4.0   A simple library to encode and decode JSON Web Tokens (JWT) in PHP. Should conform ...
guzzlehttp/guzzle                    6.5.5    Guzzle is a PHP HTTP client library
guzzlehttp/promises                  1.4.1    Guzzle promises library
guzzlehttp/psr7                      1.8.2    PSR-7 message implementation that also provides common utility methods
laminas/laminas-diactoros            2.6.0    PSR HTTP Message implementations
laminas/laminas-escaper              2.7.0    Securely and safely escape HTML, HTML attributes, JavaScript, CSS, and URLs
laminas/laminas-feed                 2.14.1   provides functionality for consuming RSS and Atom feeds
laminas/laminas-stdlib               3.3.1    SPL extensions, array utilities, error handlers, and more
laminas/laminas-zendframework-bridge 1.2.0    Alias legacy ZF class names to Laminas Project equivalents.
league/period                        3.4.0    A time range immutable value object
masterminds/html5                    2.7.4    An HTML5 parser and serializer.
pear/archive_tar                     1.4.13   Tar file management class with compression support (gzip, bzip2, lzma2)
pear/console_getopt                  v1.4.3   More info available on: http://pear.php.net/package/Console_Getopt
pear/pear-core-minimal               v1.10.10 Minimal set of PEAR core files to be used as composer dependency
pear/pear_exception                  v1.0.2   The PEAR Exception base class.
php-http/client-common               2.4.0    Common HTTP Client implementations and tools for HTTPlug
php-http/discovery                   1.14.0   Finds installed HTTPlug implementations and PSR-7 message factories
php-http/guzzle6-adapter             v2.0.2   Guzzle 6 HTTP Adapter
php-http/httplug                     2.2.0    HTTPlug, the HTTP client abstraction for PHP
php-http/message                     1.12.0   HTTP Message related tools
php-http/message-factory             v1.0.2   Factory interfaces for PSR-7 HTTP Message
php-http/promise                     1.1.0    Promise used for asynchronous HTTP requests
phpdocumentor/reflection-common      2.2.0    Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock    5.2.2    With this component, a library can provide support for annotations via DocBlocks or...
phpdocumentor/type-resolver          1.4.0    A PSR-5 based resolver of Class names, Types and Structural Element Names
psr/cache                            1.0.1    Common interface for caching libraries
psr/container                        1.1.1    Common Container Interface (PHP FIG PSR-11)
psr/http-client                      1.0.1    Common interface for HTTP clients
psr/http-factory                     1.0.1    Common interfaces for PSR-7 HTTP message factories
psr/http-message                     1.0.1    Common interface for HTTP messages
psr/log                              1.1.4    Common interface for logging libraries
ralouphie/getallheaders              3.0.3    A polyfill for getallheaders.
stack/builder                        v1.0.6   Builder for stack middleware based on HttpKernelInterface.
symfony-cmf/routing                  2.3.3    Extends the Symfony routing component for dynamic routes and chaining several routers
symfony/console                      v4.4.25  Eases the creation of beautiful and testable command line interfaces
symfony/debug                        v4.4.25  Provides tools to ease debugging PHP code
symfony/dependency-injection         v4.4.25  Allows you to standardize and centralize the way objects are constructed in your ap...
symfony/deprecation-contracts        v2.4.0   A generic function and convention to trigger deprecation notices
symfony/error-handler                v4.4.25  Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher             v4.4.25  Provides tools that allow your application components to communicate with each othe...
symfony/event-dispatcher-contracts   v1.1.9   Generic abstractions related to dispatching event
symfony/http-client-contracts        v2.4.0   Generic abstractions related to HTTP clients
symfony/http-foundation              v4.4.25  Defines an object-oriented layer for the HTTP specification
symfony/http-kernel                  v4.4.25  Provides a structured process for converting a Request into a Response
symfony/inflector                    v5.3.4   Converts words between their singular and plural forms (English only)
symfony/mime                         v5.3.0   Allows manipulating MIME messages
symfony/options-resolver             v4.4.30  Provides an improved replacement for the array_replace PHP function
symfony/polyfill-ctype               v1.23.0  Symfony polyfill for ctype functions
symfony/polyfill-iconv               v1.23.0  Symfony polyfill for the Iconv extension
symfony/polyfill-intl-grapheme       v1.23.1  Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-idn            v1.23.0  Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer     v1.23.0  Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring            v1.23.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php72               v1.23.0  Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73               v1.23.0  Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80               v1.23.0  Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/process                      v4.4.25  Executes commands in sub-processes
symfony/property-access              v4.4.30  Provides functions to read and write from/to an object or array using a simple stri...
symfony/property-info                v4.4.30  Extracts information about PHP class' properties using metadata of popular sources
symfony/psr-http-message-bridge      v2.1.0   PSR HTTP message bridge
symfony/routing                      v4.4.25  Maps an HTTP request to a set of configuration variables
symfony/serializer                   v4.4.25  Handles serializing and deserializing data structures, including object graphs, int...
symfony/service-contracts            v2.4.0   Generic abstractions related to writing services
symfony/string                       v5.3.7   Provides an object-oriented API to strings and deals with bytes, UTF-8 code points ...
symfony/translation                  v4.4.25  Provides tools to internationalize your application
symfony/translation-contracts        v2.4.0   Generic abstractions related to translation
symfony/validator                    v4.4.25  Provides tools to validate values
symfony/var-dumper                   v5.3.0   Provides mechanisms for walking through any arbitrary PHP variable
symfony/yaml                         v4.4.25  Loads and dumps YAML files
twig/twig                            v2.14.6  Twig, the flexible, fast, and secure template language for PHP
typo3/phar-stream-wrapper            v3.1.6   Interceptors for PHP's native phar:// stream handling
webmozart/assert                     1.10.0   Assertions to validate method input/output with nice error messages.

**Comment by shishir-intelli** [comment]
Hi @codetochangeMinds ,

We will recommend you to install `Apigee Edge` module through composer.

Apigee edge module includes sub-modules also, so please checkout this link to install module correctly using composer
https://www.drupal.org/project/apigee_edge#:~:text=site%20(/admin/modules).-,Installing,-You%20must%20use

**Comment by codetochangeMinds** [comment]
yeah I have installed using composer only but I am just enabling the module using Drupal admin UI.

**Comment by mxr576** [comment]
The latest patch is required from here is you would like to use Apigee Edge and JSON API on the same site.

https://www.drupal.org/project/drupal/issues/3042467

**Comment by shishir-intelli** [comment]
Closing this issue, feel free to reopen this if in case you need further help.
