### ISSUE TITLE
How to create app programmatically (Drupal 8 Edge/apigee php sdk)

### ISSUE THREAD

**Issue by rameshpongalur** [apigee/apigee-edge-drupal#634]
I want to create apigee app programmatically in drupal 8 edge. Kindly help me on this.

**Comment by mxr576** [comment]
The process is quite similar for this just the entity id is `developer_app`. Every Apigee entity is a regular Drupal entity so the same tricks are working on them.
https://github.com/apigee/apigee-edge-drupal/issues/264#issuecomment-535036590

**Comment by rameshpongalur** [comment]
@mxr576 Hi thanks for the help. How to pass the values programmatically while creating app?We need to pass app name and developer id right?

**Comment by shishir-intelli** [comment]
@rameshpongalur,
Yes, app name, developer Id and status.

**Comment by shishir-intelli** [comment]
Closing this issue, feel free to reopen this if in case you need any help.
