### ISSUE TITLE
display team member's name instead of the email 

### ISSUE THREAD

**Issue by hollyw2025** [apigee/apigee-edge-drupal#637]
## Is your feature request related to a problem? Please describe.
we would like to see the team member list their name instead of the emails. 
in current Drupal\apigee_edge_teams\Controller\TeamMembersList, we saw this comment in function buildRow()
// We only display the email address of the member in this case
      // because displaying its first name and last name would require API
      // call(s). We can not load only a set of developers from Apigee Edge
      // (like we loaded only the necessary amount of Drupal users), we can only
      // all developers which could unnecessarily slow down this page if the
      // developer entity cache is cold.
      
      Does this mean, to display team member's name instead of emails, we need to pull all Edge user's list into an Array? 

## Describe the solution you would like
we would like to see the team member list their name instead of the emails  

## Additional context 

<image removed>

**Comment by shishir-intelli** [comment]
@hollyhw15 
Yes, the team member API just returns the email address, to get the name of the developer will require a separate API call.

**Comment by hollyw2025** [comment]
shishir-intelli 
Thank you for your quick response. 
At this moment, we have list of users at the portal side: 

admin/people

For each user's profile, their name is listed under name: 
Example Profile Details
Name:
XXXXX
Username:
XXXXX
Email:
XXXXX

Are admin/people and user's profile name all pulled out from the Api call?

Thank you

Holly

**Comment by raakesh-blokhra** [comment]
@hollyhw15 I edited the comment above and removed the personal information. You do not need to reshare at the moment as Shishir has that information but in future please avoid posting email addresses, etc here. Instead you can email that information to the user directly. Their email address can be found on their profile.

Thanks for the additional information.

**Comment by hollyw2025** [comment]
Thank you, Raakesh

**Comment by shishir-intelli** [comment]
@hollyhw15 
In Drupal portal, `/admin/people` page shows the list of users which are from portal but the developer/people are synced with Apigee Edge while creating/updating the profile through API call(s),

Also, if in case those are not synced then one can go to `/admin/config/apigee-edge/developer-settings/sync` and sync with the Apigee Edge developers.

Coming back to your original question:
At present we only get a list of all developers and not a set of developer from Apigee Edge API and displaying developers first name and last name would require a separate API call which is not there in the portal at present.

**Comment by hollyw2025** [comment]
Shishir
Thank you for your answering. I suspected that our portal has a separate table for users, as I can create different test user account on different platform: dev, stage, local. 

I also attached more screenshots, hope it helps
1. under url:/admin/structure/views, people has a view page: 
People | user_admin_people | Find and manage people interacting with your site. | Page (/admin/people)
![Screen Shot 2021-11-03 at 3 26 58 PM](https://user-images.githubusercontent.com/69690136/140205269-05605395-aa26-4c6b-91fd-273409afebfe.png)

**Comment by hollyw2025** [comment]
at url:admin/people, 
user's email listed under UserName ,
![Screen Shot 2021-11-03 at 3 28 09 PM](https://user-images.githubusercontent.com/69690136/140207376-7e6fbdff-ec4a-4491-bd5a-5aed6c002afb.png)

 for each user, there are firstname and lastname field

![Screen Shot 2021-11-03 at 3 30 51 PM](https://user-images.githubusercontent.com/69690136/140208317-ab280ac3-cdf0-4127-928b-27e3d3ef0ee3.png)

**Comment by hollyw2025** [comment]
found the first_name and last_name field in table `users_field_data` , please advice how to pull them out


INSERT INTO `users_field_data` 
(`uid`, `langcode`, `preferred_langcode`, `preferred_admin_langcode`, `name`, `pass`, `mail`, `timezone`, `status`, `created`, `changed`, `access`, `login`, `init`, `default_langcode`, `first_name`, `last_name`) VALUES

**Comment by kiranjyoth** [comment]
@hollyhw15 Would you like to display User's first and last names on the` /admin/people/` page? Or is there a custom page you're building where you want to sync developers from Edge ? If you're looking for a dashboard of the all the apps and developers associated with them, here is a module we built. https://www.drupal.org/project/sm_appdashboard_apigee

**Comment by hollyw2025** [comment]
shishir

I pull out user's firstName and lastName from table users_field_data with user's email as the filter. 

/**
* @return string
*/
  public function getUserName(string $users_by_mail){    
                //pull out user's first name, last name from table users_field_data with user's email as the filter.  
                return $user_full_name;
  }

in Drupal\apigee_edge_teams\Controller\TeamMembersList class, I also added the following line  to display team member: 

protected function buildRow(string $member, array $users_by_mail, array $team_member_roles_by_mail, TeamInterface $team): array {
....
  if (array_key_exists($member, $users_by_mail)) {
        //get user full name per email()$member)
        $row['data']['name'] = $this->getUserFullName($member);
    }else {
      // For user who has no name input, just display a blank field
      $row['data']['name'] = ' ';
    }
  
  ...
}

  
member name can display with this change. 

I worked directly in Drupal\apigee_edge_teams\Controller\TeamMembersList.php, need to figure out how to make my change as custom code. 

Holly

**Comment by shishir-intelli** [comment]
@hollyhw15 ,
You can extend the `TeamMembersList.php` controller class or can use dependency injection when extending a class that implements `ControllerBase`, so you can override the `TeamMembersList.php` controller's `buildRow` function and change the logic in your custom module.

_To display developer(s) name through developer email id as parameter, then in that case you can use Drupal function `user_load_by_mail`
Please check https://api.drupal.org/api/drupal/core%21modules%21user%21user.module/function/user_load_by_mail/8.2.x_ 

Hope this information helps.

**Comment by shishir-intelli** [comment]
Closing this issue for now, feel free to reopen if you need any further help.
