### ISSUE TITLE
Some API Product Not Listing On Drupal Interface

### ISSUE THREAD

**Issue by codetochangeMinds** [apigee/apigee-edge-drupal#643]
## Description
API products with **underscore char** as part of the Name(_internal name of the API Product_) are not listing on the Drupal Interface during the app creation flow. 

## Steps to Reproduce
1. Go to Apigee X console and create API product with an internal name containing an underscore character. 
2. Go to Drupal Interface and navigate to **create app page**. 

## Actual Behavior
The API products with underscore character as part of Name(_internal name of the API Product_) are not listing on the Create App page. 

## Expected Behavior
All the products should be listed if visibility is taken care and appropriate permissions are assigned to the customer developer role. 

## Version Info
Apigee Version: **Apigee X** 
Drupal Version:  **9.2.6**

**Comment by divya-intelli** [comment]
Hi @codetochangeMinds, please verify if the 'ACCESS BY VISIBILITY' on link /admin/config/apigee-edge/developer-settings/access-control in Drupal is properly given for the role.

**Comment by codetochangeMinds** [comment]
Yeah I have verified. Even Administrator who has access to all visibility is unable to see the product on Drupal interface.

**Comment by divya-intelli** [comment]
Hi @codetochangeMinds ,
Can you enable 'Apigee Edge Debug' module and share all debug logs? Check the documentation on how to get the [debug log and remove credentials](https://www.drupal.org/docs/8/modules/apigee-edge/monitor-apigee-edge-debug-logs#configure).
