### ISSUE TITLE
PHP error on `/user/%user/team-invitations` when there is no team in the organization

### ISSUE THREAD

**Issue by boobaa** [apigee/apigee-edge-drupal#648]
## Description
When there is no team in the Apigee Edge organization, the `/user/%user/team-invitations` page throws an error: "The website encountered an unexpected error. Please try again later."

## Steps to Reproduce
1. Remove all the teams from the organization (eg. as uid=1 from the `/teams` page).
2. Clear the caches.
3. Visit the `/user/%user/team-invitations` page as an authenticated user (even as uid=1).

## Actual Behavior
An error is displayed, and there is one single line in the logs:
```
Drupal\Core\Database\InvalidQueryException: Query condition 'team_invitation.team IN ()' cannot be empty. in Drupal\Core\Database\Query\Condition->condition() (line 105 of /mnt/files/local_mount/build/web/core/lib/Drupal/Core/Database/Query/Condition.php).
```

## Expected Behavior
No error is displayed and logged; instead, either a "There are no teams yet." or a "You do not have any invitations." message should be displayed.

## Screenshots
(none)

## Notes
It doesn't matter if the organization had any teams earlier or not. The bug only appears when caches are cleared AFTER all the teams have been deleted.

There's a mitigation: if at least one team exists in the organization, the problem disappears, even if there is no invitation to or membership in this team at all.

## Version Info
```
apigee/apigee-client-php                                  2.0.6         Client library for connecting to the Apigee Edge API.
drupal/apigee_edge                                        1.22.0        Apigee Edge for Drupal.
```

**Comment by shishir-intelli** [comment]
Hi @boobaa 
I just wanted to acknowledge this ticket. If you have any patches to commit, please let us know, otherwise we will continue to work on it and push the changes when done.
