### ISSUE TITLE
smartdocs/openapi feature/question

### ISSUE THREAD

**Issue by gosunilgo** [apigee/apigee-edge-drupal#65]
| Q                           | A
| --------------------------- | -----------------------------------------------
| Bug?                        | no
| New Feature?                | yes
| Module Version              | Version or commit SHA <br> This can be the version you can see on admin/modules in Drupal or the output of this command: <code>composer show | grep drupal/apigee_edge | awk '{if ($2 ~ "dev$") print $2 " "$3; else print $2;}'</code>
| PHP Client version          | Version or commit SHA <br> This can be the output of this command: <code>composer show | grep apigee/apigee-client-php | awk '{if ($2 ~ "dev$") print $2 " "$3; else print $2;}'</code>
| Requires PHP client fix     | no|link to an Apigee Client PHP library issue or pull request

#### Question/Comment

The current apigee-drupal supports a smartdocs (Swagger/Open-API Spec).    Is this feature in the roadmap?  Or, will you recommend third-party modules -- openapi-ui module, etc..

**Comment by mxr576** [comment]
Hi @gosunilgo!

Currently the recommended method for displaying OpenAPI specs in Drupal 8 is the Swagger UI Field formatter module. You can find a tutorial about this in the official documentation of this module on drupal.org.

https://www.drupal.org/docs/8/modules/apigee-edge/document-your-apis-using-the-swagger-ui

**Comment by cnovak** [comment]
Hello @gosunilgo, 
Better API documentation we are currently working on.  Like @mxr576 pointed out we suggest using the Swagger UI Field formatter for now. 

Here is a post giving an idea on where we are planning on going:
https://cloud.google.com/blog/products/application-development/automatic-documentation-for-your-cloud-endpoints-api-now-in-ga
