### ISSUE TITLE
Incorrect parameters declaration breaks apigee_edge module (PHP 8.0)

### ISSUE THREAD

**Issue by VladimirAus** [apigee/apigee-edge-drupal#657]
## Issue

* Incorrect parameters declaration breaks `apigee_edge` module
* `PHP 8.0` and `8.1` are currently not supported by the module. 
* `Drupal 10` (`alpha1` is available now) will have minimum `PHP 8.0` or `8.1` requirement.
* Corresponding library issue: https://github.com/apigee/apigee-client-php/issues/196

### Teams / Team Apps page:
```
TypeError: Apigee\Edge\Api\Management\Entity\AppOwner::setApps(): Argument #1 must be of 
type string, array given, called in /root/vendor/symfony/property-access/PropertyAccessor.php 
on line 570 in Apigee\Edge\Api\Management\Entity\AppOwner->setApps() (line 58 of 
/root/vendor/apigee/apigee-client-php/src/Entity/Property/AppsPropertyAwareTrait.php)
```

```
Message | TypeError: Apigee\Edge\Api\Management\Entity\AppCredential::setApiProducts(): 
Argument #1 must be of type Apigee\Edge\Structure\CredentialProductInterface, array given, 
called in /root/vendor/symfony/property-access/PropertyAccessor.php on line 570 
in Apigee\Edge\Api\Management\Entity\AppCredential->setApiProducts() (line 100 of 
/root/vendor/apigee/apigee-client-php/src/Api/Management/Entity/AppCredential.php)
```

```
TypeError: Apigee\Edge\Api\Management\Entity\App::setCredentials(): Argument #1 must be of 
type Apigee\Edge\Api\Management\Entity\AppCredentialInterface, array given, called in 
/root/vendor/symfony/property-access/PropertyAccessor.php on line 570 in 
Apigee\Edge\Api\Management\Entity\App->setCredentials() (line 199 of 
/root/vendor/apigee/apigee-client-php/src/Api/Management/Entity/App.php) 
```

### Status Report page:
```
TypeError: Apigee\Edge\Api\Management\Entity\Organization::setEnvironments(): Argument #1 
must be of type string, array given, called in /root/vendor/symfony/property-access/PropertyAccessor.php 
on line 570 in Apigee\Edge\Api\Management\Entity\Organization->setEnvironments() (line 42 of 
/root/vendor/apigee/apigee-client-php/src/Entity/Property/EnvironmentsPropertyAwareTrait.php) 
```

**Comment by phdhiren** [comment]
The [apigee-client-php library](https://github.com/apigee/apigee-client-php) is still to support PHP 8, Seems the above error are coming due the library.

**Comment by jjmackow** [comment]
[the apigee-client-php library was updated on March 8th with a PR for the PHP 8.0 bug](https://github.com/apigee/apigee-client-php/pull/211)
`Deprecated: Return type of Drupal\apigee_edge\Entity\FieldableEdgeEntityBase::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/web/modules/contrib/apigee_edge/src/Entity/FieldableEdgeEntityBase.php on line 535`
from the 2.0.2 release of the module on Drupal 9.3.7 under PHP 8.1

**Comment by johnvenpin** [comment]
Just checking the status of the PHP 8 and 8.1 release for the Apigee Edge Drupal 8 module? - we are getting the following error using Drupal 9.3.11 on the Acquia cloud when enabling PHP 8. Thank you.

Apigee\Edge\Api\Management\Entity\AppOwner::setApps(): Argument #1 must be of type string, array given, called in /mnt/www/html/filstg/vendor/symfony/property-access/PropertyAccessor.php on line 581 in /mnt/www/html/filstg/vendor/apigee/apigee-client-php/src/Entity/Property/AppsPropertyAwareTrait.php on line 58 #0 /mnt/www/html/filstg/vendor/symfony/property-access/PropertyAccessor.php(581): Apigee\Edge\Api\Management\Entity\AppOwner->setApps(Array)

**Comment by phdhiren** [comment]
@johnvenpin 

The issue mentioned is fixed with the latest version of `apigee-client-php`
You should update the library via `composer update`

@jjmackow 
The issue mentioned is taken care of with the PR #693 and should be a part of upcoming release 2.0.3

Closing this issue, feel free to reopen, if required
