### ISSUE TITLE
is My App/Team App app name editable? 

### ISSUE THREAD

**Issue by hollyw2025** [apigee/apigee-edge-drupal#663]
Hi, our company asked me to edit our current portal code so that programmer can edit My App/Team App app name. 

I searched through different modules, can't find  My App/Team App app form location. 

Is My App/Team App app name editable? if yes, where to fix it? 
![Screen Shot 2022-02-04 at 2 42 04 PM](https://user-images.githubusercontent.com/69690136/152612942-d8aae393-f730-4b6f-99da-6578a3bdfd8c.png)

**Comment by phdhiren** [comment]
@hollyhw15 
The display name should be editable, but internal app_id is not editable.
Which version of apigee_edge module you're using?

**Comment by hollyw2025** [comment]
We are currently on [Drupal core](https://www.drupal.org/project/drupal) 9.3.3 

I can't find anywhere, or any code to make App display name editable, please advice

**Comment by phdhiren** [comment]
@hollyhw15 
Can you send version of apigee_edge module along with output of `composer show`? It seems there are your custom modules is restricting the App name to be editable, try disable your custom module/theme and check it out. 
The one which is visible on the form should be editable.

**Comment by hollyw2025** [comment]
On the developer portal side, here is the output of composer show. 
It seems like the app name should comes with contrib module, apigee_edge, however, I can't find where to control the app name editable 

hollys-mbp release20 % composer show
apigee/apigee-client-php                                  2.0.12         
apigee/apigee_devportal_kickstart                         1.23           
asm89/stack-cors                                          1.3.0          
bower-asset/swagger-ui                                    v3.52.5        
chi-teck/drupal-code-generator                            1.33.1         
clue/stream-filter                                        v1.5.0         
commerceguys/addressing                                   v1.2.2         
commerceguys/intl                                         v1.1.1         
composer/installers                                       v1.12.0        
composer/semver                                           3.2.6          
consolidation/annotated-command                           4.5.1          
consolidation/config                                      1.2.1          
consolidation/filter-via-dot-access-data                  1.0.0          
consolidation/log                                         2.0.4          
consolidation/output-formatters                           4.2.1          
consolidation/robo                                        3.0.7          
consolidation/self-update                                 2.0.3          
consolidation/site-alias                                  3.1.3          
consolidation/site-process                                4.1.3          
cweagans/composer-patches                                 1.7.1          
dflydev/dot-access-data                                   v1.1.0         
doctrine/annotations                                      1.13.2         
doctrine/cache                                            1.12.1         
doctrine/collections                                      1.6.8          
doctrine/common                                           2.13.3         
doctrine/event-manager                                    1.1.1          
doctrine/inflector                                        1.4.4          
doctrine/lexer                                            1.2.1          
doctrine/persistence                                      1.3.8          
doctrine/reflection                                       1.2.2          
drupal/address                                            1.9.0          
drupal/admin_toolbar                                      2.5.0          
drupal/adminimal_admin_toolbar                            1.11.0         
drupal/apigee_api_catalog                                 2.6.0          
drupal/apigee_edge                                        1.25.0         
drupal/apigee_m10n                                        1.12.0         
drupal/autologout                                         1.3.0          
drupal/better_exposed_filters                             5.0.0          
drupal/commerce                                           2.28.0         
drupal/components                                         3.0.0-beta2    
drupal/core                                               9.3.3          
drupal/core-composer-scaffold                             9.3.3          
drupal/core-project-message                               9.3.3          
drupal/core-recommended                                   9.3.3          
drupal/css_editor                                         1.3.0          
drupal/ctools                                             3.7.0          
drupal/default_content                                    1.0.0-alpha9   
drupal/devel                                              4.1.3          
drupal/email_registration                                 1.1.0          
drupal/entity                                             1.2.0          
drupal/entity_browser                                     2.6.0          
drupal/entity_reference_revisions                         1.9.0          
drupal/entity_update                                      2.0.0-rc2      
drupal/externalauth                                       1.4.0          
drupal/file_link                                          2.0.6          
drupal/fontawesome                                        2.19.0         
drupal/inline_entity_form                                 1.0.0-rc9      
drupal/jquery_ui                                          1.4.0          
drupal/jquery_ui_datepicker                               1.2.0          
drupal/jquery_ui_slider                                   1.1.0          
drupal/jquery_ui_touch_punch                              1.0.0          
drupal/key                                                1.15.0         
drupal/maxlength                                          1.0.0-rc1      
drupal/menu_per_role                                      1.4.0          
drupal/menu_trail_by_path                                 1.3.0          
drupal/paragraphs                                         1.12.0         
drupal/pathauto                                           1.8.0          
drupal/profile                                            1.3.0          
drupal/radix                                              dev-4.x 8679d77
drupal/redirect_after_logout                              1.1.0          
drupal/requirement                                        1.1.0          
drupal/seckit                                             2.0.0          
drupal/simplesamlphp_auth                                 3.2.0          
drupal/simplesamlphp_custom_attributes                    1.1.0          
drupal/smtp                                               1.0.0          
drupal/state_machine                                      1.5.0          
drupal/swagger_ui_formatter                               3.3.0          
drupal/token                                              1.10.0         
drupal/views_bulk_operations                              3.13.0         
drush/drush                                               10.6.2         
egulias/email-validator                                   3.1.2          
enlightn/security-checker                                 v1.9.0         
fightbulc/moment                                          1.33.0         
firebase/php-jwt                                          v5.5.1         
gettext/gettext                                           v4.8.6         
gettext/languages                                         2.9.0          
grasmash/expander                                         1.0.0          
grasmash/yaml-expander                                    1.4.0          
guzzlehttp/guzzle                                         6.5.5          
guzzlehttp/promises                                       1.5.1          
guzzlehttp/psr7                                           1.8.3          
laminas/laminas-diactoros                                 2.8.0          
laminas/laminas-escaper                                   2.9.0          
laminas/laminas-feed                                      2.15.0         
laminas/laminas-stdlib                                    3.6.1          
league/container                                          3.4.1          
league/period                                             3.4.0          
masterminds/html5                                         2.7.5          
nikic/php-parser                                          v4.13.2        
oomphinc/composer-installers-extender                     2.0.1          
pear/archive_tar                                          1.4.14         
pear/console_getopt                                       v1.4.3         
pear/pear-core-minimal                                    v1.10.11       
pear/pear_exception                                       v1.0.2         
php-http/client-common                                    2.5.0          
php-http/discovery                                        1.14.1         
php-http/guzzle6-adapter                                  v2.0.2         
php-http/httplug                                          2.2.0          
php-http/message                                          1.12.0         
php-http/message-factory                                  v1.0.2         
php-http/promise                                          1.1.0          
phpdocumentor/reflection-common                           2.2.0          
phpdocumentor/reflection-docblock                         5.3.0          
phpdocumentor/type-resolver                               1.6.0          
phpfastcache/riak-client                                  3.4.3          
phpmailer/phpmailer                                       v6.5.3         
psr/cache                                                 1.0.1          
psr/container                                             1.1.1          
psr/http-client                                           1.0.1          
psr/http-factory                                          1.0.1          
psr/http-message                                          1.0.1          
psr/log                                                   1.1.4          
psy/psysh                                                 v0.10.12       
ralouphie/getallheaders                                   3.0.3          
robrichards/xmlseclibs                                    3.1.1          
simplesamlphp/assert                                      v0.0.13        
simplesamlphp/composer-module-installer                   v1.1.8         
simplesamlphp/saml2                                       v4.4.0         
simplesamlphp/simplesamlphp                               v1.19.4        
simplesamlphp/simplesamlphp-module-adfs                   v0.9.9         
simplesamlphp/simplesamlphp-module-authcrypt              v0.9.4         
simplesamlphp/simplesamlphp-module-authfacebook           v0.9.3         
simplesamlphp/simplesamlphp-module-authorize              v0.9.4         
simplesamlphp/simplesamlphp-module-authtwitter            v0.9.3         
simplesamlphp/simplesamlphp-module-authwindowslive        v0.9.1         
simplesamlphp/simplesamlphp-module-authx509               v0.9.9         
simplesamlphp/simplesamlphp-module-authyubikey            v0.9.3         
simplesamlphp/simplesamlphp-module-cas                    v0.9.1         
simplesamlphp/simplesamlphp-module-cdc                    v0.9.2         
simplesamlphp/simplesamlphp-module-consent                v0.9.8         
simplesamlphp/simplesamlphp-module-consentadmin           v0.9.2         
simplesamlphp/simplesamlphp-module-discopower             v0.10.1        
simplesamlphp/simplesamlphp-module-exampleattributeserver v1.0.0         
simplesamlphp/simplesamlphp-module-expirycheck            v0.9.4         
simplesamlphp/simplesamlphp-module-ldap                   v0.9.17        
simplesamlphp/simplesamlphp-module-memcachemonitor        v0.9.3         
simplesamlphp/simplesamlphp-module-memcookie              v1.2.2         
simplesamlphp/simplesamlphp-module-metarefresh            v0.9.7         
simplesamlphp/simplesamlphp-module-negotiate              v0.9.12        
simplesamlphp/simplesamlphp-module-oauth                  v0.9.3         
simplesamlphp/simplesamlphp-module-preprodwarning         v0.9.3         
simplesamlphp/simplesamlphp-module-radius                 v0.9.4         
simplesamlphp/simplesamlphp-module-riak                   v0.9.1         
simplesamlphp/simplesamlphp-module-sanitycheck            v0.9.1         
simplesamlphp/simplesamlphp-module-smartattributes        v0.9.2         
simplesamlphp/simplesamlphp-module-sqlauth                v0.9.4         
simplesamlphp/simplesamlphp-module-statistics             v0.9.6         
simplesamlphp/twig-configurable-i18n                      v2.3.4         
stack/builder                                             v1.0.6         
symfony-cmf/routing                                       2.3.4          
symfony/cache                                             v5.4.2         
symfony/cache-contracts                                   v2.5.0         
symfony/config                                            v4.4.36        
symfony/console                                           v4.4.34        
symfony/debug                                             v4.4.31        
symfony/dependency-injection                              v4.4.34        
symfony/deprecation-contracts                             v2.5.0         
symfony/error-handler                                     v4.4.34        
symfony/event-dispatcher                                  v4.4.34        
symfony/event-dispatcher-contracts                        v1.1.11        
symfony/filesystem                                        v4.4.27        
symfony/finder                                            v5.4.2         
symfony/framework-bundle                                  v4.4.36        
symfony/http-client-contracts                             v2.5.0         
symfony/http-foundation                                   v4.4.34        
symfony/http-kernel                                       v4.4.35        
symfony/inflector                                         v5.4.0         
symfony/mime                                              v5.4.0         
symfony/options-resolver                                  v4.4.30        
symfony/polyfill-ctype                                    v1.23.0        
symfony/polyfill-iconv                                    v1.23.0        
symfony/polyfill-intl-grapheme                            v1.24.0        
symfony/polyfill-intl-idn                                 v1.23.0        
symfony/polyfill-intl-normalizer                          v1.23.0        
symfony/polyfill-mbstring                                 v1.23.1        
symfony/polyfill-php72                                    v1.24.0        
symfony/polyfill-php73                                    v1.24.0        
symfony/polyfill-php80                                    v1.23.1        
symfony/polyfill-php81                                    v1.24.0        
symfony/process                                           v4.4.35        
symfony/property-access                                   v4.4.36        
symfony/property-info                                     v4.4.31        
symfony/psr-http-message-bridge                           v2.1.2         
symfony/routing                                           v4.4.34        
symfony/serializer                                        v4.4.35        
symfony/service-contracts                                 v2.5.0         
symfony/string                                            v5.4.2         
symfony/translation                                       v4.4.34        
symfony/translation-contracts                             v2.5.0         
symfony/validator                                         v4.4.35        
symfony/var-dumper                                        v5.4.0         
symfony/var-exporter                                      v5.4.2         
symfony/yaml                                              v4.4.34        
twig/extensions                                           v1.5.4         
twig/twig                                                 v2.14.7        
typo3/phar-stream-wrapper                                 v3.1.7         
webflo/drupal-finder                                      1.2.2          
webmozart/assert                                          1.10.0         
webmozart/path-util                                       2.3.0          
whitehat101/apr1-md5                                      v1.0.0

**Comment by phdhiren** [comment]
@hollyhw15 

I would recommend to update Apigee Edge to [2.0.2](https://www.drupal.org/project/apigee_edge/releases/2.0.2) however it seems there is some customization done on your instance due to which App name is non-editable for you. I'm not able to replicate the issue.

**Comment by hollyw2025** [comment]
I will give it a try to upgrade update Apigee Edge to [2.0.2]

any suggestion where to find the App form? I looked a lot of places but can't find the form or PHP code to edit this page

**Comment by hollyw2025** [comment]
we usually upgrade Drupal core on time, rarely we just upgrade one module. Will upgrade edge affect Drupal core?

**Comment by phdhiren** [comment]
Updating apigee_edge module will not affect Drupal, in fact newer version may have bug fixes / features.

Look for custom theme / modules where the initial functionality has been altered.

**Comment by hollyw2025** [comment]
Hi, 
I found the fixing in one of our costumed functions and fixed this problem 
$form[‘displayName’][‘#disabled’] = FALSE;

Question, in the html code, I can't find this $form[‘displayName’] What should be the key field name to look for if I need to work on similar problem next time? 


what I found is 
id="edit-displayname-0-value" 
name="displayName[0][value]" 


Here is the original html code

  <div class="js-form-item form-item 
  js-form-type-textfield 
  form-item-displayname-0-value 
  js-form-item-displayname-0-value 
  form-disabled form-group">
<label for="edit-displayname-0-value" class="js-form-required form-required">
App name
<i class="fas fa-asterisk text-danger form-required__indicator"></i>
</label>
    <div class="form-children">
              
<input class="js-text-full text-full required form-control" 
data-drupal-selector="edit-displayname-0-value" 
disabled="disabled" type="text" 
id="edit-displayname-0-value" 
name="displayName[0][value]" 
value="myAppTest" size="60" 
maxlength="255" placeholder="" required="required" aria-required="true" />

</div>

**Comment by phdhiren** [comment]
@hollyhw15 

You should visit Drupal documentation of [Form API](https://www.drupal.org/docs/drupal-apis/form-api) and [rendering form elements](https://www.drupal.org/docs/drupal-apis/form-api/form-render-elements) to learn about Form API and altering the same.


Closing the issue for now, feel free to reopen if require.
