### ISSUE TITLE
After Apigee migration to version 4.51 Drupal dev portal UI has broken

### ISSUE THREAD

**Issue by pankaj-sharma31** [apigee/apigee-edge-drupal#666]
## Description
After Apigee migration to version 4.51 Drupal dev portal UI has broken.

https://docs.apigee.com/private-cloud/v4.51.00/update-apigee-edge-41906-45100

We have 5 node cluster with Apigee Drupal  portal (7.84) with Postgres SQL (10.17) on separate machine.

We ran below commands to update dev portal

/opt/apigee/apigee-setup/bin/update.sh -c dp -f /opt/apigee/response-edge.txt

![image](https://user-images.githubusercontent.com/99468991/153557468-35a6310d-2f01-4f1f-a0f4-a8846d6975ee.png)

## Steps to Reproduce

Migrate from Apigee version 4.19.06 to 4.51 version

## Actual Behavior
UI is broken after migration

## Expected Behavior
UI tab for the developer portal should be aligned properly as previous 4.19.06 version 

## Screenshots
![image](https://user-images.githubusercontent.com/99468991/153558210-25cc2000-1a49-4aad-b147-305052e0f42c.png)

## Notes

Drupal  portal (7.84) with Postgres SQL (10.17)

We also want to migrate to Drupal 9 version and followed step to use Composer file, but while using it gives error 

[1] https://www.drupal.org/docs/develop/using-composer/using-composer-to-install-drupal-and-manage-dependencies#adding-modules

[@ip-1xxx.xx wwwroot]$ composer require drupal/migrate_plus:^4.2 drupal/migrate_tools:^4.3

[ErrorException]
file_put_contents(./composer.json): failed to open stream: Permission denied

require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>]...

Observations :
= = = = =
>> We checked whether composer is installed properly by executing the below command:
$ composer
>> Modified the owner permissions:
$ sudo chown -R $USER ~/.composer/

Still no luck
## Version Info
This can be the version you can see on admin/modules in Drupal or 
the output of this command: `composer show`.  Add Drupal core and
other version information if needed.

Kindly assist in resolving the issue.

**Comment by phdhiren** [comment]
@pankaj-sharma31 
Probably you've used custom theme or base bootstrap theme. Check configuration around Appearance.

It was great to hear that you will migrate to Drupal 9. Here is some reference for migrating Drupal 7 to 9 as a whole-  https://www.drupal.org/docs/upgrading-drupal
Specific to developer portal and related modules
https://www.drupal.org/docs/8/modules/apigee-developer-portal-kickstart/migrate-drupal-7-developer-portal-entities


Please note that current repository and issue queue is for apigee_edge module for Drupal 9
