### ISSUE TITLE
Installation of Apigee Module is crashing the Drupal site

### ISSUE THREAD

**Issue by NNV111** [apigee/apigee-edge-drupal#669]
Drupal 9.3.5 has been set up in AWS Linux 2. Trying to set up the APIGEE_EDGE module (tar file downloaded for the following link - https://www.drupal.org/project/apigee_edge).
Drupal - 9.3.5; PHP - 8.0, MariaDB - 10.5, Apigee edge module- 2.0.2
After uploading, when trying to enable the uploaded module, then entire site crashes and is throwing an error saying "The website encountered an unexpected error. Please try again later.
Error: Class 'Drupal\apigee_edge\ParamConverter\ApigeeEdgeLoadUnchangedEntity' not found in Drupal\Component\DependencyInjection\Container->createService() (line 262 of core/lib/Drupal/Component/DependencyInjection/Container.php)."

Drupal\Component\DependencyInjection\Container->createService(Array, 'paramconverter.apigee_edge_load_unchanged_entity') (Line: 176) Drupal\Component\DependencyInjection\Container->get('paramconverter.apigee_edge_load_unchanged_entity', 1) (Line: 437) Drupal\Component\DependencyInjection\Container->resolveServicesAndParameters(Array) (Line: 276) Drupal\Component\DependencyInjection\Container->createService(Array, 'paramconverter_manager') (Line: 176) Drupal\Component\DependencyInjection\Container->get('paramconverter_manager', 1) (Line: 437) Drupal\Component\DependencyInjection\Container->resolveServicesAndParameters(Array) (Line: 240) Drupal\Component\DependencyInjection\Container->createService(Array, 'route_enhancer.param_conversion') (Line: 176) Drupal\Component\DependencyInjection\Container->get('route_enhancer.param_conversion', 1) (Line: 437) Drupal\Component\DependencyInjection\Container->resolveServicesAndParameters(Array) (Line: 276) Drupal\Component\DependencyInjection\Container->createService(Array, 'router.no_access_checks') (Line: 176) Drupal\Component\DependencyInjection\Container->get('router.no_access_checks', 1) (Line: 437) Drupal\Component\DependencyInjection\Container->resolveServicesAndParameters(Array) (Line: 240) Drupal\Component\DependencyInjection\Container->createService(Array, 'router') (Line: 176) Drupal\Component\DependencyInjection\Container->get('router', 1) (Line: 437) Drupal\Component\DependencyInjection\Container->resolveServicesAndParameters(Array) (Line: 240) Drupal\Component\DependencyInjection\Container->createService(Array, 'router_listener') (Line: 176) Drupal\Component\DependencyInjection\Container->get('router_listener') (Line: 136) Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch(Object, 'kernel.request') (Line: 134) Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 80) Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 58) Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 48) Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 191) Drupal\page_cache\StackMiddleware\PageCache->fetch(Object, 1, 1) (Line: 128) Drupal\page_cache\StackMiddleware\PageCache->lookup(Object, 1, 1) (Line: 82) Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 48) Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 51) Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23) Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 708) Drupal\Core\DrupalKernel->handle(Object) (Line: 19)

Tried downgrading PHP to 7.4 as well, still throws the same error. 
Have tried installing the Apigee_edge module using composer as well i.e. composer require 'drupal/apigee_edge:2.0.2' command
Still throws a similar error. 
Please let me know what fix needs to be provided to resolve the issue

**Comment by phdhiren** [comment]
@NNV111 
Currently PHP 8 is not supported with apigee_edge, however that's under active development.

I encourage you to install the module via composer instead of tar ball, remove earlier reference of the module which you'd extracted manually
```
cd /path/to/drupal/root
composer require drupal/apigee_edge
```

**Comment by jjmackow** [comment]
Rather than using Drupal 9.3.x, try using the 9.2.x stream.  https://www.drupal.org/project/drupal/releases/9.2.16 with PHP 7.4,
Drupal 9.3.0 has some information in its [release notes](https://www.drupal.org/project/drupal/releases/9.3.0) under PHP dependencies

One other thing you might try that worked for me, using the Drupal 9.3.x and PHP 7.4 is adding the following to your composer.json file in the require section...
 
 "egulias/email-validator": "2.1.25 as 3.1.2",

the email_validator 3.1.2 library is not compatible with PHP 8.0 , and this line will alias 2.1.25 to that version.
PHP 8.0 EOL is in November of this year, but it appears that work is being done to update the issues with the library.
