### ISSUE TITLE
Add team members intermittently not adding members to team

### ISSUE THREAD

**Issue by rameshvk22** [apigee/apigee-edge-drupal#691]
## Description
Sometimes when we try to add members to team it was not adding even though we get message saying it successfully added to the team .We cannot see that members under teams and also we cannot verify backend (apigee managment api) because we cannot get  member details using management api.

## Steps to Reproduce
1.Selected team one and removed member X
2. Selected team two and added the member X.
3. Removed X from team two
4. Added back member X to team two
5. Removed X from team two
6. Added  back member X to team two -->This is where its not adding .Looks like cache object queuing up and cause the issue .

## Actual Behavior
Member not adding members to team eventhough we got messgae :-The following developer has been invited to the team two team: X.

## Expected Behavior
We should be seeing member X under team team two.

## Screenshots
<img width="1563" alt="testteam_member_after adding pking" src="https://user-images.githubusercontent.com/6742220/165792865-a92a9461-bff0-4491-8a05-4260297c32ae.png">
<img width="1703" alt="testteam_members" src="https://user-images.githubusercontent.com/6742220/165792879-dfcb8d72-611e-4867-8334-19d92f4d40a5.png">
<img width="1556" alt="team one after remove user pking" src="https://user-images.githubusercontent.com/6742220/165792888-85f83c66-9521-40f4-bb59-75cafbee21b8.png">
<img width="1732" alt="Team one members" src="https://user-images.githubusercontent.com/6742220/165792891-4194fe13-164f-4153-b77f-c3b0b75b5932.png">

## Version Info
This can be the version you can see on admin/modules in Drupal or 
the output of this command: `composer show`.  Add Drupal core and
other version information if needed.

drupal/core                               9.3.12
drupal/apigee_edge                        2.0.2

**Comment by phdhiren** [comment]
@rameshvk22 

I'm trying to replicate the issue on my local.

**Comment by rameshvk22** [comment]
Thanks let me know if you need more info. We are trying to make status 1(Accepted) always. But sometimes its updated as 0 We believe that is due to caching. 
**Here is the code snippet .**
function invitation_final_status_change($form, $form_state) {
  $emails = array_map('trim', explode(',', $form_state->getValue('developers', '')));
  $storage = Drupal::entityTypeManager()->getStorage('team_invitation');
  foreach ($emails as $email) {
    kint(email);
    $invitations = $storage->loadByRecipient($email);
    if($invitations) {
      $path = \Drupal::request()->getpathInfo();
      $arg  = explode('/',$path);
      $team = $arg[2];
      $query = \Drupal::database()->select('team_invitation', 'n');
      $query->addField('n', 'uuid');
      $query->condition('n.team', $team);
      $query->condition('n.recipient', $email);
      $results = $query->execute()->fetchAll();
      $uuid = $results[0]->uuid;
      $first = $invitations[$uuid];
      $first->setStatus(TeamInvitationInterface::STATUS_ACCEPTED)->save();
    }
  }
}

**Comment by phdhiren** [comment]
@rameshvk22 

How is the above code snippet getting triggered? Is it somewhere in your custom module?

**Comment by rameshvk22** [comment]
Hook function form_later
function sbux_teams_form_apigee_edge_teams_add_team_member_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
{
  $form['username'] = array(
    '#title' => t('Username'),
    '#type' => 'entity_autocomplete',
    '#target_type' => 'user',
    '#size' => 35,
    '#tags' => TRUE,
    '#required' => TRUE,
    '#weight' => 0
  );

  $form['developers'] = FALSE;
  $form['save'] = array(
    '#type' => 'submit',
    '#value' => t('Add Users')
  );
  $form['#submit'][] = 'invitation_final_status_change';

  $validation[0] = "invitation_custom_validation";
  $validation[1] = $form['#validate'][0];
  $form['#validate'] = $validation;

  unset($form['actions']);
}

**Comment by rameshvk22** [comment]
also we need to disable email notification

**Comment by giteshk** [comment]
@rameshvk22 Can you review the PR and see if it works for you.

We are trying to add an option to disable approvals for adding someone to the Team.

**Comment by rameshvk22** [comment]
Thank you I have tested .It disabled email notification but I can see one bug .
I have1.  Added member A to Team X -->It is added to the team X
2.Removed member A from Team X--> It is removed from the team X
3.Added member A from Team X- --> It is giving message saying "The following developer has been added to the X team: A." but it is not showing up in the team members list.
When I checked **team_invitation** table status **0** instead of 1  I think thats what it causing the issue.

Thanks,
Ramesh Kuckian

**Comment by phdhiren** [comment]
@rameshvk22 

Can you confirm you've used the above patch along with the cache issue patch in #699 and checked the `Auto approve team membership for existing user`

**Comment by phdhiren** [comment]
@rameshvk22 
Can you also confirm if the custom code which was written has been removed after applying both patches?

**Comment by rameshvk22** [comment]
Yes . I have tested by removing the custom code and it is working as expected .We have added custom code for
1. Auto populate existing users 
2. To change Label Instead of Invite Members .We use Add Member both button as well as status message.

Please let us know when patch will be available.

**Comment by phdhiren** [comment]
Thank you for confirming, I'll merge this change. We should be releasing a new version by next week.

**Comment by rameshvk22** [comment]
@phdhiren @giteshk  Please let us know once  new release available.

**Comment by giteshk** [comment]
@rameshvk22 We have published a new release. Feel free to reopen if there are any issues.
