### ISSUE TITLE
Team invitations do not play nicely with Drupal Core JsonApi

### ISSUE THREAD

**Issue by audave** [apigee/apigee-edge-drupal#727]
Trying to update a team invitation via drupal core's jsonapi module gives the following error

`            "title": "Unprocessable Entity",
            "status": "422",
            "detail": "The attribute 0 does not exist on the team_invitation--team_invitation resource type.",
`

This can be fixed by adding the uuid to the entity keys
Line 68 modules/apigee_edge_teams/src/Entity/TeamInvitation.php

` *   entity_keys = {
  *     "id" = "uuid",
  *     "label" = "label",
  *     "owner" = "uid",
  *     "uuid" = "uuid",
  *    },`

**Comment by shishir-intelli** [comment]
Hi @audave,

Can you please share the steps to reproduce this behavior and the version information.

**Comment by audave** [comment]
Version 2.0.4

Enable this module & the jsonapi module. 

Send a curl request something like below. Obviously the end point will need to be updated. 

`curl --location --request POST 'http://example.com/api/v1/team-invitations' \
--header 'Content-Type: application/vnd.api+json' \
--data-raw '{
    "data": {
        "type": "team_app--team_app",
        "attributes": {
         "label": "Invitation to join atotesting as Member",
         "recipient": "collaborator2@test.com.au"

        },
        "relationships": {
            "team": {
                 "data": {
                        "type": "team--team",
                        "id": "testing"
                    }
            },
            "team_roles": {
               "data": {
                   "type": "team_role--team_role",
                   "id": "e9284307-4cb8-4793-8853-d80e976819e2"
               }
            }
        }
    }
}`

**Comment by thursdaybw** [comment]
This patch causes "Array to string conversion" error when importing the entity schema for team_invitation entity type, in a kernel test on during module install.

This is due to a core bug relating to uuid's and entity ids: see https://www.drupal.org/i/3310170

The merge request on that issue, as of today resolves the issue, but still needs a lot of work to become ready.
