### ISSUE TITLE
Error sending email with capitalization to Apigee.

### ISSUE THREAD

**Issue by dpagini** [apigee/apigee-edge-drupal#730]
## Description
Our organization is using SSO to log users into the developer portal. This creates a user in Drupal, and our identity provider is sending over the users email address. The email address gets saved with proper capitalization, so I am `David.Pagini@organization.com`. When the module takes this user and create them as a developer in Apigee, we are getting an error that email address must be lower case.

## Expected Behavior
I would expect that a Developer get created on the Apigee side.

## Screenshots
![image](https://user-images.githubusercontent.com/1724163/186952419-1ab4945d-59cc-4ead-8223-e8db97e3a4c6.png)

## Notes
I guess I would suggest that all users get set/synced to apigee with a lowercase email address.

## Version Info
Drupal core 9.4.5
Apigee_edge 2.0.4
DevPortal_Kickstart 2.1.0

**Comment by shishir-intelli** [comment]
Hi @dpagini 
Could you please tell us which Apigee Organization you are using, are you using `Apigee Edge` or `Apigeex`?

**Comment by dpagini** [comment]
Apigee X (Endpoint: https://apigee.googleapis.com/v1)

**Comment by shishir-intelli** [comment]
Hi @dpagini ,
Thank you for raising this issue. 
Yes, Apigeex Org is not accepting capitalized email addresses and Drupal portal does.

We are investigating this issue, We will keep you posted on any further update.

**Comment by dpagini** [comment]
Thanks. I would think that, the controller responsible for calling Apigee simply needs to perform a lowercase conversion on the user email before sending to Apigee?

**Comment by dpagini** [comment]
If you are able to provide a patch or diff, I'm happy to help test out. Thank you @shishir-intelli!

**Comment by shishir-intelli** [comment]
Thanks @dpagini 
Sure,
We are working on this issue, I will share a patch as soon as it's resolved.

**Comment by shishir-intelli** [comment]
Hi @dpagini 

Apologies for the delayed response.

To fix this issue, we decided to lower-case the email address for Apigee-X Org due to case sensitive restrictions.
I have attached a patch which fixes this issue.
[patch_730_1.txt](https://github.com/apigee/apigee-edge-drupal/files/9938849/patch_730_1.txt)

Please try this patch and let me know if this resolves your issue.

**Comment by dpagini** [comment]
I feel like this issue shouldn't be closed as there is still an open PR for this issue...? And that PR definitely has open conversations around approach...
