### ISSUE TITLE
Apigee Edge throws errors on site install.

### ISSUE THREAD

**Issue by dpagini** [apigee/apigee-edge-drupal#731]
## Description
When installing a new site with apigee_edge, that does not yet have a connection set up, the apigee_edge module throws hard errors when a connection key is not found.

## Steps to Reproduce
1. Install a site with `$ drush site:install apigee_devportal_kickstart`
2. View errors in output.

## Actual Behavior
You will see an error that a key to connect to apigee does not exist.

![image](https://user-images.githubusercontent.com/1724163/186984087-2eb476de-f546-4dc7-8531-70ec49248b14.png)

## Expected Behavior
If the key hasn't been set yet, the system shouldn't throw a hard error. How about a warning message?

## Version Info
Drupal core 9.4.5
Apigee_edge 2.0.4
DevPortal_Kickstart 2.1.0

**Comment by phdhiren** [comment]
@dpagini 
Thank you for your contribution. I'll try to replicate and get back to you.

**Comment by shishir-intelli** [comment]
Hi @dpagini 
Since `Drush si` cannot set default values for Apigee configuration, the portal is not able to connect to Apigee for creating a developer entity due to missing Apigee edge/x configuration durning Drupal installation.

I am creating a PR to fix this issue.
