### ISSUE TITLE
Add Apigee Edge “Team switcher” block programmatically to a content page in Drupal 9 

### ISSUE THREAD

**Issue by huilinks** [apigee/apigee-edge-drupal#739]
Hi,

I try to add Apigee Edge “Team switcher” programmatically to a content page in Drupal 9 portal. 

In my controller class, I use the following calls to render “Team switcher”  block according to https://drupal.stackexchange.com/questions/171686/how-can-i-programmatically-display-a-block

$block = \Drupal\block\Entity\Block::load('teamswitcher');
$render  = \Drupal::entityTypeManager()->getViewBuilder('block')->view($block);;
return $render;

But it returns an empty page. Can you help me with this issue?

Thanks,
Hui

**Comment by divya-intelli** [comment]
Hi @huilinks ,
Please check the condition:
https://github.com/apigee/apigee-edge-drupal/blob/563486e85acf012e5a1401b007277288dadcc7f4/modules/apigee_edge_teams/src/Plugin/Block/TeamContextSwitcherBlock.php#L139  
and 
Function : https://github.com/apigee/apigee-edge-drupal/blob/563486e85acf012e5a1401b007277288dadcc7f4/modules/apigee_edge_teams/src/TeamContextManager.php#L55 

As per above null will be passed if route does not have the options parameter. 
You will have set the below options in custom route.
<pre>
options:
   _apigee_team_route: 'entity.team.canonical'
   parameters:
     user:
       type: entity:user
</pre>

**Comment by huilinks** [comment]
After adding the above option in my custom route, it still returns empty.

my_programs.content:
  path: '/developer-programs'
  defaults:
    _controller: '\Drupal\my_programs\Controller\MyController::content'
  requirements:
    _permission: 'access content'
  options:
    _apigee_team_route: 'entity.team.canonical'
    parameters:
      user:
        type: entity:user

**Comment by divya-intelli** [comment]
Hi @huilinks , you will have to give /{user} in your path.

**Comment by huilinks** [comment]
I get the following error after adding /{user} in my path.

Symfony\Component\Routing\Exception\MissingMandatoryParametersException: Some mandatory parameters are missing ("user") to generate a URL for route "my_programs.content".

**Comment by huilinks** [comment]
content method in my controller class

  public function content(AccountInterface $user, Request $request) {
      $block = \Drupal\block\Entity\Block::load('teamswitcher');
      $render = \Drupal::entityTypeManager()->getViewBuilder('block')->view($block);
      
	  return $render;
  }
