### ISSUE TITLE
Error while editing Team App

### ISSUE THREAD

**Issue by Maheshcv63** [apigee/apigee-edge-drupal#751]
## Description
We are using Apigee Developer portal kickstart project. Experiencing a website encountered an unexpected error while editing **Team** App. While looking into the logs getting this error **TypeError: Argument 1 passed to Drupal\Core\Render\Element::children() must be of the type array, null given, called in /code/web/modules/contrib/apigee_edge/modules/apigee_edge_teams/src/Entity/Form/TeamAppEditForm.php on line 100 in Drupal\Core\Render\Element::children() (line 72 of /code/web/core/lib/Drupal/Core/Render/Element.php)**

## Steps to Reproduce
1. Log into the portal as admin and navigate '/admin/config/apigee-edge/app-settings/general' then uncheck the checkbox 'let user select the products' and select any default API products from products list.
2. Create a Team and create an App under the team.
3. After App created then click on edit app.
4. After clicking on edit will see a website encounter error on the screen.

## Version Info
Drupal -9.4.7
Apigee Developer portal kickstart project (Apigee Edge-2.0.5)

**Comment by shishir-intelli** [comment]
HI @Maheshcv63 
Thank you for your contribution.

We are investigating this issue, We will keep you posted on further updates.
