### ISSUE TITLE
Double quotes adding in Apigee Edge when we use space in Team App custom attributes from developer portal

### ISSUE THREAD

**Issue by Maheshcv63** [apigee/apigee-edge-drupal#760]
## Description
We are using Apigee Developer portal kickstart project. Here is the issue "Double quotes adding in Apigee Edge when we use space in Team App custom attributes from developer portal". This also happening for developer apps too.
## Steps to Reproduce
1. Go to '/admin/config/apigee-edge/app-settings/team-apps/fields'
2. Click on '+Add field' to create new custom attribute.
3. Then navigate to '/teams' and click 'Add team' button to create team.
4. After that click on Add team app under the team created in previous step '/teams/{team_name}/create-app'.
5. Enter App name and description then enter a text with space in custom created attribute(ex: test custom attribute).
6. Click on create app.
7. Navigate to Apigee Edge (login.apigee.com) and go to the app created with custom attribute.
8. Go down to the attributes list there you can see custom attribute value within double quotes(ex: "test custom attribute")

## Expected Behavior
Double should not add to the custom attribute under Team App

## Version Info
Drupal -9.4.7
Apigee Developer portal kickstart project (Apigee Edge-2.0.5)
PHP - 7.4

**Comment by shishir-intelli** [comment]
Hi @Maheshcv63 ,

Yes, It adds a double quote for string value and while rendering in the Drupal portal it shows string without quotes.
Could you please let us know what issue you are facing because of the double quote in Teams app.

**Comment by Maheshcv63** [comment]
@shishir-intelli ,

Thanks for your response, It's not an issue in Drupal portal. We are using the custom attribute values in proxy configuration for partner validation. When we use the custom attribute value it's fetching the value including double quotes as it's considering as incorrect value while validation. Is there any way that something we can remove double quotes while creating App?

**Comment by shishir-intelli** [comment]
Hi @Maheshcv63 , 
Apologies for the delay in response.

Those quotes are added by JSON and there is nothing wrong with it.
But in your case this is causing an issue, so I am attaching a patch to resolve this issue.
[patch_760.txt](https://github.com/apigee/apigee-edge-drupal/files/10182421/patch_760.txt)

Please apply this patch and let me know if this patch helps.
Thanks!

**Comment by shishir-intelli** [comment]
@Maheshcv63 ,
Please let us know if the above patch worked and resolves the issue.

**Comment by shishir-intelli** [comment]
Closing this issue for now, Feel free to reopen if the problem still exists. 
Thank you.
