### ISSUE TITLE
(Developer) app creation fails with keymanagement.service.ApiProductsRequired

### ISSUE THREAD

**Issue by mxr576** [apigee/apigee-edge-drupal#766]
## Description
This is another issue that we have bumped into with the same customer as in #764. However in this case it is 99% sure that the issue is caused by the `features.keymanagement.disable.unbounded.permissions` feature flag set TRUE on the Apigee org. One of the things that this flag change is:

> When creating a developer or company app, the management API requires that the app be associated with an API product. (The management UI already enforces this.)

(source: https://docs.apigee.com/release/notes/180202-apigee-edge-public-cloud-release-notes)

This feature flag is a 2018 invention, yet (AFAIK) nobody has ever reported that when that feature flag is enabled then the way how this Drupal module creates an app does not work anymore. 

This module first tries to create an "empty app"  without and after assigning a credential (with selected API products) to the created app. With this feature flag enabled it MUST do this in one API call, which is technically possible on the Apigee side.

See: https://github.com/apigee/apigee-edge-drupal/blob/2.0.6/src/Entity/Form/AppForm.php#L133-L175

## Apigee Info
Apigee Edge

## Steps to Reproduce

Have the given feature flag enabled on an organization and create a developer app.

## Actual Behavior

App creation fails with an error message and the following in the logs

```
{
    "code": "keymanagement.service.ApiProductsRequired",
    "message": "API products required",
    "contexts": []
}

```

## Expected Behavior

The app is created.

## Version Info
2.0.16

**Comment by shishir-intelli** [comment]
Thank you @mxr576  for reporting this issue and #764 ,
We are looking into this issue and keep you posted with the updates.

**Comment by gosunilgo** [comment]
@mxr576  @shishir-intelli  -  FYI I've enabled this in production and lower-envs -  OPDK 4.51.   Developers are forced to add single product to their app (individual or team/company)   We don't allow "skeleton"  api-keys, at minimum developers can add our oauth2 product - either through CI automation (python) or devportal.

**Comment by mxr576** [comment]
https://github.com/apigee/apigee-client-php/issues/214 is needed to get this solved.
