### ISSUE TITLE
API Access Key page isn't showing/hiding the API Key

### ISSUE THREAD

**Issue by uceap-web** [apigee/apigee-edge-drupal#789]
## Description
In the App listing page collapsible card, the collapsible API key is not working when clicking on it. The **Show key** link is not working.

drupal/apigee_edge 2.0.7 requires php ^8.0 but we can't proceed with the upgrade yet due to some compatibility issues with other modules we are using. _Upgrading to PHP 8.0 and latest drupal/apigee_edge 2.0.7 fixes the bug._ 

Is it possible you provide a patch for drupal/apigee_edge 2.0.6 while we get ready to use PHP 8.0? Thanks.

## Apigee Info
Apigee Edge

## Steps to Reproduce
1. Go to '/apps'
2. Click on 'Add app' to create a new app
3. Once the app is created, click on the app which we just created to check the App details.
4. Click Show key to show/hide

## Actual Behavior
Key is not visible, user is unable to view their consumer secret key when clicking the `Show key` link.

## Expected Behavior
Users should be able to view their API credentials (Consumer Key / Consumer Secret) when clicking the `Show key` link.

## Screenshots

![show-key-not-working](https://user-images.githubusercontent.com/19273307/215640798-03d9ee4c-977b-4ca1-98dc-dcb4851b5b65.png)

## Notes

The root issue is that the click handler that provides show/hide functionality is being added to the element twice. So, when the Show key button is clicked, the first click handler executes and shows the value and then the second click handler executes and hides the value.

## Version Info
Drupal 9.5.2
PHP 7.4.30
drupal/apigee_edge 2.0.6

**Comment by phdhiren** [comment]
@uceap-web 

I strongly recommend upgrading to the latest PHP and apigee modules. This [commit](https://github.com/apigee/apigee-edge-drupal/commit/b38531b3ba95dd8f1235ffe13a9c193798d0438f) should be able to help.
