### ISSUE TITLE
Retire 1.x branch

### ISSUE THREAD

**Issue by mxr576** [apigee/apigee-edge-drupal#801]
Is there a reason why still two major versions are available and support from this module? Now that #800 was merged, that restored PHP 7.4 support (:scream_cat: ) and it was said that [2.1.x](https://github.com/apigee/apigee-edge-drupal/issues/796#issuecomment-1438603328) minor branch gets opened, this module most probably have way too many supported branches.

**Comment by mxr576** [comment]
@giteshk @phdhiren please reopen, thx :)

**Comment by divya-intelli** [comment]
Closing this issue as we have 2.x(for Drupal 9) and 3.x(Drupal 10)
