### ISSUE TITLE
Background developer sync queues are not executed via CRON

### ISSUE THREAD

**Issue by tnagyce** [apigee/apigee-edge-drupal#802]
## Description
Setting up background developer sync and executing CRON doesn't process the apigee_edge_jobs queue items.

## Apigee Info
Apigee EDGE, although it seems like limited only to Drupal.

## Steps to Reproduce
1. Install a Drupal site with the apigee module.
2. Enable and setup the apigee edge module.
3. Make sure you have a few developers to sync on apigee.
4. Go to the "/admin/config/apigee-edge/developer-settings/sync" page and press the "Background developer sync" button.
5. Executing `drush queue-list` shows that there is one item in the queue.
6. Execute CRON via `drush cron` or on the UI (/admin/config/system/cron).
7. Check with `drush queue-list` again, now there are two items in the queue. (If you pressed the "Background developer sync" button multiple times, the number of newly added items will be duplicated).
8. Execute CRON again and check with `drush queue-list`, the queue items are not processed.

## Actual Behavior
Apigee edge job queue items are not getting processed.

## Expected Behavior
Apigee edge job queue items should be processed during CRON.

## Notes
It seems like that one of the problems that the `@QueueWorker` annotation is missing the cron key, without that Drupal won't execute the queue worker: \Drupal\Core\Cron::processQueues():172

However adding the `cron = {"time" = 60}` to the queue worker there seems to be another problem after running CRON, the developers are still not being synced, but the queue items are processed like this with no result.

## Version Info
apigee/apigee-client-php: 2.0.17
drupal/core-recommended: 9.5.3

**Comment by mxr576** [comment]
The underlying Drupal core issue is being discussed here: https://www.drupal.org/project/drupal/issues/3308358

**Comment by tnagyce** [comment]
@shishir-intelli Can you reopen the ticket? I think it is still not entirely fixed. Once the `cron` option is set the queue items gets processed, but no actual developer sync is happening. (I've tried to describe this under "Notes" originally.)

**Comment by shishir-intelli** [comment]
@ycecube 
https://github.com/apigee/apigee-edge-drupal/pull/814 fixes this issue.

Closing this issue for now, Feel free to reopen if the problem still exists.
