### ISSUE TITLE
SA missing permission for apigee.environments.list

### ISSUE THREAD

**Issue by cen1** [apigee/apigee-edge-drupal#807]
## Description
In the documentation here: https://www.drupal.org/docs/contributed-modules/apigee-edge/configure-the-connection-to-apigee#configure-credentials-hybrid
it is said to create an SA with the role of `Apigee Developer Administrator`. However, this role is lacking the permission of `apigee.environments.list` which causes the following issues:

1. Error in the common App settings tab where you can't select the supported environments
2. Error on the developer's app analytics tab, because it tries to fetch the analytics for the default `prod` environment instead of the environment which should be selected in point 1.

One possible workaround is adding `Apigee Analytics Viewer` to the SA which adds the missing permission.

## Apigee Info
Apigee X

## Steps to Reproduce
1. Create SA account with `Apigee Developer Administrator`
2. Configuration -> Apigee -> Apps -> General -> Analytics
3. Page is not working
 
## Actual Behavior
App analytics not working

## Expected Behavior
The documented role should have the missing permission or the documentation should add the appropriate additional roles.

## Version Info
2.0.5

**Comment by giteshk** [comment]
I have added a ticket internally and this is being fixed. Will take a few weeks to rollout.

In the mean time you can create a custom role with that apigee.evironments.list permission and assign it to the Service account that you are using.

**Comment by giteshk** [comment]
I believe this has been fixed in the Apigee Developer Admin role.

Please re-open if you see any other issues.
