### ISSUE TITLE
Sort API Products 

### ISSUE THREAD

**Issue by ssrtx** [apigee/apigee-edge-drupal#811]
We have installed Drupal 9 Apigee Kickstart  with connection to a  Apigee Edge Private Cloud instance.
Is there a way to  sort the list of API Products that are displayed in the  "Add App" form?

**Comment by shishir-intelli** [comment]
Hi @ssrtx ,

There is no such feature for sorting API Products in the Drupal portal or in the admin config as of now.
However, you can achieve this feature by customizing the module.

**Comment by giteshk** [comment]
@ssrtx , Is the list of the API Products displayed not sorted alphabetically?

@shishir-intelli, can we validate this?

**Comment by ssrtx** [comment]
@shishir-intelli,
Thanks for the recommendation.

@giteshk ,
We have validated the unsorted  API Products list on two separate installations of Devportal Kickstart with connections to  Apigee Edge Private Cloud 4.51.0

Attached screenshot from our Sandbox environment that shows unsorted list of API Products:

![image](https://user-images.githubusercontent.com/101755169/222497960-06146fa4-dc7f-4021-b65d-bb6ff922611e.png)

**Comment by giteshk** [comment]
@ssrtx , If you create a patch to fix this in our apigee-edge-drupal module. 
We can review and accept the patch.

We appreciate community contributions.

**Comment by shishir-intelli** [comment]
> @ssrtx , Is the list of the API Products displayed not sorted alphabetically?
> 
> @shishir-intelli, can we validate this?

@giteshk 
Yes, It is unsorted

**Comment by shishir-intelli** [comment]
Hi @ssrtx ,

I hope this patch fix your issue.
[patch-apiproduct-keysort.txt](https://github.com/apigee/apigee-devportal-kickstart-drupal/files/10882132/patch-apiproduct-keysort.txt)

Please apply this patch and let me know if this resolves your sorting issue.

**Comment by ssrtx** [comment]
Thanks @shishir-intelli
The patch resolved the sorting issue.
Appreciate the the quick turnaround.
