### ISSUE TITLE
Call to undefined method Apigee\Edge\Api\Management\Entity\DeveloperApp::setInitialApiProducts() 

### ISSUE THREAD

**Issue by apidevdru** [apigee/apigee-edge-drupal#820]
## Description
I have just upgraded the last version of apigee_edge version 2.0.10
## Apigee Info
Please specify if you are using Apigee X, Apigee Edge, or OPDK.
Apigee X
## Steps to Reproduce
1. Create a new user in the developer portal
2. Clic on create an App
3. There is a problem on the website 
4. Visit logs

## Actual Behavior
What happened after the steps to reproduce.
There is not possible to create an app
## Expected Behavior
Create app for developers
## Screenshots
```
Error: Call to undefined method Apigee\Edge\Api\Management\Entity\DeveloperApp::setInitialApiProducts() en Drupal\apigee_edge\Entity\App->setInitialApiProducts() (línea 465 de /app/modules/contrib/apigee_edge/src/Entity/App.php)
#0 /app/modules/contrib/apigee_edge/src/Entity/Form/AppForm.php(136): Drupal\apigee_edge\Entity\App->setInitialApiProducts(Array)
#1 /app/modules/contrib/apigee_edge/src/Entity/Form/FieldableEdgeEntityForm.php(73): Drupal\apigee_edge\Entity\Form\AppForm->buildEntity(Array, Object(Drupal\Core\Form\FormState))

```## Notes
Add any other context about the problem here.

## Version Info
This can be the version you can see on admin/modules in Drupal or 
the output of this command: `composer show`.  Add Drupal core and
other version information if needed.

Drupal core 9.5.5

**Comment by mxr576** [comment]
@apidevdru Can you please share the version of the `apigee/apigee-client-php` library that you are using? I think you are using an older version than 2.0.19. You can update it with `composer update apigee/apigee-client-php`.

As a generic advice, whenever you update the Drupal module you should also update the PHP API client too.

**Comment by mxr576** [comment]
If that is true, I am curious how your project can use an older version of the PHP API client library when 2.0.10 also updated the minimum required PHP API client library. (Earlier I though that was forgotten.)

https://github.com/apigee/apigee-edge-drupal/compare/2.0.9...2.0.10#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34R9

**Comment by giteshk** [comment]
Please upgrade to the [latest release](https://github.com/apigee/apigee-client-php/releases)  of apigee/apigee-client-php.

That should fix the issue you are facing. 

Feel free to re-open the ticket if you continue to face issues.

**Comment by apidevdru** [comment]
Thank you so much for your help. I updated **apigee-client-php** from **2.0.17** to **2.0.19**
**composer update apigee/apigee-client-php**
Gathering patches for root package.
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Lock file operations: 0 installs, 1 update, 0 removals
  - Upgrading apigee/apigee-client-php (**2.0.17** => **2.0.19**)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Downloading apigee/apigee-client-php (2.0.19)
Gathering patches for root package.
Gathering patches for dependencies. This might take a minute.
  - Upgrading apigee/apigee-client-php (2.0.17 => 2.0.19): Extracting archive
Package doctrine/reflection is abandoned, you should avoid using it. Use roave/better-reflection instead.
Package symfony/debug is abandoned, you should avoid using it. Use symfony/error-handler instead.
Package symfony/inflector is abandoned, you should avoid using it. Use EnglishInflector from the String component instead.
Package jeremeamia/superclosure is abandoned, you should avoid using it. Use opis/closure instead.
Package webmozart/path-util is abandoned, you should avoid using it. Use symfony/filesystem instead.
Generating autoload files
Hardening vendor directory with .htaccess and web.config files.
96 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Cleaning installed packages.

**Comment by apidevdru** [comment]
> he Drupal module you should also update the PHP API client too

Thank you, I will do it.

**Comment by mxr576** [comment]
I am still curious how could you install the latest version of the Apigee Edge module with Composer, without being forced to update to the latest version of the PHP API client. Composer should not allow/do the upgrade to the latest Apigee Edge module version without also updating the PHP API client.

**Comment by apidevdru** [comment]
I was able to install the latest Apigee Edge module, without upgrade PHP API Client :) I don't know how or why. But when I updated the PHP Client it works without problems. Thank you so much.
