### ISSUE TITLE
Apigee developer sync cron job

### ISSUE THREAD

**Issue by huilinks** [apigee/apigee-edge-drupal#821]
## Description
I need sync developers with Apigee Edge every 15 minutes. So I create a custom module with hook_cron, i.e my_cron.
I set up my_cron job to run every 15 minutes from /admin/config/system/cron/jobs.

But my_cron get "Maximum execution time of 120 seconds exceeded" error.

## Apigee Info
My developer portal uses Drupal 9.5.5, with Apigee Edge 2.0.10
PHP version 8.1.14

## Steps to Reproduce
1. Install a Drupal 9.5.5 site with the apigee module 2.0.10.
2. Enable and setup the apigee edge module.
3. Create a Apigee developer sync cron job to run every 15 minutes.
4. Go to /admin/config/system/cron/jobs to run the cron job.

## Actual Behavior
The  "Maximum execution time of 120 seconds exceeded" error occurs.

## Expected Behavior
A successful message of cron job completes.

## Screenshots
![image](https://user-images.githubusercontent.com/76076562/226657413-dac45c9a-a112-47b3-b8d3-e11dfaad3d13.png)

## Version Info
This can be the version you can see on admin/modules in Drupal or 
the output of this command: `composer show`.  Add Drupal core and
other version information if needed.
[composer_show.txt](https://github.com/apigee/apigee-edge-drupal/files/11030112/composer_show.txt)

**Comment by huilinks** [comment]
Try both custom crons below, and all get the same "Maximum execution time of 120 seconds exceeded" error.

1. custom cron calls DeveloperSyncController
function my_cron() { 
    \Drupal::logger('my_cron')->notice('Developer sync start ***********', []);
    $batch = DeveloperSyncController::getBatch();
    
    foreach ($batch['operations'] as $operation) {
        $context = [
            'finished' => 0,
        ];
        
        while ($context['finished'] < 1) {
            call_user_func_array($operation[0], array_merge($operation[1], [&$context]));           
            gc_collect_cycles();
        }
    }  
  
    \Drupal::logger('my_cron')->notice('Developer sync successfully', []);
}

2. custom cron calls DeveloperSync
function my_cron() {
	\Drupal::logger('my_cron')->notice('Developer sync starts 1', []);
	$filter = ((string) \Drupal::config('apigee_edge.sync')->get('filter')) ?: NULL;
	$ci = new DeveloperSync($filter);
	$result = $ci->execute();
	
	\Drupal::logger('my_cron')->notice('Developer sync successfully -'.$result, []);
}

**Comment by huilinks** [comment]
In Drupal 7, the following custom cron works, 

function my_cron() {
  devconnect_user_sync();
  watchdog('my_cron', 'Developer sync successfully');
}

**Comment by giteshk** [comment]
Please try running the cron using drush instead of the Drupal admin UI.

**Comment by huilinks** [comment]
When run "drush apigee-edge:sync" from command line, sometimes I get 401 errors when it updates Apigee developers.

When I go to /admin/config/apigee-edge/developer-settings/sync, click "Run developer sync" button to sync developers, get "Maximum execution time of 120 seconds exceeded" error.

The loadDevelopers() method in DeveloperSync.php takes over 10 minutes to complete with over 11K Apigee users.
