### ISSUE TITLE
API product RBAC when accessed PHP Fatal error:  Allowed memory size of gives  1073741824 bytes exhausted (tried to allocate 152821760 bytes) in Unknown on line 0

### ISSUE THREAD

**Issue by samhaldia** [apigee/apigee-edge-drupal#823]
## Description
Access API product RBAC page takes long time and results in 500 Error pointing to PHP Fatal error:  Allowed memory size of gives  1073741824 bytes exhausted (tried to allocate 152821760 bytes) in Unknown on line 0
Access API product RBAC page at : admin/config/apigee-edge/developer-settings/access-control
It takes long time and results in 500 Error and in logs if we see it shows:
PHP Fatal error:  Allowed memory size of gives  1073741824 bytes exhausted (tried to allocate 152821760 bytes) in Unknown on line 0
## Apigee Info
Apigee Edge 

## Steps to Reproduce
1. Go to 'admin/config/apigee-edge/developer-settings/access-control'
2. The Page takes long time to load and ends up into 500 Error code
3. In logs it says: PHP Fatal error:  Allowed memory size of gives  1073741824 bytes exhausted (tried to allocate 152821760 bytes) in Unknown on line 0

## Actual Behavior
Its failing to load the Access control Page

## Expected Behavior
The API Product RBAC should load without error

## Version Info
PHP 7.4.20 Config:
memory_limit: 1024M
max_input_vars: 10000
max_execution_time= 90
max_input_time= 60

Drupal 9.2.8
Apigee Edge: 8.x-1.25

**Comment by giteshk** [comment]
Please upgrade to the latest 2.x version of the module and test if the problem exists.

Few questions to consider: 
1. How many roles do you have in your site?
2. How many API Products do you have in your system?

**Comment by samhaldia** [comment]
Thanks for reponse, Will try to upgrade to latest version and the response to questions is as:

Few questions to consider:

How many roles do you have in your site? Around 100
How many API Products do you have in your system? Around 250

Not sure, Is these numbers impacting or causing high memory usage?

**Comment by giteshk** [comment]
I think these numbers may be why this is happening. 
Possibly 100 * 250 checkboxes to generate?

I see two options 
1.  Write your own custom module which lets you manage one role or one Product at a time.  
2. Look at other mechanisms for your RBAC to not use 100 roles.

**Comment by samhaldia** [comment]
There are few other complexities with the module.

The Apigee Product RBAC Page UI is not responsive in terms of following:

1. Even if one has 50 Roles the UI screen has lots of Horizontal  Scroll.
2. The horizontal scroll makes it complex for one to configure Product vs Roles access control mapping.

is there any possibility of enhancing the Module to address such issues in future?

Suggestions:
1. If Pagenation can be applied to Roles vs Products listing to load  limited number at a time. It will help better the UI and Load time as well
