### ISSUE TITLE
After Module update to latest version "API Products" field error raised.

### ISSUE THREAD

**Issue by Sw1m1k** [apigee/apigee-edge-drupal#827]
## Description
After Drupal and Apigee Edge module update to latest version a following error was displayed on Status Report page:

"
APP
  The API Products field needs to be installed.
"

## Steps to Reproduce
1) Update the composer.
2) Run composer update --with-dependencies --optimize-autoloader
3) Run drush updb
4) Run drush cr

## Actual Behavior
On status Report Page following error is displayed:
"
APP
  The API Products field needs to be installed.
"

## Expected Behavior
No errors should be displayed.

## Version Info
Apigee Edge module version: 2.0.10
Drupal 9.5.5

**Comment by giteshk** [comment]
@Sw1m1k Thank you for reporting this issue.

We have figured out the issue and will be fixing it next week.

**Comment by Sw1m1k** [comment]
Thank you @giteshk,

I am very waiting the fix.
