### ISSUE TITLE
Analytics issues

### ISSUE THREAD

**Issue by mejdidjaz** [apigee/apigee-edge-drupal#835]
Greetings all.

Currently we are using the Apigee Developer Portal Kickstart, based on Drupal 9.
We are facing the below issues:

- Analytics APP page is showing up the wrong time range on the chart ( See screenshots below).
The starting and ending time displayed in the Graph don’t match those specifying in time range of the filter form. 
Does somebody has an idea what could cause such a behavior?

- Excel is not showing the same time format which it is shown on Graph ( See screenshot below). 
Please advise what I should to fix this?

- I would like to know what formula is defined to display the day of month on the graph? It shows different for every month, however, it should be the same for all( See last screenshot).

![image](https://user-images.githubusercontent.com/75611310/232046123-51acdf1a-1205-4b99-be41-41980e77ff7f.png)

![image](https://user-images.githubusercontent.com/75611310/232048127-75717b06-8c1d-40ad-b8a3-f7aba98c3356.png)

![image](https://user-images.githubusercontent.com/75611310/232053761-72433433-ef8e-4e25-9f00-a1970366ceee.png)

![image](https://user-images.githubusercontent.com/75611310/232054345-b387f528-245e-44f6-82a7-ede497cb9913.png)

Thanks,

**Comment by divya-intelli** [comment]
@mejdidjaz are you using ApigeeX org?

**Comment by mejdidjaz** [comment]
@divya-intelli we are using Apigee Edge

**Comment by divya-intelli** [comment]
@mejdidjaz , Thank you for taking time to report this issue.
Can you enable the Apigee Edge debug module and share response payload when this issue occurs? Check the documentation on how to get the [debug log and remove credentials](https://www.drupal.org/docs/8/modules/apigee-edge/monitor-apigee-edge-debug-logs#configure).

**Comment by divya-intelli** [comment]
Hi @mejdidjaz ,
When passing the date range to api, the date is converted to UTC . In the downloaded **CSV** file the date is in **UTC** format.
Also the date that is on the graph is proper ie it shows the selected range. Not able to see different range as mentioned in the screenshot.
Closing this issue for now, feel free to reopen.
