### ISSUE TITLE
Team Member Roles do not play nicely with Drupal Core's JSONAPI

### ISSUE THREAD

**Issue by audave** [apigee/apigee-edge-drupal#845]
## Description
Team Member Roles are a Drupal Entity and such should be accessible using drupal core's jsonapi module.

To Replicate
Enable jsonapi module.
Go to /jsonapi/team_member_role/team_member_role

Page has a 500 error.

Patch is provided below

```diff --git a/modules/apigee_edge_teams/src/Entity/TeamMemberRole.php b/modules/apigee_edge_teams/src/Entity/TeamMemberRole.php
index b400970..e3e2fb9 100644
--- a/modules/apigee_edge_teams/src/Entity/TeamMemberRole.php
+++ b/modules/apigee_edge_teams/src/Entity/TeamMemberRole.php
@@ -20,11 +20,13 @@
 
 namespace Drupal\apigee_edge_teams\Entity;
 
+use Drupal\Core\Access\AccessResult;
 use Drupal\Core\Entity\ContentEntityBase;
 use Drupal\Core\Entity\EntityChangedTrait;
 use Drupal\Core\Entity\EntityTypeInterface;
 use Drupal\Core\Field\BaseFieldDefinition;
 use Drupal\Core\Field\FieldStorageDefinitionInterface;
+use Drupal\Core\Session\AccountInterface;
 use Drupal\user\UserInterface;
 
 /**
@@ -44,6 +46,7 @@ use Drupal\user\UserInterface;
  *   },
  *   entity_keys = {
  *     "id" = "uuid",
+ *     "uuid" = "uuid",
  *   },
  * )
  *
@@ -56,6 +59,13 @@ final class TeamMemberRole extends ContentEntityBase implements TeamMemberRoleIn
 
   use EntityChangedTrait;
 
+  /**
+   * {@inheritdoc}
+   */
+  public function access($operation, AccountInterface $account = NULL, $return_as_object = FALSE) {
+    return AccessResult::allowedIfHasPermissions($account, ['administer team', 'manage team members'], 'OR');
+  }
+
   /**
    * {@inheritdoc}
    */
```

**Comment by shishir-intelli** [comment]
Hi @audave ,

Thank you for your contribution.

Could you please also test this patch for authenticated user,
We could see this error for authenticated user
`TypeError: Drupal\Core\Access\AccessResult::allowedIfHasPermissions(): Argument #1 ($account) must be of type Drupal\Core\Session\AccountInterface, null given, called in /modules/contrib/apigee_edge/modules/apigee_edge_teams/src/Entity/TeamMemberRole.php on line 66 in Drupal\Core\Access\AccessResult::allowedIfHasPermissions() `

Feel free to create a PR for this issue.

**Comment by audave** [comment]
Issues fixed and PR created.
https://github.com/apigee/apigee-edge-drupal/pull/848

**Comment by shishir-intelli** [comment]
Thank you @audave we will review your PR.

**Comment by shishir-intelli** [comment]
@audave 
Could you please sign the Google [CLA](https://github.com/apigee/apigee-edge-drupal/pull/848/checks).
