### ISSUE TITLE
Bump version for Drupal 10 Support

### ISSUE THREAD

**Issue by divya-intelli** [apigee/apigee-edge-drupal#847]
Initial ticket for Drupal 10 compatibility. 
Changes from #761 by @VladimirAus will be included for better tracking and will go in drupal10-prep branch.  
Github action changes will be tracked in #846

**Comment by mxr576** [comment]
Why a new issue was necessary for the same topic that #761 already has? :thinking: That issue also has a long history that can be valuable reference at anytime... 

My suggestion is closing this one in favor of the older one.

**Comment by divya-intelli** [comment]
@mxr576 this ticket is only for version bump for Drupal 10. Some of the changes which are taken from #782. This is for better tracking . Test case which are failing will be tracked in #846

**Comment by divya-intelli** [comment]
Closes by PR #844
