### ISSUE TITLE
Create a guide for developers

### ISSUE THREAD

**Issue by mxr576** [apigee/apigee-edge-drupal#87]
I think we would should create guide for developers that describes how they should integrate with this module.

# Add to developer guide
* We do our best to follow Drupal 8's backward-compatibility policy after the BETA1 release: https://www.drupal.org/core/d8-bc-policy
* If an entity controller from the PHP API client has an entity controller service in Drupal (`Drupal\apigee_edge\Entity\Controller`) you should always use that for performing API calls. If it does not have yet, it is still recommended to create your own controller service for that and use that instead of the entity controller from the PHP API Client directly.
* For performing CRUDL operations on Apigee Edge entities it is highly recommended to always use the well-known Drupal entity storages (`Drupal\apigee_edge\Entity\Storage`) instead of entity controller services (`Drupal\apigee_edge\Entity\Controller`). Among the many other reasons for this recommendation, one of the major one is: persistent caching is only implemented on Drupal entity classes.
* For non-CRUDL operations (like changing status of a developer) which are intentionally not supported by entity storage classes (because it is not their scope to perform these API calls) it is perfectly fine to use entity controller services.

# TODOs
* Finalize "Add to developer guide"
* Resolve all TBDs

# TBD
* Where this guide for developer should be hosted?
  * Github Wiki?
  * A documentation page in Drupal.org?
   * A new markdown file in this repo?
   * ... ?

**Comment by gunosov** [comment]
Hi,
Any updates for this issue?

How I can load all developer apps by developer mail?

In Drupal 7 I can use $apps = entity_load('developer_app', FALSE, array('mail' => $user->mail));

I need load Developer Apps as array of App's entities

**Comment by mxr576** [comment]
Hi,

This works the same in Drupal 8 if you are familiar with the entity API. 
Classic entity API solution:
`$apps = \Drupal::entityTypeManager()->getStorage('developer_app')->loadByProperties('email', $user->mail);` in a procedural code or a trait and `$this->entityTypeManager->getStorage('developer_app')->loadByProperties('email', $user->mail);` in a class where DI available.

OR we implemented a shortcut in the developer_app storage for this `$this->entityTypeManager->getStorage('developer_app')->loadByDeveloper($user->mail);`

**Comment by Dhaneshmonds** [comment]
Hi,

I don't know that this is the right place or not to ask the below question.

I want to consume the below query from the apigee Management API.

http://{$hostname}/v1/organizations/{$org_name}/apiproducts/{$api_product_name}?query=count&entity=apps

Do we have any inbuilt method in apigee-php-client?

If anyone can guide me on this, It would be appreciated.

Regards,
Dhanesh

**Comment by cnovak** [comment]
@Dhaneshmonds I put in a separate ticket for you so we can answer it on a separate thread. #423

**Comment by cnovak** [comment]
The developer guide has been added to the Drupal.org module documentation page: https://www.drupal.org/docs/contributed-modules/apigee-edge/apigee-edge-developer-guide
