### ISSUE TITLE
Error while creating ApiDoc with api_products in payload through JSONAPI

### ISSUE THREAD

**Issue by shishir-intelli** [apigee/apigee-edge-drupal#878]
## Description
Adding `api_products` to API doc through JSONAPI throwing error
`No ID specified for related resource`

## Steps to Reproduce
Create API doc by using Jsonapi, in request payload add api_products.

## Actual Behavior
`No ID specified for related resource`

## Expected Behavior
Add ApiDoc with api products successfully

## Notes
This issue is coming when using https://github.com/apigee/apigee-smartdocs-maven-plugin
Original Issue - https://github.com/apigee/apigee-smartdocs-maven-plugin/issues/55

**Comment by ssvaidyanathan** [comment]
do we have an ETA?

**Comment by shishir-intelli** [comment]
@ssvaidyanathan 
We are working on new feature releases for ApigeeX and Drupal 10 releases for all the modules.
We have planned to work on this issue in Q3.

**Comment by ssvaidyanathan** [comment]
Can this be expedited as we have customers affected due to this issue

**Comment by shishir-intelli** [comment]
Certainly, We will prioritize this as soon as we release ApigeeX and Drupal10 new features.

**Comment by shishir-intelli** [comment]
@ssvaidyanathan ,
PR #879 resolves the `Internal server error` issue when trying to get the api-products through JSONAPI (`/jsonapi/api_product/api_product`)

The request payload to pass the api product while creating an API node is:
```
"relationships": {
    "field_api_product": {
        "data": [
              {
                "type":"api_product--api_product",
                 "id": "XXXXXX" //pass the uuid here
             }
        ]
    },
}
```

**Comment by ssvaidyanathan** [comment]
@shishir-intelli - you mentioned `//pass the uuid here`. Which uuid should I be passing if its a create operation?

**Comment by shishir-intelli** [comment]
> @shishir-intelli - you mentioned `//pass the uuid here`. Which uuid should I be passing if its a create operation?



It is `api_product` uuid
Sample response for `/jsonapi/api_product/api_product` :
![image](https://github.com/apigee/apigee-edge-drupal/assets/75600200/b90aae63-a734-47c0-afb0-4ebfe147191a)


To create a API doc with api_products by using JSONAPI:
Sample request pay load:
```
{
    "data": {
        "type": "node--apidoc",
        "attributes": {
            "status": true,
            "title": "Test API Doc",
            "body": {
                "value": "<p>Lorem ipsum...</p>",
                "format": "basic_html",
                "processed": "<p>Lorem ipsum...</p>",
                "summary": null
            },
            "field_apidoc_file_link": {
                "uri": "https://github.com/apigee/apigee-smartdocs-maven-plugin/blob/master/samples/Drupal8/DevPortal/specs/Petstore.yaml"
            },
            "field_apidoc_spec_file_source": "url"
        },
        "relationships": {
            "field_api_product": {
                "data": [
                    {
                        "type":"api_product--api_product",
                        "id": "tester"
                    },                    
                    {
                        "type":"api_product--api_product",
                        "id": "pingstatus-v1-product-test-operations"
                    }
                ]
            }
        }
    }
}
```


After executing the above JSON request payload, `Test API Doc` API Doc with api_product information will be created in Drupal portal,
Screenshot:
![image](https://github.com/apigee/apigee-edge-drupal/assets/75600200/fbb24d26-2949-44a7-b328-bee6e2afeba1)
