### ISSUE TITLE
Saving multivalue field that is part of the Team Entity results in an error.

### ISSUE THREAD

**Issue by audave** [apigee/apigee-edge-drupal#928]
## Description
Saving multivalue field that is part of the Team Entity results in an error.

## Apigee Info
Apigee Edge

## Steps to Reproduce
Enable apigee_edge_teams
Add a new field that enables having multiple values /admin/config/apigee-edge/team-settings/fields
Add a new team add with least 2 values into our new field.

## Expected behaviour
Team will save.
Field values will be save

## Actual behaviour
Hit Save, will result in a 500 error.

Error message in logs is
`Error: Call to a member function isOrganizationApigeeX() on null in Drupal\apigee_edge_teams\Entity\Form\TeamForm->buildEntity() (line 165 of /app/web/modules/contrib/apigee_edge/modules/apigee_edge_teams/src/Entity/Form/TeamForm.php).`

Replicated using Apigee Kickstart distro

**Comment by shishir-intelli** [comment]
@audave 
Thank you for addressing this issue, We are working on it.

**Comment by shishir-intelli** [comment]
@audave 
PR https://github.com/apigee/apigee-edge-drupal/pull/929 fix this issue, could you too please confirm this.

**Comment by audave** [comment]
I can confirm that the #929 fixes this issue
