### ISSUE TITLE
The `apigee-edge-teams:sync` Drush command is displayed as a global command

### ISSUE THREAD

**Issue by mxr576** [apigee/apigee-edge-drupal#951]
## Description
The `apigee-edge-teams:sync` Drush command is displayed as a global command instead of one that belongs to either `apigee-edge` or `apigee-edge-teams` group.

![image](https://github.com/apigee/apigee-edge-drupal/assets/1755573/ea112dcf-6dbe-4a70-b7c0-09b8f6f83afb)

## Apigee Info
N/A

## Steps to Reproduce
Run `drush` on a project where Apigee Edge Teams module is enabled.

## Actual Behavior
See description.

## Expected Behavior
See description.

## Screenshots
See description.

## Notes
-

## Version Info
3.0.1

**Comment by shishir-intelli** [comment]
Thank you @mxr576, 
We are checking this issue.
