### ISSUE TITLE
update.php fails on apigee_edge update #8101

### ISSUE THREAD

**Issue by vvenning-lb** [apigee/apigee-edge-drupal#959]
## Description
When attempting to run the update function, it fails on update #8101, which is 'Increase the max_length for first_name and last_name fields.'

## Apigee Info
Apigee Edge

## Steps to Reproduce
1. Have apigee_edge 2.0.* installed.  (Same results apigee_edge 2.0.2 thru 2.0.11)
2. run update.php

## Actual Behavior
Shown on screen

apigee_edge module
Update #8101
Failed: Drupal\Core\Entity\EntityStorageException: The entity update process failed while processing the entity type user, ID: 1. in Drupal\Core\Entity\Sql\SqlContentEntityStorageSchema->copyData() (line 220 of /var/www/html/web/core/lib/Drupal/Core/Entity/Sql/SqlFieldableEntityTypeListenerTrait.php)

## Expected Behavior
Success message

## Screenshots

![image](https://github.com/apigee/apigee-edge-drupal/assets/93785890/b6be5787-2254-4933-b310-5397f66b9677)

## Version Info
Drupal 9.5.10
apigee 2.0.11

**Comment by kedarkhaire** [comment]
Hi @vvenning-lb 
We checked with the steps and version details you mentioned, but we were not able to replicate the issue.
We are getting successful updates for Drupal 9.5.10 

- For Apigee Edge module from version 2.0.0 to 2.0.11 - only 9001 updates are triggered.
- For Apigee Edge module from version 8.x-1.27 to 2.0.11 - only 9001 and 8107 updates are triggered.

We do not see 8101 update triggered as described in the above issue.


Normally the update you mentioned is triggered post 8.x-1.05 version, which works on D8 sites and not on D9.


If you are in middle of D8 to D9 migration, I suggest to update the module in D8 itself with 8.x-1.27 which is compatible with D8 & D9 and also PHP 8, update the site with update script and then move ahead with D8 to D9 migration.

If there is another case, do let us know.
Thanks!

**Comment by kedarkhaire** [comment]
Hi @vvenning-lb 
I also recommend to use the latest version of Apigee Edge module, the version you are using (2.0.11) is quite outdated.
Do switch to the latest version of it.
Thanks!

**Comment by kedarkhaire** [comment]
Closing this issue for now as we didn't replicate the issue, Feel free to re-open if you are facing the issue again.
