### ISSUE TITLE
Null value compatibility with PHP 8.1

### ISSUE THREAD

**Issue by specoto** [apigee/apigee-edge-drupal#972]

**Comment by divya-intelli** [comment]
Hi @specoto , please add more details about the issue.

**Comment by specoto** [comment]
Hi, I have this error on 3.0.2 tag:

Error message
Deprecated function: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in Drupal\apigee_edge_teams\EventSubscriber\TeamStatusWarningSubscriber->onRespond() (line 102 of modules/contrib/apigee_edge/modules/apigee_edge_teams/src/EventSubscriber/TeamStatusWarningSubscriber.php). 

Basically we need to have a (string) cast to the first strpos() argument on line 102
if ($this->currentUser->isAuthenticated() && strpos(**_(string)_** $this->routeMatch->getRouteName(), 'entity.team_app.') === 0) {

**Comment by specoto** [comment]
I don't seem to have rights for PRs do here is the diff:
`diff --git a/modules/apigee_edge_teams/src/EventSubscriber/TeamStatusWarningSubscriber.php b/modules/apigee_edge_teams/src/EventSubscriber/TeamStatusWarningSubscriber.php
index 8ebf33ad..bace71dc 100644
--- a/modules/apigee_edge_teams/src/EventSubscriber/TeamStatusWarningSubscriber.php
+++ b/modules/apigee_edge_teams/src/EventSubscriber/TeamStatusWarningSubscriber.php
@@ -99,7 +99,7 @@ class TeamStatusWarningSubscriber implements EventSubscriberInterface {
    */
   public function onRespond(ResponseEvent $event) {
     // Anonymous user's does not have access to these routes.
-    if ($this->currentUser->isAuthenticated() && strpos($this->routeMatch->getRouteName(), 'entity.team_app.') === 0) {
+    if ($this->currentUser->isAuthenticated() && strpos((string) $this->routeMatch->getRouteName(), 'entity.team_app.') === 0) {
       // Team is available in most of the team app routes as a route parameter.
       /** @var \Drupal\apigee_edge_teams\Entity\TeamInterface|NULL $team */
       $team = $this->routeMatch->getParameter('team');`

**Comment by kedarkhaire** [comment]
Hi @specoto 
Let us know, the steps to reproduce the error, we will look into it.
Please add the page also where the issue is seen.

Also please check [CONTRIBUTING.md](https://github.com/apigee/apigee-edge-drupal/blob/3.x/CONTRIBUTING.md#installing-module-from-your-fork-instead-of-drupalorg) for knowing the contributing workflow.
Thanks!

**Comment by specoto** [comment]
Hi this happens when apigee_edge_teams module is enabled and PHP 8.1 is installed, the error is visible in recent logs when navigating drupal installation.

Thanks!

**Comment by mxr576** [comment]
Enabled via Drush, right?

My assumption that the current route is only available in the HTML presentation layer, not in others. Therefore `$this->routeMatch->getRouteName()` can be null.

**Comment by specoto** [comment]
Hi @mxr576 after additional debug I see that a rest resource route has been broken (locally  )and probably is the cause of this error, however it is still worth adding the cast as prevention and defensive programming.
Rector also recommends this approach with a rule: https://github.com/rectorphp/rector/blob/main/rules/Php81/Rector/FuncCall/NullToStrictStringFuncCallArgRector.php

**Comment by kedarkhaire** [comment]
Hi @specoto 
We tried to replicate the issue by enabling the Apigee Edge teams module from UI as well as via drush, but we don't see mentioned errors on the logs.

**Comment by kedarkhaire** [comment]
Hi @specoto 
We checked the other way to see the issue.
Following are the steps to reproduce-

- Create a team and Invite other members on the team.
- Now delete the team and try to access the team by visiting the old url of team or by logging in of other invited members simultaneously.
- Here the mentioned issue is generated.

Please feel free to create the PR and we will review.
Also please check [CONTRIBUTING.md](https://github.com/apigee/apigee-edge-drupal/blob/3.x/CONTRIBUTING.md#installing-module-from-your-fork-instead-of-drupalorg) for knowing the contributing workflow.

Do let us know for any issue.
Thanks!
